/**
 * English â†’ Urdu (Ù†Ø³ØªØ¹Ù„ÛŒÙ‚) meanings dictionary
 * Used across Class 6, 7, and 8 English labs to display Urdu meanings with TTS.
 *
 * Display uses Urdu script (Ù†Ø³ØªØ¹Ù„ÛŒÙ‚).
 * TTS uses Roman Urdu transliteration (for when no Urdu voice is installed on the system).
 */

// ============================================================
// URDU SCRIPT MEANINGS (for display in the UI)
// ============================================================

export const WORD_MEANINGS: Record<string, string> = {
  // === Nouns ===
  happiness: 'Ø®ÙˆØ´ÛŒ',
  team: 'Ù¹ÛŒÙ…',
  London: 'Ù„Ù†Ø¯Ù†',
  dog: 'Ú©ØªØ§',
  bunch: 'Ú¯Ú†Ú¾Ø§',
  courage: 'ÛÙ…Øª',
  Ganges: 'Ú¯Ù†Ú¯Ø§',
  book: 'Ú©ØªØ§Ø¨',
  table: 'Ù…ÛŒØ²',
  car: 'Ú¯Ø§Ú‘ÛŒ',
  apple: 'Ø³ÛŒØ¨',
  school: 'Ø§Ø³Ú©ÙˆÙ„',
  city: 'Ø´ÛØ±',
  mountain: 'Ù¾ÛØ§Ú‘',
  tree: 'Ø¯Ø±Ø®Øª',
  flower: 'Ù¾Ú¾ÙˆÙ„',
  animal: 'Ø¬Ø§Ù†ÙˆØ±',
  bird: 'Ù¾Ø±Ù†Ø¯Û',
  ocean: 'Ø³Ù…Ù†Ø¯Ø±',
  star: 'Ø³ØªØ§Ø±Û',
  house: 'Ú¯Ú¾Ø±',
  chair: 'Ú©Ø±Ø³ÛŒ',
  door: 'Ø¯Ø±ÙˆØ§Ø²Û',
  window: 'Ú©Ú¾Ú‘Ú©ÛŒ',
  food: 'Ú©Ú¾Ø§Ù†Ø§',
  water: 'Ù¾Ø§Ù†ÛŒ',
  fire: 'Ø¢Ú¯',
  earth: 'Ø²Ù…ÛŒÙ†',
  air: 'ÛÙˆØ§',
  sun: 'Ø³ÙˆØ±Ø¬',
  moon: 'Ú†Ø§Ù†Ø¯',
  information: 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª',
  library: 'Ú©ØªØ¨ Ø®Ø§Ù†Û',
  bravery: 'Ø¨ÛØ§Ø¯Ø±ÛŒ',
  elephant: 'ÛØ§ØªÚ¾ÛŒ',
  dragon: 'Ø§Ú˜Ø¯ÛØ§',
  alien: 'Ø§Ø¬Ù†Ø¨ÛŒ',
  adventure: 'Ù…ÛÙ… Ø¬ÙˆØ¦ÛŒ',
  journey: 'Ø³ÙØ±',
  story: 'Ú©ÛØ§Ù†ÛŒ',
  secret: 'Ø±Ø§Ø²',
  mystery: 'Ù¾Ø±Ø§Ø³Ø±Ø§Ø±',
  treasure: 'Ø®Ø²Ø§Ù†Û',
  power: 'Ø·Ø§Ù‚Øª',
  energy: 'ØªÙˆØ§Ù†Ø§Ø¦ÛŒ',
  strength: 'Ø·Ø§Ù‚Øª',
  wisdom: 'Ø¯Ø§Ù†Ø§Ø¦ÛŒ',
  knowledge: 'Ø¹Ù„Ù…',
  idea: 'Ø®ÛŒØ§Ù„',
  dream: 'Ø®ÙˆØ§Ø¨',
  memory: 'ÛŒØ§Ø¯Ø§Ø´Øª',
  future: 'Ù…Ø³ØªÙ‚Ø¨Ù„',
  past: 'Ù…Ø§Ø¶ÛŒ',
  present: 'Ø­Ø§Ù„',
  people: 'Ù„ÙˆÚ¯',
  person: 'Ø´Ø®Øµ',
  place: 'Ø¬Ú¯Û',
  thing: 'Ú†ÛŒØ²',
  time: 'ÙˆÙ‚Øª',
  name: 'Ù†Ø§Ù…',
  world: 'Ø¯Ù†ÛŒØ§',
  life: 'Ø²Ù†Ø¯Ú¯ÛŒ',
  head: 'Ø³Ø±',
  hand: 'ÛØ§ØªÚ¾',
  eye: 'Ø¢Ù†Ú©Ú¾',
  heart: 'Ø¯Ù„',
  body: 'Ø¬Ø³Ù…',
  face: 'Ú†ÛØ±Û',
  foot: 'Ù¾Ø§Ø¤Úº',
  arm: 'Ø¨Ø§Ø²Ùˆ',
  leg: 'Ù¹Ø§Ù†Ú¯',
  child: 'Ø¨Ú†Û',
  baby: 'Ø¨Ú†Û',
  parent: 'ÙˆØ§Ù„Ø¯ÛŒÙ†',
  mother: 'Ù…Ø§Úº',
  father: 'Ø¨Ø§Ù¾',
  brother: 'Ø¨Ú¾Ø§Ø¦ÛŒ',
  sister: 'Ø¨ÛÙ†',
  son: 'Ø¨ÛŒÙ¹Ø§',
  daughter: 'Ø¨ÛŒÙ¹ÛŒ',
  husband: 'Ø´ÙˆÛØ±',
  wife: 'Ø¨ÛŒÙˆÛŒ',
  king: 'Ø¨Ø§Ø¯Ø´Ø§Û',
  queen: 'Ù…Ù„Ú©Û',
  prince: 'Ø´ÛØ²Ø§Ø¯Û',
  princess: 'Ø´ÛØ²Ø§Ø¯ÛŒ',
  hero: 'ÛÛŒØ±Ùˆ',
  villain: 'ÙˆÙ„Ù†',
  giant: 'Ø¯ÛŒÙˆ',
  monster: 'Ø¹ÙØ±ÛŒØª',
  wizard: 'Ø¬Ø§Ø¯ÙˆÚ¯Ø±',
  fairy: 'Ù¾Ø±ÛŒ',
  ghost: 'Ø¨Ú¾ÙˆØª',
  robot: 'Ø±ÙˆØ¨ÙˆÙ¹',
  machine: 'Ù…Ø´ÛŒÙ†',
  computer: 'Ú©Ù…Ù¾ÛŒÙˆÙ¹Ø±',
  message: 'Ù¾ÛŒØºØ§Ù…',
  tool: 'Ø¢Ù„Û',
  weapon: 'ÛØªÚ¾ÛŒØ§Ø±',
  bridge: 'Ù¾Ù„',
  tower: 'Ù…ÛŒÙ†Ø§Ø±',
  castle: 'Ù‚Ù„Ø¹Û',
  palace: 'Ù…Ø­Ù„',
  temple: 'Ù…Ù†Ø¯Ø±',
  church: 'Ú¯Ø±Ø¬Ø§',
  mosque: 'Ù…Ø³Ø¬Ø¯',
  market: 'Ø¨Ø§Ø²Ø§Ø±',
  hospital: 'ÛØ³Ù¾ØªØ§Ù„',
  village: 'Ú¯Ø§Ø¤Úº',
  country: 'Ù…Ù„Ú©',
  space: 'Ø®Ù„Ø§',
  planet: 'Ø³ÛŒØ§Ø±Û',
  island: 'Ø¬Ø²ÛŒØ±Û',
  forest: 'Ø¬Ù†Ú¯Ù„',
  desert: 'ØµØ­Ø±Ø§',
  cave: 'ØºØ§Ø±',
  stone: 'Ù¾ØªÚ¾Ø±',
  rock: 'Ú†Ù¹Ø§Ù†',
  gold: 'Ø³ÙˆÙ†Ø§',
  silver: 'Ú†Ø§Ù†Ø¯ÛŒ',
  iron: 'Ù„ÙˆÛØ§',
  wood: 'Ù„Ú©Ú‘ÛŒ',
  glass: 'Ø´ÛŒØ´Û',
  paper: 'Ú©Ø§ØºØ°',
  color: 'Ø±Ù†Ú¯',
  colour: 'Ø±Ù†Ú¯',
  shape: 'Ø´Ú©Ù„',
  size: 'Ø³Ø§Ø¦Ø²',
  number: 'Ù†Ù…Ø¨Ø±',
  letter: 'Ø­Ø±Ù',
  word: 'Ù„ÙØ¸',
  sound: 'Ø¢ÙˆØ§Ø²',
  music: 'Ù…ÙˆØ³ÛŒÙ‚ÛŒ',
  song: 'Ú¯Ø§Ù†Ø§',
  picture: 'ØªØµÙˆÛŒØ±',
  map: 'Ù†Ù‚Ø´Û',
  flag: 'Ø¬Ú¾Ù†ÚˆØ§',
  game: 'Ú©Ú¾ÛŒÙ„',
  sport: 'Ú©Ú¾ÛŒÙ„',
  player: 'Ú©Ú¾Ù„Ø§Ú‘ÛŒ',
  winner: 'ÙØ§ØªØ­',
  prize: 'Ø§Ù†Ø¹Ø§Ù…',
  gift: 'ØªØ­ÙÛ',
  money: 'Ù¾ÛŒØ³Û',
  coin: 'Ø³Ú©Û',
  bag: 'Ø¨ÛŒÚ¯',
  box: 'ÚˆØ¨Û',
  bottle: 'Ø¨ÙˆØªÙ„',
  cup: 'Ù¾ÛŒØ§Ù„Û',
  plate: 'Ù¾Ù„ÛŒÙ¹',
  spoon: 'Ú†Ù…Ú†',
  knife: 'Ú†Ú¾Ø±ÛŒ',
  fork: 'Ú©Ø§Ù†Ù¹Ø§',
  bed: 'Ø¨Ø³ØªØ±',
  room: 'Ú©Ù…Ø±Û',
  wall: 'Ø¯ÛŒÙˆØ§Ø±',
  floor: 'ÙØ±Ø´',
  roof: 'Ú†Ú¾Øª',
  step: 'Ù‚Ø¯Ù…',
  path: 'Ø±Ø§Ø³ØªÛ',
  gate: 'Ú¯ÛŒÙ¹',
  key: 'Ú†Ø§Ø¨ÛŒ',
  lock: 'ØªØ§Ù„Ø§',
  bell: 'Ú¯Ú¾Ù†Ù¹ÛŒ',
  clock: 'Ú¯Ú¾Ú‘ÛŒ',
  lamp: 'Ú†Ø±Ø§Øº',
  shadow: 'Ø³Ø§ÛŒÛ',
  cloud: 'Ø¨Ø§Ø¯Ù„',
  rain: 'Ø¨Ø§Ø±Ø´',
  snow: 'Ø¨Ø±Ù',
  wind: 'ÛÙˆØ§',
  storm: 'Ø·ÙˆÙØ§Ù†',
  thunder: 'Ú¯Ø±Ø¬',
  lightning: 'Ø¨Ø¬Ù„ÛŒ',
  sky: 'Ø¢Ø³Ù…Ø§Ù†',
  ground: 'Ø²Ù…ÛŒÙ†',
  hill: 'Ù¾ÛØ§Ú‘ÛŒ',
  valley: 'ÙˆØ§Ø¯ÛŒ',
  lake: 'Ø¬Ú¾ÛŒÙ„',
  sea: 'Ø³Ù…Ù†Ø¯Ø±',
  ship: 'Ø¬ÛØ§Ø²',
  boat: 'Ú©Ø´ØªÛŒ',
  train: 'Ù¹Ø±ÛŒÙ†',
  bus: 'Ø¨Ø³',
  bicycle: 'Ø³Ø§Ø¦ÛŒÚ©Ù„',
  wheel: 'Ù¾ÛÛŒÛ',
  engine: 'Ø§Ù†Ø¬Ù†',
  pilot: 'Ù¾Ø§Ø¦Ù„Ù¹',
  driver: 'ÚˆØ±Ø§Ø¦ÛŒÙˆØ±',
  captain: 'Ú©Ù¾ØªØ§Ù†',
  soldier: 'Ø³Ù¾Ø§ÛÛŒ',
  police: 'Ù¾ÙˆÙ„ÛŒØ³',
  thief: 'Ú†ÙˆØ±',
  robber: 'ÚˆØ§Ú©Ùˆ',
  judge: 'Ø¬Ø¬',
  lawyer: 'ÙˆÚ©ÛŒÙ„',
  scientist: 'Ø³Ø§Ø¦Ù†Ø³Ø¯Ø§Ù†',
  engineer: 'Ø§Ù†Ø¬ÛŒÙ†Ø¦Ø±',
  artist: 'ÙÙ†Ú©Ø§Ø±',
  writer: 'Ù…ØµÙ†Ù',
  poet: 'Ø´Ø§Ø¹Ø±',
  farmer: 'Ú©Ø³Ø§Ù†',
  sailor: 'Ù…Ù„Ø§Ø­',
  guard: 'Ú¯Ø§Ø±Úˆ',
  servant: 'Ù†ÙˆÚ©Ø±',
  master: 'Ø¢Ù‚Ø§',
  owner: 'Ù…Ø§Ù„Ú©',
  guest: 'Ù…ÛÙ…Ø§Ù†',
  stranger: 'Ø§Ø¬Ù†Ø¨ÛŒ',
  neighbor: 'Ù¾Ú‘ÙˆØ³ÛŒ',
  neighbour: 'Ù¾Ú‘ÙˆØ³ÛŒ',
  enemy: 'Ø¯Ø´Ù…Ù†',
  friend: 'Ø¯ÙˆØ³Øª',
  family: 'Ø®Ø§Ù†Ø¯Ø§Ù†',
  group: 'Ú¯Ø±ÙˆÙ¾',
  crowd: 'ÛØ¬ÙˆÙ…',
  line: 'Ù„Ø§Ø¦Ù†',
  circle: 'Ø¯Ø§Ø¦Ø±Û',
  corner: 'Ú©ÙˆÙ†Ø§',
  edge: 'Ú©Ù†Ø§Ø±Û',
  center: 'Ù…Ø±Ú©Ø²',
  middle: 'Ø¯Ø±Ù…ÛŒØ§Ù†',
  top: 'Ø§ÙˆÙ¾Ø±',
  bottom: 'Ù†ÛŒÚ†Û’',
  front: 'Ø³Ø§Ù…Ù†Û’',
  back: 'Ù¾ÛŒÚ†Ú¾Û’',
  side: 'Ø·Ø±Ù',
  left: 'Ø¨Ø§Ø¦ÛŒÚº',
  right: 'Ø¯Ø§Ø¦ÛŒÚº',
  inside: 'Ø§Ù†Ø¯Ø±',
  outside: 'Ø¨Ø§ÛØ±',
  morning: 'ØµØ¨Ø­',
  evening: 'Ø´Ø§Ù…',
  night: 'Ø±Ø§Øª',
  noon: 'Ø¯ÙˆÙ¾ÛØ±',
  midnight: 'Ø¢Ø¯Ú¾ÛŒ Ø±Ø§Øª',
  dawn: 'ÙØ¬Ø±',
  today: 'Ø¢Ø¬',
  tomorrow: 'Ú©Ù„',
  yesterday: 'Ú©Ù„',
  week: 'ÛÙØªÛ',
  month: 'Ù…ÛÛŒÙ†Û',
  year: 'Ø³Ø§Ù„',
  season: 'Ù…ÙˆØ³Ù…',
  spring: 'Ø¨ÛØ§Ø±',
  summer: 'Ú¯Ø±Ù…ÛŒ',
  autumn: 'Ø®Ø²Ø§Úº',
  winter: 'Ø³Ø±Ø¯ÛŒ',
  temperature: 'Ø¯Ø±Ø¬Û Ø­Ø±Ø§Ø±Øª',
  degree: 'ÚˆÚ¯Ø±ÛŒ',
  meter: 'Ù…ÛŒÙ¹Ø±',
  kilometer: 'Ú©Ù„ÙˆÙ…ÛŒÙ¹Ø±',
  kilogram: 'Ú©Ù„ÙˆÚ¯Ø±Ø§Ù…',
  liter: 'Ù„ÛŒÙ¹Ø±',
  piece: 'Ù¹Ú©Ú‘Ø§',
  pair: 'Ø¬ÙˆÚ‘Ø§',
  set: 'Ø³ÛŒÙ¹',
  list: 'ÙÛØ±Ø³Øª',
  rule: 'Ù‚Ø§Ø¹Ø¯Û',
  law: 'Ù‚Ø§Ù†ÙˆÙ†',
  order: 'Ø­Ú©Ù…',
  example: 'Ù…Ø«Ø§Ù„',
  lesson: 'Ø³Ø¨Ù‚',
  class: 'Ú©Ù„Ø§Ø³',
  grade: 'Ø¯Ø±Ø¬Û',
  course: 'Ú©ÙˆØ±Ø³',
  topic: 'Ù…ÙˆØ¶ÙˆØ¹',
  test: 'Ù¹ÛŒØ³Ù¹',
  result: 'Ù†ØªÛŒØ¬Û',
  score: 'Ø§Ø³Ú©ÙˆØ±',
  mark: 'Ù†Ø´Ø§Ù†',
  question: 'Ø³ÙˆØ§Ù„',
  reason: 'ÙˆØ¬Û',
  cause: 'Ø³Ø¨Ø¨',
  effect: 'Ø§Ø«Ø±',
  difference: 'ÙØ±Ù‚',
  choice: 'Ø§Ù†ØªØ®Ø§Ø¨',
  decision: 'ÙÛŒØµÙ„Û',
  plan: 'Ù…Ù†ØµÙˆØ¨Û',
  goal: 'ÛØ¯Ù',
  target: 'Ù†Ø´Ø§Ù†Û',
  problem: 'Ù…Ø³Ø¦Ù„Û',
  solution: 'Ø­Ù„',
  method: 'Ø·Ø±ÛŒÙ‚Û',
  system: 'Ù†Ø¸Ø§Ù…',
  process: 'Ø¹Ù…Ù„',
  level: 'Ø³Ø·Ø­',
  part: 'Ø­ØµÛ',
  whole: 'Ù¾ÙˆØ±Ø§',
  half: 'Ø¢Ø¯Ú¾Ø§',
  quarter: 'Ú†ÙˆØªÚ¾Ø§Ø¦ÛŒ',
  rest: 'Ø¨Ø§Ù‚ÛŒ',
  lot: 'Ø¨ÛØª',
  bit: 'ØªÚ¾ÙˆÚ‘Ø§',
  fact: 'Ø­Ù‚ÛŒÙ‚Øª',
  truth: 'Ø³Ú†',
  lie: 'Ø¬Ú¾ÙˆÙ¹',
  opinion: 'Ø±Ø§Ø¦Û’',
  thought: 'Ø³ÙˆÚ†',
  feeling: 'Ø§Ø­Ø³Ø§Ø³',
  emotion: 'Ø¬Ø°Ø¨Û',
  action: 'Ø¹Ù…Ù„',
  event: 'ØªÙ‚Ø±ÛŒØ¨',
  situation: 'ØµÙˆØ±ØªØ­Ø§Ù„',
  condition: 'Ø­Ø§Ù„Øª',
  position: 'Ù¾ÙˆØ²ÛŒØ´Ù†',
  direction: 'Ø³Ù…Øª',
  distance: 'ÙØ§ØµÙ„Û',
  length: 'Ù„Ù…Ø¨Ø§Ø¦ÛŒ',
  height: 'Ø§ÙˆÙ†Ú†Ø§Ø¦ÛŒ',
  width: 'Ú†ÙˆÚ‘Ø§Ø¦ÛŒ',
  depth: 'Ú¯ÛØ±Ø§Ø¦ÛŒ',
  weight: 'ÙˆØ²Ù†',
  speed: 'Ø±ÙØªØ§Ø±',
  rate: 'Ø´Ø±Ø­',
  price: 'Ù‚ÛŒÙ…Øª',
  cost: 'Ù„Ø§Ú¯Øª',
  value: 'Ù‚Ø¯Ø±',
  quality: 'Ù…Ø¹ÛŒØ§Ø±',
  type: 'Ù‚Ø³Ù…',
  sort: 'Ù‚Ø³Ù…',
  way: 'Ø·Ø±ÛŒÙ‚Û',
  meaning: 'Ù…Ø¹Ù†ÛŒ',
  definition: 'ØªØ¹Ø±ÛŒÙ',
  description: 'ÙˆØ¶Ø§Ø­Øª',
  translation: 'ØªØ±Ø¬Ù…Û',
  language: 'Ø²Ø¨Ø§Ù†',
  english: 'Ø§Ù†Ú¯Ø±ÛŒØ²ÛŒ',
  urdu: 'Ø§Ø±Ø¯Ùˆ',
  grammar: 'Ú¯Ø±Ø§Ù…Ø±',
  vocabulary: 'Ø°Ø®ÛŒØ±Û Ø§Ù„ÙØ§Ø¸',
  spelling: 'ÛØ¬Û’',
  pronunciation: 'ØªÙ„ÙØ¸',
  accent: 'Ù„ÛØ¬Û',
  dialogue: 'Ù…Ú©Ø§Ù„Ù…Û',
  conversation: 'Ú¯ÙØªÚ¯Ùˆ',
  speech: 'ØªÙ‚Ø±ÛŒØ±',
  report: 'Ø±Ù¾ÙˆØ±Ù¹',
  essay: 'Ù…Ø¶Ù…ÙˆÙ†',
  composition: 'ØªØ¹Ø¨ÛŒØ±',
  diary: 'ÚˆØ§Ø¦Ø±ÛŒ',
  form: 'ÙØ§Ø±Ù…',
  chart: 'Ú†Ø§Ø±Ù¹',
  graph: 'Ú¯Ø±Ø§Ù',
  diagram: 'Ø®Ø§Ú©Û',
  symbol: 'Ø¹Ù„Ø§Ù…Øª',
  sign: 'Ù†Ø´Ø§Ù†',
  code: 'Ú©ÙˆÚˆ',
  clue: 'Ø³Ø±Ø§Øº',
  hint: 'Ø§Ø´Ø§Ø±Û',
  tip: 'Ù…Ø´ÙˆØ±Û',
  advice: 'Ù…Ø´ÙˆØ±Û',
  luck: 'Ù‚Ø³Ù…Øª',
  chance: 'Ù…ÙˆÙ‚Ø¹',
  opportunity: 'Ù…ÙˆÙ‚Ø¹',
  risk: 'Ø®Ø·Ø±Û',
  danger: 'Ø®Ø·Ø±Û',
  safety: 'Ø­ÙØ§Ø¸Øª',
  protection: 'ØªØ­ÙØ¸',
  war: 'Ø¬Ù†Ú¯',
  peace: 'Ø§Ù…Ù†',
  battle: 'Ù„Ú‘Ø§Ø¦ÛŒ',
  victory: 'ÙØªØ­',
  defeat: 'Ø´Ú©Ø³Øª',
  attack: 'Ø­Ù…Ù„Û',
  defense: 'Ø¯ÙØ§Ø¹',
  army: 'ÙÙˆØ¬',
  force: 'Ø·Ø§Ù‚Øª',

  // === Adjectives ===
  happy: 'Ø®ÙˆØ´',
  beautiful: 'Ø®ÙˆØ¨ØµÙˆØ±Øª',
  big: 'Ø¨Ú‘Ø§',
  small: 'Ú†Ú¾ÙˆÙ¹Ø§',
  tall: 'Ù„Ù…Ø¨Ø§',
  short: 'Ú†Ú¾ÙˆÙ¹Ø§',
  fast: 'ØªÛŒØ²',
  slow: 'Ø¯Ú¾ÛŒÙ…Ø§',
  hot: 'Ú¯Ø±Ù…',
  cold: 'Ù¹Ú¾Ù†ÚˆØ§',
  new: 'Ù†ÛŒØ§',
  old: 'Ù¾Ø±Ø§Ù†Ø§',
  good: 'Ø§Ú†Ú¾Ø§',
  bad: 'Ø¨Ø±Ø§',
  shiny: 'Ú†Ù…Ú©Ø¯Ø§Ø±',
  huge: 'Ø¨Ú‘Ø§',
  ferocious: 'Ø®ÙˆÙ†Ø®ÙˆØ§Ø±',
  many: 'Ø¨ÛØª',
  some: 'Ú©Ú†Ú¾',
  cheap: 'Ø³Ø³ØªØ§',
  bossy: 'Ø­Ú©Ù… Ú†Ù„Ø§Ù†Û’ ÙˆØ§Ù„Ø§',
  angry: 'ØºØµÛ',
  confused: 'Ù¾Ø±ÛŒØ´Ø§Ù†',
  determined: 'Ù…Ø³ØªÙ‚Ù„',
  assertive: 'Ø²Ø¨Ø±Ø¯Ø³Øª',
  brave: 'Ø¨ÛØ§Ø¯Ø±',
  clever: 'ÛÙˆØ´ÛŒØ§Ø±',
  smart: 'ÛÙˆØ´ÛŒØ§Ø±',
  wise: 'Ø¹Ù‚Ù„Ù…Ù†Ø¯',
  foolish: 'Ø¨Û’ ÙˆÙ‚ÙˆÙ',
  kind: 'Ù…ÛØ±Ø¨Ø§Ù†',
  cruel: 'Ø¸Ø§Ù„Ù…',
  gentle: 'Ù†Ø±Ù…',
  rough: 'Ú©Ú¾Ø±Ø¯Ø±Ø§',
  soft: 'Ù†Ø±Ù…',
  hard: 'Ø³Ø®Øª',
  strong: 'Ù…Ø¶Ø¨ÙˆØ·',
  weak: 'Ú©Ù…Ø²ÙˆØ±',
  rich: 'Ø§Ù…ÛŒØ±',
  poor: 'ØºØ±ÛŒØ¨',
  young: 'Ø¬ÙˆØ§Ù†',
  easy: 'Ø¢Ø³Ø§Ù†',
  difficult: 'Ù…Ø´Ú©Ù„',
  complex: 'Ù¾ÛŒÚ†ÛŒØ¯Û',
  important: 'Ø§ÛÙ…',
  necessary: 'Ø¶Ø±ÙˆØ±ÛŒ',
  possible: 'Ù…Ù…Ú©Ù†',
  impossible: 'Ù†Ø§Ù…Ù…Ú©Ù†',
  correct: 'Ø¯Ø±Ø³Øª',
  incorrect: 'ØºÙ„Ø·',
  true: 'Ø³Ú†',
  false: 'Ø¬Ú¾ÙˆÙ¹',
  real: 'Ø­Ù‚ÛŒÙ‚ÛŒ',
  fake: 'Ø¬Ø¹Ù„ÛŒ',
  special: 'Ø®Ø§Øµ',
  ordinary: 'Ø¹Ø§Ù…',
  strange: 'Ø¹Ø¬ÛŒØ¨',
  normal: 'Ù†Ø§Ø±Ù…Ù„',
  usual: 'Ø¹Ø§Ù…',
  rare: 'Ù†Ø§ÛŒØ§Ø¨',
  different: 'Ù…Ø®ØªÙ„Ù',
  same: 'Ø§ÛŒÚ© Ø¬ÛŒØ³Ø§',
  similar: 'Ù…Ù„ØªØ§ Ø¬Ù„ØªØ§',
  opposite: 'Ù…Ø®Ø§Ù„Ù',
  clear: 'ØµØ§Ù',
  dirty: 'Ú¯Ù†Ø¯Ø§',
  dark: 'Ø§Ù†Ø¯Ú¾ÛŒØ±Ø§',
  bright: 'Ø±ÙˆØ´Ù†',
  light: 'ÛÙ„Ú©Ø§',
  heavy: 'Ø¨Ú¾Ø§Ø±ÛŒ',
  full: 'Ø¨Ú¾Ø±Ø§',
  empty: 'Ø®Ø§Ù„ÛŒ',
  closed: 'Ø¨Ù†Ø¯',
  long: 'Ù„Ù…Ø¨Ø§',
  wide: 'Ú†ÙˆÚ‘Ø§',
  narrow: 'ØªÙ†Ú¯',
  deep: 'Ú¯ÛØ±Ø§',
  shallow: 'Ø§ØªÚ¾Ù„Ø§',
  high: 'Ø§ÙˆÙ†Ú†Ø§',
  low: 'Ù†ÛŒÚ†Ø§',
  far: 'Ø¯ÙˆØ±',
  early: 'Ø¬Ù„Ø¯ÛŒ',
  late: 'Ø¯ÛŒØ±',
  quick: 'ØªÛŒØ²',
  ready: 'ØªÛŒØ§Ø±',
  busy: 'Ù…ØµØ±ÙˆÙ',
  free: 'Ø¢Ø²Ø§Ø¯',
  sure: 'ÛŒÙ‚ÛŒÙ†ÛŒ',
  certain: 'ÛŒÙ‚ÛŒÙ†ÛŒ',
  main: 'Ø§ÛÙ…',
  single: 'ÙˆØ§Ø­Ø¯',
  double: 'Ø¯ÙˆÚ¯Ù†Ø§',
  extra: 'Ø§Ø¶Ø§ÙÛŒ',
  last: 'Ø¢Ø®Ø±ÛŒ',
  next: 'Ø§Ú¯Ù„Ø§',
  first: 'Ù¾ÛÙ„Ø§',
  second: 'Ø¯ÙˆØ³Ø±Ø§',
  third: 'ØªÛŒØ³Ø±Ø§',
  little: 'ØªÚ¾ÙˆÚ‘Ø§',
  much: 'Ø¨ÛØª',
  enough: 'Ú©Ø§ÙÛŒ',
  great: 'Ø¹Ø¸ÛŒÙ…',
  wonderful: 'Ø´Ø§Ù†Ø¯Ø§Ø±',
  amazing: 'Ø­ÛŒØ±Øª Ø§Ù†Ú¯ÛŒØ²',
  fantastic: 'Ù„Ø§Ø¬ÙˆØ§Ø¨',
  excellent: 'Ø¨ÛØªØ±ÛŒÙ†',
  perfect: 'Ú©Ø§Ù…Ù„',
  terrible: 'Ø®ÙˆÙÙ†Ø§Ú©',
  pleasant: 'Ø®ÙˆØ´Ú¯ÙˆØ§Ø±',
  lovely: 'Ù¾ÛŒØ§Ø±Ø§',
  nice: 'Ø§Ú†Ú¾Ø§',
  fine: 'Ù¹Ú¾ÛŒÚ©',
  modern: 'Ø¬Ø¯ÛŒØ¯',
  ancient: 'Ù‚Ø¯ÛŒÙ…',
  original: 'Ø§ØµÙ„ÛŒ',
  popular: 'Ù…Ù‚Ø¨ÙˆÙ„',
  famous: 'Ù…Ø´ÛÙˆØ±',
  unknown: 'Ù†Ø§Ù…Ø¹Ù„ÙˆÙ…',
  various: 'Ù…Ø®ØªÙ„Ù',
  several: 'Ú©Ø¦ÛŒ',
  specific: 'Ù…Ø®ØµÙˆØµ',
  general: 'Ø¹Ø§Ù…',
  entire: 'Ù¾ÙˆØ±Ø§',
  total: 'Ú©Ù„',
  complete: 'Ù…Ú©Ù…Ù„',
  natural: 'Ù‚Ø¯Ø±ØªÛŒ',
  artificial: 'Ù…ØµÙ†ÙˆØ¹ÛŒ',
  useful: 'Ù…ÙÛŒØ¯',
  useless: 'Ø¨ÛŒÚ©Ø§Ø±',
  careful: 'Ù…Ø­ØªØ§Ø·',
  dangerous: 'Ø®Ø·Ø±Ù†Ø§Ú©',
  safe: 'Ù…Ø­ÙÙˆØ¸',
  harmful: 'Ù†Ù‚ØµØ§Ù† Ø¯Û',
  helpful: 'Ù…Ø¯Ø¯Ú¯Ø§Ø±',
  colorful: 'Ø±Ù†Ú¯ÛŒÙ†',
  boring: 'Ø¨ÙˆØ±Ù†Ú¯',
  interesting: 'Ø¯Ù„Ú†Ø³Ù¾',
  exciting: 'Ù¾Ø±Ø¬ÙˆØ´',
  funny: 'Ù…Ø¶Ø­Ú©Û',
  sad: 'Ø§Ø¯Ø§Ø³',
  hungry: 'Ø¨Ú¾ÙˆÚ©Ø§',
  thirsty: 'Ù¾ÛŒØ§Ø³Ø§',
  sick: 'Ø¨ÛŒÙ…Ø§Ø±',
  healthy: 'ØµØ­Øª Ù…Ù†Ø¯',
  alive: 'Ø²Ù†Ø¯Û',
  dead: 'Ù…Ø±Ø¯Û',
  alone: 'Ø§Ú©ÛŒÙ„Ø§',
  together: 'Ø§ÛŒÚ© Ø³Ø§ØªÚ¾',
  silent: 'Ø®Ø§Ù…ÙˆØ´',
  loud: 'Ø§ÙˆÙ†Ú†Ø§',
  quiet: 'Ø®Ø§Ù…ÙˆØ´',
  noisy: 'Ø´ÙˆØ±',
  sweet: 'Ù…ÛŒÙ¹Ú¾Ø§',
  sour: 'Ú©Ú¾Ù¹Ø§',
  bitter: 'Ú©Ú‘ÙˆØ§',
  salty: 'Ù†Ù…Ú©ÛŒÙ†',
  spicy: 'Ù…Ø³Ø§Ù„Û Ø¯Ø§Ø±',
  delicious: 'Ù…Ø²ÛŒØ¯Ø§Ø±',
  fresh: 'ØªØ§Ø²Û',
  wet: 'Ú¯ÛŒÙ„Ø§',
  dry: 'Ø®Ø´Ú©',
  smooth: 'ÛÙ…ÙˆØ§Ø±',
  thick: 'Ù…ÙˆÙ¹Ø§',
  thin: 'Ù¾ØªÙ„Ø§',
  flat: 'Ú†Ù¾Ù¹Ø§',
  square: 'Ù…Ø±Ø¨Ø¹',
  straight: 'Ø³ÛŒØ¯Ú¾Ø§',
  even: 'Ø¨Ø±Ø§Ø¨Ø±',
  odd: 'Ø¹Ø¬ÛŒØ¨',
  fair: 'Ù…Ù†ØµÙØ§Ù†Û',
  honest: 'Ø§ÛŒÙ…Ø§Ù†Ø¯Ø§Ø±',
  loyal: 'ÙˆÙØ§Ø¯Ø§Ø±',
  polite: 'Ø´Ø§Ø¦Ø³ØªÛ',
  rude: 'Ø¨Ø¯ ØªÙ…ÛŒØ²',
  generous: 'Ø³Ø®ÛŒ',
  selfish: 'Ø®ÙˆØ¯ ØºØ±Ø¶',
  greedy: 'Ù„Ø§Ù„Ú†ÛŒ',
  lazy: 'Ø³Ø³Øª',
  energetic: 'ØªÙˆØ§Ù†Ø§',
  dull: 'Ù¾Ú¾ÛŒÚ©Ø§',
  sharp: 'ØªÛŒØ²',
  blunt: 'Ú©Ù†Ø¯',
  expensive: 'Ù…ÛÙ†Ú¯Ø§',
  valuable: 'Ù‚ÛŒÙ…ØªÛŒ',
  precious: 'Ù‚ÛŒÙ…ØªÛŒ',
  intelligent: 'Ø°ÛÛŒÙ†',
  brilliant: 'Ø°ÛÛŒÙ†',

  // === Verbs ===
  run: 'Ø¯ÙˆÚ‘Ù†Ø§',
  eat: 'Ú©Ú¾Ø§Ù†Ø§',
  sleep: 'Ø³ÙˆÙ†Ø§',
  read: 'Ù¾Ú‘Ú¾Ù†Ø§',
  write: 'Ù„Ú©Ú¾Ù†Ø§',
  speak: 'Ø¨ÙˆÙ„Ù†Ø§',
  walk: 'Ú†Ù„Ù†Ø§',
  work: 'Ú©Ø§Ù… Ú©Ø±Ù†Ø§',
  play: 'Ú©Ú¾ÛŒÙ„Ù†Ø§',
  swim: 'ØªÛŒØ±Ù†Ø§',
  jump: 'Ú©ÙˆØ¯Ù†Ø§',
  sing: 'Ú¯Ø§Ù†Ø§',
  dance: 'Ù†Ø§Ú†Ù†Ø§',
  cook: 'Ù¾Ú©Ø§Ù†Ø§',
  drink: 'Ù¾ÛŒÙ†Ø§',
  give: 'Ø¯ÛŒÙ†Ø§',
  take: 'Ù„ÛŒÙ†Ø§',
  come: 'Ø¢Ù†Ø§',
  go: 'Ø¬Ø§Ù†Ø§',
  see: 'Ø¯ÛŒÚ©Ú¾Ù†Ø§',
  hear: 'Ø³Ù†Ù†Ø§',
  teach: 'Ø³Ú©Ú¾Ø§Ù†Ø§',
  learn: 'Ø³ÛŒÚ©Ú¾Ù†Ø§',
  help: 'Ù…Ø¯Ø¯ Ú©Ø±Ù†Ø§',
  love: 'Ù…Ø­Ø¨Øª Ú©Ø±Ù†Ø§',
  make: 'Ø¨Ù†Ø§Ù†Ø§',
  break: 'ØªÙˆÚ‘Ù†Ø§',
  catch: 'Ù¾Ú©Ú‘Ù†Ø§',
  bring: 'Ù„Ø§Ù†Ø§',
  find: 'ÚˆÚ¾ÙˆÙ†ÚˆÚ¾Ù†Ø§',
  buy: 'Ø®Ø±ÛŒØ¯Ù†Ø§',
  sell: 'Ø¨ÛŒÚ†Ù†Ø§',
  talk: 'Ø¨Ø§Øª Ú©Ø±Ù†Ø§',
  sit: 'Ø¨ÛŒÙ¹Ú¾Ù†Ø§',
  stand: 'Ú©Ú¾Ú‘Ø§ ÛÙˆÙ†Ø§',
  think: 'Ø³ÙˆÚ†Ù†Ø§',
  know: 'Ø¬Ø§Ù†Ù†Ø§',
  want: 'Ú†Ø§ÛÙ†Ø§',
  need: 'Ø¶Ø±ÙˆØ±Øª ÛÙˆÙ†Ø§',
  like: 'Ù¾Ø³Ù†Ø¯ Ú©Ø±Ù†Ø§',
  ask: 'Ù¾ÙˆÚ†Ú¾Ù†Ø§',
  tell: 'Ø¨ØªØ§Ù†Ø§',
  show: 'Ø¯Ú©Ú¾Ø§Ù†Ø§',
  try: 'Ú©ÙˆØ´Ø´ Ú©Ø±Ù†Ø§',
  leave: 'Ú†Ú¾ÙˆÚ‘Ù†Ø§',
  keep: 'Ø±Ú©Ú¾Ù†Ø§',
  let: 'Ø¯ÛŒÙ†Ø§',
  begin: 'Ø´Ø±ÙˆØ¹ Ú©Ø±Ù†Ø§',
  start: 'Ø´Ø±ÙˆØ¹ Ú©Ø±Ù†Ø§',
  stop: 'Ø±Ú©Ù†Ø§',
  finish: 'Ø®ØªÙ… Ú©Ø±Ù†Ø§',
  open: 'Ú©Ú¾ÙˆÙ„Ù†Ø§',
  close: 'Ø¨Ù†Ø¯ Ú©Ø±Ù†Ø§',
  move: 'Ø­Ø±Ú©Øª Ú©Ø±Ù†Ø§',
  change: 'Ø¨Ø¯Ù„Ù†Ø§',
  follow: 'Ù¾ÛŒØ±ÙˆÛŒ Ú©Ø±Ù†Ø§',
  remember: 'ÛŒØ§Ø¯ Ø±Ú©Ú¾Ù†Ø§',
  forget: 'Ø¨Ú¾ÙˆÙ„Ù†Ø§',
  understand: 'Ø³Ù…Ø¬Ú¾Ù†Ø§',
  believe: 'ÛŒÙ‚ÛŒÙ† Ú©Ø±Ù†Ø§',
  agree: 'Ù…ØªØ¹Ù„Ù‚ ÛÙˆÙ†Ø§',
  refuse: 'Ø§Ù†Ú©Ø§Ø± Ú©Ø±Ù†Ø§',
  allow: 'Ø§Ø¬Ø§Ø²Øª Ø¯ÛŒÙ†Ø§',
  accept: 'Ù‚Ø¨ÙˆÙ„ Ú©Ø±Ù†Ø§',
  receive: 'ÙˆØµÙˆÙ„ Ú©Ø±Ù†Ø§',
  send: 'Ø¨Ú¾ÛŒØ¬Ù†Ø§',
  call: 'Ø¨Ù„Ø§Ù†Ø§',
  answer: 'Ø¬ÙˆØ§Ø¨ Ø¯ÛŒÙ†Ø§',
  explain: 'ÙˆØ¶Ø§Ø­Øª Ú©Ø±Ù†Ø§',
  describe: 'Ø¨ÛŒØ§Ù† Ú©Ø±Ù†Ø§',
  draw: 'Ø¨Ù†Ø§Ù†Ø§',
  paint: 'Ø±Ù†Ú¯Ù†Ø§',
  build: 'ØªØ¹Ù…ÛŒØ± Ú©Ø±Ù†Ø§',
  grow: 'Ø§Ú¯Ø§Ù†Ø§',
  cut: 'Ú©Ø§Ù¹Ù†Ø§',
  push: 'Ø¯Ú¾Ú©ÛŒÙ„Ù†Ø§',
  pull: 'Ú©Ú¾ÛŒÙ†Ú†Ù†Ø§',
  lift: 'Ø§Ù¹Ú¾Ø§Ù†Ø§',
  drop: 'Ú¯Ø±Ø§Ù†Ø§',
  throw: 'Ù¾Ú¾ÛŒÙ†Ú©Ù†Ø§',
  hit: 'Ù…Ø§Ø±Ù†Ø§',
  kick: 'Ù„Ø§Øª Ù…Ø§Ø±Ù†Ø§',
  hold: 'Ù¾Ú©Ú‘Ù†Ø§',
  carry: 'Ø§Ù¹Ú¾Ø§Ù†Ø§',
  put: 'Ø±Ú©Ú¾Ù†Ø§',
  rise: 'Ø§Ù¹Ú¾Ù†Ø§',
  raise: 'Ø§Ù¹Ú¾Ø§Ù†Ø§',
  fall: 'Ú¯Ø±Ù†Ø§',
  turn: 'Ù…Ú‘Ù†Ø§',
  fly: 'Ø§Ú‘Ù†Ø§',
  drive: 'Ú†Ù„Ø§Ù†Ø§',
  ride: 'Ø³ÙˆØ§Ø± ÛÙˆÙ†Ø§',
  visit: 'Ù…Ù„Ù†Ø§',
  meet: 'Ù…Ù„Ù†Ø§',
  arrive: 'Ù¾ÛÙ†Ú†Ù†Ø§',
  reach: 'Ù¾ÛÙ†Ú†Ù†Ø§',
  enter: 'Ø¯Ø§Ø®Ù„ ÛÙˆÙ†Ø§',
  return: 'ÙˆØ§Ù¾Ø³ Ø¢Ù†Ø§',
  wait: 'Ø§Ù†ØªØ¸Ø§Ø± Ú©Ø±Ù†Ø§',
  stay: 'Ø±ÛÙ†Ø§',
  live: 'Ø±ÛÙ†Ø§',
  die: 'Ù…Ø±Ù†Ø§',
  become: 'Ø¨Ù†Ù†Ø§',
  seem: 'Ù„Ú¯Ù†Ø§',
  appear: 'Ø¸Ø§ÛØ± ÛÙˆÙ†Ø§',
  exist: 'Ù…ÙˆØ¬ÙˆØ¯ ÛÙˆÙ†Ø§',
  happen: 'ÛÙˆÙ†Ø§',
  remain: 'Ø±ÛÙ†Ø§',
  continue: 'Ø¬Ø§Ø±ÛŒ Ø±ÛÙ†Ø§',
  succeed: 'Ú©Ø§Ù…ÛŒØ§Ø¨ ÛÙˆÙ†Ø§',
  fail: 'Ù†Ø§Ú©Ø§Ù… ÛÙˆÙ†Ø§',
  win: 'Ø¬ÛŒØªÙ†Ø§',
  lose: 'ÛØ§Ø±Ù†Ø§',
  save: 'Ø¨Ú†Ø§Ù†Ø§',
  spend: 'Ø®Ø±Ú† Ú©Ø±Ù†Ø§',
  waste: 'Ø¶Ø§Ø¦Ø¹ Ú©Ø±Ù†Ø§',
  share: 'Ø¨Ø§Ù†Ù¹Ù†Ø§',
  divide: 'ØªÙ‚Ø³ÛŒÙ… Ú©Ø±Ù†Ø§',
  join: 'Ø´Ø§Ù…Ù„ ÛÙˆÙ†Ø§',
  separate: 'Ø§Ù„Ú¯ Ú©Ø±Ù†Ø§',
  combine: 'Ù…Ù„Ø§Ù†Ø§',
  mix: 'Ù…Ù„Ø§Ù†Ø§',
  add: 'Ø´Ø§Ù…Ù„ Ú©Ø±Ù†Ø§',
  subtract: 'Ù…Ù†ÛØ§ Ú©Ø±Ù†Ø§',
  multiply: 'Ø¶Ø±Ø¨ Ú©Ø±Ù†Ø§',
  count: 'Ú¯Ù†Ù†Ø§',
  measure: 'Ù†Ø§Ù¾Ù†Ø§',
  weigh: 'ØªÙˆÙ„Ù†Ø§',
  choose: 'Ú†Ù†Ù†Ø§',
  select: 'Ù…Ù†ØªØ®Ø¨ Ú©Ø±Ù†Ø§',
  pick: 'Ú†Ù†Ù†Ø§',
  collect: 'Ø¬Ù…Ø¹ Ú©Ø±Ù†Ø§',
  gather: 'Ø§Ú©Ù¹Ú¾Ø§ Ú©Ø±Ù†Ø§',
  arrange: 'ØªØ±ØªÛŒØ¨ Ø¯ÛŒÙ†Ø§',
  organize: 'Ù…Ù†Ø¸Ù… Ú©Ø±Ù†Ø§',
  prepare: 'ØªÛŒØ§Ø± Ú©Ø±Ù†Ø§',
  fix: 'Ù¹Ú¾ÛŒÚ© Ú©Ø±Ù†Ø§',
  repair: 'Ù…Ø±Ù…Øª Ú©Ø±Ù†Ø§',
  clean: 'ØµØ§Ù Ú©Ø±Ù†Ø§',
  wash: 'Ø¯Ú¾ÙˆÙ†Ø§',
  hide: 'Ú†Ú¾Ù¾Ø§Ù†Ø§',
  seek: 'ØªÙ„Ø§Ø´ Ú©Ø±Ù†Ø§',
  search: 'ØªÙ„Ø§Ø´ Ú©Ø±Ù†Ø§',
  discover: 'Ø¯Ø±ÛŒØ§ÙØª Ú©Ø±Ù†Ø§',
  invent: 'Ø§ÛŒØ¬Ø§Ø¯ Ú©Ø±Ù†Ø§',
  create: 'ØªØ®Ù„ÛŒÙ‚ Ú©Ø±Ù†Ø§',
  produce: 'Ù¾ÛŒØ¯Ø§ Ú©Ø±Ù†Ø§',
  develop: 'ØªØ±Ù‚ÛŒ Ø¯ÛŒÙ†Ø§',
  improve: 'Ø¨ÛØªØ± Ú©Ø±Ù†Ø§',
  increase: 'Ø¨Ú‘Ú¾Ø§Ù†Ø§',
  decrease: 'Ú©Ù… Ú©Ø±Ù†Ø§',
  reduce: 'Ú©Ù… Ú©Ø±Ù†Ø§',
  expand: 'Ù¾Ú¾ÛŒÙ„Ø§Ù†Ø§',
  fill: 'Ø¨Ú¾Ø±Ù†Ø§',
  cover: 'ÚˆÚ¾Ø§Ù†Ù¾Ù†Ø§',
  wrap: 'Ù„Ù¾ÛŒÙ¹Ù†Ø§',
  tie: 'Ø¨Ø§Ù†Ø¯Ú¾Ù†Ø§',
  untie: 'Ú©Ú¾ÙˆÙ„Ù†Ø§',
  borrow: 'Ø§Ø¯Ú¾Ø§Ø± Ù„ÛŒÙ†Ø§',
  lend: 'Ø§Ø¯Ú¾Ø§Ø± Ø¯ÛŒÙ†Ø§',
  pay: 'Ø§Ø¯Ø§ Ú©Ø±Ù†Ø§',
  earn: 'Ú©Ù…Ø§Ù†Ø§',
  steal: 'Ú†ÙˆØ±ÛŒ Ú©Ø±Ù†Ø§',
  fight: 'Ù„Ú‘Ù†Ø§',
  defend: 'Ø¯ÙØ§Ø¹ Ú©Ø±Ù†Ø§',
  protect: 'Ø­ÙØ§Ø¸Øª Ú©Ø±Ù†Ø§',
  rescue: 'Ø¨Ú†Ø§Ù†Ø§',
  warn: 'Ø®Ø¨Ø±Ø¯Ø§Ø± Ú©Ø±Ù†Ø§',
  threaten: 'Ø¯Ú¾Ù…Ú©ÛŒ Ø¯ÛŒÙ†Ø§',
  promise: 'ÙˆØ¹Ø¯Û Ú©Ø±Ù†Ø§',
  decide: 'ÙÛŒØµÙ„Û Ú©Ø±Ù†Ø§',
  hope: 'Ø§Ù…ÛŒØ¯ Ú©Ø±Ù†Ø§',
  wish: 'Ø®ÙˆØ§ÛØ´ Ú©Ø±Ù†Ø§',
  imagine: 'ØªØµÙˆØ± Ú©Ø±Ù†Ø§',
  guess: 'Ø§Ù†Ø¯Ø§Ø²Û Ù„Ú¯Ø§Ù†Ø§',
  suppose: 'ÙØ±Ø¶ Ú©Ø±Ù†Ø§',
  doubt: 'Ø´Ú© Ú©Ø±Ù†Ø§',
  trust: 'Ø¨Ú¾Ø±ÙˆØ³Û Ú©Ø±Ù†Ø§',
  respect: 'Ø§Ø­ØªØ±Ø§Ù… Ú©Ø±Ù†Ø§',
  admire: 'ØªØ¹Ø±ÛŒÙ Ú©Ø±Ù†Ø§',
  praise: 'ØªØ¹Ø±ÛŒÙ Ú©Ø±Ù†Ø§',
  blame: 'Ø§Ù„Ø²Ø§Ù… Ù„Ú¯Ø§Ù†Ø§',
  forgive: 'Ù…Ø¹Ø§Ù Ú©Ø±Ù†Ø§',
  thank: 'Ø´Ú©Ø±ÛŒÛ Ø§Ø¯Ø§ Ú©Ø±Ù†Ø§',
  apologize: 'Ù…Ø¹Ø§ÙÛŒ Ù…Ø§Ù†Ú¯Ù†Ø§',
  invite: 'Ø¯Ø¹ÙˆØª Ø¯ÛŒÙ†Ø§',
  forbid: 'Ù…Ù†Ø¹ Ú©Ø±Ù†Ø§',
  encourage: 'Ø­ÙˆØµÙ„Û Ø§ÙØ²Ø§Ø¦ÛŒ Ú©Ø±Ù†Ø§',
  surprise: 'Ø­ÛŒØ±Ø§Ù† Ú©Ø±Ù†Ø§',
  frighten: 'ÚˆØ±Ø§Ù†Ø§',
  scare: 'ÚˆØ±Ø§Ù†Ø§',
  amuse: 'Ù…Ø­Ø¸ÙˆØ¸ Ú©Ø±Ù†Ø§',
  entertain: 'ØªÙØ±ÛŒØ­ Ú©Ø±Ù†Ø§',
  celebrate: 'Ù…Ù†Ø§Ù†Ø§',
  enjoy: 'Ù„Ø·Ù Ø§Ù¹Ú¾Ø§Ù†Ø§',
  suffer: 'ØªÚ©Ù„ÛŒÙ Ø§Ù¹Ú¾Ø§Ù†Ø§',
  cry: 'Ø±ÙˆÙ†Ø§',
  laugh: 'ÛÙ†Ø³Ù†Ø§',
  smile: 'Ù…Ø³Ú©Ø±Ø§Ù†Ø§',
  whisper: 'Ø³Ø±Ú¯ÙˆØ´ÛŒ Ú©Ø±Ù†Ø§',
  shout: 'Ú†Ù„Ø§Ù†Ø§',
  scream: 'Ú†ÛŒØ®Ù†Ø§',
  sigh: 'Ø¢Û Ø¨Ú¾Ø±Ù†Ø§',
  yawn: 'Ø¬Ù…Ø§Ø¦ÛŒ Ù„ÛŒÙ†Ø§',
  nod: 'Ø³Ø± ÛÙ„Ø§Ù†Ø§',
  wave: 'ÛØ§ØªÚ¾ ÛÙ„Ø§Ù†Ø§',
  clap: 'ØªØ§Ù„ÛŒ Ø¨Ø¬Ø§Ù†Ø§',
  knock: 'Ø¯Ø³ØªÚ© Ø¯ÛŒÙ†Ø§',
  bite: 'Ú©Ø§Ù¹Ù†Ø§',
  chew: 'Ú†Ø¨Ø§Ù†Ø§',
  smell: 'Ø³ÙˆÙ†Ú¯Ú¾Ù†Ø§',
  taste: 'Ú†Ú©Ú¾Ù†Ø§',
  touch: 'Ú†Ú¾ÙˆÙ†Ø§',
  feel: 'Ù…Ø­Ø³ÙˆØ³ Ú©Ø±Ù†Ø§',
  watch: 'Ø¯ÛŒÚ©Ú¾Ù†Ø§',
  look: 'Ø¯ÛŒÚ©Ú¾Ù†Ø§',
  listen: 'Ø³Ù†Ù†Ø§',
  bark: 'Ø¨Ú¾ÙˆÙ†Ú©Ù†Ø§',

  // === Adverbs ===
  quickly: 'Ø¬Ù„Ø¯ÛŒ Ø³Û’',
  slowly: 'Ø¢ÛØ³ØªÛ',
  happily: 'Ø®ÙˆØ´ÛŒ Ø³Û’',
  loudly: 'Ø§ÙˆÙ†Ú†ÛŒ Ø¢ÙˆØ§Ø² Ø³Û’',
  carefully: 'Ø§Ø­ØªÛŒØ§Ø· Ø³Û’',
  quietly: 'Ø®Ø§Ù…ÙˆØ´ÛŒ Ø³Û’',
  beautifully: 'Ø®ÙˆØ¨ØµÙˆØ±ØªÛŒ Ø³Û’',
  badly: 'Ø¨Ø±ÛŒ Ø·Ø±Ø­',
  always: 'ÛÙ…ÛŒØ´Û',
  never: 'Ú©Ø¨Ú¾ÛŒ Ù†ÛÛŒÚº',
  often: 'Ø§Ú©Ø«Ø±',
  sometimes: 'Ú©Ø¨Ú¾ÛŒ Ú©Ø¨Ú¾ÛŒ',
  usually: 'Ø¹Ø§Ù… Ø·ÙˆØ± Ù¾Ø±',
  rarely: 'Ø´Ø§Ø° Ùˆ Ù†Ø§Ø¯Ø±',
  definitely: 'ÛŒÙ‚ÛŒÙ†Ø§Ù‹',
  probably: 'Ø´Ø§ÛŒØ¯',
  certainly: 'Ø¨Ù„Ø§Ø´Ø¨Û',
  perfectly: 'Ø¨Ø§Ù„Ú©Ù„ Ø¯Ø±Ø³Øª',
  recently: 'Ø­Ø§Ù„ ÛÛŒ Ù…ÛŒÚº',
  immediately: 'ÙÙˆØ±ÛŒ Ø·ÙˆØ± Ù¾Ø±',
  now: 'Ø§Ø¨',
  then: 'ØªØ¨',
  here: 'ÛŒÛØ§Úº',
  there: 'ÙˆÛØ§Úº',
  everywhere: 'ÛØ± Ø¬Ú¯Û',
  somewhere: 'Ú©ÛÛŒÚº',
  anywhere: 'Ú©ÛÛŒÚº Ø¨Ú¾ÛŒ',
  nowhere: 'Ú©ÛÛŒÚº Ù†ÛÛŒÚº',
  again: 'Ø¯ÙˆØ¨Ø§Ø±Û',
  also: 'Ø¨Ú¾ÛŒ',
  too: 'Ø¨Ú¾ÛŒ',
  very: 'Ø¨ÛØª',
  quite: 'Ú©Ø§ÙÛŒ',
  almost: 'ØªÙ‚Ø±ÛŒØ¨Ø§Ù‹',
  nearly: 'Ù‚Ø±ÛŒØ¨ Ù‚Ø±ÛŒØ¨',
  already: 'Ù¾ÛÙ„Û’ ÛÛŒ',
  still: 'Ø§Ø¨ Ø¨Ú¾ÛŒ',
  yet: 'Ø§Ø¨Ú¾ÛŒ ØªÚ©',
  just: 'ØµØ±Ù',
  ever: 'Ú©Ø¨Ú¾ÛŒ',
  once: 'Ø§ÛŒÚ© Ø¨Ø§Ø±',
  twice: 'Ø¯Ùˆ Ø¨Ø§Ø±',
  forward: 'Ø¢Ú¯Û’',
  backward: 'Ù¾ÛŒÚ†Ú¾Û’',
  upward: 'Ø§ÙˆÙ¾Ø± Ú©ÛŒ Ø·Ø±Ù',
  downward: 'Ù†ÛŒÚ†Û’ Ú©ÛŒ Ø·Ø±Ù',
  ahead: 'Ø¢Ú¯Û’',

  // === Grammar Terms ===
  noun: 'Ø§Ø³Ù…',
  verb: 'ÙØ¹Ù„',
  adjective: 'ØµÙØª',
  adverb: 'Ù…ØªØ¹Ù„Ù‚',
  pronoun: 'Ø¶Ù…ÛŒØ±',
  preposition: 'Ø­Ø±Ù Ø¬Ø§Ø±',
  conjunction: 'Ø­Ø±Ù Ø¹Ø·Ù',
  interjection: 'Ø­Ø±Ù Ù†Ø¯Ø§',
  article: 'Ø­Ø±Ù ØªØ¹Ø±ÛŒÙ',
  common: 'Ø¹Ø§Ù…',
  proper: 'Ø®Ø§Øµ',
  abstract: 'ØªØ¬Ø±ÛŒØ¯ÛŒ',
  collective: 'Ø§Ø¬ØªÙ…Ø§Ø¹ÛŒ',
  concrete: 'Ù…Ø§Ø¯ÛŒ',
  countable: 'Ú¯Ù†Ù†Û’ ÙˆØ§Ù„Ø§',
  uncountable: 'Ù†Û Ú¯Ù†Ù†Û’ ÙˆØ§Ù„Ø§',
  singular: 'ÙˆØ§Ø­Ø¯',
  plural: 'Ø¬Ù…Ø¹',
  definite: 'Ù…Ø¹ÛŒÙ†',
  indefinite: 'ØºÛŒØ± Ù…Ø¹ÛŒÙ†',
  quantitative: 'Ù…Ù‚Ø¯Ø§Ø±ÛŒ',
  qualitative: 'ØªÙˆØµÛŒÙÛŒ',
  compound: 'Ù…Ø±Ú©Ø¨',
  subject: 'ÙØ§Ø¹Ù„',
  object: 'Ù…ÙØ¹ÙˆÙ„',
  tense: 'Ø²Ù…Ø§Ù†Û',
  voice: 'ØµØ¯Ø§',
  active: 'ÙØ¹Ø§Ù„',
  passive: 'Ù…Ø¬ÛÙˆÙ„',
  phrase: 'ÙÙ‚Ø±Û',
  clause: 'Ø¬Ø²Ùˆ Ø¬Ù…Ù„Û',
  sentence: 'Ø¬Ù…Ù„Û',
  paragraph: 'Ù¾ÛŒØ±Ø§Ú¯Ø±Ø§Ù',
  synonym: 'Ù…ØªØ±Ø§Ø¯Ù',
  antonym: 'Ù…ØªØ¶Ø§Ø¯',
  syllable: 'Ø­Ø±Ù',
  phonetics: 'ØµÙˆØªÛŒØ§Øª',
  prefix: 'Ø³Ø§Ø¨Ù‚Û',
  suffix: 'Ù„Ø§Ø­Ù‚Û',
  modal: 'Ù…ÙˆÚˆÙ„',
  collocation: 'ØªÙ„Ø§Ø²Ù…',
  figure: 'Ø´Ú©Ù„',
  punctuation: 'Ø¹Ù„Ø§Ù…Ø§Øª Ø§ÙˆÙ‚Ø§Ù',
  narration: 'Ø±ÙˆØ§ÛŒØª',
  morphology: 'ØµØ±Ù',
  poetry: 'Ø´Ø§Ø¹Ø±ÛŒ',
  stanza: 'Ø¨Ù†Ø¯',
  rhyme: 'Ù‚Ø§ÙÛŒÛ',
  metaphor: 'Ø§Ø³ØªØ¹Ø§Ø±Û',
  simile: 'ØªØ´Ø¨ÛŒÛ',
  personification: 'ØªØ´Ø®ÛŒØµ',
  alliteration: 'ÛÙ… Ø¢ÙˆØ§Ø²',
  direct: 'Ø¨Ø±Ø§Û Ø±Ø§Ø³Øª',
  indirect: 'Ø¨Ø§Ù„ÙˆØ§Ø³Ø·Û',
  reported: 'Ù…Ù†Ù‚ÙˆÙ„',
  denotation: 'Ù„ØºÙˆÛŒ Ù…Ø¹Ù†ÛŒ',
  connotation: 'Ù…ÙÛÙˆÙ…',
  semicolon: 'Ù†Ù‚Ø·Û ÙˆØ§Ø± Ú©Ø§Ù…Ø§',
  stylistics: 'Ø§Ø³Ù„ÙˆØ¨ÛŒØ§Øª',
  obligation: 'ÙØ±Ø¶',
  necessity: 'Ø¶Ø±ÙˆØ±Øª',
  simple: 'Ø³Ø§Ø¯Û',

  // === Determiners ===
  a: 'Ø§ÛŒÚ©',
  an: 'Ø§ÛŒÚ©',
  the: 'ÛŒÛ',
  this: 'ÛŒÛ',
  that: 'ÙˆÛ',
  these: 'ÛŒÛ',
  those: 'ÙˆÛ',
  each: 'ÛØ± Ø§ÛŒÚ©',
  every: 'ÛØ±',
  all: 'Ø³Ø¨',
  both: 'Ø¯ÙˆÙ†ÙˆÚº',
  few: 'Ú†Ù†Ø¯',
  any: 'Ú©ÙˆØ¦ÛŒ',
  no: 'Ù†ÛÛŒÚº',
  none: 'Ú©ÙˆØ¦ÛŒ Ù†ÛÛŒÚº',
  more: 'Ø²ÛŒØ§Ø¯Û',
  most: 'Ø²ÛŒØ§Ø¯Û ØªØ±',
  less: 'Ú©Ù…',
  least: 'Ú©Ù… Ø³Û’ Ú©Ù…',
  sufficient: 'Ú©Ø§ÙÛŒ',
  plenty: 'Ú©Ø§ÙÛŒ',

  // === Prepositions ===
  above: 'Ø§ÙˆÙ¾Ø±',
  across: 'Ø¢Ø± Ù¾Ø§Ø±',
  after: 'Ø¨Ø¹Ø¯',
  against: 'Ø®Ù„Ø§Ù',
  along: 'Ø³Ø§ØªÚ¾',
  among: 'Ø¯Ø±Ù…ÛŒØ§Ù†',
  around: 'Ú¯Ø±Ø¯',
  at: 'Ù¾Ø±',
  before: 'Ù¾ÛÙ„Û’',
  behind: 'Ù¾ÛŒÚ†Ú¾Û’',
  below: 'Ù†ÛŒÚ†Û’',
  beneath: 'Ù†ÛŒÚ†Û’',
  beside: 'Ù¾Ø§Ø³',
  between: 'Ø¯Ø±Ù…ÛŒØ§Ù†',
  beyond: 'Ø¢Ú¯Û’',
  by: 'Ø³Û’',
  down: 'Ù†ÛŒÚ†Û’',
  during: 'Ø¯ÙˆØ±Ø§Ù†',
  except: 'Ø³ÙˆØ§Ø¦Û’',
  for: 'Ù„Ø¦Û’',
  from: 'Ø³Û’',
  in: 'Ù…ÛŒÚº',
  into: 'Ø§Ù†Ø¯Ø±',
  near: 'Ù¾Ø§Ø³',
  of: 'Ú©Ø§',
  off: 'Ø¯ÙˆØ±',
  on: 'Ù¾Ø±',
  out: 'Ø¨Ø§ÛØ±',
  over: 'Ø§ÙˆÙ¾Ø±',
  through: 'Ú©Û’ Ø°Ø±ÛŒØ¹Û’',
  throughout: 'Ø¨Ú¾Ø±',
  to: 'Ú©Ùˆ',
  toward: 'Ú©ÛŒ Ø·Ø±Ù',
  towards: 'Ú©ÛŒ Ø·Ø±Ù',
  under: 'Ù†ÛŒÚ†Û’',
  underneath: 'Ø¨Ø§Ù„Ú©Ù„ Ù†ÛŒÚ†Û’',
  until: 'ØªÚ©',
  up: 'Ø§ÙˆÙ¾Ø±',
  upon: 'Ù¾Ø±',
  with: 'Ø³Ø§ØªÚ¾',
  within: 'Ø§Ù†Ø¯Ø±',
  without: 'Ø¨ØºÛŒØ±',

  // === Conjunctions ===
  and: 'Ø§ÙˆØ±',
  but: 'Ù„ÛŒÚ©Ù†',
  or: 'ÛŒØ§',
  because: 'Ú©ÛŒÙˆÙ†Ú©Û',
  although: 'Ø§Ú¯Ø±Ú†Û',
  so: 'ØªÙˆ',
  unless: 'Ø¬Ø¨ ØªÚ© Ù†Û',
  while: 'Ø¬Ø¨Ú©Û',
  since: 'Ø¬Ø¨ Ø³Û’',
  if: 'Ø§Ú¯Ø±',
  when: 'Ø¬Ø¨',
  where: 'Ø¬ÛØ§Úº',
  neither: 'Ù†Û ... Ø§ÙˆØ± Ù†Û',
  nor: 'Ù†Û ... Ø§ÙˆØ± Ù†Û',
  not: 'Ù†ÛÛŒÚº',
  only: 'ØµØ±Ù',
  however: 'Ù„ÛŒÚ©Ù†',
  therefore: 'Ø§Ø³ Ù„Ø¦Û’',
  consequently: 'Ù†ØªÛŒØ¬ØªØ§Ù‹',
  moreover: 'Ù…Ø²ÛŒØ¯',
  nevertheless: 'Ø¨Ø§ÙˆØ¬ÙˆØ¯',
  besides: 'Ø§Ø³ Ú©Û’ Ø¹Ù„Ø§ÙˆÛ',

  // === Modals ===
  can: 'Ø³Ú©ØªØ§ ÛÛ’',
  could: 'Ø³Ú©ØªØ§ ØªÚ¾Ø§',
  may: 'ÛÙˆ Ø³Ú©ØªØ§ ÛÛ’',
  might: 'ÛÙˆ Ø³Ú©ØªØ§ ØªÚ¾Ø§',
  must: 'Ù„Ø§Ø²Ù…ÛŒ',
  shall: 'Ú¯Ø§',
  should: 'Ú†Ø§ÛÛŒÛ’',
  will: 'Ú¯Ø§',
  would: 'Ú¯Ø§ ØªÚ¾Ø§',
  ought: 'Ú†Ø§ÛÛŒÛ’',

  // === Common words ===
  man: 'Ø¢Ø¯Ù…ÛŒ',
  woman: 'Ø¹ÙˆØ±Øª',
  boy: 'Ù„Ú‘Ú©Ø§',
  girl: 'Ù„Ú‘Ú©ÛŒ',
  children: 'Ø¨Ú†Û’',
  student: 'Ø·Ø§Ù„Ø¨ Ø¹Ù„Ù…',
  teacher: 'Ø§Ø³ØªØ§Ø¯',
  doctor: 'ÚˆØ§Ú©Ù¹Ø±',
  patient: 'Ù…Ø±ÛŒØ¶',
  garden: 'Ø¨Ø§Øº',
  park: 'Ù¾Ø§Ø±Ú©',
  street: 'Ú¯Ù„ÛŒ',
  road: 'Ø³Ú‘Ú©',
  shop: 'Ø¯Ú©Ø§Ù†',
  cat: 'Ø¨Ù„ÛŒ',
  mouse: 'Ú†ÙˆÛØ§',
  horse: 'Ú¯Ú¾ÙˆÚ‘Ø§',
  tiger: 'Ø´ÛŒØ±',
  lion: 'Ø´ÛŒØ±',
  fish: 'Ù…Ú†Ú¾Ù„ÛŒ',
  monkey: 'Ø¨Ù†Ø¯Ø±',
  rabbit: 'Ø®Ø±Ú¯ÙˆØ´',
  duck: 'Ø¨Ø·Ø®',
  hen: 'Ù…Ø±ØºÛŒ',
  cow: 'Ú¯Ø§Ø¦Û’',
  goat: 'Ø¨Ú©Ø±ÛŒ',
  sheep: 'Ø¨Ú¾ÛŒÚ‘',
  zoo: 'Ú†Ú‘ÛŒØ§ Ú¯Ú¾Ø±',
  east: 'Ù…Ø´Ø±Ù‚',
  west: 'Ù…ØºØ±Ø¨',
  north: 'Ø´Ù…Ø§Ù„',
  south: 'Ø¬Ù†ÙˆØ¨',

  // === Numbers ===
  one: 'Ø§ÛŒÚ©',
  two: 'Ø¯Ùˆ',
  three: 'ØªÛŒÙ†',
  four: 'Ú†Ø§Ø±',
  five: 'Ù¾Ø§Ù†Ú†',
  six: 'Ú†Ú¾',
  seven: 'Ø³Ø§Øª',
  eight: 'Ø¢Ù¹Ú¾',
  nine: 'Ù†Ùˆ',
  ten: 'Ø¯Ø³',

  // === Question Words ===
  what: 'Ú©ÛŒØ§',
  who: 'Ú©ÙˆÙ†',
  whom: 'Ú©Ø³ Ú©Ùˆ',
  whose: 'Ú©Ø³ Ú©Ø§',
  which: 'Ú©ÙˆÙ† Ø³Ø§',
  why: 'Ú©ÛŒÙˆÚº',
  how: 'Ú©ÛŒØ³Û’',

  // === Pronouns ===
  i: 'Ù…ÛŒÚº',
  me: 'Ù…Ø¬Ú¾Û’',
  my: 'Ù…ÛŒØ±Ø§',
  mine: 'Ù…ÛŒØ±Ø§',
  you: 'ØªÙ…',
  your: 'ØªÙ…ÛØ§Ø±Ø§',
  yours: 'ØªÙ…ÛØ§Ø±Ø§',
  he: 'ÙˆÛ',
  him: 'Ø§Ø³Û’',
  his: 'Ø§Ø³ Ú©Ø§',
  she: 'ÙˆÛ',
  her: 'Ø§Ø³Û’',
  hers: 'Ø§Ø³ Ú©Ø§',
  we: 'ÛÙ…',
  us: 'ÛÙ…ÛŒÚº',
  our: 'ÛÙ…Ø§Ø±Ø§',
  ours: 'ÛÙ…Ø§Ø±Ø§',
  they: 'ÙˆÛ',
  them: 'Ø§Ù†ÛÛŒÚº',
  their: 'Ø§Ù† Ú©Ø§',
  theirs: 'Ø§Ù† Ú©Ø§',
  itself: 'Ø®ÙˆØ¯',
  myself: 'Ø®ÙˆØ¯',
  yourself: 'Ø®ÙˆØ¯',
  himself: 'Ø®ÙˆØ¯',
  herself: 'Ø®ÙˆØ¯',
  ourselves: 'Ø®ÙˆØ¯',
  themselves: 'Ø®ÙˆØ¯',
  other: 'Ø¯ÙˆØ³Ø±Ø§',
  another: 'Ø¯ÙˆØ³Ø±Ø§',
  anybody: 'Ú©ÙˆØ¦ÛŒ',
  everybody: 'Ø³Ø¨',
  nobody: 'Ú©ÙˆØ¦ÛŒ Ù†ÛÛŒÚº',
  everything: 'Ø³Ø¨ Ú©Ú†Ú¾',
  nothing: 'Ú©Ú†Ú¾ Ù†ÛÛŒÚº',
  something: 'Ú©Ú†Ú¾',
  everyone: 'ÛØ± Ú©ÙˆØ¦ÛŒ',
  noone: 'Ú©ÙˆØ¦ÛŒ Ù†ÛÛŒÚº',
  someone: 'Ú©ÙˆØ¦ÛŒ',
  anyone: 'Ú©ÙˆØ¦ÛŒ',

  // === Additional academic words ===
  personal: 'Ø°Ø§ØªÛŒ',
  possessive: 'Ù…Ù„Ú©Ø§Ù†ÛŒ',
  reflexive: 'Ø§Ù†Ø¹Ú©Ø§Ø³ÛŒ',
  relative: 'Ù…ÙˆØµÙˆÙ„ÛŒ',
  demonstrative: 'Ø§Ø´Ø§Ø±Ø§ØªÛŒ',
  interrogative: 'Ø§Ø³ØªÙÛØ§Ù…ÛŒ',
  intensive: 'ØªØ§Ú©ÛŒØ¯ÛŒ',
  emphatic: 'ØªØ§Ú©ÛŒØ¯ÛŒ',
  reciprocal: 'Ù…ØªÙ‚Ø§Ø¨Ù„',
  homophone: 'ÛÙ… Ø¢ÙˆØ§Ø²',
  homonym: 'ÛÙ… Ù†Ø§Ù…',
  root: 'Ø¬Ú‘',
  base: 'Ø¨Ù†ÛŒØ§Ø¯',
  gender: 'Ø¬Ù†Ø³',
  masculine: 'Ù…Ø°Ú©Ø±',
  feminine: 'Ù…Ø¤Ù†Ø«',
  neutral: 'ØºÛŒØ± Ø¬Ø§Ù†Ø¨Ø¯Ø§Ø±',
  predicate: 'Ø®Ø¨Ø±',
  complement: 'ØªÚ©Ù…Ù„Û',
  comparison: 'ØªÙ‚Ø§Ø¨Ù„',
  positive: 'Ø§Ø«Ø¨Ø§ØªÛŒ',
  comparative: 'ØªÙØ¶ÛŒÙ„ÛŒ',
  superlative: 'Ø§Ø¹Ù„ÛŒÙ°',
  auxiliary: 'Ù…Ø¹Ø§ÙˆÙ†',
  linking: 'Ø±Ø¨Ø·',
  transitive: 'Ù…ØªØ¹Ø¯ÛŒ',
  intransitive: 'Ù„Ø§Ø²Ù…',
  colon: 'Ù†Ù‚Ø·Û ÙˆØ§Ø±',
  comma: 'Ú©ÙˆÙ…Ø§',
  apostrophe: 'Ø§Ù„ÙÛŒÙ',
  capital: 'Ø¨Ú‘Ø§ Ø­Ø±Ù',
  vowel: 'Ù…ØªØ­Ø±Ú©',
  consonant: 'Ø³Ø§Ú©Ù†',
  literature: 'Ø§Ø¯Ø¨',
  prose: 'Ù†Ø«Ø±',
  poem: 'Ù†Ø¸Ù…',
  narrative: 'Ø¨ÛŒØ§Ù†ÛŒÛ',
  descriptive: 'ØªÙˆØµÛŒÙÛŒ',
  introduction: 'ØªØ¹Ø§Ø±Ù',
  title: 'Ø¹Ù†ÙˆØ§Ù†',
  heading: 'Ø³Ø±Ø®ÛŒ',
  conclusion: 'Ù†ØªÛŒØ¬Û',
  summary: 'Ø®Ù„Ø§ØµÛ',
  content: 'Ù…ÙˆØ§Ø¯',
  index: 'Ø§Ø´Ø§Ø±ÛŒÛ',
  source: 'Ù…Ø§Ø®Ø°',
  text: 'Ù…ØªÙ†',
  context: 'Ø³ÛŒØ§Ù‚ Ùˆ Ø³Ø¨Ø§Ù‚',
  purpose: 'Ù…Ù‚ØµØ¯',
  audience: 'Ø³Ø§Ù…Ø¹ÛŒÙ†',
  genre: 'ØµÙ†Ù',
  theme: 'Ù…ÙˆØ¶ÙˆØ¹',
  plot: 'Ù¾Ù„Ø§Ù¹',
  setting: 'ØªØ±ØªÛŒØ¨',
  character: 'Ú©Ø±Ø¯Ø§Ø±',
  conflict: 'ØªØµØ§Ø¯Ù…',
  resolution: 'Ø­Ù„',
  climax: 'Ø¹Ø±ÙˆØ¬',
  moral: 'Ø³Ø¨Ù‚',
  cursive: 'Ú©Ø±Ø³ÛŒÙˆ',
  gerund: 'Ø§Ø³Ù… Ù…ØµØ¯Ø±',
  participle: 'ØµÙØª ÙØ¹Ù„ÛŒ',
  infinitive: 'Ù…ØµØ¯Ø±',
  verbal: 'ÙØ¹Ù„ÛŒ',
  subordinate: 'ØªØ§Ø¨Ø¹',
  coordinate: 'ÛÙ… Ø³Ø·Ø­',
  correlative: 'Ù…ØªØ¹Ù„Ù‚',
  conditional: 'Ø´Ø±Ø·ÛŒ',
  euphemism: 'Ø®ÙˆØ´ ÙÛÙ…ÛŒ',
  oxymoron: 'Ù…ØªØ¶Ø§Ø¯ Ø§Ù„ÙØ§Ø¸',
  hyphen: 'Ù†Ø´Ø§Ù† Ø±Ø¨Ø·',
  adjectival: 'ØµÙØª Ø³Û’ Ù…ØªØ¹Ù„Ù‚',
  adverbial: 'Ù…ØªØ¹Ù„Ù‚ Ø³Û’ Ù…ØªØ¹Ù„Ù‚',
  prepositional: 'Ø­Ø±Ù Ø¬Ø§Ø± Ø³Û’ Ù…ØªØ¹Ù„Ù‚',
  fiction: 'Ø§ÙØ³Ø§Ù†Û',
  drama: 'ÚˆØ±Ø§Ù…Ø§',
  safari: 'Ø³ÙØ§Ø±ÛŒ',
  jungle: 'Ø¬Ù†Ú¯Ù„',
  poster: 'Ù¾ÙˆØ³Ù¹Ø±',
  banner: 'Ø¨ÛŒÙ†Ø±',
  board: 'Ø¨ÙˆØ±Úˆ',
  click: 'Ú©Ù„Ú©',
  identify: 'Ù¾ÛÚ†Ø§Ù†Ù†Ø§',
  check: 'Ú†ÛŒÚ© Ú©Ø±ÛŒÚº',
  previous: 'Ù¾Ú†Ú¾Ù„Ø§',
  submit: 'Ø¬Ù…Ø¹ Ú©Ø±ÙˆØ§Ø¦ÛŒÚº',
  reset: 'Ø¯ÙˆØ¨Ø§Ø±Û ØªØ±ØªÛŒØ¨',
  task: 'Ú©Ø§Ù…',
  stage: 'Ù…Ø±Ø­Ù„Û',
  round: 'Ø¯ÙˆØ±',
  practice: 'Ù…Ø´Ù‚',
  exercise: 'Ù…Ø´Ù‚',
  quiz: 'Ú©ÙˆØ¦Ø²',
  points: 'Ù¾ÙˆØ§Ø¦Ù†Ù¹Ø³',
  progress: 'Ù¾ÛŒØ´Ø±ÙØª',
  mistake: 'ØºÙ„Ø·ÛŒ',
  pause: 'ØªÙˆÙ‚Ù',
  skip: 'Ú†Ú¾ÙˆÚ‘ÛŒÚº',
  undo: 'ÙˆØ§Ù¾Ø³',
  redo: 'Ø¯ÙˆØ¨Ø§Ø±Û Ú©Ø±ÛŒÚº',
  cancel: 'Ù…Ù†Ø³ÙˆØ®',
  confirm: 'ØªØµØ¯ÛŒÙ‚',
  edit: 'ØªØ±Ù…ÛŒÙ…',
  delete: 'Ø­Ø°Ù',
  remove: 'ÛÙ¹Ø§Ø¦ÛŒÚº',
  download: 'ÚˆØ§Ø¤Ù† Ù„ÙˆÚˆ',
  upload: 'Ø§Ù¾ Ù„ÙˆÚˆ',
  settings: 'ØªØ±ØªÛŒØ¨Ø§Øª',
  options: 'Ø§Ø®ØªÛŒØ§Ø±Ø§Øª',
  menu: 'Ù…ÛŒÙ†Ùˆ',
  home: 'Ú¯Ú¾Ø±',
  exit: 'Ø¨Ø§ÛØ± Ù†Ú©Ù„ÛŒÚº',
  quit: 'Ú†Ú¾ÙˆÚ‘ÛŒÚº',
  enable: 'ÙØ¹Ø§Ù„',
  disable: 'ØºÛŒØ± ÙØ¹Ø§Ù„',
  success: 'Ú©Ø§Ù…ÛŒØ§Ø¨ÛŒ',
  error: 'ØºÙ„Ø·ÛŒ',
  warning: 'Ø§Ù†ØªØ¨Ø§Û',
  info: 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª',
  featured: 'Ù†Ù…Ø§ÛŒØ§Úº',
  best: 'Ø¨ÛØªØ±ÛŒÙ†',
  worst: 'Ø¨Ø¯ØªØ±ÛŒÙ†',
  fun: 'Ù…Ø²Û',
  awesome: 'Ø²Ø¨Ø±Ø¯Ø³Øª',
  cool: 'Ù¹Ú¾Ù†ÚˆØ§',
  cousin: 'Ú©Ø²Ù†',
  sand: 'Ø±ÛŒØª',
  bone: 'ÛÚˆÛŒ',
  tail: 'Ø¯Ù…',
  wing: 'Ù¾Ø±',
  fur: 'Ø¨Ø§Ù„',
  feather: 'Ù¾Ø±',
  scale: 'Ú†Ú¾Ù„Ú©Ø§',
  shell: 'Ø®ÙˆÙ„',
  nest: 'Ú¯Ú¾ÙˆÙ†Ø³Ù„Û',
  egg: 'Ø§Ù†ÚˆÛ',
  hole: 'Ø³ÙˆØ±Ø§Ø®',
  net: 'Ø¬Ø§Ù„',
  trap: 'Ø¬Ø§Ù„',
  cage: 'Ù¾Ù†Ø¬Ø±Û',
  rope: 'Ø±Ø³ÛŒ',
  chain: 'Ø²Ù†Ø¬ÛŒØ±',
  stick: 'Ú†Ú¾Ú‘ÛŒ',
  sword: 'ØªÙ„ÙˆØ§Ø±',
  shield: 'ÚˆÚ¾Ø§Ù„',
  crown: 'ØªØ§Ø¬',
  throne: 'ØªØ®Øª',
  medal: 'Ù…ÛŒÚˆÙ„',
  trophy: 'Ù¹Ø±Ø§ÙÛŒ',
  reward: 'Ø§Ù†Ø¹Ø§Ù…',
  business: 'Ú©Ø§Ø±ÙˆØ¨Ø§Ø±',
  company: 'Ú©Ù…Ù¾Ù†ÛŒ',
  meeting: 'Ù…Ù„Ø§Ù‚Ø§Øª',
  party: 'Ù¾Ø§Ø±Ù¹ÛŒ',
  travel: 'Ø³ÙØ±',
};

// ============================================================
// ROMAN URDU TRANSLITERATIONS (for TTS speech synthesis)
// When no Urdu voice is available on the system, the browser
// can still pronounce Roman Urdu text using a standard voice.
// ============================================================

export const WORD_TRANSLITERATIONS: Record<string, string> = {
  // === Nouns ===
  happiness: 'khushi',
  team: 'team',
  London: 'London',
  dog: 'kutta',
  bunch: 'guchha',
  courage: 'himmat',
  Ganges: 'Ganges',
  book: 'kitaab',
  table: 'mez',
  car: 'gaari',
  apple: 'seb',
  school: 'school',
  city: 'sheher',
  mountain: 'pahaar',
  tree: 'darakht',
  flower: 'phool',
  animal: 'jaanwar',
  bird: 'parinda',
  ocean: 'samandar',
  star: 'sitaara',
  house: 'ghar',
  chair: 'kursi',
  door: 'darwaaza',
  window: 'khidki',
  food: 'khana',
  water: 'paani',
  fire: 'aag',
  earth: 'zameen',
  air: 'hawa',
  sun: 'sooraj',
  moon: 'chaand',
  information: 'maldaryaft',
  library: 'kutub khana',
  bravery: 'bahaduri',
  elephant: 'haathi',
  dragon: 'azhdaha',
  alien: 'ajnabee',
  adventure: 'muhim joi',
  journey: 'safar',
  story: 'kahani',
  secret: 'raaz',
  mystery: 'pur asrar',
  treasure: 'khazana',
  power: 'taqat',
  energy: 'tawanai',
  strength: 'taqat',
  wisdom: 'danai',
  knowledge: 'ilm',
  idea: 'khayal',
  dream: 'khwab',
  memory: 'yadasht',
  future: 'mustaqbil',
  past: 'mazi',
  present: 'haal',
  people: 'log',
  person: 'shakhs',
  place: 'jaga',
  thing: 'cheez',
  time: 'waqt',
  name: 'naam',
  world: 'duniya',
  life: 'zindagi',
  head: 'sar',
  hand: 'haath',
  eye: 'aankh',
  heart: 'dil',
  body: 'jism',
  face: 'chehra',
  foot: 'paon',
  arm: 'bazoo',
  leg: 'tang',
  child: 'bacha',
  baby: 'bacha',
  mother: 'maa',
  father: 'baap',
  brother: 'bhai',
  sister: 'behn',
  son: 'beta',
  daughter: 'beti',
  king: 'badshah',
  queen: 'malika',
  hero: 'hero',
  robot: 'robot',
  machine: 'machine',
  computer: 'computer',
  message: 'paighaam',
  word: 'lafz',
  sound: 'aawaz',
  picture: 'tasveer',
  map: 'naqsha',
  flag: 'jhandalala',
  game: 'khel',
  sport: 'khel',
  friend: 'dost',
  family: 'khandan',
  morning: 'subah',
  evening: 'shaam',
  night: 'raat',
  today: 'aaj',
  tomorrow: 'kal',
  yesterday: 'kal',
  week: 'hafta',
  month: 'mahina',
  year: 'saal',
  season: 'mausam',
  spring: 'bahaar',
  summer: 'garmi',
  winter: 'sardi',
  question: 'sawal',
  reason: 'wajah',
  problem: 'masla',
  solution: 'hal',
  method: 'tareeqa',
  part: 'hissa',
  fact: 'haqeeqat',
  truth: 'sach',
  lie: 'jhoot',
  thought: 'soch',
  feeling: 'ehsas',
  meaning: 'maani',
  definition: 'taarif',
  translation: 'tarjuma',
  language: 'zaban',
  english: 'angrezi',
  urdu: 'urdu',
  grammar: 'grammar',
  vocabulary: 'zakheera alfaaz',
  spelling: 'hijay',
  pronunciation: 'talafuz',
  accent: 'lahja',
  dialogue: 'mukalima',
  conversation: 'guftagu',
  speech: 'taqreer',
  report: 'report',
  essay: 'mazmoon',
  composition: 'tabeer',
  letter: 'khat',
  diary: 'diary',
  hint: 'ishara',
  advice: 'mashwara',
  chance: 'moqaa',
  opportunity: 'moqaa',
  danger: 'khatra',
  safety: 'hifazat',
  peace: 'aman',
  war: 'jang',
  battle: 'larhai',
  victory: 'fatah',
  defeat: 'shikast',
  attack: 'hamla',
  defense: 'difaa',
  army: 'fauj',
  force: 'taqat',

  // === Adjectives ===
  happy: 'khush',
  beautiful: 'khobsurat',
  big: 'bara',
  small: 'chhota',
  tall: 'lamba',
  short: 'chhota',
  fast: 'tez',
  slow: 'dheema',
  hot: 'garam',
  cold: 'thanda',
  new: 'naya',
  old: 'purana',
  good: 'acha',
  bad: 'bura',
  shiny: 'chamakdar',
  huge: 'bara',
  ferocious: 'khoonkhar',
  many: 'bohat',
  some: 'kuch',
  cheap: 'sasta',
  bossy: 'hukm chalane wala',
  angry: 'ghussa',
  confused: 'pareshan',
  brave: 'bahaadur',
  clever: 'hoshiyar',
  smart: 'hoshiyar',
  wise: 'aqalmand',
  foolish: 'be waqoof',
  kind: 'meharban',
  cruel: 'zalim',
  gentle: 'naram',
  hard: 'sakht',
  strong: 'mazboot',
  weak: 'kamzor',
  rich: 'ameer',
  poor: 'ghareeb',
  young: 'jawaan',
  easy: 'aasan',
  difficult: 'mushkil',
  important: 'ahem',
  incorrect: 'ghalat',
  true: 'sach',
  false: 'jhoot',
  real: 'haqiqi',
  special: 'khaas',
  strange: 'ajeeb',
  rare: 'nayab',
  different: 'mukhtalif',
  same: 'ek jaisa',
  opposite: 'mukhalif',
  clear: 'saaf',
  dirty: 'ganda',
  dark: 'andhera',
  bright: 'roshan',
  light: 'halka',
  heavy: 'bhaari',
  full: 'bhara',
  empty: 'khaali',
  closed: 'band',
  long: 'lamba',
  wide: 'chora',
  narrow: 'tang',
  deep: 'gahara',
  high: 'ooncha',
  low: 'neecha',
  far: 'door',
  early: 'jaldi',
  late: 'dayar',
  quick: 'tez',
  ready: 'tayyar',
  busy: 'masroof',
  free: 'aazaad',
  sure: 'yaqeeni',
  main: 'ahem',
  first: 'pehla',
  second: 'doosra',
  third: 'tesra',
  little: 'thhora',
  much: 'bohat',
  enough: 'kaafi',
  great: 'azeem',
  wonderful: 'shandar',
  amazing: 'hairat angaiz',
  fantastic: 'lajawab',
  excellent: 'behtareen',
  perfect: 'kaamil',
  terrible: 'khofnaak',
  nice: 'acha',
  fine: 'theek',
  famous: 'mashhoor',
  various: 'mukhtalif',
  complete: 'mukammal',
  natural: 'qudrati',
  useful: 'mufeed',
  dangerous: 'khatarnaak',
  safe: 'mehfooz',
  helpful: 'madadgaar',
  interesting: 'dilchasp',
  exciting: 'purjosh',
  funny: 'mazahia',
  sad: 'udaas',
  hungry: 'bhookha',
  thirsty: 'pyaasa',
  sick: 'bimaar',
  healthy: 'sehat mand',
  alive: 'zinda',
  dead: 'murda',
  alone: 'akela',
  together: 'ek saath',
  silent: 'khamosh',
  loud: 'ooncha',
  quiet: 'khamosh',
  sweet: 'meetha',
  delicious: 'mazedar',
  fresh: 'taaza',
  wet: 'geela',
  dry: 'khushk',
  expensive: 'mehnga',
  honest: 'imaandaar',
  intelligent: 'zahin',

  // === Verbs ===
  run: 'daurna',
  eat: 'khana',
  sleep: 'sona',
  read: 'parhna',
  write: 'likhna',
  speak: 'bolna',
  walk: 'chalna',
  work: 'kaam karna',
  play: 'khelna',
  swim: 'taina',
  jump: 'koodna',
  sing: 'gana',
  dance: 'naachna',
  cook: 'pakana',
  drink: 'peena',
  give: 'dena',
  take: 'lena',
  come: 'aana',
  go: 'jana',
  see: 'dekhna',
  hear: 'sunna',
  teach: 'sikhana',
  learn: 'sikhna',
  help: 'madad karna',
  love: 'mohabbat karna',
  make: 'banana',
  break: 'torna',
  catch: 'pakarna',
  bring: 'lana',
  find: 'dhoondna',
  buy: 'khareedna',
  sell: 'bechna',
  talk: 'baat karna',
  sit: 'baitna',
  stand: 'khara hona',
  think: 'sochna',
  know: 'jaanna',
  want: 'chahna',
  need: 'zaroorat hona',
  like: 'pasand karna',
  ask: 'poochna',
  tell: 'batana',
  show: 'dikhana',
  leave: 'chhorna',
  keep: 'rakhna',
  let: 'dena',
  begin: 'shuru karna',
  open: 'kholna',
  close: 'band karna',
  move: 'harkat karna',
  change: 'badalna',
  follow: 'pairwi karna',
  remember: 'yaad rakhna',
  forget: 'bhoolna',
  understand: 'samajhna',
  believe: 'yaqeen karna',
  accept: 'qabool karna',
  send: 'bhejna',
  call: 'bulana',
  answer: 'jawab dena',
  explain: 'wazahat karna',
  describe: 'bayaan karna',
  draw: 'banna',
  paint: 'rangna',
  build: 'taamer karna',
  grow: 'ugana',
  cut: 'kaatna',
  push: 'dhekelna',
  pull: 'khenchna',
  lift: 'uthana',
  drop: 'girana',
  throw: 'phenkna',
  hit: 'maarna',
  hold: 'pakarna',
  carry: 'uthana',
  put: 'rakhna',
  rise: 'uthna',
  fall: 'girna',
  turn: 'murna',
  fly: 'urna',
  drive: 'chalana',
  travel: 'safar karna',
  visit: 'milna',
  meet: 'milna',
  arrive: 'puhanchna',
  wait: 'intezaar karna',
  stay: 'rehna',
  live: 'rehna',
  die: 'marna',
  become: 'banna',
  win: 'jeetna',
  lose: 'haarna',
  share: 'baantna',
  join: 'shamil hona',
  count: 'ginana',
  choose: 'chunna',
  select: 'muntakhib karna',
  pick: 'chunna',
  clean: 'saaf karna',
  wash: 'dhona',
  hide: 'chupana',
  search: 'talash karna',
  discover: 'daryaft karna',
  create: 'takhleeq karna',
  improve: 'behtar karna',
  increase: 'barhana',
  decrease: 'kam karna',
  fill: 'bharna',
  cry: 'rona',
  laugh: 'hansna',
  smile: 'muskurana',
  shout: 'chalana',
  watch: 'dekhna',
  look: 'dekhna',
  listen: 'sunna',
  bark: 'bhonkna',

  // === Adverbs ===
  quickly: 'jaldi se',
  slowly: 'aahista',
  happily: 'khushi se',
  loudly: 'oonchi aawaz se',
  carefully: 'ehtiyat se',
  quietly: 'khamoshi se',
  beautifully: 'khobsurati se',
  badly: 'buree tarah',
  always: 'hamesha',
  never: 'kabhi nahi',
  often: 'aksar',
  sometimes: 'kabhi kabhi',
  usually: 'aam tor par',
  rarely: 'shaz o nadir',
  definitely: 'yaqeenan',
  probably: 'shayad',
  certainly: 'bilashuba',
  now: 'ab',
  then: 'tab',
  here: 'yahan',
  there: 'wahan',
  everywhere: 'har jaga',
  somewhere: 'kahin',
  also: 'bhi',
  too: 'bhi',
  very: 'bohat',
  almost: 'taqreeban',
  already: 'pehle hi',
  still: 'ab bhi',
  just: 'sirf',

  // === Grammar Terms ===
  noun: 'ism',
  verb: 'feal',
  adjective: 'sifat',
  adverb: 'mutlaq',
  pronoun: 'zameer',
  preposition: 'harf e jaar',
  conjunction: 'harf e ataf',
  interjection: 'harf e nida',
  article: 'harf e taarif',
  common: 'aam',
  proper: 'khaas',
  abstract: 'tajreedi',
  collective: 'ijtimai',
  concrete: 'maddi',
  countable: 'ginne wala',
  uncountable: 'nah ginne wala',
  singular: 'wahid',
  plural: 'jama',
  definite: 'muayyan',
  indefinite: 'ghair muayyan',
  subject: 'fail',
  object: 'mafool',
  tense: 'zamana',
  voice: 'sada',
  active: 'failiya',
  passive: 'majhool',
  phrase: 'jumla',
  clause: 'juz jumla',
  sentence: 'jumla',
  paragraph: 'paragraph',
  synonym: 'mutradif',
  antonym: 'mutazad',
  syllable: 'hijay',
  phonetics: 'sautiyaat',
  prefix: 'sabiqa',
  suffix: 'lahiqa',
  modal: 'modal',
  collocation: 'talazum',
  punctuation: 'alamaat e auqaf',
  narration: 'riwayat',
  morphology: 'sarf',
  poetry: 'shayari',
  metaphor: 'isteara',
  simile: 'tashbeeh',
  personification: 'tashkhees',
  alliteration: 'ham aawaz',
  direct: 'barah-e-raast',
  indirect: 'balawasta',
  reported: 'manqool',
  denotation: 'laghwi maani',
  connotation: 'mafhoom',
  semicolon: 'nuqta-waar-comma',
  stylistics: 'usloobiyat',
  obligation: 'farz',
  necessity: 'zaroorat',
  simple: 'saada',

  // === Prepositions ===
  above: 'upar',
  across: 'aar paar',
  after: 'baad',
  against: 'khilaf',
  along: 'saath',
  among: 'darmiyan',
  around: 'gird',
  at: 'par',
  before: 'pehle',
  behind: 'peecha',
  below: 'neeche',
  beneath: 'neeche',
  beside: 'paas',
  between: 'darmiyan',
  beyond: 'aage',
  by: 'se',
  down: 'neeche',
  during: 'doran',
  for: 'liye',
  from: 'se',
  in: 'mein',
  into: 'andar',
  near: 'paas',
  of: 'ka',
  on: 'par',
  out: 'bahar',
  over: 'upar',
  through: 'se',
  to: 'ko',
  toward: 'ki taraf',
  under: 'neeche',
  until: 'tak',
  up: 'upar',
  with: 'saath',
  within: 'andar',
  without: 'baghair',

  // === Conjunctions ===
  and: 'aur',
  but: 'lekin',
  or: 'ya',
  because: 'kyunke',
  although: 'agarche',
  so: 'toh',
  unless: 'jab tak nah',
  while: 'jabke',
  since: 'jab se',
  if: 'agar',
  when: 'jab',
  not: 'nahi',
  only: 'sirf',
  however: 'lekin',
  therefore: 'is liye',

  // === Modals ===
  can: 'sakta hai',
  could: 'sakta tha',
  may: 'ho sakta hai',
  might: 'ho sakta tha',
  must: 'lazmi',
  shall: 'ga',
  should: 'chahiye',
  will: 'ga',
  would: 'ga tha',

  // === Common words ===
  man: 'aadmi',
  woman: 'aurat',
  boy: 'larka',
  girl: 'larki',
  children: 'bachay',
  student: 'talib ilm',
  teacher: 'ustaad',
  doctor: 'doctor',
  garden: 'bagh',
  park: 'park',
  cat: 'billi',
  mouse: 'chooha',
  horse: 'ghora',
  tiger: 'sher',
  lion: 'sher',
  fish: 'machli',
  monkey: 'bandar',
  rabbit: 'khargosh',
  duck: 'batakh',
  cow: 'gaye',
  goat: 'bakri',
  sheep: 'bheer',
  zoo: 'chidya ghar',
  east: 'mashriq',
  west: 'maghrib',
  north: 'shamal',
  south: 'junoob',

  // === Numbers ===
  one: 'aik',
  two: 'do',
  three: 'teen',
  four: 'chaar',
  five: 'paanch',
  six: 'chay',
  seven: 'saat',
  eight: 'aath',
  nine: 'nau',
  ten: 'das',

  // === Question Words ===
  what: 'kya',
  who: 'kaun',
  which: 'kaun sa',
  why: 'kyun',
  how: 'kaise',
  where: 'jahan',

  // === Pronouns ===
  i: 'mein',
  me: 'mujhay',
  my: 'mera',
  you: 'tum',
  your: 'tumhara',
  he: 'woh',
  him: 'usay',
  his: 'us ka',
  she: 'woh',
  her: 'usay',
  we: 'hum',
  us: 'humein',
  our: 'hamara',
  they: 'woh',
  them: 'unhen',
  their: 'unka',
  itself: 'khud',
  myself: 'khud',
  someone: 'koi',
  everything: 'sab kuch',
  nothing: 'kuch nahi',
  something: 'kuch',
  anyone: 'koi',
  everyone: 'har koi',

  // === Additional words ===
  personal: 'zaati',
  possessive: 'malikana',
  reflexive: 'nfeasi',
  relative: 'mausooli',
  demonstrative: 'isharati',
  interrogative: 'istafhami',
  intensive: 'takeedi',
  homophone: 'ham aawaz',
  root: 'jar',
  base: 'bunyad',
  gender: 'jins',
  transitive: 'mutaddi',
  intransitive: 'lazim',
  capital: 'bara harf',
  vowel: 'mutaharrik',
  consonant: 'sakin',
  text: 'matan',
  context: 'siyaq o sabaaq',
  character: 'kirdaar',
  plot: 'plot',
  theme: 'mauzo',
  title: 'unwaan',
  heading: 'surkhi',
  summary: 'khulasa',
  conclusion: 'nataija',
  purpose: 'maqsad',
  audience: 'samaeen',
  practice: 'mashq',
  exercise: 'mashq',
  test: 'test',
  quiz: 'quiz',
  score: 'score',
  check: 'check karein',
  next: 'aagla',
  previous: 'pechla',
  start: 'shuru',
  finish: 'khatam',
  stop: 'rukna',
  continue: 'jaari rakhna',
  cancel: 'mansookh',
  confirm: 'tasdeek',
  save: 'mehfooz',
  delete: 'hazf',
  add: 'shamil',
  remove: 'hatao',
  settings: 'tarteebaat',
  options: 'ikhtiyarat',
  home: 'ghar',
  exit: 'bahar nikle',
  success: 'kaamyabi',
  error: 'ghalti',
  warning: 'intabah',
  info: 'maldaryaft',
  correct: 'durust',
  wrong: 'ghalat',
  try: 'koshish',
  again: 'dobara',
};

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Get the Urdu script meaning for an English word.
 */
export function getMeaning(word: string): string {
  const key = word.toLowerCase().trim();
  return WORD_MEANINGS[key] || '';
}

/**
 * Get the Roman Urdu transliteration for TTS.
 * If no transliteration exists, returns the English word itself
 * as a fallback so TTS still works.
 */
export function getTransliteration(word: string): string {
  const key = word.toLowerCase().trim();
  return WORD_TRANSLITERATIONS[key] || key;
}

/**
 * Check if a word has an Urdu meaning available.
 */
export function hasMeaning(word: string): boolean {
  return !!getMeaning(word);
}

/**
 * Extract all unique words from text that have meanings available.
 */
export function extractMeaningfulWords(text: string): string[] {
  const words = text.match(/\b[a-zA-Z]+(?:-[a-zA-Z]+)*\b/g) || [];
  const unique = new Set(words.map(w => w.toLowerCase().trim()));
  return Array.from(unique).filter(w => hasMeaning(w));
}

