/**
 * WordMeaning — displays the Urdu script meaning of an English word inline.
 * Uses a built-in dictionary of common English vocabulary words mapped to
 * Urdu in Nastaliq script for easy readability.
 *
 * The font uses Noto Nastaliq Urdu in a small, clear style that's distinct
 * from the English vocabulary word and easy on the eyes.
 *
 * Usage:
 *   <WordMeaning word="happiness" />
 *   // renders:  (خوشی)
 */

// Comprehensive English → Roman Urdu dictionary for vocabulary found in English labs
const WORD_MEANINGS: Record<string, string> = {
  // === Grammar / Parts of Speech ===
  'noun': 'اسم',
  'pronoun': 'ضمیر',
  'verb': 'فعل',
  'adverb': 'متعارف',
  'adjective': 'صفت',
  'preposition': 'حرف جر',
  'conjunction': 'حرف عطف',
  'interjection': 'حرف ندا',
  'article': 'حرف تعریف',
  'common': 'عام',
  'proper': 'خاص',
  'abstract': 'تجربدی',
  'collective': 'اجتماعی',
  'concrete': 'واضعی',
  'countable': 'گنا جا سکنے والا',
  'uncountable': 'ناقابل گنتی',
  'singular': 'واحد',
  'plural': 'جمع',
  'tense': 'زمان',
  'active': 'فعلی',
  'passive': 'مجہول',
  'simple': 'سادہ',
  'continuous': 'جاری',
  'perfect': 'مکمل',
  'past': 'ماضی',
  'present': 'حال',
  'future': 'مستقبل',
  'positive': 'مثبت',
  'negative': 'منفی',
  'interrogative': 'سوالیہ',
  'modal': 'معدولہ',
  'linking': 'جوڑنے والا',
  'transitive': 'متعدی',
  'intransitive': 'لازم',
  'finite': 'محدود',
  'non-finite': 'non-finite',
  'regular': 'باقاعدہ',
  'irregular': 'بے قاعدہ',
  'gerund': 'مصدر',
  'infinitive': 'مصدر',
  'participle': 'صفت فعلی',
  'subject': 'فاعل',
  'object': 'مفعول',
  'predicate': 'خبر',
  'affix': 'لاحقہ',
  'prefix': 'سابقہ',
  'suffix': 'لاحقہ',
  'root': 'جذر',
  'phrase': 'جملہ',
  'clause': 'شق',
  'dependent': 'منحصر',
  'independent': 'آزاد',
  'relative': 'نسبتی',
  'adverb clause': 'متعارف جملہ',
  'noun clause': 'اسمی جملہ',
  'prepositional phrase': 'حرف جری جملہ',

  // === Figures of Speech ===
  'simile': 'تشبیہ',
  'metaphor': 'استعارہ',
  'personification': 'تشخیص',
  'hyperbole': 'مبالغہ',
  'alliteration': 'حروف متشابہ',
  'oxymoron': 'متضاد',
  'euphemism': 'کنایہ',
  'anaphora': 'تکرار',
  'allusion': 'اشارہ',
  'irony': 'طنز',
  'synecdoche': 'کُل بہ جز',
  'metonymy': 'مجاز مرسل',

  // === Common Vocab from E6 Nouns ===
  'happiness': 'خوشی',
  'team': 'ٹیم',
  'dog': 'کتا',
  'she': 'وہ',
  'courage': 'ہمت',
  'river': 'دریا',
  'they': 'وہ',
  'elephant': 'ہاتھی',
  'library': 'کتب خانہ',
  'information': 'معلومات',
  'bravery': 'بہادری',
  'crowd': 'ہجوم',
  'family': 'خاندان',
  'class': 'جماعت',
  'school': 'مدرسہ',
  'beauty': 'خوبصورتی',
  'health': 'صحت',
  'honesty': 'ایمانداری',
  'freedom': 'آزادی',
  'justice': 'انصاف',
  'peace': 'امن',
  'strength': 'طاقت',
  'wisdom': 'حکمت',
  'knowledge': 'علم',
  'power': 'طاقت',

  // === E7 Vocab ===
  'midnight': 'آدھی رات',
  'musings': 'خیالات',
  'moon': 'چاند',
  'ghostly': 'بھوتیا',
  'galleon': 'بحری جہاز',
  'cloudy': 'ابر آلود',
  'seas': 'سمندر',
  'stars': 'ستارے',
  'sparkled': 'چمکا',
  'diamonds': 'ہیرے',
  'dark': 'اندھیرا',
  'night': 'رات',
  'sky': 'آسمان',
  'old': 'پرانا',
  'house': 'گھر',
  'groaned': 'کڑکایا',
  'complained': 'شکایت کی',
  'strong': 'مضبوط',
  'wind': 'ہوا',
  'weighs': 'وزن ہے',
  'ton': 'ٹن',
  'whispering': 'سرگوشی',
  'wandering': 'آوارہ',
  'weeping': 'روتا ہوا',
  'willows': 'بید مجنوں',
  'queen': 'ملکہ',
  'king': 'بادشاہ',
  'kingdom': 'سلطنت',
  'knights': 'شورویروں',
  'crown': 'تاج',
  'wise': 'عقلمند',
  'battle': 'جنگ',
  'castle': 'قلعہ',
  'sword': 'تلوار',
  'shield': 'ڈھال',
  'messenger': 'قاصد',
  'treasure': 'خزانہ',
  'map': 'نقشہ',
  'adventure': 'مہم جوئی',
  'journey': 'سفر',
  'story': 'کہانی',
  'poem': 'نظم',
  'writer': 'مصنف',
  'reader': 'قاری',
  'editor': 'مدون',
  'author': 'مصنف',
  'poet': 'شاعر',
  'line': 'سطر',
  'verse': 'آیت',
  'stanza': 'بند',
  'rhyme': 'قافیہ',
  'rhythm': 'وزن',

  // === E8 Vocab ===
  'data': 'اعداد و شمار',
  'archives': 'محفوظات',
  'lexicon': 'لغت',
  'vocabulary': 'ذخیرہ الفاظ',
  'dictionary': 'لغت',
  'synonym': 'مترادف',
  'antonym': 'متضاد',
  'meaning': 'معنی',
  'definition': 'تعریف',
  'example': 'مثال',
  'syllable': 'حرف',
  'letter': 'حرف',
  'word': 'لفظ',
  'sentence': 'جملہ',
  'paragraph': 'پیرا',
  'essay': 'مضمون',
  'composition': 'تقریر',
  'grammar': 'قواعد',
  'spelling': 'ہجے',
  'punctuation': 'رموز اوقاف',
  'period': 'وقفہ',
  'comma': 'کوما',
  'question': 'سوال',
  'exclamation': 'تعجب',
  'quotation': 'اقتباس',
  'apostrophe': 'علامت اضافت',
  'colon': 'نقطہ دو',
  'semicolon': 'نقطہ وار',
  'dash': 'خط',
  'hyphen': 'نشانہ',
  'bracket': 'قوسین',
  'capital': 'بڑا',
  'uppercase': 'بڑی عبارت',
  'lowercase': 'چھوٹی عبارت',
  'phonetics': 'صوتیات',
  'pronunciation': 'تلفظ',
  'accent': 'لہجہ',
  'stress': 'زور',
  'intonation': 'لہجہ',

  // === Modals / Verbs ===
  'must': 'لازمی',
  'should': 'چاہیے',
  'could': 'سکتا',
  'would': 'گا',
  'may': 'سکتا ہے',
  'might': 'شاید',
  'can': 'سکتا',
  'will': 'گا',
  'shall': 'گا',
  'ought to': 'چاہیے',
  'have to': 'لازمی',
  'need to': 'ضرورت',
  'used to': 'کرتا تھا',
  'dare to': 'جرأت',
  'able': 'قابل',
  'must not': 'نہیں چاہیے',
  'cannot': 'نہیں سکتا',
  'should not': 'نہیں چاہیے',
  'need not': 'ضرورت نہیں',

  // === Prepositions ===
  'in': 'میں',
  'on': 'پر',
  'at': 'پر',
  'under': 'نیچے',
  'over': 'اوپر',
  'through': 'سے',
  'during': 'درمیان',
  'before': 'پہلے',
  'after': 'بعد',
  'between': 'درمیان',
  'among': 'mein_1',
  'against': 'خلاف',
  'beside': 'پاس',
  'besides': 'علاوہ',
  'across': 'آر پار',
  'along': 'ساتھ',
  'around': 'ارد گرد',
  'behind': 'پیچھے',
  'below': 'نیچے',
  'beneath': 'نیچے',
  'inside': 'اندر',
  'outside': 'باہر',
  'toward': 'کی طرف',
  'upon': 'پر',
  'within': 'اندر',
  'without': 'بغیر',
  'because of': 'کی وجہ سے',
  'in spite of': 'باوجود',
  'instead of': 'بجائے',
  'apart from': 'علاوہ',
  'according to': 'کے مطابق',
  'in addition to': 'کے علاوہ',
  'due to': 'کی وجہ سے',
  'out of': 'میں سے',
  'throughout': 'بھر میں',
  'consequently': 'نتیجتاً',
  'therefore': 'لہٰذا',
  'however': 'تاہم',
  'meanwhile': 'اسی دوران',
  'nevertheless': 'باوصف',

  // === Conjunctions ===
  'and': 'اور',
  'or': 'یا',
  'but': 'لیکن',
  'yet': 'پھر بھی',
  'so': 'تو',
  'for': 'کیونکہ',
  'nor': 'نہ',
  'although': 'اگرچہ',
  'because': 'کیونکہ',
  'since': 'چونکہ',
  'unless': 'جب تک',
  'while': 'جبکہ',
  'when': 'جب',
  'where': 'جہاں',
  'after_1': 'after_1',
  'if': 'اگر',
  'than': 'سے',
  'as': 'جیسا',

  // === Pronouns ===
  'i': 'میں',
  'you': 'تم',
  'he': 'وہ',
  'she_1': 'وہ',
  'it': 'یہ',
  'we': 'ہم',
  'my': 'میرا',
  'your': 'تمہارا',
  'his': 'اس کا',
  'her': 'اس کا',
  'its': 'اس کا',
  'our': 'ہمارا',
  'their': 'ان کا',
  'me': 'مجھے',
  'him': 'اسے',
  'her_1': 'اسے',
  'us': 'ہمیں',
  'them': 'انہیں',
  'this': 'یہ',
  'that': 'وہ',
  'these': 'یہ',
  'those': 'وہ',
  'some': 'کچھ',
  'any': 'کوئی',
  'every': 'ہر',
  'each': 'ہر ایک',
  'none': 'کوئی نہیں',
  'all': 'سب',
  'both': 'دونوں',
  'few': 'چند',
  'many': 'بہت',
  'much': 'بہت',
  'several': 'کئی',
  'nobody': 'کوئی نہیں',
  'nothing': 'کچھ نہیں',
  'everyone': 'ہر کوئی',
  'everything': 'سب کچھ',
  'someone': 'کوئی',
  'something': 'کچھ',

  // === Numbers / Determiners ===
  'a': 'ایک',
  'an': 'ایک',
  'the': 'یہ',
  'no': 'نہیں',
  'not': 'نہیں',

  // === E9+ Advanced Vocab ===
  'phrase_1': 'جملہ',
  'narration': 'روایت',
  'reported': 'منقول',
  'direct': 'براہ راست',
  'indirect': 'بالواسطہ',
  'command': 'حکم',
  'request': 'درخواست',
  'statement': 'بیان',
  'exclamation_1': 'تعجب',
  'assertive': 'اثباتی',
  'interrogative_1': 'سوالیہ',
  'imperative': 'امریہ',
  'conditional': 'شرطیہ',
  'zero': 'صفر',
  'first': 'پہلا',
  'second': 'دوسرا',
  'third': 'تیسرا',
  'type': 'ٹائپ کرنا',
  'real': 'حقیقی',
  'unreal': 'غیر حقیقی',
  'possible': 'ممکن',
  'impossible': 'ناممکن',
  'general truth': 'عام حقیقت',
  'result': 'نتیجہ',
  'cause': 'سبب',
  'effect': 'اثر',
  'situation': 'صورت حال',
  'scenario': 'منظر نامہ',

  // === Tense-related ===
  'arrives': 'آتا ہے',
  'arrived': 'آیا',
  'had arrived': 'آیا تھا',
  'will arrive': 'آئے گا',
  'is repairing': 'مرمت کر رہا ہے',
  'was being built': 'تعمیر ہو رہا تھا',
  'will travel': 'سفر کرے گا',
  'will be watching': 'دیکھ رہا ہو گا',
  'were being typed': 'ٹائپ ہو رہے تھے',
  'repair': 'مرمت کرنا',
  'build': 'تعمیر کرنا',
  'travel': 'سفر کرنا',
  'watch': 'دیکھنا',
  'study': 'پڑھنا',
  'pass': 'پاس کرنا',
  'win': 'جیتنا',
  'buy': 'خریدنا',
  'cool': 'ٹھنڈا کرنا',
  'freeze': 'جمانا',
  'wait': 'انتظار کرنا',
  'rest': 'آرام کرنا',
  'write': 'لکھنا',
  'read': 'پڑھنا',
  'speak': 'بولنا',
  'listen': 'سننا',
  'learn': 'سیکھنا',
  'teach': 'پڑھانا',
  'begin': 'شروع کرنا',
  'finish': 'ختم کرنا',
  'continue': 'جاری رکھنا',
  'sit': 'بیٹھنا',
  'stand': 'کھڑا ہونا',
  'run': 'دوڑنا',
  'walk': 'چلنا',
  'eat': 'کھانا',
  'drink': 'پینا',
  'sleep': 'سونا',
  'wake': 'جاگنا',
  'play': 'کھیلنا',
  'work': 'کام کرنا',
  'help': 'مدد کرنا',
  'make': 'بنانا',
  'take': 'لینا',
  'give': 'دینا',
  'come': 'آنا',
  'go': 'جانا',
  'see': 'دیکھنا',
  'know': 'جاننا',
  'think': 'سوچنا',
  'feel': 'محسوس کرنا',
  'find': 'ڈھونڈنا',
  'show': 'دکھانا',
  'tell': 'بتانا',
  'say': 'کہنا',
  'ask': 'پوچھنا',
  'answer': 'جواب دینا',
  'call': 'بلانا',
  'use': 'استعمال کرنا',
  'try': 'کوشش کرنا',
  'keep': 'رکھنا',
  'leave': 'چھوڑنا',
  'turn': 'موڑنا',
  'put': 'رکھنا',
  'set': 'رکھنا',
  'bring': 'لانا',
  'send': 'بھیجنا',
  'move': 'ہلنا',
  'change': 'بدلنا',

  // === Time words ===
  'today': 'آج',
  'tonight': 'آج رات',
  'tomorrow': 'کل',
  'yesterday': 'کل',
  'now': 'اب',
  'soon': 'جلد',
  'always': 'ہمیشہ',
  'never': 'کبھی نہیں',
  'often': 'اکثر',
  'sometimes': 'کبھی کبھی',
  'usually': 'معمولاً',
  'already': 'پہلے سے',
  'still': 'ابھی تک',
  'yet_1': 'ابھی تک',

  // === Misc Educational ===
  'sentence_1': 'جملہ',
  'syllabus': 'نصاب',
  'chapter': 'سبق',
  'lesson': 'سبق',
  'exercise': 'مشق',
  'practice': 'مشق',
  'test': 'امتحان',
  'exam': 'امتحان',
  'question_1': 'سوال',
  'mark': 'نشان',
  'grade': 'درجہ',
  'score': 'سکور',
  'answer_1': 'جواب',
  'learn_1': 'learn_1',
  'understand': 'سمجھنا',
  'remember': 'یاد رکھنا',
  'forget': 'بھولنا',
  'repeat': 'دہرانا',
  'explain': 'وضاحت کرنا',
  'describe': 'بیان کرنا',
  'identify': 'پہچاننا',
  'choose': 'چننا',
  'select': 'منتخب کرنا',
  'match': 'ملانا',
  'complete': 'مکمل کرنا',
  'correct': 'درست کرنا',
  'check': 'جانچنا',
  'review': 'دوبارہ دیکھنا',
  'practice_1': 'مشق کرنا',
  'improve': 'بہتر کرنا',
  'master': 'ماہر ہونا',
  'skill': 'ہنر',
  'ability': 'قابلیت',
  'goal': 'مقصد',
  'objective': 'مقصد',
  // === Additional vocabulary from labs ===
  'abstract noun': 'اسم معنی',
  'action verb': 'فعلی فعل',
  'alien': 'اجنبی',
  'apple': 'سیب',
  'beautiful': 'خوبصورت',
  'brick': 'اینٹ',
  'bunch': 'گچھا',
  'capable': 'قابل',
  'car': 'گاڑی',
  'clever': 'ہوشیار',
  'clumsily': 'بےڈھنگے پن سے',
  'committee': 'کمیٹی',
  'compound': 'مرکب',
  'danger': 'خطرہ',
  'deafening silence': 'بےحد خاموشی',
  'demonstrative': 'اشارہ',
  'dependent clause': 'منحصر جملہ',
  'ditransitive': 'دو متعدی',
  'dodged': 'بچ گیا',
  'dragon': 'اژدہا',
  'error': 'غلطی',
  'exclamatory': 'تعجبیہ',
  'ferocious': 'خوفناک',
  'fire': 'آگ',
  'five': 'پانچ',
  'flock': 'ریوڑ',
  'fought': 'لڑا',
  'fox': 'لومڑی',
  'ganges': 'گنگا',
  'huge': 'بہت بڑا',
  'inquisitive': 'تجسس',
  'interfering': 'مداخلت کرنے والا',
  'into': 'میں',
  'jury': 'جری',
  'keyboard': 'کی بورڈ',
  'later': 'بعد میں',
  'little': 'تھوڑا',
  'london': 'لندن',
  'lost': 'کھو دیا',
  'microscope': 'خردبین',
  'optative': 'خواہشیہ',
  'paradox': 'متضاد',
  'perfect continuous': 'مکمل جاری',
  'personal pronoun': 'ذاتی ضمیر',
  'possessive': 'اضافی',
  'protect': 'حفاظت کرنا',
  'prying': 'تجسس',
  'quantitative': 'مقداری',
  'quickly': 'جلدی سے',
  'realized': 'احساس ہوا',
  'red': 'سرخ',
  'reflexive pronoun': 'رجوعی ضمیر',
  'relative clause': 'نسبتی جملہ',
  'relative pronoun': 'نسبتی ضمیر',
  'round': 'گول',
  'said': 'کہا',
  'shiny': 'چمکدار',
  'similarly': 'اسی طرح',
  'small': 'چھوٹا',
  'success': 'کامیابی',
  'summoned': 'طلب کیا',
  'table': 'میز',
  'themselves': 'خود',
  'tired': 'تھکا ہوا',
  'to': 'کو',
  'toothbrush': 'دانتوں کا برش',
  'well-known': 'مشہور',
  'wooden': 'لکڑی کا',
  'who': 'کون',
  // === Additional prepositions ===
  'above': 'اوپر',
  'down': 'نیچے',
  'up': 'اوپر',
  'off': 'دور',
  'near': 'قریب',
  'far': 'دور',
  'forward': 'آگے',
  'backward': 'پیچھے',
  'towards': 'کی طرف',
  // === Additional adjectives ===
  'happy': 'خوش',
  'sad': 'اداس',
  'angry': 'ناراض',
  'excited': 'پرجوش',
  'calm': 'پرسکون',
  'nervous': 'گھبرایا',
  'brave': 'بہادر',
  'wise_1': 'عقلمند',
  'foolish': 'بیوقوف',
  'kind': 'مہربان',
  'cruel': 'ظالم',
  'generous': 'سخی',
  'selfish': 'خود غرض',
  'polite': 'شائستہ',
  'rude': 'بدتمیز',
  'lazy': 'سست',
  'hardworking': 'محنتی',
  'honest': 'ایماندار',
  'patient': 'صابر',
  'intelligent': 'ذہین',
  // === Additional pronouns ===
  'myself': 'خود',
  'yourself': 'خود',
  'himself': 'خود',
  'herself': 'خود',
  'itself': 'خود',
  'ourselves': 'خود',
  'yourselves': 'خود',
  // === Additional verbs ===
  'become': 'بننا',
  'became': 'بنا',
  'begin_1': 'شروع کرنا',
  'began': 'شروع کیا',
  'break': 'توڑنا',
  'broken': 'ٹوٹا',
  'bring_1': 'لانا',
  'brought': 'لایا',
  'catch': 'پکڑنا',
  'caught': 'پکڑا',
  'choose_1': 'چننا',
  'chose': 'چنا',
  'cut': 'کاٹنا',
  'draw': 'کھینچنا',
  'drew': 'کھینچا',
  'drink_1': 'پینا',
  'drank': 'پیا',
  'drive': 'چلانا',
  'drove': 'چلایا',
  'eat_1': 'کھانا',
  'ate': 'کھایا',
  'fall': 'گرنا',
  'fell': 'گرا',
  'fly': 'اڑنا',
  'flew': 'اڑا',
  'forget_1': 'بھولنا',
  'forgot': 'بھولا',
  'grow': 'بڑھنا',
  'grew': 'بڑھا',
  'hide': 'چھپنا',
  'hid': 'چھپا',
  'hold': 'پکڑنا',
  'held': 'پکڑا',
  'hurt': 'چوٹ لگنا',
  'keep_1': 'رکھنا',
  'kept': 'رکھا',
  'lead': 'رہنمائی کرنا',
  'led': 'رہنمائی کی',
  'lend': 'قرض دینا',
  'lent': 'قرض دیا',
  'lie': 'جھوٹ بولنا',
  'lay': 'لیٹنا',
  'mean': 'مطلب رکھنا',
  'meant': 'مطلب تھا',
  'meet': 'ملنا',
  'met': 'ملا',
  'pay': 'ادا کرنا',
  'paid': 'ادا کیا',
  'prove': 'ثابت کرنا',
  'proved': 'ثابت کیا',
  'put_1': 'رکھنا',
  'quit': 'چھوڑنا',
  'quit_1': 'چھوڑ دیا',
  'rise': 'اٹھنا',
  'rose': 'اٹھا',
  'sell': 'بیچنا',
  'sold': 'بیچا',
  'shake': 'ہلانا',
  'shook': 'ہلایا',
  'shine': 'چمکنا',
  'shone': 'چمکا',
  'shut': 'بند کرنا',
  'sing': 'گانا',
  'sang': 'گایا',
  'sink': 'ڈوبنا',
  'sank': 'ڈوبا',
  'spend': 'خرچ کرنا',
  'spent': 'خرچ کیا',
  'spread': 'پھیلانا',
  'steal': 'چوری کرنا',
  'stole': 'چوری کیا',
  'stolen': 'چوری شدہ',
  'swim': 'تیرنا',
  'swam': 'تیرا',
  'tear': 'پھاڑنا',
  'tore': 'پھاڑا',
  'throw': 'پھینکنا',
  'threw': 'پھینکا',
  'understand_1': 'سمجھنا',
  'understood': 'سمجھا',
  'wear': 'پہننا',
  'wore': 'پہنا',
  'weep': 'رونا',
  'wept': 'رویا',
  'withdraw': 'واپس لینا',
  'withdrew': 'واپس لیا',
  'withdrawn': 'واپس لیا گیا',
  'awake': 'جاگنا',
  'awoke': 'جاگا',
  'beat': 'ہرانا',
  'beat_1': 'ہرایا',
  'bend': 'موڑنا',
  'bent': 'موڑا',
  'bet': 'شرط لگانا',
  'bite': 'کاٹنا',
  'bit': 'کاٹا',
  'blow': 'پھونکنا',
  'blew': 'پھونکا',
  'burn': 'جلنا',
  'burnt': 'جلا',
  'climb': 'چڑھنا',
  'climbed': 'چڑھا',
  'cost': 'قیمت',
  'deal': 'نمٹنا',
  'dealt': 'نمٹا',
  'dig': 'کھودنا',
  'dug': 'کھودا',
  'dream': 'خواب دیکھنا',
  'dreamt': 'خواب دیکھا',
  'feed': 'کھلاانا',
  'fed': 'کھلایا',
  'fight': 'لڑنا',
  'fought_1': 'لڑا',
  'fit': 'فٹ ہونا',
  'forgive': 'معاف کرنا',
  'forgave': 'معاف کیا',
  'freeze_1': 'جمنہ',
  'froze': 'جم گیا',
  'frozen': 'جم گیا',
  'grind': 'پیسنا',
  'ground': 'پیسا',
  'hang': 'لٹکانا',
  'hung': 'لٹکایا',
  'kneel': 'گھٹنے ٹیکنا',
  'knelt': 'گھٹنے ٹیکے',
  'knit': 'بننا',
  'knitted': 'بنا',
  'lean': 'جھکنا',
  'leapt': 'چھلانگ لگایا',
  'leap': 'چھلانگ',
  'light': 'روشنی',
  'lit': 'روشن کیا',
  'lose': 'کھونا',
  'lost_1': 'کھو دیا',
  'mislead': 'گمراہ کرنا',
  'misled': 'گمراہ کیا',
  'mistake': 'غلطی کرنا',
  'mistook': 'غلطی کی',
  'mistaken': 'غلطی ہوئی',
  'overcome': 'قابو پانا',
  'overcame': 'قابو پایا',
  'ride': 'سواری کرنا',
  'rode': 'سواری کی',
  'ring': 'بجنا',
  'rang': 'بجا',
  'rung': 'بجایا',
  'seek': 'تلاش کرنا',
  'sought': 'تلاش کی',
  'sew': 'سلائی کرنا',
  'sewed': 'سلائی کیا',
  'sewn': 'سلایا ہوا',
  'shoot': 'گولی مارنا',
  'shot': 'گولی ماری',
  'shrink': 'سکڑنا',
  'shrank': 'سکڑ گیا',
  'shrunken': 'سکڑا ہوا',
  'slide': 'پھسلنا',
  'slid': 'پھسلا',
  'sow': 'بونا',
  'sowed': 'بویا',
  'sown': 'بویا ہوا',
  'spin': 'گھمانا',
  'spun': 'گھمایا',
  'spring': 'چھلانگ لگانا',
  'sprang': 'چھلانگ لگایا',
  'sting': 'ڈنک مارنا',
  'stung': 'ڈنک مارا',
  'stink': 'بدبودار ہونا',
  'stank': 'بدبودار تھا',
  'stride': 'بڑے قدم اٹھانا',
  'strode': 'بڑے قدم اٹھائے',
  'strike': 'مارنا',
  'struck': 'مارا',
  'strive': 'کوشش کرنا',
  'strove': 'کوشش کی',
  'striven': 'کوشش کی',
  'sweep': 'جھاڑو دینا',
  'swept': 'جھاڑو دیا',
  'swell': 'پھولنا',
  'swelled': 'پھول گیا',
  'swollen': 'پھولا ہوا',
  'swing': 'جھولنا',
  'swung': 'جھولا',
  'teach_1': 'سکھانا',
  'taught': 'سکھایا',
  'think_1': 'سوچنا',
  'thought': 'سوچا',
  'thrive': 'پھلنا پھولنا',
  'throve': 'پھلا پھولا',
  'thriven': 'پھلا پھولا',
  'tread': 'چلنا',
  'trod': 'چلا',
  'trodden': 'چلا ہوا',
  'wake_1': 'جاگنا',
  'woke': 'جاگا',
  'woken': 'جاگا ہوا',
  'weave': 'بننا',
  'wove': 'بنا',
  'woven': 'بنا ہوا',
  'win_1': 'جیتنا',
  'won': 'جیتا',
  'wring': 'نچوڑنا',
  'wrung': 'نچوڑا',
  'write_1': 'لکھنا',
  'wrote': 'لکھا',
  'written': 'لکھا ہوا',
  // === Additional common nouns ===
  'animal': 'جانور',
  'book': 'کتاب',
  'chair': 'کرسی',
  'child': 'بچہ',
  'city': 'شہر',
  'country': 'ملک',
  'door': 'دروازہ',
  'earth': 'زمین',
  'eye': 'آنکھ',
  'face': 'چہرہ',
  'father': 'باپ',
  'field': 'میدان',
  'flower': 'پھول',
  'food': 'کھانا',
  'friend': 'دوست',
  'fruit': 'پھل',
  'game': 'کھیل',
  'garden': 'باغ',
  'god': 'خدا',
  'gold': 'سونا',
  'ground_1': 'زمین',
  'hand': 'ہاتھ',
  'head': 'سر',
  'heart': 'دل',
  'horse': 'گھوڑا',
  'island': 'جزیرہ',
  'language': 'زبان',
  'law': 'قانون',
  'life': 'زندگی',
  'light_1': 'روشنی',
  'love': 'محبت',
  'man': 'آدمی',
  'mind': 'دماغ',
  'minute': 'منٹ',
  'money': 'پیسہ',
  'month': 'مہینہ',
  'mother': 'ماں',
  'mountain': 'پہاڑ',
  'mouth': 'منہ',
  'music': 'موسیقی',
  'name': 'نام',
  'nation': 'قوم',
  'nature': 'فطرت',
  'news': 'خبر',
  'ocean': 'سمندر',
  'pain': 'درد',
  'paper': 'کاغذ',
  'people': 'لوگ',
  'picture': 'تصویر',
  'place': 'جگہ',
  'plant': 'پودا',
  'rain': 'بارش',
  'reason': 'وجہ',
  'road': 'سڑک',
  'rock': 'پتھر',
  'room': 'کمرہ',
  'sea': 'سمندر',
  'ship': 'جہاز',
  'side': 'طرف',
  'sign': 'نشان',
  'silver': 'چاندی',
  'son': 'بیٹا',
  'soul': 'روح',
  'sound': 'آواز',
  'south': 'جنوب',
  'space': 'خلا',
  'spring_1': 'بہار',
  'star': 'ستارہ',
  'steel': 'فولاد',
  'stone': 'پتھر',
  'storm': 'طوفان',
  'sun': 'سورج',
  'system': 'نظام',
  'teacher': 'استاد',
  'thought_1': 'خیال',
  'time': 'وقت',
  'tree': 'درخت',
  'truth': 'سچ',
  'universe': 'کائنات',
  'valley': 'وادی',
  'village': 'گاؤں',
  'voice': 'آواز / صیغہ',
  'war': 'جنگ',
  'water': 'پانی',
  'way': 'راستہ',
  'wealth': 'دولت',
  'week': 'ہفتہ',
  'west': 'مغرب',
  'wife': 'بیوی',
  'woman': 'عورت',
  'world': 'دنیا',
  'year': 'سال',
  // === Additional adjectives ===
  'alive': 'زندہ',
  'alone': 'اکیلا',
  'ancient': 'قدیم',
  'asleep': 'سویا ہوا',
  'aware': 'آگاہ',
  'bad': 'برا',
  'big': 'بڑا',
  'bitter': 'کڑوا',
  'blue': 'نیلا',
  'broad': 'چوڑا',
  'certain': 'یقینی',
  'cheap': 'سستا',
  'clean': 'صاف',
  'clear': 'واضح',
  'close': 'قریب',
  'cold': 'ٹھنڈا',
  'common_1': 'عام',
  'complex': 'پیچیدہ',
  'constant': 'مستقل',
  'curious': 'متجسس',
  'dangerous': 'خطرناک',
  'dead': 'مردہ',
  'deep': 'گہرا',
  'delicate': 'نازک',
  'different': 'مختلف',
  'difficult': 'مشکل',
  'dirty': 'گندا',
  'dry': 'خشک',
  'due': 'واجب',
  'dull': 'پھیکا',
  'eager': 'بے چین',
  'early': 'جلد',
  'east': 'مشرق',
  'eastern': 'مشرقی',
  'easy': 'آسان',
  'elastic': 'لچکدار',
  'electric': 'برقی',
  'empty': 'خالی',
  'entire': 'پورا',
  'equal': 'برابر',
  'even': 'برابر',
  'evil': 'برا',
  'exact': 'عین',
  'extra': 'اضافی',
  'extreme': 'انتہائی',
  'faint': 'ہلکا',
  'fair': 'منصفانہ',
  'false': 'جھوٹا',
  'famous': 'مشہور',
  'fast': 'تیز',
  'fat': 'موٹا',
  'favorite': 'پسندیدہ',
  'female': 'مونث',
  'fierce': 'خوفناک',
  'final': 'آخری',
  'fine': 'ٹھیک',
  'firm': 'مضبوط',
  'flat': 'چپٹا',
  'fleet': 'بحری بیڑا',
  'flexible': 'لچکدار',
  'following': 'مندرجہ ذیل',
  'fond': 'شوقین',
  'foreign': 'غیر ملکی',
  'former': 'سابقہ',
  'frank': 'صاف گو',
  'free': 'آزاد',
  'fresh': 'تازہ',
  'friendly': 'دوستانہ',
  'front': 'سامنے',
  'full': 'بھرا',
  'general': 'عام',
  'gentle': 'نرم',
  'glad': 'خوش',
  'golden': 'سنہری',
  'good': 'اچھا',
  'gradual': 'بتدریج',
  'grand': 'عظیم',
  'gray': 'سرمئی',
  'great': 'بڑا',
  'green': 'سبز',
  'half': 'آدھا',
  'handsome': 'خوبصورت',
  'happy_1': 'خوش',
  'hard': 'مشکل',
  'healthy': 'صحت مند',
  'heavy': 'بھاری',
  'helpful': 'مددگار',
  'high': 'اونچا',
  'hollow': 'کھوکھلا',
  'holy': 'مقدس',
  'hot': 'گرم',
  'humble': 'عاجز',
  'hungry': 'بھوکا',
  'ideal': 'مثالی',
  'ill': 'بیمار',
  'important': 'اہم',
  'inner': 'اندرونی',
  'innocent': 'بے قصور',
  'instant': 'فوری',
  'jealous': 'حسود',
  'joint': 'مشترکہ',
  'junior': 'جونیئر',
  'just': 'منصفانہ',
  'keen': 'مشتاق',
  'large': 'بڑا',
  'last': 'آخری',
  'late': 'دیر',
  'lawful': 'قانونی',
  'leading': 'اہم',
  'lean_1': 'دبلا',
  'least': 'کم سے کم',
  'left': 'بایاں',
  'legal': 'قانونی',
  'level': 'برابر',
  'likely': 'ممکنہ',
  'live': 'زندہ',
  'loose': 'ڈھیلا',
  'loud': 'بلند',
  'lovely': 'پیارا',
  'low': 'نیچا',
  'lower': 'نیچے',
  'royal': 'شاہی',
  'safe': 'محفوظ',
  'smooth': 'ہموار',
  'soft': 'نرم',
  'solar': 'شمسی',
  'solid': 'ٹھوس',
  'sorry': 'افسوس',
  'sour': 'کھٹا',
  'southern': 'جنوبی',
  'spare': 'فالتو',
  'special': 'خاص',
  'steady': 'مستقل',
  'steep': 'ڈھلوان',
  'stern': 'سخت',
  'sticky': 'چپکنے والا',
  'still_1': 'خاموش',
  'straight': 'سیدھا',
  'strange': 'عجیب',
  'strict': 'سخت',
  'stubborn': 'ضدی',
  'sudden': 'اچانک',
  'sufficient': 'کافی',
  'suitable': 'مناسب',
  'sunny': 'دھوپ',
  'superior': 'برتر',
  'sure': 'یقین',
  'surprised': 'حیران',
  'sweet': 'میٹھا',
  'swift': 'تیز',
  'tall': 'لمبا',
  'tender': 'نرم',
  'terrible': 'خوفناک',
  'thick': 'موٹا',
  'thin': 'پتلا',
  'thirsty': 'پیاسا',
  'tight': 'سخت',
  'tiny': 'ننھا',
  'total': 'کل',
  'tough': 'مشکل',
  'tropical': 'اشناطدی',
  'ugly': 'بدصورت',
  'unable': 'ناقابل',
  'uncle': 'چچا',
  'unfair': 'غیر منصفانہ',
  'unfit': 'ناقابل',
  'unhappy': 'ناخوش',
  'unique': 'منفرد',
  'united': 'متحد',
  'unknown': 'نامعلوم',
  'upper': 'بالا',
  'upright': 'سیدھا',
  'upset': 'پریشان',
  'urban': 'شہری',
  'urgent': 'فوری',
  'usual': 'معمول',
  'vacant': 'خالی',
  'vain': 'فضول',
  'valid': 'درست',
  'valuable': 'قیمتی',
  'vast': 'وسیع',
  'vegetable': 'سبزی',
  'vertical': 'عمودی',
  'violent': 'پرتشدد',
  'visible': 'مرئی',
  'vital': 'ضروری',
  'vivid': 'روشن',
  'warm': 'گرم',
  'weak': 'کمزور',
  'wealthy': 'امیر',
  'weary': 'تھکا ہوا',
  'western': 'مغربی',
  'whole': 'پورا',
  'wicked': 'شریر',
  'wide': 'وسیع',
  'wild': 'جنگلی',
  'willing': 'تیار',
  'winning': 'جیتنے والا',
  'winter': 'سردی',
  'wonderful': 'شاندار',
  'worthy': 'قابل',
  'wrong': 'غلط',
  'young': 'جوان',


  // === Additional sentence fragments ===
  'aaaa': 'ہم قافیہ',
  'abab': 'متبادل قافیہ',
  'abcb': 'غیر ہم قافیہ',
  'action or process': 'عمل یا طریقہ',
  'collective noun': 'اسم جمع',
  'independent clause': 'آزاد شق',
  'capable of': 'قابل',
  'unassigned': 'غیر تفویض شدہ',
  'aliens': 'خارجی مخلوق',
  'dragons': 'اژدہے',
  'einstein': 'آئن سٹائن',
  'the chef': 'شیف',
  'the ancient manuscript': 'قدیم مخطوطہ',
  'dining': 'کھانا کھانا',
  'awfully good': 'بہت اچھا',
  'fire-breathing': 'آگ اگلنے والا',
  'breathed': 'سانس لیا',
  'was': 'تھا',
  'have begun': 'شروع کر چکے ہیں',
  'have eaten': 'کھا چکے ہیں',
  'have travelled': 'سفر کر چکے ہیں',
  'have written': 'لکھ چکے ہیں',
  'he finished the report': 'اس نے رپورٹ ختم کی',
  'he finishes the report': 'وہ رپورٹ ختم کرتا ہے',
  'he had finished the report': 'اس نے رپورٹ ختم کر لی تھی',
  'he has finished the report': 'اس نے رپورٹ ختم کر لی ہے',
  'he is finishing the report': 'وہ رپورٹ ختم کر رہا ہے',
  'he was finishing the report': 'وہ رپورٹ ختم کر رہا تھا',
  'he will finish the report': 'وہ رپورٹ ختم کرے گا',
  'we decided': 'ہم نے فیصلہ کیا',
  'were beginning': 'شروع کر رہے تھے',
  'were eating': 'کھا رہے تھے',
  'were travelling': 'سفر کر رہے تھے',
  'were writing': 'لکھ رہے تھے',
  'revealed secrets': 'راز افشا کیے',
  'although it was damaged': 'اگرچہ یہ خراب تھا',
  'at the ceremony': 'تقریب میں',
  'because it was raining heavily': 'کیونکہ تیز بارش ہو رہی تھی',
  'before the audience': 'سامعین کے سامنے',
  'behind the props': 'پرپس کے پیچھے',
  'in the morning': 'صبح کے وقت',
  'inside the house': 'گھر کے اندر',
  'over the wall': 'دیوار کے اوپر',
  'under the floorboards': 'فرش بورڈز کے نیچے',
  'under the tree': 'درخت کے نیچے',
  'upstairs': 'اوپر کی منزل',
  'that we should stay': 'کہ ہمیں رہنا چاہیے',
  'the book that i read was fascinating': 'وہ کتاب جو میں نے پڑھی دلچسپ تھی',
  'they plan to travel to japan next year': 'وہ اگلے سال جاپان جانے کا ارادہ رکھتے ہیں',
  'to act impulsively': 'جلد بازی میں کام کرنا',
  'to avoid talking about what is important': 'اہم باتوں سے گریز کرنا',
  'to go on a long hike': 'لمبی سیر پر جانا',
  'which was discovered': 'جو دریافت ہوا',
  'whoever finishes first': 'جو بھی پہلے ختم کرے',
  'will receive the grand prize': 'عظیم انعام ملے گا',
  'change y to i before adding the suffix': 'لاحقہ لگانے سے پہلے Y کو I میں بدلیں',
  'double the y': 'Y کو دہرائیں',
  'keep the y and add the suffix': 'Y رکھیں اور لاحقہ لگائیں',
  'gi': 'جی',

  // === More missing vocabulary ===
  'act': 'عمل کرنا',
  'action': 'عمل',
  'appearance': 'ظاہری شکل',
  'care': 'دیکھ بھال',
  'connotation': 'مفہوم',
  'create': 'تخلیق کرنا',
  'definite': 'یقینی',
  'fill': 'بھرنا',
  'idiom': 'محاورہ',
  'incorrect': 'غلط',
  'indefinite': 'غیر یقینی',
  'magic': 'جادو',
  'other': 'دوسرا',
  'personality': 'شخصیت',
  'rely': 'انحصار کرنا',
  'silent': 'خاموش',
  'size': 'سائز',
  'status': 'حیثیت',
  'text': 'متن',
  'transition': 'انتقال',
  '1st person': 'اول شخص',
  '3rd person': 'غائب شخص',
  'active voice': 'فعل معلوم',
  'analyze input': 'ان پٹ کا تجزیہ کریں',
  'conj': 'حرف عطف',
  'keep analyzing': 'تجزیہ جاری رکھیں',
  'mcq': 'کثیر انتخابی سوال',
  'switch to passive voice': 'مجبول صیغے میں تبدیل کریں',
  'switch to dark mode': 'ڈارک موڈ میں تبدیل کریں',
  'dream house': 'خوابوں کا گھر',
  'exam result': 'امتحانی نتیجہ',
  'high-risk project': 'خطرناک منصوبہ',
  'liquid water': 'پانی',
  'structure intact': 'ساخت برقرار',
  'well-known expert': 'مشہور ماہر',
  'not quite right': 'بالکل درست نہیں',
  'skip to next': 'اگلے پر جائیں',
  'try another': 'دوسرا آزمائیں',
  'do you like tea': 'کیا آپ کو چائے پسند ہے',
  'he went to sleep': 'وہ سو گیا',
  'i love to sleep': 'مجھے سونا پسند ہے',
  'the sleeping baby is peaceful': 'سوتا ہوا بچہ پر سکون ہے',
  'c1': 'سی ایک',
  'c2': 'سی دو',
  'info': 'معلومات',
};

export { WORD_MEANINGS };

interface WordMeaningProps {
  word: string;
}

/**
 * Displays the Roman Urdu meaning of an English word in a small,
 * italic, easy-to-read style. Uses Georgia/serif font for
 * excellent readability of Roman Urdu text.
 * 
 * Returns null if the word is not in the dictionary.
 */
export default function WordMeaning({ word }: WordMeaningProps) {
  if (!word || typeof word !== 'string') return null;
  
  const cleanWord = word.toLowerCase().trim().replace(/[.,!?;:'"()]/g, '');
  const meaning = WORD_MEANINGS[cleanWord];
  if (!meaning) return null;
  
  return (
    <span
      className="font-urdu text-[13px] leading-relaxed text-slate-500 dark:text-slate-400"
      style={{
        letterSpacing: '0.01em',
        fontWeight: 500,
      }}
    >
      ({meaning})
    </span>
  );
}
