/**
 * WordMeaning — displays the Urdu script meaning of an English word inline.
 * Uses a built-in dictionary of common English vocabulary words mapped to
 * Urdu in Nastaliq script for easy readability.
 *
 * The font uses Noto Nastaliq Urdu in a small, clear style that's distinct
 * from the English vocabulary word and easy on the eyes.
 *
 * Usage:
 *   <WordMeaning word="happiness" />
 *   // renders:  (Ø®ÙˆØ´ÛŒ)
 */

// Comprehensive English → Roman Urdu dictionary for vocabulary found in English labs
const WORD_MEANINGS: Record<string, string> = {
  // === Grammar / Parts of Speech ===
  'noun': 'Ø§Ø³Ù…',
  'pronoun': 'Ø¶Ù…ÛŒØ±',
  'verb': 'ÙØ¹Ù„',
  'adverb': 'Ù…ØªØ¹Ø§Ø±Ù',
  'adjective': 'ØµÙØª',
  'preposition': 'Ø­Ø±Ù Ø¬Ø±',
  'conjunction': 'Ø­Ø±Ù Ø¹Ø·Ù',
  'interjection': 'Ø­Ø±Ù Ù†Ø¯Ø§',
  'article': 'Ø­Ø±Ù ØªØ¹Ø±ÛŒÙ',
  'common': 'Ø¹Ø§Ù…',
  'proper': 'Ø®Ø§Øµ',
  'abstract': 'ØªØ¬Ø±Ø¨Ø¯ÛŒ',
  'collective': 'Ø§Ø¬ØªÙ…Ø§Ø¹ÛŒ',
  'concrete': 'ÙˆØ§Ø¶Ø¹ÛŒ',
  'countable': 'Ú¯Ù†Ø§ Ø¬Ø§ Ø³Ú©Ù†Û’ ÙˆØ§Ù„Ø§',
  'uncountable': 'Ù†Ø§Ù‚Ø§Ø¨Ù„ Ú¯Ù†ØªÛŒ',
  'singular': 'ÙˆØ§Ø­Ø¯',
  'plural': 'Ø¬Ù…Ø¹',
  'tense': 'Ø²Ù…Ø§Ù†',
  'active': 'ÙØ¹Ù„ÛŒ',
  'passive': 'Ù…Ø¬ÛÙˆÙ„',
  'simple': 'Ø³Ø§Ø¯Û',
  'continuous': 'Ø¬Ø§Ø±ÛŒ',
  'perfect': 'Ù…Ú©Ù…Ù„',
  'past': 'Ù…Ø§Ø¶ÛŒ',
  'present': 'Ø­Ø§Ù„',
  'future': 'Ù…Ø³ØªÙ‚Ø¨Ù„',
  'positive': 'Ù…Ø«Ø¨Øª',
  'negative': 'Ù…Ù†ÙÛŒ',
  'interrogative': 'Ø³ÙˆØ§Ù„ÛŒÛ',
  'modal': 'Ù…Ø¹Ø¯ÙˆÙ„Û',
  'linking': 'Ø¬ÙˆÚ‘Ù†Û’ ÙˆØ§Ù„Ø§',
  'transitive': 'Ù…ØªØ¹Ø¯ÛŒ',
  'intransitive': 'Ù„Ø§Ø²Ù…',
  'finite': 'Ù…Ø­Ø¯ÙˆØ¯',
  'non-finite': 'non-finite',
  'regular': 'Ø¨Ø§Ù‚Ø§Ø¹Ø¯Û',
  'irregular': 'Ø¨Û’ Ù‚Ø§Ø¹Ø¯Û',
  'gerund': 'Ù…ØµØ¯Ø±',
  'infinitive': 'Ù…ØµØ¯Ø±',
  'participle': 'ØµÙØª ÙØ¹Ù„ÛŒ',
  'subject': 'ÙØ§Ø¹Ù„',
  'object': 'Ù…ÙØ¹ÙˆÙ„',
  'predicate': 'Ø®Ø¨Ø±',
  'affix': 'Ù„Ø§Ø­Ù‚Û',
  'prefix': 'Ø³Ø§Ø¨Ù‚Û',
  'suffix': 'Ù„Ø§Ø­Ù‚Û',
  'root': 'Ø¬Ø°Ø±',
  'phrase': 'Ø¬Ù…Ù„Û',
  'clause': 'Ø´Ù‚',
  'dependent': 'Ù…Ù†Ø­ØµØ±',
  'independent': 'Ø¢Ø²Ø§Ø¯',
  'relative': 'Ù†Ø³Ø¨ØªÛŒ',
  'adverb clause': 'Ù…ØªØ¹Ø§Ø±Ù Ø¬Ù…Ù„Û',
  'noun clause': 'Ø§Ø³Ù…ÛŒ Ø¬Ù…Ù„Û',
  'prepositional phrase': 'Ø­Ø±Ù Ø¬Ø±ÛŒ Ø¬Ù…Ù„Û',

  // === Figures of Speech ===
  'simile': 'ØªØ´Ø¨ÛŒÛ',
  'metaphor': 'Ø§Ø³ØªØ¹Ø§Ø±Û',
  'personification': 'ØªØ´Ø®ÛŒØµ',
  'hyperbole': 'Ù…Ø¨Ø§Ù„ØºÛ',
  'alliteration': 'Ø­Ø±ÙˆÙ Ù…ØªØ´Ø§Ø¨Û',
  'oxymoron': 'Ù…ØªØ¶Ø§Ø¯',
  'euphemism': 'Ú©Ù†Ø§ÛŒÛ',
  'anaphora': 'ØªÚ©Ø±Ø§Ø±',
  'allusion': 'Ø§Ø´Ø§Ø±Û',
  'irony': 'Ø·Ù†Ø²',
  'synecdoche': 'Ú©ÙÙ„ Ø¨Û Ø¬Ø²',
  'metonymy': 'Ù…Ø¬Ø§Ø² Ù…Ø±Ø³Ù„',

  // === Common Vocab from E6 Nouns ===
  'happiness': 'Ø®ÙˆØ´ÛŒ',
  'team': 'Ù¹ÛŒÙ…',
  'dog': 'Ú©ØªØ§',
  'she': 'ÙˆÛ',
  'courage': 'ÛÙ…Øª',
  'river': 'Ø¯Ø±ÛŒØ§',
  'they': 'ÙˆÛ',
  'elephant': 'ÛØ§ØªÚ¾ÛŒ',
  'library': 'Ú©ØªØ¨ Ø®Ø§Ù†Û',
  'information': 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª',
  'bravery': 'Ø¨ÛØ§Ø¯Ø±ÛŒ',
  'crowd': 'ÛØ¬ÙˆÙ…',
  'family': 'Ø®Ø§Ù†Ø¯Ø§Ù†',
  'class': 'Ø¬Ù…Ø§Ø¹Øª',
  'school': 'Ù…Ø¯Ø±Ø³Û',
  'beauty': 'Ø®ÙˆØ¨ØµÙˆØ±ØªÛŒ',
  'health': 'ØµØ­Øª',
  'honesty': 'Ø§ÛŒÙ…Ø§Ù†Ø¯Ø§Ø±ÛŒ',
  'freedom': 'Ø¢Ø²Ø§Ø¯ÛŒ',
  'justice': 'Ø§Ù†ØµØ§Ù',
  'peace': 'Ø§Ù…Ù†',
  'strength': 'Ø·Ø§Ù‚Øª',
  'wisdom': 'Ø­Ú©Ù…Øª',
  'knowledge': 'Ø¹Ù„Ù…',
  'power': 'Ø·Ø§Ù‚Øª',

  // === E7 Vocab ===
  'midnight': 'Ø¢Ø¯Ú¾ÛŒ Ø±Ø§Øª',
  'musings': 'Ø®ÛŒØ§Ù„Ø§Øª',
  'moon': 'Ú†Ø§Ù†Ø¯',
  'ghostly': 'Ø¨Ú¾ÙˆØªÛŒØ§',
  'galleon': 'Ø¨Ø­Ø±ÛŒ Ø¬ÛØ§Ø²',
  'cloudy': 'Ø§Ø¨Ø± Ø¢Ù„ÙˆØ¯',
  'seas': 'Ø³Ù…Ù†Ø¯Ø±',
  'stars': 'Ø³ØªØ§Ø±Û’',
  'sparkled': 'Ú†Ù…Ú©Ø§',
  'diamonds': 'ÛÛŒØ±Û’',
  'dark': 'Ø§Ù†Ø¯Ú¾ÛŒØ±Ø§',
  'night': 'Ø±Ø§Øª',
  'sky': 'Ø¢Ø³Ù…Ø§Ù†',
  'old': 'Ù¾Ø±Ø§Ù†Ø§',
  'house': 'Ú¯Ú¾Ø±',
  'groaned': 'Ú©Ú‘Ú©Ø§ÛŒØ§',
  'complained': 'Ø´Ú©Ø§ÛŒØª Ú©ÛŒ',
  'strong': 'Ù…Ø¶Ø¨ÙˆØ·',
  'wind': 'ÛÙˆØ§',
  'weighs': 'ÙˆØ²Ù† ÛÛ’',
  'ton': 'Ù¹Ù†',
  'whispering': 'Ø³Ø±Ú¯ÙˆØ´ÛŒ',
  'wandering': 'Ø¢ÙˆØ§Ø±Û',
  'weeping': 'Ø±ÙˆØªØ§ ÛÙˆØ§',
  'willows': 'Ø¨ÛŒØ¯ Ù…Ø¬Ù†ÙˆÚº',
  'queen': 'Ù…Ù„Ú©Û',
  'king': 'Ø¨Ø§Ø¯Ø´Ø§Û',
  'kingdom': 'Ø³Ù„Ø·Ù†Øª',
  'knights': 'Ø´ÙˆØ±ÙˆÛŒØ±ÙˆÚº',
  'crown': 'ØªØ§Ø¬',
  'wise': 'Ø¹Ù‚Ù„Ù…Ù†Ø¯',
  'battle': 'Ø¬Ù†Ú¯',
  'castle': 'Ù‚Ù„Ø¹Û',
  'sword': 'ØªÙ„ÙˆØ§Ø±',
  'shield': 'ÚˆÚ¾Ø§Ù„',
  'messenger': 'Ù‚Ø§ØµØ¯',
  'treasure': 'Ø®Ø²Ø§Ù†Û',
  'map': 'Ù†Ù‚Ø´Û',
  'adventure': 'Ù…ÛÙ… Ø¬ÙˆØ¦ÛŒ',
  'journey': 'Ø³ÙØ±',
  'story': 'Ú©ÛØ§Ù†ÛŒ',
  'poem': 'Ù†Ø¸Ù…',
  'writer': 'Ù…ØµÙ†Ù',
  'reader': 'Ù‚Ø§Ø±ÛŒ',
  'editor': 'Ù…Ø¯ÙˆÙ†',
  'author': 'Ù…ØµÙ†Ù',
  'poet': 'Ø´Ø§Ø¹Ø±',
  'line': 'Ø³Ø·Ø±',
  'verse': 'Ø¢ÛŒØª',
  'stanza': 'Ø¨Ù†Ø¯',
  'rhyme': 'Ù‚Ø§ÙÛŒÛ',
  'rhythm': 'ÙˆØ²Ù†',

  // === E8 Vocab ===
  'data': 'Ø§Ø¹Ø¯Ø§Ø¯ Ùˆ Ø´Ù…Ø§Ø±',
  'archives': 'Ù…Ø­ÙÙˆØ¸Ø§Øª',
  'lexicon': 'Ù„ØºØª',
  'vocabulary': 'Ø°Ø®ÛŒØ±Û Ø§Ù„ÙØ§Ø¸',
  'dictionary': 'Ù„ØºØª',
  'synonym': 'Ù…ØªØ±Ø§Ø¯Ù',
  'antonym': 'Ù…ØªØ¶Ø§Ø¯',
  'meaning': 'Ù…Ø¹Ù†ÛŒ',
  'definition': 'ØªØ¹Ø±ÛŒÙ',
  'example': 'Ù…Ø«Ø§Ù„',
  'syllable': 'Ø­Ø±Ù',
  'letter': 'Ø­Ø±Ù',
  'word': 'Ù„ÙØ¸',
  'sentence': 'Ø¬Ù…Ù„Û',
  'paragraph': 'Ù¾ÛŒØ±Ø§',
  'essay': 'Ù…Ø¶Ù…ÙˆÙ†',
  'composition': 'ØªÙ‚Ø±ÛŒØ±',
  'grammar': 'Ù‚ÙˆØ§Ø¹Ø¯',
  'spelling': 'ÛØ¬Û’',
  'punctuation': 'Ø±Ù…ÙˆØ² Ø§ÙˆÙ‚Ø§Ù',
  'period': 'ÙˆÙ‚ÙÛ',
  'comma': 'Ú©ÙˆÙ…Ø§',
  'question': 'Ø³ÙˆØ§Ù„',
  'exclamation': 'ØªØ¹Ø¬Ø¨',
  'quotation': 'Ø§Ù‚ØªØ¨Ø§Ø³',
  'apostrophe': 'Ø¹Ù„Ø§Ù…Øª Ø§Ø¶Ø§ÙØª',
  'colon': 'Ù†Ù‚Ø·Û Ø¯Ùˆ',
  'semicolon': 'Ù†Ù‚Ø·Û ÙˆØ§Ø±',
  'dash': 'Ø®Ø·',
  'hyphen': 'Ù†Ø´Ø§Ù†Û',
  'bracket': 'Ù‚ÙˆØ³ÛŒÙ†',
  'capital': 'Ø¨Ú‘Ø§',
  'uppercase': 'Ø¨Ú‘ÛŒ Ø¹Ø¨Ø§Ø±Øª',
  'lowercase': 'Ú†Ú¾ÙˆÙ¹ÛŒ Ø¹Ø¨Ø§Ø±Øª',
  'phonetics': 'ØµÙˆØªÛŒØ§Øª',
  'pronunciation': 'ØªÙ„ÙØ¸',
  'accent': 'Ù„ÛØ¬Û',
  'stress': 'Ø²ÙˆØ±',
  'intonation': 'Ù„ÛØ¬Û',

  // === Modals / Verbs ===
  'must': 'Ù„Ø§Ø²Ù…ÛŒ',
  'should': 'Ú†Ø§ÛÛŒÛ’',
  'could': 'Ø³Ú©ØªØ§',
  'would': 'Ú¯Ø§',
  'may': 'Ø³Ú©ØªØ§ ÛÛ’',
  'might': 'Ø´Ø§ÛŒØ¯',
  'can': 'Ø³Ú©ØªØ§',
  'will': 'Ú¯Ø§',
  'shall': 'Ú¯Ø§',
  'ought to': 'Ú†Ø§ÛÛŒÛ’',
  'have to': 'Ù„Ø§Ø²Ù…ÛŒ',
  'need to': 'Ø¶Ø±ÙˆØ±Øª',
  'used to': 'Ú©Ø±ØªØ§ ØªÚ¾Ø§',
  'dare to': 'Ø¬Ø±Ø£Øª',
  'able': 'Ù‚Ø§Ø¨Ù„',
  'must not': 'Ù†ÛÛŒÚº Ú†Ø§ÛÛŒÛ’',
  'cannot': 'Ù†ÛÛŒÚº Ø³Ú©ØªØ§',
  'should not': 'Ù†ÛÛŒÚº Ú†Ø§ÛÛŒÛ’',
  'need not': 'Ø¶Ø±ÙˆØ±Øª Ù†ÛÛŒÚº',

  // === Prepositions ===
  'in': 'Ù…ÛŒÚº',
  'on': 'Ù¾Ø±',
  'at': 'Ù¾Ø±',
  'under': 'Ù†ÛŒÚ†Û’',
  'over': 'Ø§ÙˆÙ¾Ø±',
  'through': 'Ø³Û’',
  'during': 'Ø¯Ø±Ù…ÛŒØ§Ù†',
  'before': 'Ù¾ÛÙ„Û’',
  'after': 'Ø¨Ø¹Ø¯',
  'between': 'Ø¯Ø±Ù…ÛŒØ§Ù†',
  'among': 'mein_1',
  'against': 'Ø®Ù„Ø§Ù',
  'beside': 'Ù¾Ø§Ø³',
  'besides': 'Ø¹Ù„Ø§ÙˆÛ',
  'across': 'Ø¢Ø± Ù¾Ø§Ø±',
  'along': 'Ø³Ø§ØªÚ¾',
  'around': 'Ø§Ø±Ø¯ Ú¯Ø±Ø¯',
  'behind': 'Ù¾ÛŒÚ†Ú¾Û’',
  'below': 'Ù†ÛŒÚ†Û’',
  'beneath': 'Ù†ÛŒÚ†Û’',
  'inside': 'Ø§Ù†Ø¯Ø±',
  'outside': 'Ø¨Ø§ÛØ±',
  'toward': 'Ú©ÛŒ Ø·Ø±Ù',
  'upon': 'Ù¾Ø±',
  'within': 'Ø§Ù†Ø¯Ø±',
  'without': 'Ø¨ØºÛŒØ±',
  'because of': 'Ú©ÛŒ ÙˆØ¬Û Ø³Û’',
  'in spite of': 'Ø¨Ø§ÙˆØ¬ÙˆØ¯',
  'instead of': 'Ø¨Ø¬Ø§Ø¦Û’',
  'apart from': 'Ø¹Ù„Ø§ÙˆÛ',
  'according to': 'Ú©Û’ Ù…Ø·Ø§Ø¨Ù‚',
  'in addition to': 'Ú©Û’ Ø¹Ù„Ø§ÙˆÛ',
  'due to': 'Ú©ÛŒ ÙˆØ¬Û Ø³Û’',
  'out of': 'Ù…ÛŒÚº Ø³Û’',
  'throughout': 'Ø¨Ú¾Ø± Ù…ÛŒÚº',
  'consequently': 'Ù†ØªÛŒØ¬ØªØ§Ù‹',
  'therefore': 'Ù„ÛÙ°Ø°Ø§',
  'however': 'ØªØ§ÛÙ…',
  'meanwhile': 'Ø§Ø³ÛŒ Ø¯ÙˆØ±Ø§Ù†',
  'nevertheless': 'Ø¨Ø§ÙˆØµÙ',

  // === Conjunctions ===
  'and': 'Ø§ÙˆØ±',
  'or': 'ÛŒØ§',
  'but': 'Ù„ÛŒÚ©Ù†',
  'yet': 'Ù¾Ú¾Ø± Ø¨Ú¾ÛŒ',
  'so': 'ØªÙˆ',
  'for': 'Ú©ÛŒÙˆÙ†Ú©Û',
  'nor': 'Ù†Û',
  'although': 'Ø§Ú¯Ø±Ú†Û',
  'because': 'Ú©ÛŒÙˆÙ†Ú©Û',
  'since': 'Ú†ÙˆÙ†Ú©Û',
  'unless': 'Ø¬Ø¨ ØªÚ©',
  'while': 'Ø¬Ø¨Ú©Û',
  'when': 'Ø¬Ø¨',
  'where': 'Ø¬ÛØ§Úº',
  'after_1': 'after_1',
  'if': 'Ø§Ú¯Ø±',
  'than': 'Ø³Û’',
  'as': 'Ø¬ÛŒØ³Ø§',

  // === Pronouns ===
  'i': 'Ù…ÛŒÚº',
  'you': 'ØªÙ…',
  'he': 'ÙˆÛ',
  'she_1': 'ÙˆÛ',
  'it': 'ÛŒÛ',
  'we': 'ÛÙ…',
  'my': 'Ù…ÛŒØ±Ø§',
  'your': 'ØªÙ…ÛØ§Ø±Ø§',
  'his': 'Ø§Ø³ Ú©Ø§',
  'her': 'Ø§Ø³ Ú©Ø§',
  'its': 'Ø§Ø³ Ú©Ø§',
  'our': 'ÛÙ…Ø§Ø±Ø§',
  'their': 'Ø§Ù† Ú©Ø§',
  'me': 'Ù…Ø¬Ú¾Û’',
  'him': 'Ø§Ø³Û’',
  'her_1': 'Ø§Ø³Û’',
  'us': 'ÛÙ…ÛŒÚº',
  'them': 'Ø§Ù†ÛÛŒÚº',
  'this': 'ÛŒÛ',
  'that': 'ÙˆÛ',
  'these': 'ÛŒÛ',
  'those': 'ÙˆÛ',
  'some': 'Ú©Ú†Ú¾',
  'any': 'Ú©ÙˆØ¦ÛŒ',
  'every': 'ÛØ±',
  'each': 'ÛØ± Ø§ÛŒÚ©',
  'none': 'Ú©ÙˆØ¦ÛŒ Ù†ÛÛŒÚº',
  'all': 'Ø³Ø¨',
  'both': 'Ø¯ÙˆÙ†ÙˆÚº',
  'few': 'Ú†Ù†Ø¯',
  'many': 'Ø¨ÛØª',
  'much': 'Ø¨ÛØª',
  'several': 'Ú©Ø¦ÛŒ',
  'nobody': 'Ú©ÙˆØ¦ÛŒ Ù†ÛÛŒÚº',
  'nothing': 'Ú©Ú†Ú¾ Ù†ÛÛŒÚº',
  'everyone': 'ÛØ± Ú©ÙˆØ¦ÛŒ',
  'everything': 'Ø³Ø¨ Ú©Ú†Ú¾',
  'someone': 'Ú©ÙˆØ¦ÛŒ',
  'something': 'Ú©Ú†Ú¾',

  // === Numbers / Determiners ===
  'a': 'Ø§ÛŒÚ©',
  'an': 'Ø§ÛŒÚ©',
  'the': 'ÛŒÛ',
  'no': 'Ù†ÛÛŒÚº',
  'not': 'Ù†ÛÛŒÚº',

  // === E9+ Advanced Vocab ===
  'phrase_1': 'Ø¬Ù…Ù„Û',
  'narration': 'Ø±ÙˆØ§ÛŒØª',
  'reported': 'Ù…Ù†Ù‚ÙˆÙ„',
  'direct': 'Ø¨Ø±Ø§Û Ø±Ø§Ø³Øª',
  'indirect': 'Ø¨Ø§Ù„ÙˆØ§Ø³Ø·Û',
  'command': 'Ø­Ú©Ù…',
  'request': 'Ø¯Ø±Ø®ÙˆØ§Ø³Øª',
  'statement': 'Ø¨ÛŒØ§Ù†',
  'exclamation_1': 'ØªØ¹Ø¬Ø¨',
  'assertive': 'Ø§Ø«Ø¨Ø§ØªÛŒ',
  'interrogative_1': 'Ø³ÙˆØ§Ù„ÛŒÛ',
  'imperative': 'Ø§Ù…Ø±ÛŒÛ',
  'conditional': 'Ø´Ø±Ø·ÛŒÛ',
  'zero': 'ØµÙØ±',
  'first': 'Ù¾ÛÙ„Ø§',
  'second': 'Ø¯ÙˆØ³Ø±Ø§',
  'third': 'ØªÛŒØ³Ø±Ø§',
  'type': 'Ù¹Ø§Ø¦Ù¾ Ú©Ø±Ù†Ø§',
  'real': 'Ø­Ù‚ÛŒÙ‚ÛŒ',
  'unreal': 'ØºÛŒØ± Ø­Ù‚ÛŒÙ‚ÛŒ',
  'possible': 'Ù…Ù…Ú©Ù†',
  'impossible': 'Ù†Ø§Ù…Ù…Ú©Ù†',
  'general truth': 'Ø¹Ø§Ù… Ø­Ù‚ÛŒÙ‚Øª',
  'result': 'Ù†ØªÛŒØ¬Û',
  'cause': 'Ø³Ø¨Ø¨',
  'effect': 'Ø§Ø«Ø±',
  'situation': 'ØµÙˆØ±Øª Ø­Ø§Ù„',
  'scenario': 'Ù…Ù†Ø¸Ø± Ù†Ø§Ù…Û',

  // === Tense-related ===
  'arrives': 'Ø¢ØªØ§ ÛÛ’',
  'arrived': 'Ø¢ÛŒØ§',
  'had arrived': 'Ø¢ÛŒØ§ ØªÚ¾Ø§',
  'will arrive': 'Ø¢Ø¦Û’ Ú¯Ø§',
  'is repairing': 'Ù…Ø±Ù…Øª Ú©Ø± Ø±ÛØ§ ÛÛ’',
  'was being built': 'ØªØ¹Ù…ÛŒØ± ÛÙˆ Ø±ÛØ§ ØªÚ¾Ø§',
  'will travel': 'Ø³ÙØ± Ú©Ø±Û’ Ú¯Ø§',
  'will be watching': 'Ø¯ÛŒÚ©Ú¾ Ø±ÛØ§ ÛÙˆ Ú¯Ø§',
  'were being typed': 'Ù¹Ø§Ø¦Ù¾ ÛÙˆ Ø±ÛÛ’ ØªÚ¾Û’',
  'repair': 'Ù…Ø±Ù…Øª Ú©Ø±Ù†Ø§',
  'build': 'ØªØ¹Ù…ÛŒØ± Ú©Ø±Ù†Ø§',
  'travel': 'Ø³ÙØ± Ú©Ø±Ù†Ø§',
  'watch': 'Ø¯ÛŒÚ©Ú¾Ù†Ø§',
  'study': 'Ù¾Ú‘Ú¾Ù†Ø§',
  'pass': 'Ù¾Ø§Ø³ Ú©Ø±Ù†Ø§',
  'win': 'Ø¬ÛŒØªÙ†Ø§',
  'buy': 'Ø®Ø±ÛŒØ¯Ù†Ø§',
  'cool': 'Ù¹Ú¾Ù†ÚˆØ§ Ú©Ø±Ù†Ø§',
  'freeze': 'Ø¬Ù…Ø§Ù†Ø§',
  'wait': 'Ø§Ù†ØªØ¸Ø§Ø± Ú©Ø±Ù†Ø§',
  'rest': 'Ø¢Ø±Ø§Ù… Ú©Ø±Ù†Ø§',
  'write': 'Ù„Ú©Ú¾Ù†Ø§',
  'read': 'Ù¾Ú‘Ú¾Ù†Ø§',
  'speak': 'Ø¨ÙˆÙ„Ù†Ø§',
  'listen': 'Ø³Ù†Ù†Ø§',
  'learn': 'Ø³ÛŒÚ©Ú¾Ù†Ø§',
  'teach': 'Ù¾Ú‘Ú¾Ø§Ù†Ø§',
  'begin': 'Ø´Ø±ÙˆØ¹ Ú©Ø±Ù†Ø§',
  'finish': 'Ø®ØªÙ… Ú©Ø±Ù†Ø§',
  'continue': 'Ø¬Ø§Ø±ÛŒ Ø±Ú©Ú¾Ù†Ø§',
  'sit': 'Ø¨ÛŒÙ¹Ú¾Ù†Ø§',
  'stand': 'Ú©Ú¾Ú‘Ø§ ÛÙˆÙ†Ø§',
  'run': 'Ø¯ÙˆÚ‘Ù†Ø§',
  'walk': 'Ú†Ù„Ù†Ø§',
  'eat': 'Ú©Ú¾Ø§Ù†Ø§',
  'drink': 'Ù¾ÛŒÙ†Ø§',
  'sleep': 'Ø³ÙˆÙ†Ø§',
  'wake': 'Ø¬Ø§Ú¯Ù†Ø§',
  'play': 'Ú©Ú¾ÛŒÙ„Ù†Ø§',
  'work': 'Ú©Ø§Ù… Ú©Ø±Ù†Ø§',
  'help': 'Ù…Ø¯Ø¯ Ú©Ø±Ù†Ø§',
  'make': 'Ø¨Ù†Ø§Ù†Ø§',
  'take': 'Ù„ÛŒÙ†Ø§',
  'give': 'Ø¯ÛŒÙ†Ø§',
  'come': 'Ø¢Ù†Ø§',
  'go': 'Ø¬Ø§Ù†Ø§',
  'see': 'Ø¯ÛŒÚ©Ú¾Ù†Ø§',
  'know': 'Ø¬Ø§Ù†Ù†Ø§',
  'think': 'Ø³ÙˆÚ†Ù†Ø§',
  'feel': 'Ù…Ø­Ø³ÙˆØ³ Ú©Ø±Ù†Ø§',
  'find': 'ÚˆÚ¾ÙˆÙ†ÚˆÙ†Ø§',
  'show': 'Ø¯Ú©Ú¾Ø§Ù†Ø§',
  'tell': 'Ø¨ØªØ§Ù†Ø§',
  'say': 'Ú©ÛÙ†Ø§',
  'ask': 'Ù¾ÙˆÚ†Ú¾Ù†Ø§',
  'answer': 'Ø¬ÙˆØ§Ø¨ Ø¯ÛŒÙ†Ø§',
  'call': 'Ø¨Ù„Ø§Ù†Ø§',
  'use': 'Ø§Ø³ØªØ¹Ù…Ø§Ù„ Ú©Ø±Ù†Ø§',
  'try': 'Ú©ÙˆØ´Ø´ Ú©Ø±Ù†Ø§',
  'keep': 'Ø±Ú©Ú¾Ù†Ø§',
  'leave': 'Ú†Ú¾ÙˆÚ‘Ù†Ø§',
  'turn': 'Ù…ÙˆÚ‘Ù†Ø§',
  'put': 'Ø±Ú©Ú¾Ù†Ø§',
  'set': 'Ø±Ú©Ú¾Ù†Ø§',
  'bring': 'Ù„Ø§Ù†Ø§',
  'send': 'Ø¨Ú¾ÛŒØ¬Ù†Ø§',
  'move': 'ÛÙ„Ù†Ø§',
  'change': 'Ø¨Ø¯Ù„Ù†Ø§',

  // === Time words ===
  'today': 'Ø¢Ø¬',
  'tonight': 'Ø¢Ø¬ Ø±Ø§Øª',
  'tomorrow': 'Ú©Ù„',
  'yesterday': 'Ú©Ù„',
  'now': 'Ø§Ø¨',
  'soon': 'Ø¬Ù„Ø¯',
  'always': 'ÛÙ…ÛŒØ´Û',
  'never': 'Ú©Ø¨Ú¾ÛŒ Ù†ÛÛŒÚº',
  'often': 'Ø§Ú©Ø«Ø±',
  'sometimes': 'Ú©Ø¨Ú¾ÛŒ Ú©Ø¨Ú¾ÛŒ',
  'usually': 'Ù…Ø¹Ù…ÙˆÙ„Ø§Ù‹',
  'already': 'Ù¾ÛÙ„Û’ Ø³Û’',
  'still': 'Ø§Ø¨Ú¾ÛŒ ØªÚ©',
  'yet_1': 'Ø§Ø¨Ú¾ÛŒ ØªÚ©',

  // === Misc Educational ===
  'sentence_1': 'Ø¬Ù…Ù„Û',
  'syllabus': 'Ù†ØµØ§Ø¨',
  'chapter': 'Ø³Ø¨Ù‚',
  'lesson': 'Ø³Ø¨Ù‚',
  'exercise': 'Ù…Ø´Ù‚',
  'practice': 'Ù…Ø´Ù‚',
  'test': 'Ø§Ù…ØªØ­Ø§Ù†',
  'exam': 'Ø§Ù…ØªØ­Ø§Ù†',
  'question_1': 'Ø³ÙˆØ§Ù„',
  'mark': 'Ù†Ø´Ø§Ù†',
  'grade': 'Ø¯Ø±Ø¬Û',
  'score': 'Ø³Ú©ÙˆØ±',
  'answer_1': 'Ø¬ÙˆØ§Ø¨',
  'learn_1': 'learn_1',
  'understand': 'Ø³Ù…Ø¬Ú¾Ù†Ø§',
  'remember': 'ÛŒØ§Ø¯ Ø±Ú©Ú¾Ù†Ø§',
  'forget': 'Ø¨Ú¾ÙˆÙ„Ù†Ø§',
  'repeat': 'Ø¯ÛØ±Ø§Ù†Ø§',
  'explain': 'ÙˆØ¶Ø§Ø­Øª Ú©Ø±Ù†Ø§',
  'describe': 'Ø¨ÛŒØ§Ù† Ú©Ø±Ù†Ø§',
  'identify': 'Ù¾ÛÚ†Ø§Ù†Ù†Ø§',
  'choose': 'Ú†Ù†Ù†Ø§',
  'select': 'Ù…Ù†ØªØ®Ø¨ Ú©Ø±Ù†Ø§',
  'match': 'Ù…Ù„Ø§Ù†Ø§',
  'complete': 'Ù…Ú©Ù…Ù„ Ú©Ø±Ù†Ø§',
  'correct': 'Ø¯Ø±Ø³Øª Ú©Ø±Ù†Ø§',
  'check': 'Ø¬Ø§Ù†Ú†Ù†Ø§',
  'review': 'Ø¯ÙˆØ¨Ø§Ø±Û Ø¯ÛŒÚ©Ú¾Ù†Ø§',
  'practice_1': 'Ù…Ø´Ù‚ Ú©Ø±Ù†Ø§',
  'improve': 'Ø¨ÛØªØ± Ú©Ø±Ù†Ø§',
  'master': 'Ù…Ø§ÛØ± ÛÙˆÙ†Ø§',
  'skill': 'ÛÙ†Ø±',
  'ability': 'Ù‚Ø§Ø¨Ù„ÛŒØª',
  'goal': 'Ù…Ù‚ØµØ¯',
  'objective': 'Ù…Ù‚ØµØ¯',
  // === Additional vocabulary from labs ===
  'abstract noun': 'Ø§Ø³Ù… Ù…Ø¹Ù†ÛŒ',
  'action verb': 'ÙØ¹Ù„ÛŒ ÙØ¹Ù„',
  'alien': 'Ø§Ø¬Ù†Ø¨ÛŒ',
  'apple': 'Ø³ÛŒØ¨',
  'beautiful': 'Ø®ÙˆØ¨ØµÙˆØ±Øª',
  'brick': 'Ø§ÛŒÙ†Ù¹',
  'bunch': 'Ú¯Ú†Ú¾Ø§',
  'capable': 'Ù‚Ø§Ø¨Ù„',
  'car': 'Ú¯Ø§Ú‘ÛŒ',
  'clever': 'ÛÙˆØ´ÛŒØ§Ø±',
  'clumsily': 'Ø¨Û’ÚˆÚ¾Ù†Ú¯Û’ Ù¾Ù† Ø³Û’',
  'committee': 'Ú©Ù…ÛŒÙ¹ÛŒ',
  'compound': 'Ù…Ø±Ú©Ø¨',
  'danger': 'Ø®Ø·Ø±Û',
  'deafening silence': 'Ø¨Û’Ø­Ø¯ Ø®Ø§Ù…ÙˆØ´ÛŒ',
  'demonstrative': 'Ø§Ø´Ø§Ø±Û',
  'dependent clause': 'Ù…Ù†Ø­ØµØ± Ø¬Ù…Ù„Û',
  'ditransitive': 'Ø¯Ùˆ Ù…ØªØ¹Ø¯ÛŒ',
  'dodged': 'Ø¨Ú† Ú¯ÛŒØ§',
  'dragon': 'Ø§Ú˜Ø¯ÛØ§',
  'error': 'ØºÙ„Ø·ÛŒ',
  'exclamatory': 'ØªØ¹Ø¬Ø¨ÛŒÛ',
  'ferocious': 'Ø®ÙˆÙÙ†Ø§Ú©',
  'fire': 'Ø¢Ú¯',
  'five': 'Ù¾Ø§Ù†Ú†',
  'flock': 'Ø±ÛŒÙˆÚ‘',
  'fought': 'Ù„Ú‘Ø§',
  'fox': 'Ù„ÙˆÙ…Ú‘ÛŒ',
  'ganges': 'Ú¯Ù†Ú¯Ø§',
  'huge': 'Ø¨ÛØª Ø¨Ú‘Ø§',
  'inquisitive': 'ØªØ¬Ø³Ø³',
  'interfering': 'Ù…Ø¯Ø§Ø®Ù„Øª Ú©Ø±Ù†Û’ ÙˆØ§Ù„Ø§',
  'into': 'Ù…ÛŒÚº',
  'jury': 'Ø¬Ø±ÛŒ',
  'keyboard': 'Ú©ÛŒ Ø¨ÙˆØ±Úˆ',
  'later': 'Ø¨Ø¹Ø¯ Ù…ÛŒÚº',
  'little': 'ØªÚ¾ÙˆÚ‘Ø§',
  'london': 'Ù„Ù†Ø¯Ù†',
  'lost': 'Ú©Ú¾Ùˆ Ø¯ÛŒØ§',
  'microscope': 'Ø®Ø±Ø¯Ø¨ÛŒÙ†',
  'optative': 'Ø®ÙˆØ§ÛØ´ÛŒÛ',
  'paradox': 'Ù…ØªØ¶Ø§Ø¯',
  'perfect continuous': 'Ù…Ú©Ù…Ù„ Ø¬Ø§Ø±ÛŒ',
  'personal pronoun': 'Ø°Ø§ØªÛŒ Ø¶Ù…ÛŒØ±',
  'possessive': 'Ø§Ø¶Ø§ÙÛŒ',
  'protect': 'Ø­ÙØ§Ø¸Øª Ú©Ø±Ù†Ø§',
  'prying': 'ØªØ¬Ø³Ø³',
  'quantitative': 'Ù…Ù‚Ø¯Ø§Ø±ÛŒ',
  'quickly': 'Ø¬Ù„Ø¯ÛŒ Ø³Û’',
  'realized': 'Ø§Ø­Ø³Ø§Ø³ ÛÙˆØ§',
  'red': 'Ø³Ø±Ø®',
  'reflexive pronoun': 'Ø±Ø¬ÙˆØ¹ÛŒ Ø¶Ù…ÛŒØ±',
  'relative clause': 'Ù†Ø³Ø¨ØªÛŒ Ø¬Ù…Ù„Û',
  'relative pronoun': 'Ù†Ø³Ø¨ØªÛŒ Ø¶Ù…ÛŒØ±',
  'round': 'Ú¯ÙˆÙ„',
  'said': 'Ú©ÛØ§',
  'shiny': 'Ú†Ù…Ú©Ø¯Ø§Ø±',
  'similarly': 'Ø§Ø³ÛŒ Ø·Ø±Ø­',
  'small': 'Ú†Ú¾ÙˆÙ¹Ø§',
  'success': 'Ú©Ø§Ù…ÛŒØ§Ø¨ÛŒ',
  'summoned': 'Ø·Ù„Ø¨ Ú©ÛŒØ§',
  'table': 'Ù…ÛŒØ²',
  'themselves': 'Ø®ÙˆØ¯',
  'tired': 'ØªÚ¾Ú©Ø§ ÛÙˆØ§',
  'to': 'Ú©Ùˆ',
  'toothbrush': 'Ø¯Ø§Ù†ØªÙˆÚº Ú©Ø§ Ø¨Ø±Ø´',
  'well-known': 'Ù…Ø´ÛÙˆØ±',
  'wooden': 'Ù„Ú©Ú‘ÛŒ Ú©Ø§',
  'who': 'Ú©ÙˆÙ†',
  // === Additional prepositions ===
  'above': 'Ø§ÙˆÙ¾Ø±',
  'down': 'Ù†ÛŒÚ†Û’',
  'up': 'Ø§ÙˆÙ¾Ø±',
  'off': 'Ø¯ÙˆØ±',
  'near': 'Ù‚Ø±ÛŒØ¨',
  'far': 'Ø¯ÙˆØ±',
  'forward': 'Ø¢Ú¯Û’',
  'backward': 'Ù¾ÛŒÚ†Ú¾Û’',
  'towards': 'Ú©ÛŒ Ø·Ø±Ù',
  // === Additional adjectives ===
  'happy': 'Ø®ÙˆØ´',
  'sad': 'Ø§Ø¯Ø§Ø³',
  'angry': 'Ù†Ø§Ø±Ø§Ø¶',
  'excited': 'Ù¾Ø±Ø¬ÙˆØ´',
  'calm': 'Ù¾Ø±Ø³Ú©ÙˆÙ†',
  'nervous': 'Ú¯Ú¾Ø¨Ø±Ø§ÛŒØ§',
  'brave': 'Ø¨ÛØ§Ø¯Ø±',
  'wise_1': 'Ø¹Ù‚Ù„Ù…Ù†Ø¯',
  'foolish': 'Ø¨ÛŒÙˆÙ‚ÙˆÙ',
  'kind': 'Ù…ÛØ±Ø¨Ø§Ù†',
  'cruel': 'Ø¸Ø§Ù„Ù…',
  'generous': 'Ø³Ø®ÛŒ',
  'selfish': 'Ø®ÙˆØ¯ ØºØ±Ø¶',
  'polite': 'Ø´Ø§Ø¦Ø³ØªÛ',
  'rude': 'Ø¨Ø¯ØªÙ…ÛŒØ²',
  'lazy': 'Ø³Ø³Øª',
  'hardworking': 'Ù…Ø­Ù†ØªÛŒ',
  'honest': 'Ø§ÛŒÙ…Ø§Ù†Ø¯Ø§Ø±',
  'patient': 'ØµØ§Ø¨Ø±',
  'intelligent': 'Ø°ÛÛŒÙ†',
  // === Additional pronouns ===
  'myself': 'Ø®ÙˆØ¯',
  'yourself': 'Ø®ÙˆØ¯',
  'himself': 'Ø®ÙˆØ¯',
  'herself': 'Ø®ÙˆØ¯',
  'itself': 'Ø®ÙˆØ¯',
  'ourselves': 'Ø®ÙˆØ¯',
  'yourselves': 'Ø®ÙˆØ¯',
  // === Additional verbs ===
  'become': 'Ø¨Ù†Ù†Ø§',
  'became': 'Ø¨Ù†Ø§',
  'begin_1': 'Ø´Ø±ÙˆØ¹ Ú©Ø±Ù†Ø§',
  'began': 'Ø´Ø±ÙˆØ¹ Ú©ÛŒØ§',
  'break': 'ØªÙˆÚ‘Ù†Ø§',
  'broken': 'Ù¹ÙˆÙ¹Ø§',
  'bring_1': 'Ù„Ø§Ù†Ø§',
  'brought': 'Ù„Ø§ÛŒØ§',
  'catch': 'Ù¾Ú©Ú‘Ù†Ø§',
  'caught': 'Ù¾Ú©Ú‘Ø§',
  'choose_1': 'Ú†Ù†Ù†Ø§',
  'chose': 'Ú†Ù†Ø§',
  'cut': 'Ú©Ø§Ù¹Ù†Ø§',
  'draw': 'Ú©Ú¾ÛŒÙ†Ú†Ù†Ø§',
  'drew': 'Ú©Ú¾ÛŒÙ†Ú†Ø§',
  'drink_1': 'Ù¾ÛŒÙ†Ø§',
  'drank': 'Ù¾ÛŒØ§',
  'drive': 'Ú†Ù„Ø§Ù†Ø§',
  'drove': 'Ú†Ù„Ø§ÛŒØ§',
  'eat_1': 'Ú©Ú¾Ø§Ù†Ø§',
  'ate': 'Ú©Ú¾Ø§ÛŒØ§',
  'fall': 'Ú¯Ø±Ù†Ø§',
  'fell': 'Ú¯Ø±Ø§',
  'fly': 'Ø§Ú‘Ù†Ø§',
  'flew': 'Ø§Ú‘Ø§',
  'forget_1': 'Ø¨Ú¾ÙˆÙ„Ù†Ø§',
  'forgot': 'Ø¨Ú¾ÙˆÙ„Ø§',
  'grow': 'Ø¨Ú‘Ú¾Ù†Ø§',
  'grew': 'Ø¨Ú‘Ú¾Ø§',
  'hide': 'Ú†Ú¾Ù¾Ù†Ø§',
  'hid': 'Ú†Ú¾Ù¾Ø§',
  'hold': 'Ù¾Ú©Ú‘Ù†Ø§',
  'held': 'Ù¾Ú©Ú‘Ø§',
  'hurt': 'Ú†ÙˆÙ¹ Ù„Ú¯Ù†Ø§',
  'keep_1': 'Ø±Ú©Ú¾Ù†Ø§',
  'kept': 'Ø±Ú©Ú¾Ø§',
  'lead': 'Ø±ÛÙ†Ù…Ø§Ø¦ÛŒ Ú©Ø±Ù†Ø§',
  'led': 'Ø±ÛÙ†Ù…Ø§Ø¦ÛŒ Ú©ÛŒ',
  'lend': 'Ù‚Ø±Ø¶ Ø¯ÛŒÙ†Ø§',
  'lent': 'Ù‚Ø±Ø¶ Ø¯ÛŒØ§',
  'lie': 'Ø¬Ú¾ÙˆÙ¹ Ø¨ÙˆÙ„Ù†Ø§',
  'lay': 'Ù„ÛŒÙ¹Ù†Ø§',
  'mean': 'Ù…Ø·Ù„Ø¨ Ø±Ú©Ú¾Ù†Ø§',
  'meant': 'Ù…Ø·Ù„Ø¨ ØªÚ¾Ø§',
  'meet': 'Ù…Ù„Ù†Ø§',
  'met': 'Ù…Ù„Ø§',
  'pay': 'Ø§Ø¯Ø§ Ú©Ø±Ù†Ø§',
  'paid': 'Ø§Ø¯Ø§ Ú©ÛŒØ§',
  'prove': 'Ø«Ø§Ø¨Øª Ú©Ø±Ù†Ø§',
  'proved': 'Ø«Ø§Ø¨Øª Ú©ÛŒØ§',
  'put_1': 'Ø±Ú©Ú¾Ù†Ø§',
  'quit': 'Ú†Ú¾ÙˆÚ‘Ù†Ø§',
  'quit_1': 'Ú†Ú¾ÙˆÚ‘ Ø¯ÛŒØ§',
  'rise': 'Ø§Ù¹Ú¾Ù†Ø§',
  'rose': 'Ø§Ù¹Ú¾Ø§',
  'sell': 'Ø¨ÛŒÚ†Ù†Ø§',
  'sold': 'Ø¨ÛŒÚ†Ø§',
  'shake': 'ÛÙ„Ø§Ù†Ø§',
  'shook': 'ÛÙ„Ø§ÛŒØ§',
  'shine': 'Ú†Ù…Ú©Ù†Ø§',
  'shone': 'Ú†Ù…Ú©Ø§',
  'shut': 'Ø¨Ù†Ø¯ Ú©Ø±Ù†Ø§',
  'sing': 'Ú¯Ø§Ù†Ø§',
  'sang': 'Ú¯Ø§ÛŒØ§',
  'sink': 'ÚˆÙˆØ¨Ù†Ø§',
  'sank': 'ÚˆÙˆØ¨Ø§',
  'spend': 'Ø®Ø±Ú† Ú©Ø±Ù†Ø§',
  'spent': 'Ø®Ø±Ú† Ú©ÛŒØ§',
  'spread': 'Ù¾Ú¾ÛŒÙ„Ø§Ù†Ø§',
  'steal': 'Ú†ÙˆØ±ÛŒ Ú©Ø±Ù†Ø§',
  'stole': 'Ú†ÙˆØ±ÛŒ Ú©ÛŒØ§',
  'stolen': 'Ú†ÙˆØ±ÛŒ Ø´Ø¯Û',
  'swim': 'ØªÛŒØ±Ù†Ø§',
  'swam': 'ØªÛŒØ±Ø§',
  'tear': 'Ù¾Ú¾Ø§Ú‘Ù†Ø§',
  'tore': 'Ù¾Ú¾Ø§Ú‘Ø§',
  'throw': 'Ù¾Ú¾ÛŒÙ†Ú©Ù†Ø§',
  'threw': 'Ù¾Ú¾ÛŒÙ†Ú©Ø§',
  'understand_1': 'Ø³Ù…Ø¬Ú¾Ù†Ø§',
  'understood': 'Ø³Ù…Ø¬Ú¾Ø§',
  'wear': 'Ù¾ÛÙ†Ù†Ø§',
  'wore': 'Ù¾ÛÙ†Ø§',
  'weep': 'Ø±ÙˆÙ†Ø§',
  'wept': 'Ø±ÙˆÛŒØ§',
  'withdraw': 'ÙˆØ§Ù¾Ø³ Ù„ÛŒÙ†Ø§',
  'withdrew': 'ÙˆØ§Ù¾Ø³ Ù„ÛŒØ§',
  'withdrawn': 'ÙˆØ§Ù¾Ø³ Ù„ÛŒØ§ Ú¯ÛŒØ§',
  'awake': 'Ø¬Ø§Ú¯Ù†Ø§',
  'awoke': 'Ø¬Ø§Ú¯Ø§',
  'beat': 'ÛØ±Ø§Ù†Ø§',
  'beat_1': 'ÛØ±Ø§ÛŒØ§',
  'bend': 'Ù…ÙˆÚ‘Ù†Ø§',
  'bent': 'Ù…ÙˆÚ‘Ø§',
  'bet': 'Ø´Ø±Ø· Ù„Ú¯Ø§Ù†Ø§',
  'bite': 'Ú©Ø§Ù¹Ù†Ø§',
  'bit': 'Ú©Ø§Ù¹Ø§',
  'blow': 'Ù¾Ú¾ÙˆÙ†Ú©Ù†Ø§',
  'blew': 'Ù¾Ú¾ÙˆÙ†Ú©Ø§',
  'burn': 'Ø¬Ù„Ù†Ø§',
  'burnt': 'Ø¬Ù„Ø§',
  'climb': 'Ú†Ú‘Ú¾Ù†Ø§',
  'climbed': 'Ú†Ú‘Ú¾Ø§',
  'cost': 'Ù‚ÛŒÙ…Øª',
  'deal': 'Ù†Ù…Ù¹Ù†Ø§',
  'dealt': 'Ù†Ù…Ù¹Ø§',
  'dig': 'Ú©Ú¾ÙˆØ¯Ù†Ø§',
  'dug': 'Ú©Ú¾ÙˆØ¯Ø§',
  'dream': 'Ø®ÙˆØ§Ø¨ Ø¯ÛŒÚ©Ú¾Ù†Ø§',
  'dreamt': 'Ø®ÙˆØ§Ø¨ Ø¯ÛŒÚ©Ú¾Ø§',
  'feed': 'Ú©Ú¾Ù„Ø§Ø§Ù†Ø§',
  'fed': 'Ú©Ú¾Ù„Ø§ÛŒØ§',
  'fight': 'Ù„Ú‘Ù†Ø§',
  'fought_1': 'Ù„Ú‘Ø§',
  'fit': 'ÙÙ¹ ÛÙˆÙ†Ø§',
  'forgive': 'Ù…Ø¹Ø§Ù Ú©Ø±Ù†Ø§',
  'forgave': 'Ù…Ø¹Ø§Ù Ú©ÛŒØ§',
  'freeze_1': 'Ø¬Ù…Ù†Û',
  'froze': 'Ø¬Ù… Ú¯ÛŒØ§',
  'frozen': 'Ø¬Ù… Ú¯ÛŒØ§',
  'grind': 'Ù¾ÛŒØ³Ù†Ø§',
  'ground': 'Ù¾ÛŒØ³Ø§',
  'hang': 'Ù„Ù¹Ú©Ø§Ù†Ø§',
  'hung': 'Ù„Ù¹Ú©Ø§ÛŒØ§',
  'kneel': 'Ú¯Ú¾Ù¹Ù†Û’ Ù¹ÛŒÚ©Ù†Ø§',
  'knelt': 'Ú¯Ú¾Ù¹Ù†Û’ Ù¹ÛŒÚ©Û’',
  'knit': 'Ø¨Ù†Ù†Ø§',
  'knitted': 'Ø¨Ù†Ø§',
  'lean': 'Ø¬Ú¾Ú©Ù†Ø§',
  'leapt': 'Ú†Ú¾Ù„Ø§Ù†Ú¯ Ù„Ú¯Ø§ÛŒØ§',
  'leap': 'Ú†Ú¾Ù„Ø§Ù†Ú¯',
  'light': 'Ø±ÙˆØ´Ù†ÛŒ',
  'lit': 'Ø±ÙˆØ´Ù† Ú©ÛŒØ§',
  'lose': 'Ú©Ú¾ÙˆÙ†Ø§',
  'lost_1': 'Ú©Ú¾Ùˆ Ø¯ÛŒØ§',
  'mislead': 'Ú¯Ù…Ø±Ø§Û Ú©Ø±Ù†Ø§',
  'misled': 'Ú¯Ù…Ø±Ø§Û Ú©ÛŒØ§',
  'mistake': 'ØºÙ„Ø·ÛŒ Ú©Ø±Ù†Ø§',
  'mistook': 'ØºÙ„Ø·ÛŒ Ú©ÛŒ',
  'mistaken': 'ØºÙ„Ø·ÛŒ ÛÙˆØ¦ÛŒ',
  'overcome': 'Ù‚Ø§Ø¨Ùˆ Ù¾Ø§Ù†Ø§',
  'overcame': 'Ù‚Ø§Ø¨Ùˆ Ù¾Ø§ÛŒØ§',
  'ride': 'Ø³ÙˆØ§Ø±ÛŒ Ú©Ø±Ù†Ø§',
  'rode': 'Ø³ÙˆØ§Ø±ÛŒ Ú©ÛŒ',
  'ring': 'Ø¨Ø¬Ù†Ø§',
  'rang': 'Ø¨Ø¬Ø§',
  'rung': 'Ø¨Ø¬Ø§ÛŒØ§',
  'seek': 'ØªÙ„Ø§Ø´ Ú©Ø±Ù†Ø§',
  'sought': 'ØªÙ„Ø§Ø´ Ú©ÛŒ',
  'sew': 'Ø³Ù„Ø§Ø¦ÛŒ Ú©Ø±Ù†Ø§',
  'sewed': 'Ø³Ù„Ø§Ø¦ÛŒ Ú©ÛŒØ§',
  'sewn': 'Ø³Ù„Ø§ÛŒØ§ ÛÙˆØ§',
  'shoot': 'Ú¯ÙˆÙ„ÛŒ Ù…Ø§Ø±Ù†Ø§',
  'shot': 'Ú¯ÙˆÙ„ÛŒ Ù…Ø§Ø±ÛŒ',
  'shrink': 'Ø³Ú©Ú‘Ù†Ø§',
  'shrank': 'Ø³Ú©Ú‘ Ú¯ÛŒØ§',
  'shrunken': 'Ø³Ú©Ú‘Ø§ ÛÙˆØ§',
  'slide': 'Ù¾Ú¾Ø³Ù„Ù†Ø§',
  'slid': 'Ù¾Ú¾Ø³Ù„Ø§',
  'sow': 'Ø¨ÙˆÙ†Ø§',
  'sowed': 'Ø¨ÙˆÛŒØ§',
  'sown': 'Ø¨ÙˆÛŒØ§ ÛÙˆØ§',
  'spin': 'Ú¯Ú¾Ù…Ø§Ù†Ø§',
  'spun': 'Ú¯Ú¾Ù…Ø§ÛŒØ§',
  'spring': 'Ú†Ú¾Ù„Ø§Ù†Ú¯ Ù„Ú¯Ø§Ù†Ø§',
  'sprang': 'Ú†Ú¾Ù„Ø§Ù†Ú¯ Ù„Ú¯Ø§ÛŒØ§',
  'sting': 'ÚˆÙ†Ú© Ù…Ø§Ø±Ù†Ø§',
  'stung': 'ÚˆÙ†Ú© Ù…Ø§Ø±Ø§',
  'stink': 'Ø¨Ø¯Ø¨ÙˆØ¯Ø§Ø± ÛÙˆÙ†Ø§',
  'stank': 'Ø¨Ø¯Ø¨ÙˆØ¯Ø§Ø± ØªÚ¾Ø§',
  'stride': 'Ø¨Ú‘Û’ Ù‚Ø¯Ù… Ø§Ù¹Ú¾Ø§Ù†Ø§',
  'strode': 'Ø¨Ú‘Û’ Ù‚Ø¯Ù… Ø§Ù¹Ú¾Ø§Ø¦Û’',
  'strike': 'Ù…Ø§Ø±Ù†Ø§',
  'struck': 'Ù…Ø§Ø±Ø§',
  'strive': 'Ú©ÙˆØ´Ø´ Ú©Ø±Ù†Ø§',
  'strove': 'Ú©ÙˆØ´Ø´ Ú©ÛŒ',
  'striven': 'Ú©ÙˆØ´Ø´ Ú©ÛŒ',
  'sweep': 'Ø¬Ú¾Ø§Ú‘Ùˆ Ø¯ÛŒÙ†Ø§',
  'swept': 'Ø¬Ú¾Ø§Ú‘Ùˆ Ø¯ÛŒØ§',
  'swell': 'Ù¾Ú¾ÙˆÙ„Ù†Ø§',
  'swelled': 'Ù¾Ú¾ÙˆÙ„ Ú¯ÛŒØ§',
  'swollen': 'Ù¾Ú¾ÙˆÙ„Ø§ ÛÙˆØ§',
  'swing': 'Ø¬Ú¾ÙˆÙ„Ù†Ø§',
  'swung': 'Ø¬Ú¾ÙˆÙ„Ø§',
  'teach_1': 'Ø³Ú©Ú¾Ø§Ù†Ø§',
  'taught': 'Ø³Ú©Ú¾Ø§ÛŒØ§',
  'think_1': 'Ø³ÙˆÚ†Ù†Ø§',
  'thought': 'Ø³ÙˆÚ†Ø§',
  'thrive': 'Ù¾Ú¾Ù„Ù†Ø§ Ù¾Ú¾ÙˆÙ„Ù†Ø§',
  'throve': 'Ù¾Ú¾Ù„Ø§ Ù¾Ú¾ÙˆÙ„Ø§',
  'thriven': 'Ù¾Ú¾Ù„Ø§ Ù¾Ú¾ÙˆÙ„Ø§',
  'tread': 'Ú†Ù„Ù†Ø§',
  'trod': 'Ú†Ù„Ø§',
  'trodden': 'Ú†Ù„Ø§ ÛÙˆØ§',
  'wake_1': 'Ø¬Ø§Ú¯Ù†Ø§',
  'woke': 'Ø¬Ø§Ú¯Ø§',
  'woken': 'Ø¬Ø§Ú¯Ø§ ÛÙˆØ§',
  'weave': 'Ø¨Ù†Ù†Ø§',
  'wove': 'Ø¨Ù†Ø§',
  'woven': 'Ø¨Ù†Ø§ ÛÙˆØ§',
  'win_1': 'Ø¬ÛŒØªÙ†Ø§',
  'won': 'Ø¬ÛŒØªØ§',
  'wring': 'Ù†Ú†ÙˆÚ‘Ù†Ø§',
  'wrung': 'Ù†Ú†ÙˆÚ‘Ø§',
  'write_1': 'Ù„Ú©Ú¾Ù†Ø§',
  'wrote': 'Ù„Ú©Ú¾Ø§',
  'written': 'Ù„Ú©Ú¾Ø§ ÛÙˆØ§',
  // === Additional common nouns ===
  'animal': 'Ø¬Ø§Ù†ÙˆØ±',
  'book': 'Ú©ØªØ§Ø¨',
  'chair': 'Ú©Ø±Ø³ÛŒ',
  'child': 'Ø¨Ú†Û',
  'city': 'Ø´ÛØ±',
  'country': 'Ù…Ù„Ú©',
  'door': 'Ø¯Ø±ÙˆØ§Ø²Û',
  'earth': 'Ø²Ù…ÛŒÙ†',
  'eye': 'Ø¢Ù†Ú©Ú¾',
  'face': 'Ú†ÛØ±Û',
  'father': 'Ø¨Ø§Ù¾',
  'field': 'Ù…ÛŒØ¯Ø§Ù†',
  'flower': 'Ù¾Ú¾ÙˆÙ„',
  'food': 'Ú©Ú¾Ø§Ù†Ø§',
  'friend': 'Ø¯ÙˆØ³Øª',
  'fruit': 'Ù¾Ú¾Ù„',
  'game': 'Ú©Ú¾ÛŒÙ„',
  'garden': 'Ø¨Ø§Øº',
  'god': 'Ø®Ø¯Ø§',
  'gold': 'Ø³ÙˆÙ†Ø§',
  'ground_1': 'Ø²Ù…ÛŒÙ†',
  'hand': 'ÛØ§ØªÚ¾',
  'head': 'Ø³Ø±',
  'heart': 'Ø¯Ù„',
  'horse': 'Ú¯Ú¾ÙˆÚ‘Ø§',
  'island': 'Ø¬Ø²ÛŒØ±Û',
  'language': 'Ø²Ø¨Ø§Ù†',
  'law': 'Ù‚Ø§Ù†ÙˆÙ†',
  'life': 'Ø²Ù†Ø¯Ú¯ÛŒ',
  'light_1': 'Ø±ÙˆØ´Ù†ÛŒ',
  'love': 'Ù…Ø­Ø¨Øª',
  'man': 'Ø¢Ø¯Ù…ÛŒ',
  'mind': 'Ø¯Ù…Ø§Øº',
  'minute': 'Ù…Ù†Ù¹',
  'money': 'Ù¾ÛŒØ³Û',
  'month': 'Ù…ÛÛŒÙ†Û',
  'mother': 'Ù…Ø§Úº',
  'mountain': 'Ù¾ÛØ§Ú‘',
  'mouth': 'Ù…Ù†Û',
  'music': 'Ù…ÙˆØ³ÛŒÙ‚ÛŒ',
  'name': 'Ù†Ø§Ù…',
  'nation': 'Ù‚ÙˆÙ…',
  'nature': 'ÙØ·Ø±Øª',
  'news': 'Ø®Ø¨Ø±',
  'ocean': 'Ø³Ù…Ù†Ø¯Ø±',
  'pain': 'Ø¯Ø±Ø¯',
  'paper': 'Ú©Ø§ØºØ°',
  'people': 'Ù„ÙˆÚ¯',
  'picture': 'ØªØµÙˆÛŒØ±',
  'place': 'Ø¬Ú¯Û',
  'plant': 'Ù¾ÙˆØ¯Ø§',
  'rain': 'Ø¨Ø§Ø±Ø´',
  'reason': 'ÙˆØ¬Û',
  'road': 'Ø³Ú‘Ú©',
  'rock': 'Ù¾ØªÚ¾Ø±',
  'room': 'Ú©Ù…Ø±Û',
  'sea': 'Ø³Ù…Ù†Ø¯Ø±',
  'ship': 'Ø¬ÛØ§Ø²',
  'side': 'Ø·Ø±Ù',
  'sign': 'Ù†Ø´Ø§Ù†',
  'silver': 'Ú†Ø§Ù†Ø¯ÛŒ',
  'son': 'Ø¨ÛŒÙ¹Ø§',
  'soul': 'Ø±ÙˆØ­',
  'sound': 'Ø¢ÙˆØ§Ø²',
  'south': 'Ø¬Ù†ÙˆØ¨',
  'space': 'Ø®Ù„Ø§',
  'spring_1': 'Ø¨ÛØ§Ø±',
  'star': 'Ø³ØªØ§Ø±Û',
  'steel': 'ÙÙˆÙ„Ø§Ø¯',
  'stone': 'Ù¾ØªÚ¾Ø±',
  'storm': 'Ø·ÙˆÙØ§Ù†',
  'sun': 'Ø³ÙˆØ±Ø¬',
  'system': 'Ù†Ø¸Ø§Ù…',
  'teacher': 'Ø§Ø³ØªØ§Ø¯',
  'thought_1': 'Ø®ÛŒØ§Ù„',
  'time': 'ÙˆÙ‚Øª',
  'tree': 'Ø¯Ø±Ø®Øª',
  'truth': 'Ø³Ú†',
  'universe': 'Ú©Ø§Ø¦Ù†Ø§Øª',
  'valley': 'ÙˆØ§Ø¯ÛŒ',
  'village': 'Ú¯Ø§Ø¤Úº',
  'voice': 'Ø¢ÙˆØ§Ø² / ØµÛŒØºÛ',
  'war': 'Ø¬Ù†Ú¯',
  'water': 'Ù¾Ø§Ù†ÛŒ',
  'way': 'Ø±Ø§Ø³ØªÛ',
  'wealth': 'Ø¯ÙˆÙ„Øª',
  'week': 'ÛÙØªÛ',
  'west': 'Ù…ØºØ±Ø¨',
  'wife': 'Ø¨ÛŒÙˆÛŒ',
  'woman': 'Ø¹ÙˆØ±Øª',
  'world': 'Ø¯Ù†ÛŒØ§',
  'year': 'Ø³Ø§Ù„',
  // === Additional adjectives ===
  'alive': 'Ø²Ù†Ø¯Û',
  'alone': 'Ø§Ú©ÛŒÙ„Ø§',
  'ancient': 'Ù‚Ø¯ÛŒÙ…',
  'asleep': 'Ø³ÙˆÛŒØ§ ÛÙˆØ§',
  'aware': 'Ø¢Ú¯Ø§Û',
  'bad': 'Ø¨Ø±Ø§',
  'big': 'Ø¨Ú‘Ø§',
  'bitter': 'Ú©Ú‘ÙˆØ§',
  'blue': 'Ù†ÛŒÙ„Ø§',
  'broad': 'Ú†ÙˆÚ‘Ø§',
  'certain': 'ÛŒÙ‚ÛŒÙ†ÛŒ',
  'cheap': 'Ø³Ø³ØªØ§',
  'clean': 'ØµØ§Ù',
  'clear': 'ÙˆØ§Ø¶Ø­',
  'close': 'Ù‚Ø±ÛŒØ¨',
  'cold': 'Ù¹Ú¾Ù†ÚˆØ§',
  'common_1': 'Ø¹Ø§Ù…',
  'complex': 'Ù¾ÛŒÚ†ÛŒØ¯Û',
  'constant': 'Ù…Ø³ØªÙ‚Ù„',
  'curious': 'Ù…ØªØ¬Ø³Ø³',
  'dangerous': 'Ø®Ø·Ø±Ù†Ø§Ú©',
  'dead': 'Ù…Ø±Ø¯Û',
  'deep': 'Ú¯ÛØ±Ø§',
  'delicate': 'Ù†Ø§Ø²Ú©',
  'different': 'Ù…Ø®ØªÙ„Ù',
  'difficult': 'Ù…Ø´Ú©Ù„',
  'dirty': 'Ú¯Ù†Ø¯Ø§',
  'dry': 'Ø®Ø´Ú©',
  'due': 'ÙˆØ§Ø¬Ø¨',
  'dull': 'Ù¾Ú¾ÛŒÚ©Ø§',
  'eager': 'Ø¨Û’ Ú†ÛŒÙ†',
  'early': 'Ø¬Ù„Ø¯',
  'east': 'Ù…Ø´Ø±Ù‚',
  'eastern': 'Ù…Ø´Ø±Ù‚ÛŒ',
  'easy': 'Ø¢Ø³Ø§Ù†',
  'elastic': 'Ù„Ú†Ú©Ø¯Ø§Ø±',
  'electric': 'Ø¨Ø±Ù‚ÛŒ',
  'empty': 'Ø®Ø§Ù„ÛŒ',
  'entire': 'Ù¾ÙˆØ±Ø§',
  'equal': 'Ø¨Ø±Ø§Ø¨Ø±',
  'even': 'Ø¨Ø±Ø§Ø¨Ø±',
  'evil': 'Ø¨Ø±Ø§',
  'exact': 'Ø¹ÛŒÙ†',
  'extra': 'Ø§Ø¶Ø§ÙÛŒ',
  'extreme': 'Ø§Ù†ØªÛØ§Ø¦ÛŒ',
  'faint': 'ÛÙ„Ú©Ø§',
  'fair': 'Ù…Ù†ØµÙØ§Ù†Û',
  'false': 'Ø¬Ú¾ÙˆÙ¹Ø§',
  'famous': 'Ù…Ø´ÛÙˆØ±',
  'fast': 'ØªÛŒØ²',
  'fat': 'Ù…ÙˆÙ¹Ø§',
  'favorite': 'Ù¾Ø³Ù†Ø¯ÛŒØ¯Û',
  'female': 'Ù…ÙˆÙ†Ø«',
  'fierce': 'Ø®ÙˆÙÙ†Ø§Ú©',
  'final': 'Ø¢Ø®Ø±ÛŒ',
  'fine': 'Ù¹Ú¾ÛŒÚ©',
  'firm': 'Ù…Ø¶Ø¨ÙˆØ·',
  'flat': 'Ú†Ù¾Ù¹Ø§',
  'fleet': 'Ø¨Ø­Ø±ÛŒ Ø¨ÛŒÚ‘Ø§',
  'flexible': 'Ù„Ú†Ú©Ø¯Ø§Ø±',
  'following': 'Ù…Ù†Ø¯Ø±Ø¬Û Ø°ÛŒÙ„',
  'fond': 'Ø´ÙˆÙ‚ÛŒÙ†',
  'foreign': 'ØºÛŒØ± Ù…Ù„Ú©ÛŒ',
  'former': 'Ø³Ø§Ø¨Ù‚Û',
  'frank': 'ØµØ§Ù Ú¯Ùˆ',
  'free': 'Ø¢Ø²Ø§Ø¯',
  'fresh': 'ØªØ§Ø²Û',
  'friendly': 'Ø¯ÙˆØ³ØªØ§Ù†Û',
  'front': 'Ø³Ø§Ù…Ù†Û’',
  'full': 'Ø¨Ú¾Ø±Ø§',
  'general': 'Ø¹Ø§Ù…',
  'gentle': 'Ù†Ø±Ù…',
  'glad': 'Ø®ÙˆØ´',
  'golden': 'Ø³Ù†ÛØ±ÛŒ',
  'good': 'Ø§Ú†Ú¾Ø§',
  'gradual': 'Ø¨ØªØ¯Ø±ÛŒØ¬',
  'grand': 'Ø¹Ø¸ÛŒÙ…',
  'gray': 'Ø³Ø±Ù…Ø¦ÛŒ',
  'great': 'Ø¨Ú‘Ø§',
  'green': 'Ø³Ø¨Ø²',
  'half': 'Ø¢Ø¯Ú¾Ø§',
  'handsome': 'Ø®ÙˆØ¨ØµÙˆØ±Øª',
  'happy_1': 'Ø®ÙˆØ´',
  'hard': 'Ù…Ø´Ú©Ù„',
  'healthy': 'ØµØ­Øª Ù…Ù†Ø¯',
  'heavy': 'Ø¨Ú¾Ø§Ø±ÛŒ',
  'helpful': 'Ù…Ø¯Ø¯Ú¯Ø§Ø±',
  'high': 'Ø§ÙˆÙ†Ú†Ø§',
  'hollow': 'Ú©Ú¾ÙˆÚ©Ú¾Ù„Ø§',
  'holy': 'Ù…Ù‚Ø¯Ø³',
  'hot': 'Ú¯Ø±Ù…',
  'humble': 'Ø¹Ø§Ø¬Ø²',
  'hungry': 'Ø¨Ú¾ÙˆÚ©Ø§',
  'ideal': 'Ù…Ø«Ø§Ù„ÛŒ',
  'ill': 'Ø¨ÛŒÙ…Ø§Ø±',
  'important': 'Ø§ÛÙ…',
  'inner': 'Ø§Ù†Ø¯Ø±ÙˆÙ†ÛŒ',
  'innocent': 'Ø¨Û’ Ù‚ØµÙˆØ±',
  'instant': 'ÙÙˆØ±ÛŒ',
  'jealous': 'Ø­Ø³ÙˆØ¯',
  'joint': 'Ù…Ø´ØªØ±Ú©Û',
  'junior': 'Ø¬ÙˆÙ†ÛŒØ¦Ø±',
  'just': 'Ù…Ù†ØµÙØ§Ù†Û',
  'keen': 'Ù…Ø´ØªØ§Ù‚',
  'large': 'Ø¨Ú‘Ø§',
  'last': 'Ø¢Ø®Ø±ÛŒ',
  'late': 'Ø¯ÛŒØ±',
  'lawful': 'Ù‚Ø§Ù†ÙˆÙ†ÛŒ',
  'leading': 'Ø§ÛÙ…',
  'lean_1': 'Ø¯Ø¨Ù„Ø§',
  'least': 'Ú©Ù… Ø³Û’ Ú©Ù…',
  'left': 'Ø¨Ø§ÛŒØ§Úº',
  'legal': 'Ù‚Ø§Ù†ÙˆÙ†ÛŒ',
  'level': 'Ø¨Ø±Ø§Ø¨Ø±',
  'likely': 'Ù…Ù…Ú©Ù†Û',
  'live': 'Ø²Ù†Ø¯Û',
  'loose': 'ÚˆÚ¾ÛŒÙ„Ø§',
  'loud': 'Ø¨Ù„Ù†Ø¯',
  'lovely': 'Ù¾ÛŒØ§Ø±Ø§',
  'low': 'Ù†ÛŒÚ†Ø§',
  'lower': 'Ù†ÛŒÚ†Û’',
  'royal': 'Ø´Ø§ÛÛŒ',
  'safe': 'Ù…Ø­ÙÙˆØ¸',
  'smooth': 'ÛÙ…ÙˆØ§Ø±',
  'soft': 'Ù†Ø±Ù…',
  'solar': 'Ø´Ù…Ø³ÛŒ',
  'solid': 'Ù¹Ú¾ÙˆØ³',
  'sorry': 'Ø§ÙØ³ÙˆØ³',
  'sour': 'Ú©Ú¾Ù¹Ø§',
  'southern': 'Ø¬Ù†ÙˆØ¨ÛŒ',
  'spare': 'ÙØ§Ù„ØªÙˆ',
  'special': 'Ø®Ø§Øµ',
  'steady': 'Ù…Ø³ØªÙ‚Ù„',
  'steep': 'ÚˆÚ¾Ù„ÙˆØ§Ù†',
  'stern': 'Ø³Ø®Øª',
  'sticky': 'Ú†Ù¾Ú©Ù†Û’ ÙˆØ§Ù„Ø§',
  'still_1': 'Ø®Ø§Ù…ÙˆØ´',
  'straight': 'Ø³ÛŒØ¯Ú¾Ø§',
  'strange': 'Ø¹Ø¬ÛŒØ¨',
  'strict': 'Ø³Ø®Øª',
  'stubborn': 'Ø¶Ø¯ÛŒ',
  'sudden': 'Ø§Ú†Ø§Ù†Ú©',
  'sufficient': 'Ú©Ø§ÙÛŒ',
  'suitable': 'Ù…Ù†Ø§Ø³Ø¨',
  'sunny': 'Ø¯Ú¾ÙˆÙ¾',
  'superior': 'Ø¨Ø±ØªØ±',
  'sure': 'ÛŒÙ‚ÛŒÙ†',
  'surprised': 'Ø­ÛŒØ±Ø§Ù†',
  'sweet': 'Ù…ÛŒÙ¹Ú¾Ø§',
  'swift': 'ØªÛŒØ²',
  'tall': 'Ù„Ù…Ø¨Ø§',
  'tender': 'Ù†Ø±Ù…',
  'terrible': 'Ø®ÙˆÙÙ†Ø§Ú©',
  'thick': 'Ù…ÙˆÙ¹Ø§',
  'thin': 'Ù¾ØªÙ„Ø§',
  'thirsty': 'Ù¾ÛŒØ§Ø³Ø§',
  'tight': 'Ø³Ø®Øª',
  'tiny': 'Ù†Ù†Ú¾Ø§',
  'total': 'Ú©Ù„',
  'tough': 'Ù…Ø´Ú©Ù„',
  'tropical': 'Ø§Ø´Ù†Ø§Ø·Ø¯ÛŒ',
  'ugly': 'Ø¨Ø¯ØµÙˆØ±Øª',
  'unable': 'Ù†Ø§Ù‚Ø§Ø¨Ù„',
  'uncle': 'Ú†Ú†Ø§',
  'unfair': 'ØºÛŒØ± Ù…Ù†ØµÙØ§Ù†Û',
  'unfit': 'Ù†Ø§Ù‚Ø§Ø¨Ù„',
  'unhappy': 'Ù†Ø§Ø®ÙˆØ´',
  'unique': 'Ù…Ù†ÙØ±Ø¯',
  'united': 'Ù…ØªØ­Ø¯',
  'unknown': 'Ù†Ø§Ù…Ø¹Ù„ÙˆÙ…',
  'upper': 'Ø¨Ø§Ù„Ø§',
  'upright': 'Ø³ÛŒØ¯Ú¾Ø§',
  'upset': 'Ù¾Ø±ÛŒØ´Ø§Ù†',
  'urban': 'Ø´ÛØ±ÛŒ',
  'urgent': 'ÙÙˆØ±ÛŒ',
  'usual': 'Ù…Ø¹Ù…ÙˆÙ„',
  'vacant': 'Ø®Ø§Ù„ÛŒ',
  'vain': 'ÙØ¶ÙˆÙ„',
  'valid': 'Ø¯Ø±Ø³Øª',
  'valuable': 'Ù‚ÛŒÙ…ØªÛŒ',
  'vast': 'ÙˆØ³ÛŒØ¹',
  'vegetable': 'Ø³Ø¨Ø²ÛŒ',
  'vertical': 'Ø¹Ù…ÙˆØ¯ÛŒ',
  'violent': 'Ù¾Ø±ØªØ´Ø¯Ø¯',
  'visible': 'Ù…Ø±Ø¦ÛŒ',
  'vital': 'Ø¶Ø±ÙˆØ±ÛŒ',
  'vivid': 'Ø±ÙˆØ´Ù†',
  'warm': 'Ú¯Ø±Ù…',
  'weak': 'Ú©Ù…Ø²ÙˆØ±',
  'wealthy': 'Ø§Ù…ÛŒØ±',
  'weary': 'ØªÚ¾Ú©Ø§ ÛÙˆØ§',
  'western': 'Ù…ØºØ±Ø¨ÛŒ',
  'whole': 'Ù¾ÙˆØ±Ø§',
  'wicked': 'Ø´Ø±ÛŒØ±',
  'wide': 'ÙˆØ³ÛŒØ¹',
  'wild': 'Ø¬Ù†Ú¯Ù„ÛŒ',
  'willing': 'ØªÛŒØ§Ø±',
  'winning': 'Ø¬ÛŒØªÙ†Û’ ÙˆØ§Ù„Ø§',
  'winter': 'Ø³Ø±Ø¯ÛŒ',
  'wonderful': 'Ø´Ø§Ù†Ø¯Ø§Ø±',
  'worthy': 'Ù‚Ø§Ø¨Ù„',
  'wrong': 'ØºÙ„Ø·',
  'young': 'Ø¬ÙˆØ§Ù†',


  // === Additional sentence fragments ===
  'aaaa': 'ÛÙ… Ù‚Ø§ÙÛŒÛ',
  'abab': 'Ù…ØªØ¨Ø§Ø¯Ù„ Ù‚Ø§ÙÛŒÛ',
  'abcb': 'ØºÛŒØ± ÛÙ… Ù‚Ø§ÙÛŒÛ',
  'action or process': 'Ø¹Ù…Ù„ ÛŒØ§ Ø·Ø±ÛŒÙ‚Û',
  'collective noun': 'Ø§Ø³Ù… Ø¬Ù…Ø¹',
  'independent clause': 'Ø¢Ø²Ø§Ø¯ Ø´Ù‚',
  'capable of': 'Ù‚Ø§Ø¨Ù„',
  'unassigned': 'ØºÛŒØ± ØªÙÙˆÛŒØ¶ Ø´Ø¯Û',
  'aliens': 'Ø®Ø§Ø±Ø¬ÛŒ Ù…Ø®Ù„ÙˆÙ‚',
  'dragons': 'Ø§Ú˜Ø¯ÛÛ’',
  'einstein': 'Ø¢Ø¦Ù† Ø³Ù¹Ø§Ø¦Ù†',
  'the chef': 'Ø´ÛŒÙ',
  'the ancient manuscript': 'Ù‚Ø¯ÛŒÙ… Ù…Ø®Ø·ÙˆØ·Û',
  'dining': 'Ú©Ú¾Ø§Ù†Ø§ Ú©Ú¾Ø§Ù†Ø§',
  'awfully good': 'Ø¨ÛØª Ø§Ú†Ú¾Ø§',
  'fire-breathing': 'Ø¢Ú¯ Ø§Ú¯Ù„Ù†Û’ ÙˆØ§Ù„Ø§',
  'breathed': 'Ø³Ø§Ù†Ø³ Ù„ÛŒØ§',
  'was': 'ØªÚ¾Ø§',
  'have begun': 'Ø´Ø±ÙˆØ¹ Ú©Ø± Ú†Ú©Û’ ÛÛŒÚº',
  'have eaten': 'Ú©Ú¾Ø§ Ú†Ú©Û’ ÛÛŒÚº',
  'have travelled': 'Ø³ÙØ± Ú©Ø± Ú†Ú©Û’ ÛÛŒÚº',
  'have written': 'Ù„Ú©Ú¾ Ú†Ú©Û’ ÛÛŒÚº',
  'he finished the report': 'Ø§Ø³ Ù†Û’ Ø±Ù¾ÙˆØ±Ù¹ Ø®ØªÙ… Ú©ÛŒ',
  'he finishes the report': 'ÙˆÛ Ø±Ù¾ÙˆØ±Ù¹ Ø®ØªÙ… Ú©Ø±ØªØ§ ÛÛ’',
  'he had finished the report': 'Ø§Ø³ Ù†Û’ Ø±Ù¾ÙˆØ±Ù¹ Ø®ØªÙ… Ú©Ø± Ù„ÛŒ ØªÚ¾ÛŒ',
  'he has finished the report': 'Ø§Ø³ Ù†Û’ Ø±Ù¾ÙˆØ±Ù¹ Ø®ØªÙ… Ú©Ø± Ù„ÛŒ ÛÛ’',
  'he is finishing the report': 'ÙˆÛ Ø±Ù¾ÙˆØ±Ù¹ Ø®ØªÙ… Ú©Ø± Ø±ÛØ§ ÛÛ’',
  'he was finishing the report': 'ÙˆÛ Ø±Ù¾ÙˆØ±Ù¹ Ø®ØªÙ… Ú©Ø± Ø±ÛØ§ ØªÚ¾Ø§',
  'he will finish the report': 'ÙˆÛ Ø±Ù¾ÙˆØ±Ù¹ Ø®ØªÙ… Ú©Ø±Û’ Ú¯Ø§',
  'we decided': 'ÛÙ… Ù†Û’ ÙÛŒØµÙ„Û Ú©ÛŒØ§',
  'were beginning': 'Ø´Ø±ÙˆØ¹ Ú©Ø± Ø±ÛÛ’ ØªÚ¾Û’',
  'were eating': 'Ú©Ú¾Ø§ Ø±ÛÛ’ ØªÚ¾Û’',
  'were travelling': 'Ø³ÙØ± Ú©Ø± Ø±ÛÛ’ ØªÚ¾Û’',
  'were writing': 'Ù„Ú©Ú¾ Ø±ÛÛ’ ØªÚ¾Û’',
  'revealed secrets': 'Ø±Ø§Ø² Ø§ÙØ´Ø§ Ú©ÛŒÛ’',
  'although it was damaged': 'Ø§Ú¯Ø±Ú†Û ÛŒÛ Ø®Ø±Ø§Ø¨ ØªÚ¾Ø§',
  'at the ceremony': 'ØªÙ‚Ø±ÛŒØ¨ Ù…ÛŒÚº',
  'because it was raining heavily': 'Ú©ÛŒÙˆÙ†Ú©Û ØªÛŒØ² Ø¨Ø§Ø±Ø´ ÛÙˆ Ø±ÛÛŒ ØªÚ¾ÛŒ',
  'before the audience': 'Ø³Ø§Ù…Ø¹ÛŒÙ† Ú©Û’ Ø³Ø§Ù…Ù†Û’',
  'behind the props': 'Ù¾Ø±Ù¾Ø³ Ú©Û’ Ù¾ÛŒÚ†Ú¾Û’',
  'in the morning': 'ØµØ¨Ø­ Ú©Û’ ÙˆÙ‚Øª',
  'inside the house': 'Ú¯Ú¾Ø± Ú©Û’ Ø§Ù†Ø¯Ø±',
  'over the wall': 'Ø¯ÛŒÙˆØ§Ø± Ú©Û’ Ø§ÙˆÙ¾Ø±',
  'under the floorboards': 'ÙØ±Ø´ Ø¨ÙˆØ±ÚˆØ² Ú©Û’ Ù†ÛŒÚ†Û’',
  'under the tree': 'Ø¯Ø±Ø®Øª Ú©Û’ Ù†ÛŒÚ†Û’',
  'upstairs': 'Ø§ÙˆÙ¾Ø± Ú©ÛŒ Ù…Ù†Ø²Ù„',
  'that we should stay': 'Ú©Û ÛÙ…ÛŒÚº Ø±ÛÙ†Ø§ Ú†Ø§ÛÛŒÛ’',
  'the book that i read was fascinating': 'ÙˆÛ Ú©ØªØ§Ø¨ Ø¬Ùˆ Ù…ÛŒÚº Ù†Û’ Ù¾Ú‘Ú¾ÛŒ Ø¯Ù„Ú†Ø³Ù¾ ØªÚ¾ÛŒ',
  'they plan to travel to japan next year': 'ÙˆÛ Ø§Ú¯Ù„Û’ Ø³Ø§Ù„ Ø¬Ø§Ù¾Ø§Ù† Ø¬Ø§Ù†Û’ Ú©Ø§ Ø§Ø±Ø§Ø¯Û Ø±Ú©Ú¾ØªÛ’ ÛÛŒÚº',
  'to act impulsively': 'Ø¬Ù„Ø¯ Ø¨Ø§Ø²ÛŒ Ù…ÛŒÚº Ú©Ø§Ù… Ú©Ø±Ù†Ø§',
  'to avoid talking about what is important': 'Ø§ÛÙ… Ø¨Ø§ØªÙˆÚº Ø³Û’ Ú¯Ø±ÛŒØ² Ú©Ø±Ù†Ø§',
  'to go on a long hike': 'Ù„Ù…Ø¨ÛŒ Ø³ÛŒØ± Ù¾Ø± Ø¬Ø§Ù†Ø§',
  'which was discovered': 'Ø¬Ùˆ Ø¯Ø±ÛŒØ§ÙØª ÛÙˆØ§',
  'whoever finishes first': 'Ø¬Ùˆ Ø¨Ú¾ÛŒ Ù¾ÛÙ„Û’ Ø®ØªÙ… Ú©Ø±Û’',
  'will receive the grand prize': 'Ø¹Ø¸ÛŒÙ… Ø§Ù†Ø¹Ø§Ù… Ù…Ù„Û’ Ú¯Ø§',
  'change y to i before adding the suffix': 'Ù„Ø§Ø­Ù‚Û Ù„Ú¯Ø§Ù†Û’ Ø³Û’ Ù¾ÛÙ„Û’ Y Ú©Ùˆ I Ù…ÛŒÚº Ø¨Ø¯Ù„ÛŒÚº',
  'double the y': 'Y Ú©Ùˆ Ø¯ÛØ±Ø§Ø¦ÛŒÚº',
  'keep the y and add the suffix': 'Y Ø±Ú©Ú¾ÛŒÚº Ø§ÙˆØ± Ù„Ø§Ø­Ù‚Û Ù„Ú¯Ø§Ø¦ÛŒÚº',
  'gi': 'Ø¬ÛŒ',

  // === More missing vocabulary ===
  'act': 'Ø¹Ù…Ù„ Ú©Ø±Ù†Ø§',
  'action': 'Ø¹Ù…Ù„',
  'appearance': 'Ø¸Ø§ÛØ±ÛŒ Ø´Ú©Ù„',
  'care': 'Ø¯ÛŒÚ©Ú¾ Ø¨Ú¾Ø§Ù„',
  'connotation': 'Ù…ÙÛÙˆÙ…',
  'create': 'ØªØ®Ù„ÛŒÙ‚ Ú©Ø±Ù†Ø§',
  'definite': 'ÛŒÙ‚ÛŒÙ†ÛŒ',
  'fill': 'Ø¨Ú¾Ø±Ù†Ø§',
  'idiom': 'Ù…Ø­Ø§ÙˆØ±Û',
  'incorrect': 'ØºÙ„Ø·',
  'indefinite': 'ØºÛŒØ± ÛŒÙ‚ÛŒÙ†ÛŒ',
  'magic': 'Ø¬Ø§Ø¯Ùˆ',
  'other': 'Ø¯ÙˆØ³Ø±Ø§',
  'personality': 'Ø´Ø®ØµÛŒØª',
  'rely': 'Ø§Ù†Ø­ØµØ§Ø± Ú©Ø±Ù†Ø§',
  'silent': 'Ø®Ø§Ù…ÙˆØ´',
  'size': 'Ø³Ø§Ø¦Ø²',
  'status': 'Ø­ÛŒØ«ÛŒØª',
  'text': 'Ù…ØªÙ†',
  'transition': 'Ø§Ù†ØªÙ‚Ø§Ù„',
  '1st person': 'Ø§ÙˆÙ„ Ø´Ø®Øµ',
  '3rd person': 'ØºØ§Ø¦Ø¨ Ø´Ø®Øµ',
  'active voice': 'ÙØ¹Ù„ Ù…Ø¹Ù„ÙˆÙ…',
  'analyze input': 'Ø§Ù† Ù¾Ù¹ Ú©Ø§ ØªØ¬Ø²ÛŒÛ Ú©Ø±ÛŒÚº',
  'conj': 'Ø­Ø±Ù Ø¹Ø·Ù',
  'keep analyzing': 'ØªØ¬Ø²ÛŒÛ Ø¬Ø§Ø±ÛŒ Ø±Ú©Ú¾ÛŒÚº',
  'mcq': 'Ú©Ø«ÛŒØ± Ø§Ù†ØªØ®Ø§Ø¨ÛŒ Ø³ÙˆØ§Ù„',
  'switch to passive voice': 'Ù…Ø¬Ø¨ÙˆÙ„ ØµÛŒØºÛ’ Ù…ÛŒÚº ØªØ¨Ø¯ÛŒÙ„ Ú©Ø±ÛŒÚº',
  'switch to dark mode': 'ÚˆØ§Ø±Ú© Ù…ÙˆÚˆ Ù…ÛŒÚº ØªØ¨Ø¯ÛŒÙ„ Ú©Ø±ÛŒÚº',
  'dream house': 'Ø®ÙˆØ§Ø¨ÙˆÚº Ú©Ø§ Ú¯Ú¾Ø±',
  'exam result': 'Ø§Ù…ØªØ­Ø§Ù†ÛŒ Ù†ØªÛŒØ¬Û',
  'high-risk project': 'Ø®Ø·Ø±Ù†Ø§Ú© Ù…Ù†ØµÙˆØ¨Û',
  'liquid water': 'Ù¾Ø§Ù†ÛŒ',
  'structure intact': 'Ø³Ø§Ø®Øª Ø¨Ø±Ù‚Ø±Ø§Ø±',
  'well-known expert': 'Ù…Ø´ÛÙˆØ± Ù…Ø§ÛØ±',
  'not quite right': 'Ø¨Ø§Ù„Ú©Ù„ Ø¯Ø±Ø³Øª Ù†ÛÛŒÚº',
  'skip to next': 'Ø§Ú¯Ù„Û’ Ù¾Ø± Ø¬Ø§Ø¦ÛŒÚº',
  'try another': 'Ø¯ÙˆØ³Ø±Ø§ Ø¢Ø²Ù…Ø§Ø¦ÛŒÚº',
  'do you like tea': 'Ú©ÛŒØ§ Ø¢Ù¾ Ú©Ùˆ Ú†Ø§Ø¦Û’ Ù¾Ø³Ù†Ø¯ ÛÛ’',
  'he went to sleep': 'ÙˆÛ Ø³Ùˆ Ú¯ÛŒØ§',
  'i love to sleep': 'Ù…Ø¬Ú¾Û’ Ø³ÙˆÙ†Ø§ Ù¾Ø³Ù†Ø¯ ÛÛ’',
  'the sleeping baby is peaceful': 'Ø³ÙˆØªØ§ ÛÙˆØ§ Ø¨Ú†Û Ù¾Ø± Ø³Ú©ÙˆÙ† ÛÛ’',
  'c1': 'Ø³ÛŒ Ø§ÛŒÚ©',
  'c2': 'Ø³ÛŒ Ø¯Ùˆ',
  'info': 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª',
};

export { WORD_MEANINGS };

interface WordMeaningProps {
  word: string;
}

/**
 * Displays the Roman Urdu meaning of an English word in a small,
 * italic, easy-to-read style. Uses Georgia/serif font for
 * excellent readability of Roman Urdu text.
 * 
 * Returns null if the word is not in the dictionary.
 */
export default function WordMeaning({ word }: WordMeaningProps) {
  if (!word || typeof word !== 'string') return null;
  
  const cleanWord = word.toLowerCase().trim().replace(/[.,!?;:'"()]/g, '');
  const meaning = WORD_MEANINGS[cleanWord];
  if (!meaning) return null;
  
  return (
    <span
      className="font-urdu text-[13px] leading-relaxed text-slate-500 dark:text-slate-400"
      style={{
        letterSpacing: '0.01em',
        fontWeight: 500,
      }}
    >
      ({meaning})
    </span>
  );
}

