import { lazy } from 'react';


// Lazy load all lab components
const labComponents: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {
  // Class 8 Computer
  LabDataComm: lazy(() => import('../components/labs/class8/computer/LabDataComm')),
  LabNetworkDevices: lazy(() => import('../components/labs/class8/computer/LabNetworkDevices')),
  LabCricketSpreadsheet: lazy(() => import('../components/labs/class8/computer/LabCricketSpreadsheet')),
  LabDataWorksheets: lazy(() => import('../components/labs/class8/computer/LabDataWorksheets')),
  LabPseudocodeInterpreter: lazy(() => import('../components/labs/class8/computer/LabPseudocodeInterpreter')),
  LabDiceGameAlgorithm: lazy(() => import('../components/labs/class8/computer/LabDiceGameAlgorithm')),
  LabScratchMaze: lazy(() => import('../components/labs/class8/computer/LabScratchMaze')),
  LabCyberScout: lazy(() => import('../components/labs/class8/computer/LabCyberScout')),
  LabAntivirus: lazy(() => import('../components/labs/class8/computer/LabAntivirus')),
  LabBusinessPlan: lazy(() => import('../components/labs/class8/computer/LabBusinessPlan')),
  LabDigitalMarketing: lazy(() => import('../components/labs/class8/computer/LabDigitalMarketing')),

  // Class 7 Computer
  LabC7Hardware: lazy(() => import('../components/labs/class7/computer/LabC7Hardware')),
  LabC7EmergingTech: lazy(() => import('../components/labs/class7/computer/LabC7EmergingTech')),
  LabC7Generations: lazy(() => import('../components/labs/class7/computer/LabC7Generations')),
  LabC7NetworkDiagram: lazy(() => import('../components/labs/class7/computer/LabC7NetworkDiagram')),
  LabC7UrduTyping: lazy(() => import('../components/labs/class7/computer/LabC7UrduTyping')),
  LabC7LetterFormat: lazy(() => import('../components/labs/class7/computer/LabC7LetterFormat')),
  LabC7CVCreation: lazy(() => import('../components/labs/class7/computer/LabC7CVCreation')),
  LabC7IllustratedStory: lazy(() => import('../components/labs/class7/computer/LabC7IllustratedStory')),
  LabC7PowerPointGeometry: lazy(() => import('../components/labs/class7/computer/LabC7PowerPointGeometry')),
  LabC7WondersResearch: lazy(() => import('../components/labs/class7/computer/LabC7WondersResearch')),
  LabC7ConditionalLogic: lazy(() => import('../components/labs/class7/computer/LabC7ConditionalLogic')),
  LabC7GradingFlowchart: lazy(() => import('../components/labs/class7/computer/LabC7GradingFlowchart')),
  LabC7ReverseFlowchart: lazy(() => import('../components/labs/class7/computer/LabC7ReverseFlowchart')),
  LabC7SpriteManipulation: lazy(() => import('../components/labs/class7/computer/LabC7SpriteManipulation')),
  LabC7LoopAdjustments: lazy(() => import('../components/labs/class7/computer/LabC7LoopAdjustments')),
  LabC7BouncingBall: lazy(() => import('../components/labs/class7/computer/LabC7BouncingBall')),
  LabC7AnimatedDialogue: lazy(() => import('../components/labs/class7/computer/LabC7AnimatedDialogue')),
  LabC7InteractivePiano: lazy(() => import('../components/labs/class7/computer/LabC7InteractivePiano')),
  LabC7Cybercrime: lazy(() => import('../components/labs/class7/computer/LabC7Cybercrime')),
  LabC7DevianceDiscussion: lazy(() => import('../components/labs/class7/computer/LabC7DevianceDiscussion')),
  LabC7EthicsChart: lazy(() => import('../components/labs/class7/computer/LabC7EthicsChart')),
  LabC7DesignPrototype: lazy(() => import('../components/labs/class7/computer/LabC7DesignPrototype')),
  LabC7MothersDay: lazy(() => import('../components/labs/class7/computer/LabC7MothersDay')),

  // Class 6 Computer
  LabC6HealthCampaign: lazy(() => import('../components/labs/class6/computer/LabC6HealthCampaign')),
  LabC6HardwareCharts: lazy(() => import('../components/labs/class6/computer/LabC6HardwareCharts')),
  LabC6LabRules: lazy(() => import('../components/labs/class6/computer/LabC6LabRules')),
  LabC6GroupPresentations: lazy(() => import('../components/labs/class6/computer/LabC6GroupPresentations')),
  LabC6SystemSoftware: lazy(() => import('../components/labs/class6/computer/LabC6SystemSoftware')),
  LabC6FileManagement1: lazy(() => import('../components/labs/class6/computer/LabC6FileManagement1')),
  LabC6FileManagement2: lazy(() => import('../components/labs/class6/computer/LabC6FileManagement2')),
  LabC6DietExercise: lazy(() => import('../components/labs/class6/computer/LabC6DietExercise')),
  LabC6Paint3DFace: lazy(() => import('../components/labs/class6/computer/LabC6Paint3DFace')),
  LabC6SolarSystem: lazy(() => import('../components/labs/class6/computer/LabC6SolarSystem')),
  LabC6ProblemDecomposition: lazy(() => import('../components/labs/class6/computer/LabC6ProblemDecomposition')),
  LabC6RoadSafetyProcess: lazy(() => import('../components/labs/class6/computer/LabC6RoadSafetyProcess')),
  LabC6CoordinateExp: lazy(() => import('../components/labs/class6/computer/LabC6CoordinateExp')),
  LabC6CostumeChange: lazy(() => import('../components/labs/class6/computer/LabC6CostumeChange')),
  LabC6MovementTracking: lazy(() => import('../components/labs/class6/computer/LabC6MovementTracking')),
  LabC6LoopAdjustments: lazy(() => import('../components/labs/class6/computer/LabC6LoopAdjustments')),
  LabC6EthicsChart: lazy(() => import('../components/labs/class6/computer/LabC6EthicsChart')),
  LabC6CyberScout: lazy(() => import('../components/labs/class6/computer/LabC6CyberScout')),
  LabC6PosterCompetition: lazy(() => import('../components/labs/class6/computer/LabC6PosterCompetition')),
  LabC6HobbyMonetization: lazy(() => import('../components/labs/class6/computer/LabC6HobbyMonetization')),

  // Class 8 Science
  LabS8GreenhouseEffect: lazy(() => import('../components/labs/class8/science/LabS8GreenhouseEffect')),
  LabS8StimulusResponse: lazy(() => import('../components/labs/class8/science/LabS8StimulusResponse')),
  LabS8KneeJerk: lazy(() => import('../components/labs/class8/science/LabS8KneeJerk')),
  LabS8ReflexTime: lazy(() => import('../components/labs/class8/science/LabS8ReflexTime')),
  LabS8DNAExtraction: lazy(() => import('../components/labs/class8/science/LabS8DNAExtraction')),
  LabS8HumanVariations: lazy(() => import('../components/labs/class8/science/LabS8HumanVariations')),
  LabS8CrossingOver: lazy(() => import('../components/labs/class8/science/LabS8CrossingOver')),
  LabS8MakingYogurt: lazy(() => import('../components/labs/class8/science/LabS8MakingYogurt')),
  LabS8PeriodicTable: lazy(() => import('../components/labs/class8/science/LabS8PeriodicTable')),
  LabS8ElectronicConfig: lazy(() => import('../components/labs/class8/science/LabS8ElectronicConfig')),
  LabS8Malleability: lazy(() => import('../components/labs/class8/science/LabS8Malleability')),
  LabS8Flexibility: lazy(() => import('../components/labs/class8/science/LabS8Flexibility')),
  LabS8Density: lazy(() => import('../components/labs/class8/science/LabS8Density')),
  LabS8ThermalConductivity: lazy(() => import('../components/labs/class8/science/LabS8ThermalConductivity')),
  LabS8Sonorous: lazy(() => import('../components/labs/class8/science/LabS8Sonorous')),
  LabS8ChemicalReactionSigns: lazy(() => import('../components/labs/class8/science/LabS8ChemicalReactionSigns')),
  LabS8ConservationMass: lazy(() => import('../components/labs/class8/science/LabS8ConservationMass')),
  LabS8Endothermic: lazy(() => import('../components/labs/class8/science/LabS8Endothermic')),
  LabS8Exothermic: lazy(() => import('../components/labs/class8/science/LabS8Exothermic')),
  LabS8AcidLitmus: lazy(() => import('../components/labs/class8/science/LabS8AcidLitmus')),
  LabS8AlkaliLitmus: lazy(() => import('../components/labs/class8/science/LabS8AlkaliLitmus')),
  LabS8Neutralization: lazy(() => import('../components/labs/class8/science/LabS8Neutralization')),
  LabS8DeterminingPH: lazy(() => import('../components/labs/class8/science/LabS8DeterminingPH')),
  LabS8NailPressure: lazy(() => import('../components/labs/class8/science/LabS8NailPressure')),
  LabS8HydraulicElevator: lazy(() => import('../components/labs/class8/science/LabS8HydraulicElevator')),
  LabS8WaterRocket: lazy(() => import('../components/labs/class8/science/LabS8WaterRocket')),
  LabS8LaserMaze: lazy(() => import('../components/labs/class8/science/LabS8LaserMaze')),
  LabS8Periscope: lazy(() => import('../components/labs/class8/science/LabS8Periscope')),
  LabS8RefractionPencil: lazy(() => import('../components/labs/class8/science/LabS8RefractionPencil')),
  LabS8ConcaveMirror: lazy(() => import('../components/labs/class8/science/LabS8ConcaveMirror')),
  LabS8ConvexMirror: lazy(() => import('../components/labs/class8/science/LabS8ConvexMirror')),
  LabS8Electromagnet: lazy(() => import('../components/labs/class8/science/LabS8Electromagnet')),
  LabS8Toothpaste: lazy(() => import('../components/labs/class8/science/LabS8Toothpaste')),
  LabS8SoapMaking: lazy(() => import('../components/labs/class8/science/LabS8SoapMaking')),
  LabS8MilkPlastic: lazy(() => import('../components/labs/class8/science/LabS8MilkPlastic')),
  LabS8Detergent: lazy(() => import('../components/labs/class8/science/LabS8Detergent')),
  LabS8SolarCooker: lazy(() => import('../components/labs/class8/science/LabS8SolarCooker')),
  LabS8WindTurbine: lazy(() => import('../components/labs/class8/science/LabS8WindTurbine')),
  LabS8ChemicalCar: lazy(() => import('../components/labs/class8/science/LabS8ChemicalCar')),
  LabS8Windsock: lazy(() => import('../components/labs/class8/science/LabS8Windsock')),
  LabS8SkyMap: lazy(() => import('../components/labs/class8/science/LabS8SkyMap')),

  // Class 7 Science
  LabS7XylemTransport: lazy(() => import('../components/labs/class7/science/LabS7XylemTransport')),
  LabS7TranspirationObservation: lazy(() => import('../components/labs/class7/science/LabS7TranspirationObservation')),
  LabS7TranspirationLeaves: lazy(() => import('../components/labs/class7/science/LabS7TranspirationLeaves')),
  LabS7MineralsPlantGrowth: lazy(() => import('../components/labs/class7/science/LabS7MineralsPlantGrowth')),
  LabS7Unit1Projects: lazy(() => import('../components/labs/class7/science/LabS7Unit1Projects')),
  LabS7MeasuringLungCapacity: lazy(() => import('../components/labs/class7/science/LabS7MeasuringLungCapacity')),
  LabS7PulseRateExercise: lazy(() => import('../components/labs/class7/science/LabS7PulseRateExercise')),
  LabS7Unit2Projects: lazy(() => import('../components/labs/class7/science/LabS7Unit2Projects')),
  LabS7ImmuneSystemRolePlay: lazy(() => import('../components/labs/class7/science/LabS7ImmuneSystemRolePlay')),
  LabS7Unit3Projects: lazy(() => import('../components/labs/class7/science/LabS7Unit3Projects')),
  LabS7ChemicalChange: lazy(() => import('../components/labs/class7/science/LabS7ChemicalChange')),
  LabS7ThermalConduction: lazy(() => import('../components/labs/class7/science/LabS7ThermalConduction')),
  LabS7Unit4Projects: lazy(() => import('../components/labs/class7/science/LabS7Unit4Projects')),
  LabS7CalculatingSubatomicParticles: lazy(() => import('../components/labs/class7/science/LabS7CalculatingSubatomicParticles')),
  LabS7AtomModel: lazy(() => import('../components/labs/class7/science/LabS7AtomModel')),
  LabS7LithiumBonding: lazy(() => import('../components/labs/class7/science/LabS7LithiumBonding')),
  LabS7DiluteConcentratedSolutions: lazy(() => import('../components/labs/class7/science/LabS7DiluteConcentratedSolutions')),
  LabS7CleaningCoins: lazy(() => import('../components/labs/class7/science/LabS7CleaningCoins')),
  LabS7MakingRockCandy: lazy(() => import('../components/labs/class7/science/LabS7MakingRockCandy')),
  LabS7OilPollutants: lazy(() => import('../components/labs/class7/science/LabS7OilPollutants')),
  LabS7BalloonRocket: lazy(() => import('../components/labs/class7/science/LabS7BalloonRocket')),
  LabS7Unit8Projects: lazy(() => import('../components/labs/class7/science/LabS7Unit8Projects')),
  LabS7VibratingLengthPitch: lazy(() => import('../components/labs/class7/science/LabS7VibratingLengthPitch')),
  LabS7Unit9Projects: lazy(() => import('../components/labs/class7/science/LabS7Unit9Projects')),
  LabS7Unit10Projects: lazy(() => import('../components/labs/class7/science/LabS7Unit10Projects')),
  LabS7DripIrrigation: lazy(() => import('../components/labs/class7/science/LabS7DripIrrigation')),
  LabS7MakeStethoscope: lazy(() => import('../components/labs/class7/science/LabS7MakeStethoscope')),
  LabS7HandSanitizer: lazy(() => import('../components/labs/class7/science/LabS7HandSanitizer')),
  LabS7Unit11Projects: lazy(() => import('../components/labs/class7/science/LabS7Unit11Projects')),
  LabS7EarthSeasons: lazy(() => import('../components/labs/class7/science/LabS7EarthSeasons')),

  // Class 10 Physics
  LabP10ThermionicEmission: lazy(() => import('../components/labs/class10/physics/LabP10ThermionicEmission')),
  LabP10LogicGates: lazy(() => import('../components/labs/class10/physics/LabP10LogicGates')),
  LabP10RadioTransmission: lazy(() => import('../components/labs/class10/physics/LabP10RadioTransmission')),
  LabP10OpticalFibers: lazy(() => import('../components/labs/class10/physics/LabP10OpticalFibers')),
  LabP10Radioactivity: lazy(() => import('../components/labs/class10/physics/LabP10Radioactivity')),
  LabP10HalfLife: lazy(() => import('../components/labs/class10/physics/LabP10HalfLife')),
  LabP10ElectrostaticCharges: lazy(() => import('../components/labs/class10/physics/LabP10ElectrostaticCharges')),
  LabP10Electroscope: lazy(() => import('../components/labs/class10/physics/LabP10Electroscope')),
  LabP10OhmLaw: lazy(() => import('../components/labs/class10/physics/LabP10OhmLaw')),
  LabP10SeriesCircuit: lazy(() => import('../components/labs/class10/physics/LabP10SeriesCircuit')),
  LabP10ParallelCircuit: lazy(() => import('../components/labs/class10/physics/LabP10ParallelCircuit')),
  LabP10MagneticField: lazy(() => import('../components/labs/class10/physics/LabP10MagneticField')),
  LabP10ElectromagnetDC: lazy(() => import('../components/labs/class10/physics/LabP10ElectromagnetDC')),
  LabP10FaradayLaw: lazy(() => import('../components/labs/class10/physics/LabP10FaradayLaw')),
  LabP10WaveMotion: lazy(() => import('../components/labs/class10/physics/LabP10WaveMotion')),
  LabP10RippleTank: lazy(() => import('../components/labs/class10/physics/LabP10RippleTank')),
  LabP10RefractionIllusion: lazy(() => import('../components/labs/class10/physics/LabP10RefractionIllusion')),
  LabP10SoundProduction: lazy(() => import('../components/labs/class10/physics/LabP10SoundProduction')),
  LabP10SoundMedium: lazy(() => import('../components/labs/class10/physics/LabP10SoundMedium')),
  LabP10StringTelephone: lazy(() => import('../components/labs/class10/physics/LabP10StringTelephone')),
  LabP10SpeakerProject: lazy(() => import('../components/labs/class10/physics/LabP10SpeakerProject')),
  LabP10PlaneMirror: lazy(() => import('../components/labs/class10/physics/LabP10PlaneMirror')),
  LabP10RefractionBlocks: lazy(() => import('../components/labs/class10/physics/LabP10RefractionBlocks')),
  LabP10TotalInternalReflection: lazy(() => import('../components/labs/class10/physics/LabP10TotalInternalReflection')),
  LabP10CarbonFootprint: lazy(() => import('../components/labs/class10/physics/LabP10CarbonFootprint')),
  LabP10SpecificHeatMixture: lazy(() => import('../components/labs/class10/physics/LabP10SpecificHeatMixture')),
  LabP10SpecificHeatElectrical: lazy(() => import('../components/labs/class10/physics/LabP10SpecificHeatElectrical')),
  LabP10ThermalConduction: lazy(() => import('../components/labs/class10/physics/LabP10ThermalConduction')),
  LabP10ConvectionCurrents: lazy(() => import('../components/labs/class10/physics/LabP10ConvectionCurrents')),
  LabP10InsulatingMaterials: lazy(() => import('../components/labs/class10/physics/LabP10InsulatingMaterials')),
  LabP10AbsorbersReflectors: lazy(() => import('../components/labs/class10/physics/LabP10AbsorbersReflectors')),
  LabP10LeslieCube: lazy(() => import('../components/labs/class10/physics/LabP10LeslieCube')),
  LabP10ThermalExpansionSolid: lazy(() => import('../components/labs/class10/physics/LabP10ThermalExpansionSolid')),
  LabP10ExpansionLiquids: lazy(() => import('../components/labs/class10/physics/LabP10ExpansionLiquids')),
  LabP10GasPressureBalloon: lazy(() => import('../components/labs/class10/physics/LabP10GasPressureBalloon')),
  LabP10LatentHeat: lazy(() => import('../components/labs/class10/physics/LabP10LatentHeat')),

  // Class 10 Physics Derivations
  LabP10DerivationSpecificHeatMixtures: lazy(() => import('../components/labs/class10/physics/LabP10DerivationSpecificHeatMixtures')),
  LabP10DerivationSpecificHeatElectrical: lazy(() => import('../components/labs/class10/physics/LabP10DerivationSpecificHeatElectrical')),
  LabP10DerivationLinearExpansion: lazy(() => import('../components/labs/class10/physics/LabP10DerivationLinearExpansion')),
  LabP10DerivationVolumetricExpansion: lazy(() => import('../components/labs/class10/physics/LabP10DerivationVolumetricExpansion')),
  LabP10DerivationExpansionLiquids: lazy(() => import('../components/labs/class10/physics/LabP10DerivationExpansionLiquids')),
  LabP10DerivationWaveEquation: lazy(() => import('../components/labs/class10/physics/LabP10DerivationWaveEquation')),
  LabP10DerivationEcho: lazy(() => import('../components/labs/class10/physics/LabP10DerivationEcho')),
  LabP10DerivationCriticalAngle: lazy(() => import('../components/labs/class10/physics/LabP10DerivationCriticalAngle')),
  LabP10DerivationMagnification: lazy(() => import('../components/labs/class10/physics/LabP10DerivationMagnification')),
  LabP10DerivationResistivity: lazy(() => import('../components/labs/class10/physics/LabP10DerivationResistivity')),
  LabP10DerivationTempCoefficient: lazy(() => import('../components/labs/class10/physics/LabP10DerivationTempCoefficient')),
  LabP10DerivationPotentialDivider: lazy(() => import('../components/labs/class10/physics/LabP10DerivationPotentialDivider')),
  LabP10DerivationSeriesResistance: lazy(() => import('../components/labs/class10/physics/LabP10DerivationSeriesResistance')),
  LabP10DerivationParallelResistance: lazy(() => import('../components/labs/class10/physics/LabP10DerivationParallelResistance')),
  LabP10DerivationElectricalEnergy: lazy(() => import('../components/labs/class10/physics/LabP10DerivationElectricalEnergy')),
  LabP10DerivationElectricPower: lazy(() => import('../components/labs/class10/physics/LabP10DerivationElectricPower')),
  LabP10DerivationTransistorGain: lazy(() => import('../components/labs/class10/physics/LabP10DerivationTransistorGain')),
  LabP10DerivationTransformer: lazy(() => import('../components/labs/class10/physics/LabP10DerivationTransformer')),
  LabP10DerivationPhotonEnergy: lazy(() => import('../components/labs/class10/physics/LabP10DerivationPhotonEnergy')),
  LabP10DerivationRadioactiveDecay: lazy(() => import('../components/labs/class10/physics/LabP10DerivationRadioactiveDecay')),

  // Class 10 Chemistry
  LabC10DiluteSolution: lazy(() => import('../components/labs/class10/chemistry/LabC10DiluteSolution')),
  LabC10StandardizationTitration: lazy(() => import('../components/labs/class10/chemistry/LabC10StandardizationTitration')),
  LabC10SaltTitration: lazy(() => import('../components/labs/class10/chemistry/LabC10SaltTitration')),
  LabC10SaltExcessMetal: lazy(() => import('../components/labs/class10/chemistry/LabC10SaltExcessMetal')),
  LabC10SaltExcessBase: lazy(() => import('../components/labs/class10/chemistry/LabC10SaltExcessBase')),
  LabC10SaltExcessCarbonate: lazy(() => import('../components/labs/class10/chemistry/LabC10SaltExcessCarbonate')),
  LabC10MetalReactivity: lazy(() => import('../components/labs/class10/chemistry/LabC10MetalReactivity')),
  LabC10SaturatedUnsaturated: lazy(() => import('../components/labs/class10/chemistry/LabC10SaturatedUnsaturated')),
  LabC10AceticAcidMetal: lazy(() => import('../components/labs/class10/chemistry/LabC10AceticAcidMetal')),
  LabC10AceticAcidCarbonate: lazy(() => import('../components/labs/class10/chemistry/LabC10AceticAcidCarbonate')),
  LabC10DownsCell: lazy(() => import('../components/labs/class10/chemistry/LabC10DownsCell')),
  LabC10MoltenLeadChloride: lazy(() => import('../components/labs/class10/chemistry/LabC10MoltenLeadChloride')),
  LabC10AqueousElectrolysis: lazy(() => import('../components/labs/class10/chemistry/LabC10AqueousElectrolysis')),
  LabC10CopperRefining: lazy(() => import('../components/labs/class10/chemistry/LabC10CopperRefining')),
  LabC10Electroplating: lazy(() => import('../components/labs/class10/chemistry/LabC10Electroplating')),
  LabC10DanielCell: lazy(() => import('../components/labs/class10/chemistry/LabC10DanielCell')),
  LabC10FuelCell: lazy(() => import('../components/labs/class10/chemistry/LabC10FuelCell')),
  LabC10SurfaceAreaRate: lazy(() => import('../components/labs/class10/chemistry/LabC10SurfaceAreaRate')),
  LabC10ConcentrationRate: lazy(() => import('../components/labs/class10/chemistry/LabC10ConcentrationRate')),
  LabC10Esterification: lazy(() => import('../components/labs/class10/chemistry/LabC10Esterification')),
  LabC10EthanolFermentation: lazy(() => import('../components/labs/class10/chemistry/LabC10EthanolFermentation')),
  LabC10EthanolHydration: lazy(() => import('../components/labs/class10/chemistry/LabC10EthanolHydration')),
  LabC10AlcoholCombustion: lazy(() => import('../components/labs/class10/chemistry/LabC10AlcoholCombustion')),
  LabC10AdditionPolymerisation: lazy(() => import('../components/labs/class10/chemistry/LabC10AdditionPolymerisation')),
  LabC10CondensationPolymerisation: lazy(() => import('../components/labs/class10/chemistry/LabC10CondensationPolymerisation')),
  LabC10PETAcidHydrolysis: lazy(() => import('../components/labs/class10/chemistry/LabC10PETAcidHydrolysis')),
  LabC10BiochemicalTest: lazy(() => import('../components/labs/class10/chemistry/LabC10BiochemicalTest')),

  // Class 10 Computer Science
  LabCS10NumberSystems: lazy(() => import('../components/labs/class10/computer/LabCS10NumberSystems')),
  LabCS10HelloWorld: lazy(() => import('../components/labs/class10/computer/LabCS10HelloWorld')),
  LabCS10ComputationalThinking: lazy(() => import('../components/labs/class10/computer/LabCS10ComputationalThinking')),
  LabCS10HTMLCSS: lazy(() => import('../components/labs/class10/computer/LabCS10HTMLCSS')),
  LabCS10JSAlgorithms: lazy(() => import('../components/labs/class10/computer/LabCS10JSAlgorithms')),
  LabCS10DynamicList: lazy(() => import('../components/labs/class10/computer/LabCS10DynamicList')),
  LabCS10DataVisualization: lazy(() => import('../components/labs/class10/computer/LabCS10DataVisualization')),
  LabCS10ChurnPrediction: lazy(() => import('../components/labs/class10/computer/LabCS10ChurnPrediction')),
  LabCS10FutureTech: lazy(() => import('../components/labs/class10/computer/LabCS10FutureTech')),
  LabCS10CyberSafety: lazy(() => import('../components/labs/class10/computer/LabCS10CyberSafety')),
  LabCS10DigitalMarketing: lazy(() => import('../components/labs/class10/computer/LabCS10DigitalMarketing')),
  LabCS10MarketResearch: lazy(() => import('../components/labs/class10/computer/LabCS10MarketResearch')),
  LabCS10Financials: lazy(() => import('../components/labs/class10/computer/LabCS10Financials')),
  LabCS10BusinessPitch: lazy(() => import('../components/labs/class10/computer/LabCS10BusinessPitch')),

  // Class 10 Mathematics
  LabM10Vectors: lazy(() => import('../components/labs/class10/math/LabM10Vectors')),
  LabM10ChordBisectors: lazy(() => import('../components/labs/class10/math/LabM10ChordBisectors')),
  LabM10EqualChords: lazy(() => import('../components/labs/class10/math/LabM10EqualChords')),
  LabM10TangentProperties: lazy(() => import('../components/labs/class10/math/LabM10TangentProperties')),
  LabM10CircleAngles: lazy(() => import('../components/labs/class10/math/LabM10CircleAngles')),
  LabM10CircleBasics: lazy(() => import('../components/labs/class10/math/LabM10CircleBasics')),
  LabM10TangentConstruction: lazy(() => import('../components/labs/class10/math/LabM10TangentConstruction')),
  LabM10CommonTangents: lazy(() => import('../components/labs/class10/math/LabM10CommonTangents')),
  LabM10StatisticsWheels: lazy(() => import('../components/labs/class10/math/LabM10StatisticsWheels')),
  LabM10ComplexApplications: lazy(() => import('../components/labs/class10/math/LabM10ComplexApplications')),
  LabM10QuadraticApplications: lazy(() => import('../components/labs/class10/math/LabM10QuadraticApplications')),
  LabM10MatrixApplications: lazy(() => import('../components/labs/class10/math/LabM10MatrixApplications')),
  LabM10InequalityApplications: lazy(() => import('../components/labs/class10/math/LabM10InequalityApplications')),
  LabM10FractionApplications: lazy(() => import('../components/labs/class10/math/LabM10FractionApplications')),
  LabM10FunctionApplications: lazy(() => import('../components/labs/class10/math/LabM10FunctionApplications')),
  LabM10VectorApplications: lazy(() => import('../components/labs/class10/math/LabM10VectorApplications')),
  LabM10TrigApplications: lazy(() => import('../components/labs/class10/math/LabM10TrigApplications')),
  LabM10CircleApplications: lazy(() => import('../components/labs/class10/math/LabM10CircleApplications')),
  LabM10StatsApplications: lazy(() => import('../components/labs/class10/math/LabM10StatsApplications')),

  // Class 10 Biology
  LabB10DigestiveSystem: lazy(() => import('../components/labs/class10/biology/LabB10DigestiveSystem')),
  LabB10BloodSmear: lazy(() => import('../components/labs/class10/biology/LabB10BloodSmear')),
  LabB10RespiratorySystem: lazy(() => import('../components/labs/class10/biology/LabB10RespiratorySystem')),
  LabB10KidneyDissection: lazy(() => import('../components/labs/class10/biology/LabB10KidneyDissection')),
  LabB10NervousSystem: lazy(() => import('../components/labs/class10/biology/LabB10NervousSystem')),
  LabB10Genetics: lazy(() => import('../components/labs/class10/biology/LabB10Genetics')),
  LabB10Biostatistics: lazy(() => import('../components/labs/class10/biology/LabB10Biostatistics')),

  // Class 9 Biology
  LabB9Biodiversity: lazy(() => import('../components/labs/class9/biology/LabB9Biodiversity')),
  LabB9Microscopy: lazy(() => import('../components/labs/class9/biology/LabB9Microscopy')),
  LabB9Biochemistry: lazy(() => import('../components/labs/class9/biology/LabB9Biochemistry')),
  LabB9Enzymes: lazy(() => import('../components/labs/class9/biology/LabB9Enzymes')),
  LabB9PlantPhysiology: lazy(() => import('../components/labs/class9/biology/LabB9PlantPhysiology')),
  LabB9PlantReproduction: lazy(() => import('../components/labs/class9/biology/LabB9PlantReproduction')),

  // Class 9 Chemistry
  LabC9StatesOfMatter: lazy(() => import('../components/labs/class9/chemistry/LabC9StatesOfMatter')),
  LabC9AtomicStructure: lazy(() => import('../components/labs/class9/chemistry/LabC9AtomicStructure')),
  LabC9Electrochemistry: lazy(() => import('../components/labs/class9/chemistry/LabC9Electrochemistry')),
  LabC9EnvironmentalChem: lazy(() => import('../components/labs/class9/chemistry/LabC9EnvironmentalChem')),
  LabC9OrganicChem: lazy(() => import('../components/labs/class9/chemistry/LabC9OrganicChem')),
  LabC9SeparationTech: lazy(() => import('../components/labs/class9/chemistry/LabC9SeparationTech')),
  LabC9QualitativeAnalysis: lazy(() => import('../components/labs/class9/chemistry/LabC9QualitativeAnalysis')),

  // Class 9 Physics
  LabP9DerivationForceMomentum: lazy(() => import('../components/labs/class9/physics/LabP9DerivationForceMomentum')),
  LabP9DerivationRecoil: lazy(() => import('../components/labs/class9/physics/LabP9DerivationRecoil')),
  LabP9DerivationOrbital: lazy(() => import('../components/labs/class9/physics/LabP9DerivationOrbital')),
  LabP9DerivationLiquidPressure: lazy(() => import('../components/labs/class9/physics/LabP9DerivationLiquidPressure')),
  LabP9DerivationHydraulic: lazy(() => import('../components/labs/class9/physics/LabP9DerivationHydraulic')),
  LabP9DerivationKE: lazy(() => import('../components/labs/class9/physics/LabP9DerivationKE')),
  LabP9DerivationGPE: lazy(() => import('../components/labs/class9/physics/LabP9DerivationGPE')),
  LabP9MeasurementTools: lazy(() => import('../components/labs/class9/physics/LabP9MeasurementTools')),
  LabP9VolumeDensity: lazy(() => import('../components/labs/class9/physics/LabP9VolumeDensity')),
  LabP9Kinematics: lazy(() => import('../components/labs/class9/physics/LabP9Kinematics')),
  LabP9Inertia: lazy(() => import('../components/labs/class9/physics/LabP9Inertia')),
  LabP9Friction: lazy(() => import('../components/labs/class9/physics/LabP9Friction')),
  LabP9Pressure: lazy(() => import('../components/labs/class9/physics/LabP9Pressure')),
  LabP9Springs: lazy(() => import('../components/labs/class9/physics/LabP9Springs')),
  LabP9MagnetismFields: lazy(() => import('../components/labs/class9/physics/LabP9MagnetismFields')),
  LabP9MagnetismInduction: lazy(() => import('../components/labs/class9/physics/LabP9MagnetismInduction')),
  LabP9EverydayPhysics: lazy(() => import('../components/labs/class9/physics/LabP9EverydayPhysics')),

  // Class 9 Computer Science
  LabCS9ComputerSystems: lazy(() => import('../components/labs/class9/computer/LabCS9ComputerSystems')),
  LabCS9Algorithms: lazy(() => import('../components/labs/class9/computer/LabCS9Algorithms')),
  LabCS9WebBasics: lazy(() => import('../components/labs/class9/computer/LabCS9WebBasics')),
  LabCS9JavaScript: lazy(() => import('../components/labs/class9/computer/LabCS9JavaScript')),
  LabCS9WebProjects: lazy(() => import('../components/labs/class9/computer/LabCS9WebProjects')),
  LabCS9DataAnalysis: lazy(() => import('../components/labs/class9/computer/LabCS9DataAnalysis')),
  LabCS9AIApplications: lazy(() => import('../components/labs/class9/computer/LabCS9AIApplications')),
  LabCS9CyberSafety: lazy(() => import('../components/labs/class9/computer/LabCS9CyberSafety')),
  LabCS9Entrepreneurship: lazy(() => import('../components/labs/class9/computer/LabCS9Entrepreneurship')),

  // Class 9 Mathematics
  LabM9RealNumbers: lazy(() => import('../components/labs/class9/math/LabM9RealNumbers')),
  LabM9Logarithms: lazy(() => import('../components/labs/class9/math/LabM9Logarithms')),
  LabM9SetsRelations: lazy(() => import('../components/labs/class9/math/LabM9SetsRelations')),
  LabM9AlgebraicManipulation: lazy(() => import('../components/labs/class9/math/LabM9AlgebraicManipulation')),
  LabM9Trigonometry: lazy(() => import('../components/labs/class9/math/LabM9Trigonometry')),
  LabM9CoordinateGeometry: lazy(() => import('../components/labs/class9/math/LabM9CoordinateGeometry')),
  LabM9LinearGraphs: lazy(() => import('../components/labs/class9/math/LabM9LinearGraphs')),
  LabM9GeometryPolygons: lazy(() => import('../components/labs/class9/math/LabM9GeometryPolygons')),
  LabM9BasicStatistics: lazy(() => import('../components/labs/class9/math/LabM9BasicStatistics')),

  // Class 11 Chemistry
  LabC11AtomicStructure: lazy(() => import('../components/labs/class11/chemistry/LabC11AtomicStructure')),
  LabC11MolecularBonding: lazy(() => import('../components/labs/class11/chemistry/LabC11MolecularBonding')),
  LabC11Stoichiometry: lazy(() => import('../components/labs/class11/chemistry/LabC11Stoichiometry')),
  LabC11PhasesOfMatter: lazy(() => import('../components/labs/class11/chemistry/LabC11PhasesOfMatter')),
  LabC11EnergeticsKinetics: lazy(() => import('../components/labs/class11/chemistry/LabC11EnergeticsKinetics')),
  LabC11IndustrialEquilibrium: lazy(() => import('../components/labs/class11/chemistry/LabC11IndustrialEquilibrium')),
  LabC11AcidsBases: lazy(() => import('../components/labs/class11/chemistry/LabC11AcidsBases')),
  LabC11EnvironmentalChem: lazy(() => import('../components/labs/class11/chemistry/LabC11EnvironmentalChem')),
  LabC11OrganicAnalysis: lazy(() => import('../components/labs/class11/chemistry/LabC11OrganicAnalysis')),
  LabC11OrganicSynthesis: lazy(() => import('../components/labs/class11/chemistry/LabC11OrganicSynthesis')),

  // Class 11 Physics
  LabP11PhysicalQuantities: lazy(() => import('../components/labs/class11/physics/LabP11PhysicalQuantities')),
  LabP11Vectors: lazy(() => import('../components/labs/class11/physics/LabP11Vectors')),
  LabP11TranslatoryMotion: lazy(() => import('../components/labs/class11/physics/LabP11TranslatoryMotion')),
  LabP11RotationalMotion: lazy(() => import('../components/labs/class11/physics/LabP11RotationalMotion')),
  LabP11WorkEnergy: lazy(() => import('../components/labs/class11/physics/LabP11WorkEnergy')),
  LabP11FluidMechanics: lazy(() => import('../components/labs/class11/physics/LabP11FluidMechanics')),
  LabP11Solids: lazy(() => import('../components/labs/class11/physics/LabP11Solids')),
  LabP11Thermodynamics: lazy(() => import('../components/labs/class11/physics/LabP11Thermodynamics')),
  LabP11Waves: lazy(() => import('../components/labs/class11/physics/LabP11Waves')),
  LabP11Electrostatics: lazy(() => import('../components/labs/class11/physics/LabP11Electrostatics')),
  LabP11Electricity: lazy(() => import('../components/labs/class11/physics/LabP11Electricity')),
  LabP11Electromagnetism: lazy(() => import('../components/labs/class11/physics/LabP11Electromagnetism')),
  LabP11ModernPhysics: lazy(() => import('../components/labs/class11/physics/LabP11ModernPhysics')),

  // Class 11 Computer Science
  LabCS11SystemsNetworks: lazy(() => import('../components/labs/class11/computer/LabCS11SystemsNetworks')),
  LabCS11Algorithms: lazy(() => import('../components/labs/class11/computer/LabCS11Algorithms')),
  LabCS11Python: lazy(() => import('../components/labs/class11/computer/LabCS11Python')),
  LabCS11DataScience: lazy(() => import('../components/labs/class11/computer/LabCS11DataScience')),
  LabCS11Applications: lazy(() => import('../components/labs/class11/computer/LabCS11Applications')),
  LabCS11Impacts: lazy(() => import('../components/labs/class11/computer/LabCS11Impacts')),
  LabCS11Research: lazy(() => import('../components/labs/class11/computer/LabCS11Research')),
  LabCS11ProductDev: lazy(() => import('../components/labs/class11/computer/LabCS11ProductDev')),

  // Class 11 Biology
  LabB11Cytology: lazy(() => import('../components/labs/class11/biology/LabB11Cytology')),
  LabB11Biomolecules: lazy(() => import('../components/labs/class11/biology/LabB11Biomolecules')),
  LabB11Enzymes: lazy(() => import('../components/labs/class11/biology/LabB11Enzymes')),
  LabB11Bioenergetics: lazy(() => import('../components/labs/class11/biology/LabB11Bioenergetics')),
  LabB11Microbiology: lazy(() => import('../components/labs/class11/biology/LabB11Microbiology')),
  LabB11Fungi: lazy(() => import('../components/labs/class11/biology/LabB11Fungi')),
  LabB11PlantPhysiology: lazy(() => import('../components/labs/class11/biology/LabB11PlantPhysiology')),
  LabB11Inheritance: lazy(() => import('../components/labs/class11/biology/LabB11Inheritance')),
  LabB11Genetics: lazy(() => import('../components/labs/class11/biology/LabB11Genetics')),

  // Class 12 Biology
  LabB12Digestive: lazy(() => import('../components/labs/class12/biology/LabB12Digestive')),
  LabB12Cardiorespiratory: lazy(() => import('../components/labs/class12/biology/LabB12Cardiorespiratory')),
  LabB12Urinary: lazy(() => import('../components/labs/class12/biology/LabB12Urinary')),
  LabB12NeuroEndocrine: lazy(() => import('../components/labs/class12/biology/LabB12NeuroEndocrine')),
  LabB12Skeletal: lazy(() => import('../components/labs/class12/biology/LabB12Skeletal')),
  LabB12Immunity: lazy(() => import('../components/labs/class12/biology/LabB12Immunity')),
  LabB12Biotechnology: lazy(() => import('../components/labs/class12/biology/LabB12Biotechnology')),
  LabB12StructuralStats: lazy(() => import('../components/labs/class12/biology/LabB12StructuralStats')),
  LabB12PharmacologyEcology: lazy(() => import('../components/labs/class12/biology/LabB12PharmacologyEcology')),

  // Class 11 Physics (batch 2)
  LabP11DerivationProjectileTimeFlight: lazy(() => import('../components/labs/class11/physics/LabP11DerivationProjectileTimeFlight')),
  LabP11DerivationAngularMomentum: lazy(() => import('../components/labs/class11/physics/LabP11DerivationAngularMomentum')),
  LabP11DerivationTorqueInertia: lazy(() => import('../components/labs/class11/physics/LabP11DerivationTorqueInertia')),
  LabP11DerivationArtificialGravity: lazy(() => import('../components/labs/class11/physics/LabP11DerivationArtificialGravity')),
  LabP11DerivationTerminalVelocity: lazy(() => import('../components/labs/class11/physics/LabP11DerivationTerminalVelocity')),
  LabP11DerivationResistanceSeries: lazy(() => import('../components/labs/class11/physics/LabP11DerivationResistanceSeries')),
  LabP11DerivationResistanceParallel: lazy(() => import('../components/labs/class11/physics/LabP11DerivationResistanceParallel')),
  LabP11DerivationVenturiMeter: lazy(() => import('../components/labs/class11/physics/LabP11DerivationVenturiMeter')),
  LabP11DerivationElasticPotentialEnergy: lazy(() => import('../components/labs/class11/physics/LabP11DerivationElasticPotentialEnergy')),
  LabP11DerivationWorkDoneGas: lazy(() => import('../components/labs/class11/physics/LabP11DerivationWorkDoneGas')),
  LabP11DerivationCopRefrigerator: lazy(() => import('../components/labs/class11/physics/LabP11DerivationCopRefrigerator')),
  LabP11DerivationDopplerListenerAway: lazy(() => import('../components/labs/class11/physics/LabP11DerivationDopplerListenerAway')),
  LabP11DerivationDopplerSourceTowards: lazy(() => import('../components/labs/class11/physics/LabP11DerivationDopplerSourceTowards')),
  LabP11DerivationStationaryWavesAirColumn: lazy(() => import('../components/labs/class11/physics/LabP11DerivationStationaryWavesAirColumn')),
  LabP11DerivationPotentialGradient: lazy(() => import('../components/labs/class11/physics/LabP11DerivationPotentialGradient')),
  LabP11DerivationMaximumPowerOutput: lazy(() => import('../components/labs/class11/physics/LabP11DerivationMaximumPowerOutput')),
  LabP11DerivationWheatstoneBridge: lazy(() => import('../components/labs/class11/physics/LabP11DerivationWheatstoneBridge')),
  LabP11DerivationForceBetweenConductors: lazy(() => import('../components/labs/class11/physics/LabP11DerivationForceBetweenConductors')),
  LabP11DerivationChargedParticleBField: lazy(() => import('../components/labs/class11/physics/LabP11DerivationChargedParticleBField')),
  LabP11DerivationVelocitySelector: lazy(() => import('../components/labs/class11/physics/LabP11DerivationVelocitySelector')),

// Class 12 Physics
  LabP12Gravitation: lazy(() => import('../components/labs/class12/physics/LabP12Gravitation')),
  LabP12ThermoMechanics: lazy(() => import('../components/labs/class12/physics/LabP12ThermoMechanics')),
  LabP12SHM: lazy(() => import('../components/labs/class12/physics/LabP12SHM')),
  LabP12Diffraction: lazy(() => import('../components/labs/class12/physics/LabP12Diffraction')),
  LabP12ElectricPotential: lazy(() => import('../components/labs/class12/physics/LabP12ElectricPotential')),
  LabP12AlternatingCurrent: lazy(() => import('../components/labs/class12/physics/LabP12AlternatingCurrent')),
  LabP12QuantumNuclear: lazy(() => import('../components/labs/class12/physics/LabP12QuantumNuclear')),
  LabP12CosmologyClimate: lazy(() => import('../components/labs/class12/physics/LabP12CosmologyClimate')),
  LabP12MedicalImaging: lazy(() => import('../components/labs/class12/physics/LabP12MedicalImaging')),
  LabP12SolarCell: lazy(() => import('../components/labs/class12/physics/LabP12SolarCell')),

  // Class 12 Physics Derivations
  // Class 11 Physics Derivations
  LabP11DerivationDimensionalWavelength: lazy(() => import('../components/labs/class11/physics/LabP11DerivationDimensionalWavelength')),
  LabP11DerivationDimensionalPendulum: lazy(() => import('../components/labs/class11/physics/LabP11DerivationDimensionalPendulum')),
  LabP11DerivationRectangularComponents: lazy(() => import('../components/labs/class11/physics/LabP11DerivationRectangularComponents')),
  LabP11DerivationFirstEquation: lazy(() => import('../components/labs/class11/physics/LabP11DerivationFirstEquation')),
  LabP11DerivationSecondEquation: lazy(() => import('../components/labs/class11/physics/LabP11DerivationSecondEquation')),
  LabP11DerivationThirdEquation: lazy(() => import('../components/labs/class11/physics/LabP11DerivationThirdEquation')),
  LabP11DerivationProjectileHeight: lazy(() => import('../components/labs/class11/physics/LabP11DerivationProjectileHeight')),
  LabP11DerivationProjectileRange: lazy(() => import('../components/labs/class11/physics/LabP11DerivationProjectileRange')),
  LabP11DerivationElasticCollision: lazy(() => import('../components/labs/class11/physics/LabP11DerivationElasticCollision')),
  LabP11DerivationLinearAngular: lazy(() => import('../components/labs/class11/physics/LabP11DerivationLinearAngular')),
  LabP11DerivationCentripetalAcceleration: lazy(() => import('../components/labs/class11/physics/LabP11DerivationCentripetalAcceleration')),
  LabP11DerivationKineticEnergyDerivation: lazy(() => import('../components/labs/class11/physics/LabP11DerivationKineticEnergyDerivation')),
  LabP11DerivationArchimedesUpthrust: lazy(() => import('../components/labs/class11/physics/LabP11DerivationArchimedesUpthrust')),
  LabP11DerivationContinuityEquation: lazy(() => import('../components/labs/class11/physics/LabP11DerivationContinuityEquation')),
  LabP11DerivationBernoulliEquation: lazy(() => import('../components/labs/class11/physics/LabP11DerivationBernoulliEquation')),
  LabP11DerivationCarnotEfficiency: lazy(() => import('../components/labs/class11/physics/LabP11DerivationCarnotEfficiency')),
  LabP11DerivationDopplerListenerTowards: lazy(() => import('../components/labs/class11/physics/LabP11DerivationDopplerListenerTowards')),
  LabP11DerivationStationaryWavesString: lazy(() => import('../components/labs/class11/physics/LabP11DerivationStationaryWavesString')),
  LabP11DerivationElectricFieldPoint: lazy(() => import('../components/labs/class11/physics/LabP11DerivationElectricFieldPoint')),
  LabP11DerivationDriftVelocity: lazy(() => import('../components/labs/class11/physics/LabP11DerivationDriftVelocity')),
  LabP11DerivationMagneticForce: lazy(() => import('../components/labs/class11/physics/LabP11DerivationMagneticForce')),
  LabP11DerivationFaradayLawDerivation: lazy(() => import('../components/labs/class11/physics/LabP11DerivationFaradayLawDerivation')),
  LabP11DerivationDopplerSourceAway: lazy(() => import('../components/labs/class11/physics/LabP11DerivationDopplerSourceAway')),
  LabP11DerivationPotentiometer: lazy(() => import('../components/labs/class11/physics/LabP11DerivationPotentiometer')),
  LabP11DerivationDiracMomentum: lazy(() => import('../components/labs/class11/physics/LabP11DerivationDiracMomentum')),

  LabP12DerivationGravitationLaw: lazy(() => import('../components/labs/class12/physics/LabP12DerivationGravitationLaw')),
  LabP12DerivationGOnSurface: lazy(() => import('../components/labs/class12/physics/LabP12DerivationGOnSurface')),
  LabP12DerivationGWithAltitude: lazy(() => import('../components/labs/class12/physics/LabP12DerivationGWithAltitude')),
  LabP12DerivationOrbitalVelocity: lazy(() => import('../components/labs/class12/physics/LabP12DerivationOrbitalVelocity')),
  LabP12DerivationGeostationaryOrbit: lazy(() => import('../components/labs/class12/physics/LabP12DerivationGeostationaryOrbit')),
  LabP12DerivationAbsoluteGPE: lazy(() => import('../components/labs/class12/physics/LabP12DerivationAbsoluteGPE')),
  LabP12DerivationGravPotential: lazy(() => import('../components/labs/class12/physics/LabP12DerivationGravPotential')),
  LabP12DerivationIdealGasPressure: lazy(() => import('../components/labs/class12/physics/LabP12DerivationIdealGasPressure')),
  LabP12DerivationPressureKE: lazy(() => import('../components/labs/class12/physics/LabP12DerivationPressureKE')),
  LabP12DerivationTemperatureKE: lazy(() => import('../components/labs/class12/physics/LabP12DerivationTemperatureKE')),
  LabP12DerivationRMSSpeed: lazy(() => import('../components/labs/class12/physics/LabP12DerivationRMSSpeed')),
  LabP12DerivationSHMMassSpring: lazy(() => import('../components/labs/class12/physics/LabP12DerivationSHMMassSpring')),
  LabP12DerivationSHMDisplacement: lazy(() => import('../components/labs/class12/physics/LabP12DerivationSHMDisplacement')),
  LabP12DerivationSimplePendulum: lazy(() => import('../components/labs/class12/physics/LabP12DerivationSimplePendulum')),
  LabP12DerivationSHMEnergy: lazy(() => import('../components/labs/class12/physics/LabP12DerivationSHMEnergy')),
  LabP12DerivationYoungsDoubleSlit: lazy(() => import('../components/labs/class12/physics/LabP12DerivationYoungsDoubleSlit')),
  LabP12DerivationDiffractionGrating: lazy(() => import('../components/labs/class12/physics/LabP12DerivationDiffractionGrating')),
  LabP12DerivationElectricPotentialPoint: lazy(() => import('../components/labs/class12/physics/LabP12DerivationElectricPotentialPoint')),
  LabP12DerivationCapacitancePP: lazy(() => import('../components/labs/class12/physics/LabP12DerivationCapacitancePP')),
  LabP12DerivationEquivalentCapacitance: lazy(() => import('../components/labs/class12/physics/LabP12DerivationEquivalentCapacitance')),
  LabP12DerivationCapacitorEnergy: lazy(() => import('../components/labs/class12/physics/LabP12DerivationCapacitorEnergy')),
  LabP12DerivationRCCircuit: lazy(() => import('../components/labs/class12/physics/LabP12DerivationRCCircuit')),
  LabP12DerivationACPower: lazy(() => import('../components/labs/class12/physics/LabP12DerivationACPower')),
  LabP12DerivationInductiveReactance: lazy(() => import('../components/labs/class12/physics/LabP12DerivationInductiveReactance')),
  LabP12DerivationCapacitiveReactance: lazy(() => import('../components/labs/class12/physics/LabP12DerivationCapacitiveReactance')),
  LabP12DerivationImpedanceRLRC: lazy(() => import('../components/labs/class12/physics/LabP12DerivationImpedanceRLRC')),
  LabP12DerivationPhotoelectricEffect: lazy(() => import('../components/labs/class12/physics/LabP12DerivationPhotoelectricEffect')),
  LabP12DerivationDeBroglieWavelength: lazy(() => import('../components/labs/class12/physics/LabP12DerivationDeBroglieWavelength')),
  LabP12DerivationMassDefect: lazy(() => import('../components/labs/class12/physics/LabP12DerivationMassDefect')),
  LabP12DerivationDecayLaw: lazy(() => import('../components/labs/class12/physics/LabP12DerivationDecayLaw')),
  LabP12DerivationHalfLifeRelation: lazy(() => import('../components/labs/class12/physics/LabP12DerivationHalfLifeRelation')),
  LabP12DerivationWiensDisplacement: lazy(() => import('../components/labs/class12/physics/LabP12DerivationWiensDisplacement')),
  LabP12DerivationHubbleLaw: lazy(() => import('../components/labs/class12/physics/LabP12DerivationHubbleLaw')),
  LabP12DerivationCoriolisForce: lazy(() => import('../components/labs/class12/physics/LabP12DerivationCoriolisForce')),
  LabP12DerivationNewtonCannonball: lazy(() => import('../components/labs/class12/physics/LabP12DerivationNewtonCannonball')),

  // Class 12 Chemistry
  LabC12Electrochemistry: lazy(() => import('../components/labs/class12/chemistry/LabC12Electrochemistry')),
  LabC12EquilibriumAcidBase: lazy(() => import('../components/labs/class12/chemistry/LabC12EquilibriumAcidBase')),
  LabC12TransitionMetals: lazy(() => import('../components/labs/class12/chemistry/LabC12TransitionMetals')),
  LabC12OrganicSynthesis: lazy(() => import('../components/labs/class12/chemistry/LabC12OrganicSynthesis')),
  LabC12Biochemistry: lazy(() => import('../components/labs/class12/chemistry/LabC12Biochemistry')),
  LabC12SpectroscopyChromatography: lazy(() => import('../components/labs/class12/chemistry/LabC12SpectroscopyChromatography')),
  LabC12Medicine: lazy(() => import('../components/labs/class12/chemistry/LabC12Medicine')),
  LabC12Agriculture: lazy(() => import('../components/labs/class12/chemistry/LabC12Agriculture')),
  LabC12IndustryMaterials: lazy(() => import('../components/labs/class12/chemistry/LabC12IndustryMaterials')),

  // Class 12 Computer Science
  LabCS12HCI: lazy(() => import('../components/labs/class12/computer/LabCS12HCI')),
  LabCS12DataStructures: lazy(() => import('../components/labs/class12/computer/LabCS12DataStructures')),
  LabCS12Programming: lazy(() => import('../components/labs/class12/computer/LabCS12Programming')),
  LabCS12MachineLearning: lazy(() => import('../components/labs/class12/computer/LabCS12MachineLearning')),
  LabCS12DeepLearning: lazy(() => import('../components/labs/class12/computer/LabCS12DeepLearning')),
  LabCS12IoTCloud: lazy(() => import('../components/labs/class12/computer/LabCS12IoTCloud')),
  LabCS12Cybersecurity: lazy(() => import('../components/labs/class12/computer/LabCS12Cybersecurity')),
  LabCS12DigitalLiteracy: lazy(() => import('../components/labs/class12/computer/LabCS12DigitalLiteracy')),
  LabCS12Entrepreneurship: lazy(() => import('../components/labs/class12/computer/LabCS12Entrepreneurship')),

  // Class 11 Mathematics
  LabM11ComplexNumbers: lazy(() => import('../components/labs/class11/math/LabM11ComplexNumbers')),
  LabM11Matrices: lazy(() => import('../components/labs/class11/math/LabM11Matrices')),
  LabM11Vectors: lazy(() => import('../components/labs/class11/math/LabM11Vectors')),
  LabM11SequencesSeries: lazy(() => import('../components/labs/class11/math/LabM11SequencesSeries')),
  LabM11Polynomials: lazy(() => import('../components/labs/class11/math/LabM11Polynomials')),
  LabM11Trigonometry: lazy(() => import('../components/labs/class11/math/LabM11Trigonometry')),
  LabM11Permutations: lazy(() => import('../components/labs/class11/math/LabM11Permutations')),
  LabM11BinomialInduction: lazy(() => import('../components/labs/class11/math/LabM11BinomialInduction')),

  // Class 12 Mathematics
  LabM12Derivatives: lazy(() => import('../components/labs/class12/math/LabM12Derivatives')),
  LabM12Integration: lazy(() => import('../components/labs/class12/math/LabM12Integration')),
  LabM12DifferentialEq: lazy(() => import('../components/labs/class12/math/LabM12DifferentialEq')),
  LabM12Conics: lazy(() => import('../components/labs/class12/math/LabM12Conics')),
  LabM12AnalyticalGeometry: lazy(() => import('../components/labs/class12/math/LabM12AnalyticalGeometry')),
  LabM12Kinematics: lazy(() => import('../components/labs/class12/math/LabM12Kinematics')),
  LabM12Functions: lazy(() => import('../components/labs/class12/math/LabM12Functions')),
  LabM12InverseTrig: lazy(() => import('../components/labs/class12/math/LabM12InverseTrig')),

  // Class 6 Science
  LabS6Microscope: lazy(() => import('../components/labs/class6/science/LabS6Microscope')),
  LabS6Unit1Projects: lazy(() => import('../components/labs/class6/science/LabS6Unit1Projects')),
  LabS6VegetativePropagation: lazy(() => import('../components/labs/class6/science/LabS6VegetativePropagation')),
  LabS6FatDetection: lazy(() => import('../components/labs/class6/science/LabS6FatDetection')),
  LabS6BalancedDiet: lazy(() => import('../components/labs/class6/science/LabS6BalancedDiet')),
  LabS6DigestionMechanics: lazy(() => import('../components/labs/class6/science/LabS6DigestionMechanics')),
  LabS6AlimentaryCanal: lazy(() => import('../components/labs/class6/science/LabS6AlimentaryCanal')),
  LabS6LungModel: lazy(() => import('../components/labs/class6/science/LabS6LungModel')),
  LabS6ParticleSimulation: lazy(() => import('../components/labs/class6/science/LabS6ParticleSimulation')),
  LabS6MolecularBuilder: lazy(() => import('../components/labs/class6/science/LabS6MolecularBuilder')),
  LabS6ElementsCompounds: lazy(() => import('../components/labs/class6/science/LabS6ElementsCompounds')),
  LabS6Separation: lazy(() => import('../components/labs/class6/science/LabS6Separation')),
  LabS6SolutionInvestigation: lazy(() => import('../components/labs/class6/science/LabS6SolutionInvestigation')),
  LabS6EnergyTransformation: lazy(() => import('../components/labs/class6/science/LabS6EnergyTransformation')),
  LabS6EnergyProjects: lazy(() => import('../components/labs/class6/science/LabS6EnergyProjects')),
  LabS6CircuitBuilder: lazy(() => import('../components/labs/class6/science/LabS6CircuitBuilder')),
  LabS6ConductorsInsulators: lazy(() => import('../components/labs/class6/science/LabS6ConductorsInsulators')),
  LabS6Magnetism: lazy(() => import('../components/labs/class6/science/LabS6Magnetism')),
  LabS6PlantGrowth: lazy(() => import('../components/labs/class6/science/LabS6PlantGrowth')),
  LabS6SolarSystemBuilder: lazy(() => import('../components/labs/class6/science/LabS6SolarSystemBuilder')),
  LabS6EverydayTech: lazy(() => import('../components/labs/class6/science/LabS6EverydayTech')),

  // Class 6 Math
  LabM6Factors: lazy(() => import('../components/labs/class6/math/LabM6Factors')),
  LabM6Integers: lazy(() => import('../components/labs/class6/math/LabM6Integers')),
  LabM6Proportions: lazy(() => import('../components/labs/class6/math/LabM6Proportions')),
  LabM6Sets: lazy(() => import('../components/labs/class6/math/LabM6Sets')),
  LabM6Algebra: lazy(() => import('../components/labs/class6/math/LabM6Algebra')),
  LabM6Geometry: lazy(() => import('../components/labs/class6/math/LabM6Geometry')),
  LabM6Mensuration: lazy(() => import('../components/labs/class6/math/LabM6Mensuration')),
  LabM6Data: lazy(() => import('../components/labs/class6/math/LabM6Data')),

  // Class 7 Math
  LabM7RationalSquares: lazy(() => import('../components/labs/class7/math/LabM7RationalSquares')),
  LabM7ProportionsKinematics: lazy(() => import('../components/labs/class7/math/LabM7ProportionsKinematics')),
  LabM7FinancialArithmetic: lazy(() => import('../components/labs/class7/math/LabM7FinancialArithmetic')),
  LabM7SetsAlgebra: lazy(() => import('../components/labs/class7/math/LabM7SetsAlgebra')),
  LabM7Transformations: lazy(() => import('../components/labs/class7/math/LabM7Transformations')),
  LabM7Equations: lazy(() => import('../components/labs/class7/math/LabM7Equations')),
  LabM7GeometryDrafting: lazy(() => import('../components/labs/class7/math/LabM7GeometryDrafting')),
  LabM7MensurationData: lazy(() => import('../components/labs/class7/math/LabM7MensurationData')),

  // Class 8 Math
  LabM8RealEstimation: lazy(() => import('../components/labs/class8/math/LabM8RealEstimation')),
  LabM8RootsFinance: lazy(() => import('../components/labs/class8/math/LabM8RootsFinance')),
  LabM8SetsAlgebra: lazy(() => import('../components/labs/class8/math/LabM8SetsAlgebra')),
  LabM8EquationsInequalities: lazy(() => import('../components/labs/class8/math/LabM8EquationsInequalities')),
  LabM8Transformations: lazy(() => import('../components/labs/class8/math/LabM8Transformations')),
  LabM8GeometryTriangles: lazy(() => import('../components/labs/class8/math/LabM8GeometryTriangles')),
  LabM8Mensuration: lazy(() => import('../components/labs/class8/math/LabM8Mensuration')),
  LabM8DataProbability: lazy(() => import('../components/labs/class8/math/LabM8DataProbability')),

  // Class 6 English
  LabE6NounsPronouns: lazy(() => import('../components/labs/class6/english/LabE6NounsPronouns')),
  LabE6SentencesAffixes: lazy(() => import('../components/labs/class6/english/LabE6SentencesAffixes')),
  LabE6VerbsAdverbs: lazy(() => import('../components/labs/class6/english/LabE6VerbsAdverbs')),
  LabE6PrepositionsStructure: lazy(() => import('../components/labs/class6/english/LabE6PrepositionsStructure')),
  LabE6ClausesConjunctions: lazy(() => import('../components/labs/class6/english/LabE6ClausesConjunctions')),
  LabE6TensesPunctuation: lazy(() => import('../components/labs/class6/english/LabE6TensesPunctuation')),
  LabE6FiguresOfSpeech: lazy(() => import('../components/labs/class6/english/LabE6FiguresOfSpeech')),
  LabE6WritingMechanics: lazy(() => import('../components/labs/class6/english/LabE6WritingMechanics')),

  // Class 7 English
  LabE7ArticlesAdjectives: lazy(() => import('../components/labs/class7/english/LabE7ArticlesAdjectives')),
  LabE7FiguresOfSpeech: lazy(() => import('../components/labs/class7/english/LabE7FiguresOfSpeech')),
  LabE7PrepositionsModals: lazy(() => import('../components/labs/class7/english/LabE7PrepositionsModals')),
  LabE7VerbsCollocations: lazy(() => import('../components/labs/class7/english/LabE7VerbsCollocations')),
  LabE7Tenses: lazy(() => import('../components/labs/class7/english/LabE7Tenses')),
  LabE7Conjunctions: lazy(() => import('../components/labs/class7/english/LabE7Conjunctions')),
  LabE7PronounsClauses: lazy(() => import('../components/labs/class7/english/LabE7PronounsClauses')),
  LabE7VocabPunctuation: lazy(() => import('../components/labs/class7/english/LabE7VocabPunctuation')),

  // Class 8 English
  LabE8NounsPhonetics: lazy(() => import('../components/labs/class8/english/LabE8NounsPhonetics')),
  LabE8PronounsMorphology: lazy(() => import('../components/labs/class8/english/LabE8PronounsMorphology')),
  LabE8AdjectivesPoetry: lazy(() => import('../components/labs/class8/english/LabE8AdjectivesPoetry')),
  LabE8VerbsModals: lazy(() => import('../components/labs/class8/english/LabE8VerbsModals')),
  LabE8AdverbsPrepositions: lazy(() => import('../components/labs/class8/english/LabE8AdverbsPrepositions')),
  LabE8ConjunctionsClauses: lazy(() => import('../components/labs/class8/english/LabE8ConjunctionsClauses')),
  LabE8TensesVoice: lazy(() => import('../components/labs/class8/english/LabE8TensesVoice')),
  LabE8NarrationConditionals: lazy(() => import('../components/labs/class8/english/LabE8NarrationConditionals')),


  // Class 9 English
  LabE9PartsOfSpeech: lazy(() => import('../components/labs/class9/english/LabE9PartsOfSpeech')),
  LabE9Verbals: lazy(() => import('../components/labs/class9/english/LabE9Verbals')),
  LabE9TensesAgreement: lazy(() => import('../components/labs/class9/english/LabE9TensesAgreement')),
  LabE9Phrases: lazy(() => import('../components/labs/class9/english/LabE9Phrases')),
  LabE9PrepositionsConjunctions: lazy(() => import('../components/labs/class9/english/LabE9PrepositionsConjunctions')),
  LabE9SentenceStructure: lazy(() => import('../components/labs/class9/english/LabE9SentenceStructure')),
  LabE9Narration: lazy(() => import('../components/labs/class9/english/LabE9Narration')),
  LabE9PunctuationVocabulary: lazy(() => import('../components/labs/class9/english/LabE9PunctuationVocabulary')),

  // Class 10 English
  LabE10NounsPronouns: lazy(() => import('../components/labs/class10/english/LabE10NounsPronouns')),
  LabE10VerbsAdjectives: lazy(() => import('../components/labs/class10/english/LabE10VerbsAdjectives')),
  LabE10AdverbsPrepositions: lazy(() => import('../components/labs/class10/english/LabE10AdverbsPrepositions')),
  LabE10ConjunctionsTenses: lazy(() => import('../components/labs/class10/english/LabE10ConjunctionsTenses')),
  LabE10ModalsConditionals: lazy(() => import('../components/labs/class10/english/LabE10ModalsConditionals')),
  LabE10PhrasesClauses: lazy(() => import('../components/labs/class10/english/LabE10PhrasesClauses')),
  LabE10SentenceNarration: lazy(() => import('../components/labs/class10/english/LabE10SentenceNarration')),
  LabE10VocabularyStylistics: lazy(() => import('../components/labs/class10/english/LabE10VocabularyStylistics')),
  
  // Class 11 English
  LabE11NounsPronouns: lazy(() => import('../components/labs/class11/english/LabE11NounsPronouns')),
  LabE11AdjectivesAdverbs: lazy(() => import('../components/labs/class11/english/LabE11AdjectivesAdverbs')),
  LabE11PrepositionsConjunctions: lazy(() => import('../components/labs/class11/english/LabE11PrepositionsConjunctions')),
  LabE11VerbsModals: lazy(() => import('../components/labs/class11/english/LabE11VerbsModals')),
  LabE11TensesVerbals: lazy(() => import('../components/labs/class11/english/LabE11TensesVerbals')),
  LabE11PhrasesClauses: lazy(() => import('../components/labs/class11/english/LabE11PhrasesClauses')),
  LabE11SentenceStructure: lazy(() => import('../components/labs/class11/english/LabE11SentenceStructure')),
  LabE11VocabularyStylistics: lazy(() => import('../components/labs/class11/english/LabE11VocabularyStylistics')),

  // Class 9 Math Theorems
  LabM9TheoremViewer: lazy(() => import('../components/labs/class9/math/LabM9TheoremViewer')),
  LabM9Theorems: lazy(() => import('../components/labs/class9/math/LabM9Theorems')),
  LabM10Theorems: lazy(() => import('../components/labs/class10/math/LabM10Theorems')),
  LabM10TheoremViewer: lazy(() => import('../components/labs/class10/math/LabM10TheoremViewer')),
  LabM11TheoremViewer: lazy(() => import('../components/labs/class11/math/LabM11TheoremViewer')),
  LabM12TheoremViewer: lazy(() => import('../components/labs/class12/math/LabM12TheoremViewer')),

    // Class 12 English
  LabE12NounsPronouns: lazy(() => import('../components/labs/class12/english/LabE12NounsPronouns')),
  LabE12AdjectivesAdverbs: lazy(() => import('../components/labs/class12/english/LabE12AdjectivesAdverbs')),
  LabE12PrepositionsConjunctions: lazy(() => import('../components/labs/class12/english/LabE12PrepositionsConjunctions')),
  LabE12VerbsModals: lazy(() => import('../components/labs/class12/english/LabE12VerbsModals')),
  LabE12TensesVerbals: lazy(() => import('../components/labs/class12/english/LabE12TensesVerbals')),
  LabE12PhrasesClauses: lazy(() => import('../components/labs/class12/english/LabE12PhrasesClauses')),
  LabE12SentenceStructure: lazy(() => import('../components/labs/class12/english/LabE12SentenceStructure')),
  LabE12VocabularyStylistics: lazy(() => import('../components/labs/class12/english/LabE12VocabularyStylistics')),


};

// Module ID to component name mapping
const moduleIdToComponent: Record<string, string> = {
  // Class 8 Computer
  'c8c_1_1': 'LabDataComm',
  'c8c_1_2': 'LabNetworkDevices',
  'c8c_2_1': 'LabCricketSpreadsheet',
  'c8c_2_2': 'LabDataWorksheets',
  'c8c_3_1': 'LabPseudocodeInterpreter',
  'c8c_3_2': 'LabDiceGameAlgorithm',
  'c8c_4_1': 'LabScratchMaze',
  'c8c_5_1': 'LabCyberScout',
  'c8c_5_2': 'LabAntivirus',
  'c8c_6_1': 'LabBusinessPlan',
  'c8c_6_2': 'LabDigitalMarketing',

  // Class 7 Computer
  'c7c_1_1': 'LabC7Hardware',
  'c7c_1_2': 'LabC7EmergingTech',
  'c7c_1_3': 'LabC7Generations',
  'c7c_1_4': 'LabC7NetworkDiagram',
  'c7c_2_1': 'LabC7UrduTyping',
  'c7c_2_2': 'LabC7LetterFormat',
  'c7c_2_3': 'LabC7CVCreation',
  'c7c_2_4': 'LabC7IllustratedStory',
  'c7c_2_5': 'LabC7PowerPointGeometry',
  'c7c_2_6': 'LabC7WondersResearch',
  'c7c_3_1': 'LabC7ConditionalLogic',
  'c7c_3_2': 'LabC7GradingFlowchart',
  'c7c_3_3': 'LabC7ReverseFlowchart',
  'c7c_4_1': 'LabC7SpriteManipulation',
  'c7c_4_2': 'LabC7LoopAdjustments',
  'c7c_4_3': 'LabC7BouncingBall',
  'c7c_4_4': 'LabC7AnimatedDialogue',
  'c7c_4_5': 'LabC7InteractivePiano',
  'c7c_5_1': 'LabC7Cybercrime',
  'c7c_5_2': 'LabC7DevianceDiscussion',
  'c7c_5_3': 'LabC7EthicsChart',
  'c7c_6_1': 'LabC7DesignPrototype',
  'c7c_6_2': 'LabC7MothersDay',

  // Class 6 Computer
  'c6c_1_1': 'LabC6HealthCampaign',
  'c6c_1_2': 'LabC6HardwareCharts',
  'c6c_1_3': 'LabC6LabRules',
  'c6c_1_4': 'LabC6GroupPresentations',
  'c6c_2_1': 'LabC6SystemSoftware',
  'c6c_2_2': 'LabC6FileManagement1',
  'c6c_2_3': 'LabC6FileManagement2',
  'c6c_2_4': 'LabC6DietExercise',
  'c6c_2_5': 'LabC6Paint3DFace',
  'c6c_2_6': 'LabC6SolarSystem',
  'c6c_3_1': 'LabC6ProblemDecomposition',
  'c6c_3_2': 'LabC6RoadSafetyProcess',
  'c6c_4_1': 'LabC6CoordinateExp',
  'c6c_4_2': 'LabC6CostumeChange',
  'c6c_4_3': 'LabC6MovementTracking',
  'c6c_4_4': 'LabC6LoopAdjustments',
  'c6c_5_1': 'LabC6EthicsChart',
  'c6c_5_2': 'LabC6CyberScout',
  'c6c_5_3': 'LabC6PosterCompetition',
  'c6c_6_1': 'LabC6HobbyMonetization',

  // Class 8 Science
  'c8s_1_1': 'LabS8GreenhouseEffect',
  'c8s_1_2': 'LabS6EverydayTech', // Using S6 EverydayTech as placeholder (component c8s_1_2 doesn't exist)
  'c8s_2_1': 'LabS8StimulusResponse',
  'c8s_2_2': 'LabS8KneeJerk',
  'c8s_2_3': 'LabS8ReflexTime',
  'c8s_3_1': 'LabS8DNAExtraction',
  'c8s_3_2': 'LabS8HumanVariations',
  'c8s_3_3': 'LabS8CrossingOver',
  'c8s_4_1': 'LabS8MakingYogurt',
  'c8s_5_1': 'LabS8PeriodicTable',
  'c8s_5_2': 'LabS8ElectronicConfig',
  'c8s_5_3': 'LabS8Malleability',
  'c8s_5_4': 'LabS8Flexibility',
  'c8s_5_5': 'LabS8Density',
  'c8s_5_6': 'LabS8ThermalConductivity',
  'c8s_5_7': 'LabS8Sonorous',
  'c8s_6_1': 'LabS8ChemicalReactionSigns',
  'c8s_6_2': 'LabS8ConservationMass',
  'c8s_6_3': 'LabS8Endothermic',
  'c8s_6_4': 'LabS8Exothermic',
  'c8s_7_1': 'LabS8AcidLitmus',
  'c8s_7_2': 'LabS8AlkaliLitmus',
  'c8s_7_3': 'LabS8Neutralization',
  'c8s_7_4': 'LabS8DeterminingPH',
  'c8s_8_1': 'LabS8NailPressure',
  'c8s_8_2': 'LabS8HydraulicElevator',
  'c8s_8_3': 'LabS8WaterRocket',
  'c8s_9_1': 'LabS8LaserMaze',
  'c8s_9_3': 'LabS8Periscope',
  'c8s_9_4': 'LabS8RefractionPencil',
  'c8s_9_5': 'LabS8ConcaveMirror',
  'c8s_9_6': 'LabS8ConvexMirror',
  'c8s_10_1': 'LabS8Electromagnet',
  'c8s_11_1': 'LabS8Toothpaste',
  'c8s_11_2': 'LabS8SoapMaking',
  'c8s_11_3': 'LabS8MilkPlastic',
  'c8s_11_4': 'LabS8Detergent',
  'c8s_11_5': 'LabS8SolarCooker',
  'c8s_11_7': 'LabS8WindTurbine',
  'c8s_11_8': 'LabS8ChemicalCar',
  'c8s_11_9': 'LabS8Windsock',
  'c8s_12_1': 'LabS8SkyMap',

  // Class 7 Science
  'c7s_1_1': 'LabS7XylemTransport',
  'c7s_1_2': 'LabS7TranspirationObservation',
  'c7s_1_3': 'LabS7TranspirationLeaves',
  'c7s_1_4': 'LabS7MineralsPlantGrowth',
  'c7s_1_5': 'LabS7Unit1Projects',
  'c7s_2_1': 'LabS7MeasuringLungCapacity',
  'c7s_2_2': 'LabS7PulseRateExercise',
  'c7s_2_3': 'LabS7Unit2Projects',
  'c7s_3_1': 'LabS7ImmuneSystemRolePlay',
  'c7s_3_2': 'LabS7Unit3Projects',
  'c7s_4_1': 'LabS7ChemicalChange',
  'c7s_4_2': 'LabS7ThermalConduction',
  'c7s_4_3': 'LabS7Unit4Projects',
  'c7s_5_1': 'LabS7CalculatingSubatomicParticles',
  'c7s_5_2': 'LabS7AtomModel',
  'c7s_6_1': 'LabS7LithiumBonding',
  'c7s_7_1': 'LabS7DiluteConcentratedSolutions',
  'c7s_7_2': 'LabS7CleaningCoins',
  'c7s_7_3': 'LabS7MakingRockCandy',
  'c7s_7_4': 'LabS7OilPollutants',
  'c7s_8_1': 'LabS7BalloonRocket',
  'c7s_8_2': 'LabS7Unit8Projects',
  'c7s_9_1': 'LabS7VibratingLengthPitch',
  'c7s_9_2': 'LabS7Unit9Projects',
  'c7s_10_1': 'LabS7Unit10Projects',
  'c7s_11_1': 'LabS7DripIrrigation',
  'c7s_11_2': 'LabS7MakeStethoscope',
  'c7s_11_3': 'LabS7HandSanitizer',
  'c7s_11_4': 'LabS7Unit11Projects',
  'c7s_12_1': 'LabS7EarthSeasons',

  // Class 10 Physics
  'p10_10_1': 'LabP10CarbonFootprint',
  'p10_10_2': 'LabP10SpecificHeatMixture',
  'p10_10_3': 'LabP10SpecificHeatElectrical',
  'p10_10_4': 'LabP10ThermalConduction',
  'p10_10_5': 'LabP10ConvectionCurrents',
  'p10_10_6': 'LabP10InsulatingMaterials',
  'p10_10_7': 'LabP10AbsorbersReflectors',
  'p10_10_8': 'LabP10LeslieCube',
  'p10_11_1': 'LabP10ThermalExpansionSolid',
  'p10_11_2': 'LabP10ExpansionLiquids',
  'p10_11_3': 'LabP10GasPressureBalloon',
  'p10_11_4': 'LabP10LatentHeat',
  'p10_12_1': 'LabP10WaveMotion',
  'p10_12_2': 'LabP10RippleTank',
  'p10_12_3': 'LabP10RefractionIllusion',
  'p10_13_1': 'LabP10SoundProduction',
  'p10_13_2': 'LabP10SoundMedium',
  'p10_13_3': 'LabP10StringTelephone',
  'p10_13_4': 'LabP10SpeakerProject',
  'p10_14_1': 'LabP10PlaneMirror',
  'p10_14_2': 'LabP10RefractionBlocks',
  'p10_14_3': 'LabP10TotalInternalReflection',
  'p10_15_1': 'LabP10ElectrostaticCharges',
  'p10_15_2': 'LabP10Electroscope',
  'p10_16_1': 'LabP10OhmLaw',
  'p10_16_2': 'LabP10SeriesCircuit',
  'p10_16_3': 'LabP10ParallelCircuit',
  'p10_17_1': 'LabP10MagneticField',
  'p10_17_2': 'LabP10ElectromagnetDC',
  'p10_17_3': 'LabP10FaradayLaw',
  'p10_18_1': 'LabP10ThermionicEmission',
  'p10_18_2': 'LabP10LogicGates',
  'p10_19_1': 'LabP10RadioTransmission',
  'p10_19_2': 'LabP10OpticalFibers',
  'p10_20_1': 'LabP10Radioactivity',
  'p10_20_2': 'LabP10HalfLife',

  // Class 10 Physics Derivations
  'p10_deriv_specific_heat_mixtures': 'LabP10DerivationSpecificHeatMixtures',
  'p10_deriv_specific_heat_electrical': 'LabP10DerivationSpecificHeatElectrical',
  'p10_deriv_linear_expansion': 'LabP10DerivationLinearExpansion',
  'p10_deriv_volumetric_expansion': 'LabP10DerivationVolumetricExpansion',
  'p10_deriv_expansion_liquids': 'LabP10DerivationExpansionLiquids',
  'p10_deriv_wave_equation': 'LabP10DerivationWaveEquation',
  'p10_deriv_echo': 'LabP10DerivationEcho',
  'p10_deriv_critical_angle': 'LabP10DerivationCriticalAngle',
  'p10_deriv_magnification': 'LabP10DerivationMagnification',
  'p10_deriv_resistivity': 'LabP10DerivationResistivity',
  'p10_deriv_temp_coefficient': 'LabP10DerivationTempCoefficient',
  'p10_deriv_potential_divider': 'LabP10DerivationPotentialDivider',
  'p10_deriv_series_resistance': 'LabP10DerivationSeriesResistance',
  'p10_deriv_parallel_resistance': 'LabP10DerivationParallelResistance',
  'p10_deriv_electrical_energy': 'LabP10DerivationElectricalEnergy',
  'p10_deriv_electric_power': 'LabP10DerivationElectricPower',
  'p10_deriv_transistor_gain': 'LabP10DerivationTransistorGain',
  'p10_deriv_transformer': 'LabP10DerivationTransformer',
  'p10_deriv_photon_energy': 'LabP10DerivationPhotonEnergy',
  'p10_deriv_radioactive_decay': 'LabP10DerivationRadioactiveDecay',

  // Class 10 Chemistry
  'c10_3_1': 'LabC10DiluteSolution',
  'c10_3_2': 'LabC10StandardizationTitration',
  'c10_6_1': 'LabC10SaltTitration',
  'c10_6_2': 'LabC10SaltExcessMetal',
  'c10_6_3': 'LabC10SaltExcessBase',
  'c10_6_4': 'LabC10SaltExcessCarbonate',
  'c10_7_1': 'LabC10MetalReactivity',
  'c10_9_1': 'LabC10SaturatedUnsaturated',
  'c10_11_1': 'LabC10AceticAcidMetal',
  'c10_11_2': 'LabC10AceticAcidCarbonate',
  'c10_4_1': 'LabC10DownsCell',
  'c10_4_2': 'LabC10MoltenLeadChloride',
  'c10_4_3': 'LabC10AqueousElectrolysis',
  'c10_4_4': 'LabC10CopperRefining',
  'c10_4_5': 'LabC10Electroplating',
  'c10_4_6': 'LabC10DanielCell',
  'c10_4_7': 'LabC10FuelCell',
  'c10_5_1': 'LabC10SurfaceAreaRate',
  'c10_5_2': 'LabC10ConcentrationRate',
  'c10_8_1': 'LabC10Esterification',
  'c10_10_1': 'LabC10EthanolFermentation',
  'c10_10_2': 'LabC10EthanolHydration',
  'c10_10_3': 'LabC10AlcoholCombustion',
  'c10_12_1': 'LabC10AdditionPolymerisation',
  'c10_12_2': 'LabC10CondensationPolymerisation',
  'c10_12_3': 'LabC10PETAcidHydrolysis',
  'c10_13_1': 'LabC10BiochemicalTest',

  // Class 10 Computer Science
  'cs10_1_1': 'LabCS10NumberSystems',
  'cs10_1_2': 'LabCS10HelloWorld',
  'cs10_2_1': 'LabCS10ComputationalThinking',
  'cs10_3_1': 'LabCS10HTMLCSS',
  'cs10_4_1': 'LabCS10JSAlgorithms',
  'cs10_5_1': 'LabCS10DynamicList',
  'cs10_6_1': 'LabCS10DataVisualization',
  'cs10_7_1': 'LabCS10ChurnPrediction',
  'cs10_8_1': 'LabCS10FutureTech',

  // Class 10 Mathematics

  // Class 10 Biology

  // Class 9 Biology

  // Class 9 Chemistry

  // Class 9 Physics
  'p9_deriv_force_momentum': 'LabP9DerivationForceMomentum',
  'p9_deriv_recoil': 'LabP9DerivationRecoil',
  'p9_deriv_orbital': 'LabP9DerivationOrbital',
  'p9_deriv_liquid_pressure': 'LabP9DerivationLiquidPressure',
  'p9_deriv_hydraulic': 'LabP9DerivationHydraulic',
  'p9_deriv_ke': 'LabP9DerivationKE',
  'p9_deriv_gpe': 'LabP9DerivationGPE',

  // Class 9 Computer Science

  // Class 9 Mathematics


  // Class 9 Math Theorems
  'm9_theorem_product_log': 'LabM9TheoremViewer',
  'm9_theorem_quotient_log': 'LabM9TheoremViewer',
  'm9_theorem_power_log': 'LabM9TheoremViewer',
  'm9_theorem_change_base': 'LabM9TheoremViewer',
  'm9_theorem_union_assoc': 'LabM9TheoremViewer',
  'm9_theorem_intersection_assoc': 'LabM9TheoremViewer',
  'm9_theorem_distributive_union': 'LabM9TheoremViewer',
  'm9_theorem_distributive_intersection': 'LabM9TheoremViewer',
  'm9_theorem_quotient_identity': 'LabM9TheoremViewer',
  'm9_theorem_pythagorean_identity': 'LabM9TheoremViewer',
  'm9_theorem_distance_formula': 'LabM9TheoremViewer',
  'm9_theorem_slope_intercept': 'LabM9TheoremViewer',
  'm9_theorem_point_slope': 'LabM9TheoremViewer',
  'm9_theorem_two_point': 'LabM9TheoremViewer',
  'm9_theorem_two_intercept': 'LabM9TheoremViewer',
  'm9_theorem_normal_form': 'LabM9TheoremViewer',
  'm9_theorem_angle_between_lines': 'LabM9TheoremViewer',

  // Class 10 Math Theorems
  'm10_theorem_quadratic_formula': 'LabM10TheoremViewer',
  'm10_theorem_vector_diff': 'LabM10TheoremViewer',
  'm10_theorem_law_cosines': 'LabM10TheoremViewer',
  'm10_theorem_law_sines': 'LabM10TheoremViewer',
  'm10_theorem_law_tangents': 'LabM10TheoremViewer',
  'm10_theorem_half_angle_cos': 'LabM10TheoremViewer',
  'm10_theorem_half_angle_sin': 'LabM10TheoremViewer',
  'm10_theorem_area_sas': 'LabM10TheoremViewer',
  'm10_theorem_area_aas': 'LabM10TheoremViewer',
  'm10_theorem_heros': 'LabM10TheoremViewer',
  'm10_theorem_circum_radius': 'LabM10TheoremViewer',
  'm10_theorem_in_radius': 'LabM10TheoremViewer',
  'm10_theorem_ex_radius': 'LabM10TheoremViewer',
  'm10_theorem_three_point_circle': 'LabM10TheoremViewer',
  'm10_theorem_centre_bisects': 'LabM10TheoremViewer',
  'm10_theorem_perp_bisects': 'LabM10TheoremViewer',
  'm10_theorem_equal_chords_equal_dist': 'LabM10TheoremViewer',
  'm10_theorem_equidistant_chords': 'LabM10TheoremViewer',
  'm10_theorem_congruent_arcs': 'LabM10TheoremViewer',
  'm10_theorem_equal_chords_arcs': 'LabM10TheoremViewer',
  'm10_theorem_equal_chords_angles': 'LabM10TheoremViewer',
  'm10_theorem_equal_angles_chords': 'LabM10TheoremViewer',
  'm10_theorem_perp_radius_tangent': 'LabM10TheoremViewer',
  'm10_theorem_tangent_perp_radius': 'LabM10TheoremViewer',
  'm10_theorem_equal_tangents': 'LabM10TheoremViewer',
  'm10_theorem_external_touching': 'LabM10TheoremViewer',
  'm10_theorem_internal_touching': 'LabM10TheoremViewer',
  'm10_theorem_alternate_segment': 'LabM10TheoremViewer',
  'm10_theorem_central_angle': 'LabM10TheoremViewer',
  'm10_theorem_same_segment': 'LabM10TheoremViewer',
  'm10_theorem_semicircle': 'LabM10TheoremViewer',
  'm10_theorem_major_segment': 'LabM10TheoremViewer',
  'm10_theorem_minor_segment': 'LabM10TheoremViewer',
  'm10_theorem_cyclic_quad': 'LabM10TheoremViewer',
  // Class 11 Chemistry

  // Class 11 Physics

  // Class 11 Computer Science

  // Class 11 Biology

  // Class 12 Biology

  // Class 12 Physics

  // Class 12 Chemistry

  // Class 12 Computer Science

  // Class 11 Mathematics Theorems
  'm11_theorem_complex_magnitude': 'LabM11TheoremViewer',
  'm11_theorem_complex_inverse_polar': 'LabM11TheoremViewer',
  'm11_theorem_complex_division_polar': 'LabM11TheoremViewer',
  'm11_theorem_determinant_transpose': 'LabM11TheoremViewer',
  'm11_theorem_determinant_interchange': 'LabM11TheoremViewer',
  'm11_theorem_determinant_identical': 'LabM11TheoremViewer',
  'm11_theorem_parallelogram_diagonals': 'LabM11TheoremViewer',
  'm11_theorem_triangle_midpoint': 'LabM11TheoremViewer',
  'm11_theorem_trapezium_midpoint': 'LabM11TheoremViewer',
  'm11_theorem_geometric_sum': 'LabM11TheoremViewer',
  'm11_theorem_arithmetico_geometric_sum': 'LabM11TheoremViewer',
  'm11_theorem_remainder': 'LabM11TheoremViewer',
  'm11_theorem_factor': 'LabM11TheoremViewer',
  'm11_theorem_combination': 'LabM11TheoremViewer',
  'm11_theorem_binomial': 'LabM11TheoremViewer',
  'm11_theorem_fundamental_trig': 'LabM11TheoremViewer',
  'm11_theorem_trig_identities': 'LabM11TheoremViewer',

  // Class 12 Mathematics Theorems
  'm12_theorem_power_rule': 'LabM12TheoremViewer',
  'm12_theorem_sin_derivative': 'LabM12TheoremViewer',
  'm12_theorem_inverse_trig_derivatives': 'LabM12TheoremViewer',
  'm12_theorem_basic_integrals': 'LabM12TheoremViewer',
  'm12_theorem_substitution_integrals': 'LabM12TheoremViewer',
  'm12_theorem_fundamental_theorem_calc': 'LabM12TheoremViewer',
  'm12_theorem_concurrency_altitudes': 'LabM12TheoremViewer',
  'm12_theorem_concurrency_bisectors': 'LabM12TheoremViewer',
  'm12_theorem_concurrency_medians': 'LabM12TheoremViewer',
  'm12_theorem_homogeneous_second_degree': 'LabM12TheoremViewer',
  'm12_theorem_circle_general': 'LabM12TheoremViewer',
  'm12_theorem_circle_tangent': 'LabM12TheoremViewer',
  'm12_theorem_parabola_standard': 'LabM12TheoremViewer',
  'm12_theorem_parabola_tangent': 'LabM12TheoremViewer',
  'm12_theorem_ellipse_standard': 'LabM12TheoremViewer',
  'm12_theorem_hyperbola_standard': 'LabM12TheoremViewer',

  // Class 12 Mathematics

  // Class 6 Science
  'c6s_1_1': 'LabS6Microscope',
  'c6s_1_3': 'LabS6Unit1Projects',
  'c6s_2_1': 'LabS6VegetativePropagation',
  'c6s_3_1': 'LabS6FatDetection',
  'c6s_3_2': 'LabS6BalancedDiet',
  'c6s_4_1': 'LabS6DigestionMechanics',
  'c6s_4_2': 'LabS6AlimentaryCanal',
  'c6s_4_4': 'LabS6LungModel',
  'c6s_5_1': 'LabS6ParticleSimulation',
  'c6s_6_1': 'LabS6MolecularBuilder',
  'c6s_6_2': 'LabS6ElementsCompounds',
  'c6s_7_1': 'LabS6Separation',
  'c6s_7_2': 'LabS6SolutionInvestigation',
  'c6s_8_1': 'LabS6EnergyTransformation',
  'c6s_8_2': 'LabS6EnergyProjects',
  'c6s_9_1': 'LabS6CircuitBuilder',
  'c6s_9_2': 'LabS6ConductorsInsulators',
  'c6s_10_1': 'LabS6Magnetism',
  'c6s_11_1': 'LabS6PlantGrowth',
  'c6s_12_1': 'LabS6SolarSystemBuilder',
  'c6s_12_2': 'LabS6EverydayTech',
  // (Class 8 Science mappings above are now correct, duplicates removed)
  'cs10_3_2': 'LabCS10JSAlgorithms',
  'cs10_3_3': 'LabCS10DynamicList',
  'cs10_4_2': 'LabCS10ChurnPrediction',
  'cs10_8_2': 'LabCS10Financials',
  'cs10_8_3': 'LabCS10BusinessPitch',
  'm10_7_1': 'LabM10Vectors',
  'm10_9_1': 'LabM10ChordBisectors',
  'm10_9_2': 'LabM10EqualChords',
  'm10_10_1': 'LabM10TangentProperties',
  'm10_10_2': 'LabM10CircleAngles',
  'm10_11_1': 'LabM10CircleBasics',
  'm10_11_2': 'LabM10TangentConstruction',
  'm10_11_3': 'LabM10CommonTangents',
  'm10_12_1': 'LabM10StatisticsWheels',
  'm10_app_1': 'LabM10ComplexApplications',
  'm10_app_2': 'LabM10QuadraticApplications',
  'm10_app_3': 'LabM10MatrixApplications',
  'm10_app_4': 'LabM10InequalityApplications',
  'm10_app_5': 'LabM10FractionApplications',
  'm10_app_6': 'LabM10FunctionApplications',
  'm10_app_7': 'LabM10VectorApplications',
  'm10_app_8': 'LabM10TrigApplications',
  'm10_app_9': 'LabM10CircleApplications',
  'm10_app_12': 'LabM10StatsApplications',
  'b10_1': 'LabB10DigestiveSystem',
  'b10_2': 'LabB10BloodSmear',
  'b10_3': 'LabB10RespiratorySystem',
  'b10_4': 'LabB10KidneyDissection',
  'b10_5': 'LabB10NervousSystem',
  'b10_7': 'LabB10Genetics',
  'b10_11': 'LabB10Biostatistics',
  'b9_1': 'LabB9Biodiversity',
  'b9_3': 'LabB9Microscopy',
  'b9_6': 'LabB9Biochemistry',
  'b9_7': 'LabB9Enzymes',
  'b9_8': 'LabB9PlantPhysiology',
  'b9_9': 'LabB9PlantReproduction',
  'c9_1': 'LabC9StatesOfMatter',
  'c9_2': 'LabC9AtomicStructure',
  'c9_3': 'LabC9Electrochemistry',
  'c9_4': 'LabC9EnvironmentalChem',
  'c9_5': 'LabC9OrganicChem',
  'c9_6': 'LabC9SeparationTech',
  'c9_7': 'LabC9QualitativeAnalysis',
  'p9_1': 'LabP9MeasurementTools',
  'p9_2': 'LabP9VolumeDensity',
  'p9_3': 'LabP9Kinematics',
  'p9_4': 'LabP9Inertia',
  'p9_5': 'LabP9Friction',
  'p9_6': 'LabP9Pressure',
  'p9_7': 'LabP9Springs',
  'p9_8': 'LabP9MagnetismFields',
  'p9_9': 'LabP9MagnetismInduction',
  'p9_10': 'LabP9EverydayPhysics',
  'cs9_1': 'LabCS9ComputerSystems',
  'cs9_2': 'LabCS9Algorithms',
  'cs9_3': 'LabCS9WebBasics',
  'cs9_4': 'LabCS9JavaScript',
  'cs9_5': 'LabCS9WebProjects',
  'cs9_6': 'LabCS9DataAnalysis',
  'cs9_7': 'LabCS9AIApplications',
  'cs9_8': 'LabCS9CyberSafety',
  'cs9_9': 'LabCS9Entrepreneurship',
  'm9_1': 'LabM9RealNumbers',
  'm9_2': 'LabM9Logarithms',
  'm9_3': 'LabM9SetsRelations',
  'm9_4': 'LabM9AlgebraicManipulation',
  'm9_5': 'LabM9Trigonometry',
  'm9_6': 'LabM9CoordinateGeometry',
  'm9_7': 'LabM9LinearGraphs',
  'm9_8': 'LabM9GeometryPolygons',
  'm9_9': 'LabM9BasicStatistics',
  'c11_1': 'LabC11AtomicStructure',
  'c11_2': 'LabC11MolecularBonding',
  'c11_3': 'LabC11Stoichiometry',
  'c11_4': 'LabC11PhasesOfMatter',
  'c11_5': 'LabC11EnergeticsKinetics',
  'c11_6': 'LabC11IndustrialEquilibrium',
  'c11_7': 'LabC11AcidsBases',
  'c11_8': 'LabC11EnvironmentalChem',
  'c11_9': 'LabC11OrganicAnalysis',
  'c11_10': 'LabC11OrganicSynthesis',
  'p11_1': 'LabP11PhysicalQuantities',
  'p11_2': 'LabP11Vectors',
  'p11_3': 'LabP11TranslatoryMotion',
  'p11_4': 'LabP11RotationalMotion',
  'p11_5': 'LabP11WorkEnergy',
  'p11_6': 'LabP11FluidMechanics',
  'p11_7': 'LabP11Solids',
  'p11_8': 'LabP11Thermodynamics',
  'p11_9': 'LabP11Waves',
  'p11_10': 'LabP11Electrostatics',
  'p11_11': 'LabP11Electricity',
  'p11_12': 'LabP11Electromagnetism',
  'p11_13': 'LabP11ModernPhysics',
  'cs11_1': 'LabCS11SystemsNetworks',
  'cs11_2': 'LabCS11Algorithms',
  'cs11_3': 'LabCS11Python',
  'cs11_4': 'LabCS11DataScience',
  'cs11_5': 'LabCS11Applications',
  'cs11_6': 'LabCS11Impacts',
  'cs11_7': 'LabCS11Research',
  'cs11_8': 'LabCS11ProductDev',
  'b11_1': 'LabB11Cytology',
  'b11_2': 'LabB11Biomolecules',
  'b11_3': 'LabB11Enzymes',
  'b11_4': 'LabB11Bioenergetics',
  'b11_5': 'LabB11Microbiology',
  'b11_6': 'LabB11Fungi',
  'b11_7': 'LabB11PlantPhysiology',
  'b11_8': 'LabB11Inheritance',
  'b11_9': 'LabB11Genetics',
  'b12_1': 'LabB12Digestive',
  'b12_2': 'LabB12Cardiorespiratory',
  'b12_3': 'LabB12Urinary',
  'b12_4': 'LabB12NeuroEndocrine',
  'b12_5': 'LabB12Skeletal',
  'b12_6': 'LabB12Immunity',
  'b12_7': 'LabB12Biotechnology',
  'b12_8': 'LabB12StructuralStats',
  'b12_9': 'LabB12PharmacologyEcology',
  'm11_1': 'LabM11ComplexNumbers',
  'm11_2': 'LabM11Matrices',
  'm11_3': 'LabM11Vectors',
  'm11_4': 'LabM11SequencesSeries',
  'm11_5': 'LabM11Polynomials',
  'm11_6': 'LabM11Permutations',
  'm11_7': 'LabM11BinomialInduction',
  'm11_8': 'LabM11Trigonometry',
  'm12_1': 'LabM12Derivatives',
  'm12_2': 'LabM12Integration',
  'm12_3': 'LabM12DifferentialEq',
  'm12_4': 'LabM12Conics',
  'm12_5': 'LabM12AnalyticalGeometry',
  'm12_6': 'LabM12Kinematics',
  'm12_7': 'LabM12Functions',
  'm12_8': 'LabM12InverseTrig',
  'p12_1': 'LabP12Gravitation',
  'p12_2': 'LabP12ThermoMechanics',
  'p12_3': 'LabP12SHM',
  'p12_4': 'LabP12Diffraction',
  'p12_5': 'LabP12ElectricPotential',
  'p12_6': 'LabP12AlternatingCurrent',
  'p12_7': 'LabP12QuantumNuclear',
  'p12_8': 'LabP12CosmologyClimate',
  'p12_9': 'LabP12MedicalImaging',
  'p12_capstone_solar': 'LabP12SolarCell',

  // Class 11 Physics Derivations
  'p11_deriv_dimensional_wavelength': 'LabP11DerivationDimensionalWavelength',
  'p11_deriv_dimensional_pendulum': 'LabP11DerivationDimensionalPendulum',
  'p11_deriv_rectangular_components': 'LabP11DerivationRectangularComponents',
  'p11_deriv_first_equation': 'LabP11DerivationFirstEquation',
  'p11_deriv_second_equation': 'LabP11DerivationSecondEquation',
  'p11_deriv_third_equation': 'LabP11DerivationThirdEquation',
  'p11_deriv_projectile_height': 'LabP11DerivationProjectileHeight',
  'p11_deriv_projectile_range': 'LabP11DerivationProjectileRange',
  'p11_deriv_elastic_collision': 'LabP11DerivationElasticCollision',
  'p11_deriv_linear_angular': 'LabP11DerivationLinearAngular',
  'p11_deriv_centripetal_acceleration': 'LabP11DerivationCentripetalAcceleration',
  'p11_deriv_kinetic_energy': 'LabP11DerivationKineticEnergyDerivation',
  'p11_deriv_archimedes': 'LabP11DerivationArchimedesUpthrust',
  'p11_deriv_continuity': 'LabP11DerivationContinuityEquation',
  'p11_deriv_bernoulli': 'LabP11DerivationBernoulliEquation',
  'p11_deriv_carnot_efficiency': 'LabP11DerivationCarnotEfficiency',
  'p11_deriv_doppler_listener_towards': 'LabP11DerivationDopplerListenerTowards',
  'p11_deriv_stationary_waves_string': 'LabP11DerivationStationaryWavesString',
  'p11_deriv_electric_field_point': 'LabP11DerivationElectricFieldPoint',
  'p11_deriv_drift_velocity': 'LabP11DerivationDriftVelocity',
  'p11_deriv_magnetic_force': 'LabP11DerivationMagneticForce',
  'p11_deriv_faraday_law': 'LabP11DerivationFaradayLawDerivation',
  'p11_deriv_projectile_time_flight': 'LabP11DerivationProjectileTimeFlight',
  'p11_deriv_angular_momentum': 'LabP11DerivationAngularMomentum',
  'p11_deriv_torque_inertia': 'LabP11DerivationTorqueInertia',
  'p11_deriv_artificial_gravity': 'LabP11DerivationArtificialGravity',
  'p11_deriv_terminal_velocity': 'LabP11DerivationTerminalVelocity',
  'p11_deriv_resistance_series': 'LabP11DerivationResistanceSeries',
  'p11_deriv_resistance_parallel': 'LabP11DerivationResistanceParallel',
  'p11_deriv_venturi_meter': 'LabP11DerivationVenturiMeter',
  'p11_deriv_elastic_potential_energy': 'LabP11DerivationElasticPotentialEnergy',
  'p11_deriv_work_done_gas': 'LabP11DerivationWorkDoneGas',
  'p11_deriv_cop_refrigerator': 'LabP11DerivationCopRefrigerator',
  'p11_deriv_doppler_listener_away': 'LabP11DerivationDopplerListenerAway',
  'p11_deriv_doppler_source_towards': 'LabP11DerivationDopplerSourceTowards',
  'p11_deriv_stationary_waves_air_column': 'LabP11DerivationStationaryWavesAirColumn',
  'p11_deriv_potential_gradient': 'LabP11DerivationPotentialGradient',
  'p11_deriv_maximum_power_output': 'LabP11DerivationMaximumPowerOutput',
  'p11_deriv_wheatstone_bridge': 'LabP11DerivationWheatstoneBridge',
  'p11_deriv_force_between_conductors': 'LabP11DerivationForceBetweenConductors',
  'p11_deriv_charged_particle_b_field': 'LabP11DerivationChargedParticleBField',
  'p11_deriv_velocity_selector': 'LabP11DerivationVelocitySelector',
  'p11_deriv_doppler_source_away': 'LabP11DerivationDopplerSourceAway',
  'p11_deriv_potentiometer': 'LabP11DerivationPotentiometer',
  'p11_deriv_dirac_momentum': 'LabP11DerivationDiracMomentum',

  // Class 12 Physics Derivations
  'p12_deriv_gravitation_law': 'LabP12DerivationGravitationLaw',
  'p12_deriv_g_on_surface': 'LabP12DerivationGOnSurface',
  'p12_deriv_g_variation': 'LabP12DerivationGWithAltitude',
  'p12_deriv_orbital_velocity': 'LabP12DerivationOrbitalVelocity',
  'p12_deriv_geostationary': 'LabP12DerivationGeostationaryOrbit',
  'p12_deriv_absolute_gpe': 'LabP12DerivationAbsoluteGPE',
  'p12_deriv_gravitational_potential': 'LabP12DerivationGravPotential',
  'p12_deriv_ideal_gas_pressure': 'LabP12DerivationIdealGasPressure',
  'p12_deriv_pressure_ke': 'LabP12DerivationPressureKE',
  'p12_deriv_temperature_ke': 'LabP12DerivationTemperatureKE',
  'p12_deriv_rms_speed': 'LabP12DerivationRMSSpeed',
  'p12_deriv_shm_mass_spring': 'LabP12DerivationSHMMassSpring',
  'p12_deriv_shm_displacement': 'LabP12DerivationSHMDisplacement',
  'p12_deriv_simple_pendulum': 'LabP12DerivationSimplePendulum',
  'p12_deriv_shm_energy': 'LabP12DerivationSHMEnergy',
  'p12_deriv_youngs_double_slit': 'LabP12DerivationYoungsDoubleSlit',
  'p12_deriv_diffraction_grating': 'LabP12DerivationDiffractionGrating',
  'p12_deriv_electric_potential_point': 'LabP12DerivationElectricPotentialPoint',
  'p12_deriv_capacitance': 'LabP12DerivationCapacitancePP',
  'p12_deriv_equivalent_capacitance': 'LabP12DerivationEquivalentCapacitance',
  'p12_deriv_capacitor_energy': 'LabP12DerivationCapacitorEnergy',
  'p12_deriv_rc_circuit': 'LabP12DerivationRCCircuit',
  'p12_deriv_ac_power': 'LabP12DerivationACPower',
  'p12_deriv_inductive_reactance': 'LabP12DerivationInductiveReactance',
  'p12_deriv_capacitive_reactance': 'LabP12DerivationCapacitiveReactance',
  'p12_deriv_impedance': 'LabP12DerivationImpedanceRLRC',
  'p12_deriv_photoelectric': 'LabP12DerivationPhotoelectricEffect',
  'p12_deriv_de_broglie': 'LabP12DerivationDeBroglieWavelength',
  'p12_deriv_mass_defect': 'LabP12DerivationMassDefect',
  'p12_deriv_decay_law': 'LabP12DerivationDecayLaw',
  'p12_deriv_half_life': 'LabP12DerivationHalfLifeRelation',
  'p12_deriv_wien_law': 'LabP12DerivationWiensDisplacement',
  'p12_deriv_hubble_law': 'LabP12DerivationHubbleLaw',
  'p12_deriv_coriolis': 'LabP12DerivationCoriolisForce',
  'p12_deriv_newton_cannon': 'LabP12DerivationNewtonCannonball',

  'c12_1': 'LabC12Electrochemistry',
  'c12_2': 'LabC12EquilibriumAcidBase',
  'c12_3': 'LabC12TransitionMetals',
  'c12_4': 'LabC12OrganicSynthesis',
  'c12_5': 'LabC12Biochemistry',
  'c12_6': 'LabC12SpectroscopyChromatography',
  'c12_7': 'LabC12Medicine',
  'c12_8': 'LabC12Agriculture',
  'c12_9': 'LabC12IndustryMaterials',
  'cs12_1': 'LabCS12HCI',
  'cs12_2': 'LabCS12DataStructures',
  'cs12_3': 'LabCS12Programming',
  'cs12_4': 'LabCS12MachineLearning',
  'cs12_5': 'LabCS12DeepLearning',
  'cs12_6': 'LabCS12IoTCloud',
  'cs12_7': 'LabCS12Cybersecurity',
  'cs12_8': 'LabCS12DigitalLiteracy',
  'cs12_9': 'LabCS12Entrepreneurship',

  // Class 6 Math
  'm6_1': 'LabM6Factors',
  'm6_2': 'LabM6Integers',
  'm6_3': 'LabM6Proportions',
  'm6_4': 'LabM6Sets',
  'm6_5': 'LabM6Algebra',
  'm6_6': 'LabM6Geometry',
  'm6_7': 'LabM6Mensuration',
  'm6_8': 'LabM6Data',

  // Class 7 Math
  'm7_1': 'LabM7RationalSquares',
  'm7_2': 'LabM7ProportionsKinematics',
  'm7_3': 'LabM7FinancialArithmetic',
  'm7_4': 'LabM7SetsAlgebra',
  'm7_5': 'LabM7Transformations',
  'm7_6': 'LabM7Equations',
  'm7_7': 'LabM7GeometryDrafting',
  'm7_8': 'LabM7MensurationData',

  // Class 8 Math
  'm8_1': 'LabM8RealEstimation',
  'm8_2': 'LabM8RootsFinance',
  'm8_3': 'LabM8SetsAlgebra',
  'm8_4': 'LabM8EquationsInequalities',
  'm8_5': 'LabM8Transformations',
  'm8_6': 'LabM8GeometryTriangles',
  'm8_7': 'LabM8Mensuration',
  'm8_8': 'LabM8DataProbability',

  // Class 6 English
  'e6_1': 'LabE6NounsPronouns',
  'e6_2': 'LabE6SentencesAffixes',
  'e6_3': 'LabE6VerbsAdverbs',
  'e6_4': 'LabE6PrepositionsStructure',
  'e6_5': 'LabE6ClausesConjunctions',
  'e6_6': 'LabE6TensesPunctuation',
  'e6_7': 'LabE6FiguresOfSpeech',
  'e6_8': 'LabE6WritingMechanics',

  // Class 7 English
  'e7_1': 'LabE7ArticlesAdjectives',
  'e7_2': 'LabE7FiguresOfSpeech',
  'e7_3': 'LabE7PrepositionsModals',
  'e7_4': 'LabE7VerbsCollocations',
  'e7_5': 'LabE7Tenses',
  'e7_6': 'LabE7Conjunctions',
  'e7_7': 'LabE7PronounsClauses',
  'e7_8': 'LabE7VocabPunctuation',

  // Class 8 English
  'e8_1': 'LabE8NounsPhonetics',
  'e8_2': 'LabE8PronounsMorphology',
  'e8_3': 'LabE8AdjectivesPoetry',
  'e8_4': 'LabE8VerbsModals',
  'e8_5': 'LabE8AdverbsPrepositions',
  'e8_6': 'LabE8ConjunctionsClauses',
  'e8_7': 'LabE8TensesVoice',
  'e8_8': 'LabE8NarrationConditionals',

  // Class 9 English
  'c9e_1': 'LabE9PartsOfSpeech',
  'c9e_2': 'LabE9Verbals',
  'c9e_3': 'LabE9TensesAgreement',
  'c9e_4': 'LabE9Phrases',
  'c9e_5': 'LabE9PrepositionsConjunctions',
  'c9e_6': 'LabE9SentenceStructure',
  'c9e_7': 'LabE9Narration',
  'c9e_8': 'LabE9PunctuationVocabulary',
  
  // Class 10 English
  'c10e_1': 'LabE10NounsPronouns',
  'c10e_2': 'LabE10VerbsAdjectives',
  'c10e_3': 'LabE10AdverbsPrepositions',
  'c10e_4': 'LabE10ConjunctionsTenses',
  'c10e_5': 'LabE10ModalsConditionals',
  'c10e_6': 'LabE10PhrasesClauses',
  'c10e_7': 'LabE10SentenceNarration',
  'c10e_8': 'LabE10VocabularyStylistics',
  
  // Class 11 English
  'c11e_1': 'LabE11NounsPronouns',
  'c11e_2': 'LabE11AdjectivesAdverbs',
  'c11e_3': 'LabE11PrepositionsConjunctions',
  'c11e_4': 'LabE11VerbsModals',
  'c11e_5': 'LabE11TensesVerbals',
  'c11e_6': 'LabE11PhrasesClauses',
  'c11e_7': 'LabE11SentenceStructure',
  'c11e_8': 'LabE11VocabularyStylistics',

  // Class 12 English
  'e12-1': 'LabE12NounsPronouns',
  'e12-2': 'LabE12AdjectivesAdverbs',
  'e12-3': 'LabE12PrepositionsConjunctions',
  'e12-4': 'LabE12VerbsModals',
  'e12-5': 'LabE12TensesVerbals',
  'e12-6': 'LabE12PhrasesClauses',
  'e12-7': 'LabE12SentenceStructure',
  'e12-8': 'LabE12VocabularyStylistics',


};

// Get component by module ID
export const getLabComponent = (moduleId: string): React.LazyExoticComponent<React.ComponentType<any>> | null => {
  const componentName = moduleIdToComponent[moduleId];
  if (!componentName) return null;
  return labComponents[componentName] || null;
}

