export interface SliderVariable {
  key: string;
  label: string;
  min: number;
  max: number;
  step: number;
  default: number;
  unit: string;
}

export interface ComputedVariable {
  key: string;
  label: string;
  expr: string; // e.g. "v0 * t - 0.5 * g * t^2"
  unit: string;
}

export interface CanvasPrimitive {
  id: string;
  type: string; // Flexible type generated by AI
  shape?: 'path' | 'circle' | 'rect' | 'text' | 'line' | 'polygon' | string;
  label?: string;
  description?: string; // AI-generated description for this component
  color?: string;
  fill?: string;
  stroke?: string;
  pathData?: string; // SVG path commands or custom drawing data
  points?: Array<{ x: number; y: number }>;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  radius?: number;
  xExpr?: string; // Math expression for X position
  yExpr?: string; // Math expression for Y position
  radiusExpr?: string;
  lengthExpr?: string;
  angleExpr?: string;
  vxExpr?: string;
  vyExpr?: string;
  valueExpr?: string;
  highlightExpr?: string; // Highlight condition (e.g., "index == 1")
  connections?: string[]; // Component connection IDs
}

export interface DerivationStepSpec {
  stepNumber: number;
  label: string;
  formula: string;
  explanation: string;
}

export interface QuizItemSpec {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  hint: string;
  explanation: string;
}

export interface AISimulationSpec {
  id: string;
  title: string;
  description: string;
  subject: 'Physics' | 'Chemistry' | 'Biology' | 'Mathematics' | 'Computer Science';
  classLevel: string; // e.g. 'Class 9', 'Class 10', 'Class 11', 'Class 12', 'General'
  category: string;
  createdAt: number;
  
  theory: {
    overview: string;
    keyConcepts: string[];
    realWorldApplication: string;
    formulaSummary: string;
  };

  variables: SliderVariable[];
  computedVars: ComputedVariable[];
  visualType?: 'brain' | 'eye' | 'kidney' | 'heart' | 'cell' | 'neuron' | 'beaker' | 'pendulum' | 'spring' | 'projectile' | 'wave' | 'circuit' | 'english_syntax' | string;
  canvasPrimitives?: CanvasPrimitive[];
  renderCode?: string; // Optional custom HTML5 Canvas JS code generated by AI
  
  chart: {
    xAxisVar: string; // e.g. 't' or variable key
    yAxisExpr: string; // e.g. 'y' or formula
    xLabel: string;
    yLabel: string;
  };

  derivation?: {
    title: string;
    steps: DerivationStepSpec[];
  };

  quiz: QuizItemSpec[];
}
