/**
 * English → Urdu (نستعلیق) meanings dictionary
 * Used across Class 6, 7, and 8 English labs to display Urdu meanings with TTS.
 *
 * Display uses Urdu script (نستعلیق).
 * TTS uses Roman Urdu transliteration (for when no Urdu voice is installed on the system).
 */

// ============================================================
// URDU SCRIPT MEANINGS (for display in the UI)
// ============================================================

export const WORD_MEANINGS: Record<string, string> = {
  // === Nouns ===
  happiness: 'خوشی',
  team: 'ٹیم',
  London: 'لندن',
  dog: 'کتا',
  bunch: 'گچھا',
  courage: 'ہمت',
  Ganges: 'گنگا',
  book: 'کتاب',
  table: 'میز',
  car: 'گاڑی',
  apple: 'سیب',
  school: 'اسکول',
  city: 'شہر',
  mountain: 'پہاڑ',
  tree: 'درخت',
  flower: 'پھول',
  animal: 'جانور',
  bird: 'پرندہ',
  ocean: 'سمندر',
  star: 'ستارہ',
  house: 'گھر',
  chair: 'کرسی',
  door: 'دروازہ',
  window: 'کھڑکی',
  food: 'کھانا',
  water: 'پانی',
  fire: 'آگ',
  earth: 'زمین',
  air: 'ہوا',
  sun: 'سورج',
  moon: 'چاند',
  information: 'معلومات',
  library: 'کتب خانہ',
  bravery: 'بہادری',
  elephant: 'ہاتھی',
  dragon: 'اژدہا',
  alien: 'اجنبی',
  adventure: 'مہم جوئی',
  journey: 'سفر',
  story: 'کہانی',
  secret: 'راز',
  mystery: 'پراسرار',
  treasure: 'خزانہ',
  power: 'طاقت',
  energy: 'توانائی',
  strength: 'طاقت',
  wisdom: 'دانائی',
  knowledge: 'علم',
  idea: 'خیال',
  dream: 'خواب',
  memory: 'یاداشت',
  future: 'مستقبل',
  past: 'ماضی',
  present: 'حال',
  people: 'لوگ',
  person: 'شخص',
  place: 'جگہ',
  thing: 'چیز',
  time: 'وقت',
  name: 'نام',
  world: 'دنیا',
  life: 'زندگی',
  head: 'سر',
  hand: 'ہاتھ',
  eye: 'آنکھ',
  heart: 'دل',
  body: 'جسم',
  face: 'چہرہ',
  foot: 'پاؤں',
  arm: 'بازو',
  leg: 'ٹانگ',
  child: 'بچہ',
  baby: 'بچہ',
  parent: 'والدین',
  mother: 'ماں',
  father: 'باپ',
  brother: 'بھائی',
  sister: 'بہن',
  son: 'بیٹا',
  daughter: 'بیٹی',
  husband: 'شوہر',
  wife: 'بیوی',
  king: 'بادشاہ',
  queen: 'ملکہ',
  prince: 'شہزادہ',
  princess: 'شہزادی',
  hero: 'ہیرو',
  villain: 'ولن',
  giant: 'دیو',
  monster: 'عفریت',
  wizard: 'جادوگر',
  fairy: 'پری',
  ghost: 'بھوت',
  robot: 'روبوٹ',
  machine: 'مشین',
  computer: 'کمپیوٹر',
  message: 'پیغام',
  tool: 'آلہ',
  weapon: 'ہتھیار',
  bridge: 'پل',
  tower: 'مینار',
  castle: 'قلعہ',
  palace: 'محل',
  temple: 'مندر',
  church: 'گرجا',
  mosque: 'مسجد',
  market: 'بازار',
  hospital: 'ہسپتال',
  village: 'گاؤں',
  country: 'ملک',
  space: 'خلا',
  planet: 'سیارہ',
  island: 'جزیرہ',
  forest: 'جنگل',
  desert: 'صحرا',
  cave: 'غار',
  stone: 'پتھر',
  rock: 'چٹان',
  gold: 'سونا',
  silver: 'چاندی',
  iron: 'لوہا',
  wood: 'لکڑی',
  glass: 'شیشہ',
  paper: 'کاغذ',
  color: 'رنگ',
  colour: 'رنگ',
  shape: 'شکل',
  size: 'سائز',
  number: 'نمبر',
  letter: 'حرف',
  word: 'لفظ',
  sound: 'آواز',
  music: 'موسیقی',
  song: 'گانا',
  picture: 'تصویر',
  map: 'نقشہ',
  flag: 'جھنڈا',
  game: 'کھیل',
  sport: 'کھیل',
  player: 'کھلاڑی',
  winner: 'فاتح',
  prize: 'انعام',
  gift: 'تحفہ',
  money: 'پیسہ',
  coin: 'سکہ',
  bag: 'بیگ',
  box: 'ڈبہ',
  bottle: 'بوتل',
  cup: 'پیالہ',
  plate: 'پلیٹ',
  spoon: 'چمچ',
  knife: 'چھری',
  fork: 'کانٹا',
  bed: 'بستر',
  room: 'کمرہ',
  wall: 'دیوار',
  floor: 'فرش',
  roof: 'چھت',
  step: 'قدم',
  path: 'راستہ',
  gate: 'گیٹ',
  key: 'چابی',
  lock: 'تالا',
  bell: 'گھنٹی',
  clock: 'گھڑی',
  lamp: 'چراغ',
  shadow: 'سایہ',
  cloud: 'بادل',
  rain: 'بارش',
  snow: 'برف',
  wind: 'ہوا',
  storm: 'طوفان',
  thunder: 'گرج',
  lightning: 'بجلی',
  sky: 'آسمان',
  ground: 'زمین',
  hill: 'پہاڑی',
  valley: 'وادی',
  lake: 'جھیل',
  sea: 'سمندر',
  ship: 'جہاز',
  boat: 'کشتی',
  train: 'ٹرین',
  bus: 'بس',
  bicycle: 'سائیکل',
  wheel: 'پہیہ',
  engine: 'انجن',
  pilot: 'پائلٹ',
  driver: 'ڈرائیور',
  captain: 'کپتان',
  soldier: 'سپاہی',
  police: 'پولیس',
  thief: 'چور',
  robber: 'ڈاکو',
  judge: 'جج',
  lawyer: 'وکیل',
  scientist: 'سائنسدان',
  engineer: 'انجینئر',
  artist: 'فنکار',
  writer: 'مصنف',
  poet: 'شاعر',
  farmer: 'کسان',
  sailor: 'ملاح',
  guard: 'گارڈ',
  servant: 'نوکر',
  master: 'آقا',
  owner: 'مالک',
  guest: 'مہمان',
  stranger: 'اجنبی',
  neighbor: 'پڑوسی',
  neighbour: 'پڑوسی',
  enemy: 'دشمن',
  friend: 'دوست',
  family: 'خاندان',
  group: 'گروپ',
  crowd: 'ہجوم',
  line: 'لائن',
  circle: 'دائرہ',
  corner: 'کونا',
  edge: 'کنارہ',
  center: 'مرکز',
  middle: 'درمیان',
  top: 'اوپر',
  bottom: 'نیچے',
  front: 'سامنے',
  back: 'پیچھے',
  side: 'طرف',
  left: 'بائیں',
  right: 'دائیں',
  inside: 'اندر',
  outside: 'باہر',
  morning: 'صبح',
  evening: 'شام',
  night: 'رات',
  noon: 'دوپہر',
  midnight: 'آدھی رات',
  dawn: 'فجر',
  today: 'آج',
  tomorrow: 'کل',
  yesterday: 'کل',
  week: 'ہفتہ',
  month: 'مہینہ',
  year: 'سال',
  season: 'موسم',
  spring: 'بہار',
  summer: 'گرمی',
  autumn: 'خزاں',
  winter: 'سردی',
  temperature: 'درجہ حرارت',
  degree: 'ڈگری',
  meter: 'میٹر',
  kilometer: 'کلومیٹر',
  kilogram: 'کلوگرام',
  liter: 'لیٹر',
  piece: 'ٹکڑا',
  pair: 'جوڑا',
  set: 'سیٹ',
  list: 'فہرست',
  rule: 'قاعدہ',
  law: 'قانون',
  order: 'حکم',
  example: 'مثال',
  lesson: 'سبق',
  class: 'کلاس',
  grade: 'درجہ',
  course: 'کورس',
  topic: 'موضوع',
  test: 'ٹیسٹ',
  result: 'نتیجہ',
  score: 'اسکور',
  mark: 'نشان',
  question: 'سوال',
  reason: 'وجہ',
  cause: 'سبب',
  effect: 'اثر',
  difference: 'فرق',
  choice: 'انتخاب',
  decision: 'فیصلہ',
  plan: 'منصوبہ',
  goal: 'ہدف',
  target: 'نشانہ',
  problem: 'مسئلہ',
  solution: 'حل',
  method: 'طریقہ',
  system: 'نظام',
  process: 'عمل',
  level: 'سطح',
  part: 'حصہ',
  whole: 'پورا',
  half: 'آدھا',
  quarter: 'چوتھائی',
  rest: 'باقی',
  lot: 'بہت',
  bit: 'تھوڑا',
  fact: 'حقیقت',
  truth: 'سچ',
  lie: 'جھوٹ',
  opinion: 'رائے',
  thought: 'سوچ',
  feeling: 'احساس',
  emotion: 'جذبہ',
  action: 'عمل',
  event: 'تقریب',
  situation: 'صورتحال',
  condition: 'حالت',
  position: 'پوزیشن',
  direction: 'سمت',
  distance: 'فاصلہ',
  length: 'لمبائی',
  height: 'اونچائی',
  width: 'چوڑائی',
  depth: 'گہرائی',
  weight: 'وزن',
  speed: 'رفتار',
  rate: 'شرح',
  price: 'قیمت',
  cost: 'لاگت',
  value: 'قدر',
  quality: 'معیار',
  type: 'قسم',
  sort: 'قسم',
  way: 'طریقہ',
  meaning: 'معنی',
  definition: 'تعریف',
  description: 'وضاحت',
  translation: 'ترجمہ',
  language: 'زبان',
  english: 'انگریزی',
  urdu: 'اردو',
  grammar: 'گرامر',
  vocabulary: 'ذخیرہ الفاظ',
  spelling: 'ہجے',
  pronunciation: 'تلفظ',
  accent: 'لہجہ',
  dialogue: 'مکالمہ',
  conversation: 'گفتگو',
  speech: 'تقریر',
  report: 'رپورٹ',
  essay: 'مضمون',
  composition: 'تعبیر',
  diary: 'ڈائری',
  form: 'فارم',
  chart: 'چارٹ',
  graph: 'گراف',
  diagram: 'خاکہ',
  symbol: 'علامت',
  sign: 'نشان',
  code: 'کوڈ',
  clue: 'سراغ',
  hint: 'اشارہ',
  tip: 'مشورہ',
  advice: 'مشورہ',
  luck: 'قسمت',
  chance: 'موقع',
  opportunity: 'موقع',
  risk: 'خطرہ',
  danger: 'خطرہ',
  safety: 'حفاظت',
  protection: 'تحفظ',
  war: 'جنگ',
  peace: 'امن',
  battle: 'لڑائی',
  victory: 'فتح',
  defeat: 'شکست',
  attack: 'حملہ',
  defense: 'دفاع',
  army: 'فوج',
  force: 'طاقت',

  // === Adjectives ===
  happy: 'خوش',
  beautiful: 'خوبصورت',
  big: 'بڑا',
  small: 'چھوٹا',
  tall: 'لمبا',
  short: 'چھوٹا',
  fast: 'تیز',
  slow: 'دھیما',
  hot: 'گرم',
  cold: 'ٹھنڈا',
  new: 'نیا',
  old: 'پرانا',
  good: 'اچھا',
  bad: 'برا',
  shiny: 'چمکدار',
  huge: 'بڑا',
  ferocious: 'خونخوار',
  many: 'بہت',
  some: 'کچھ',
  cheap: 'سستا',
  bossy: 'حکم چلانے والا',
  angry: 'غصہ',
  confused: 'پریشان',
  determined: 'مستقل',
  assertive: 'زبردست',
  brave: 'بہادر',
  clever: 'ہوشیار',
  smart: 'ہوشیار',
  wise: 'عقلمند',
  foolish: 'بے وقوف',
  kind: 'مہربان',
  cruel: 'ظالم',
  gentle: 'نرم',
  rough: 'کھردرا',
  soft: 'نرم',
  hard: 'سخت',
  strong: 'مضبوط',
  weak: 'کمزور',
  rich: 'امیر',
  poor: 'غریب',
  young: 'جوان',
  easy: 'آسان',
  difficult: 'مشکل',
  complex: 'پیچیدہ',
  important: 'اہم',
  necessary: 'ضروری',
  possible: 'ممکن',
  impossible: 'ناممکن',
  correct: 'درست',
  incorrect: 'غلط',
  true: 'سچ',
  false: 'جھوٹ',
  real: 'حقیقی',
  fake: 'جعلی',
  special: 'خاص',
  ordinary: 'عام',
  strange: 'عجیب',
  normal: 'نارمل',
  usual: 'عام',
  rare: 'نایاب',
  different: 'مختلف',
  same: 'ایک جیسا',
  similar: 'ملتا جلتا',
  opposite: 'مخالف',
  clear: 'صاف',
  dirty: 'گندا',
  dark: 'اندھیرا',
  bright: 'روشن',
  light: 'ہلکا',
  heavy: 'بھاری',
  full: 'بھرا',
  empty: 'خالی',
  closed: 'بند',
  long: 'لمبا',
  wide: 'چوڑا',
  narrow: 'تنگ',
  deep: 'گہرا',
  shallow: 'اتھلا',
  high: 'اونچا',
  low: 'نیچا',
  far: 'دور',
  early: 'جلدی',
  late: 'دیر',
  quick: 'تیز',
  ready: 'تیار',
  busy: 'مصروف',
  free: 'آزاد',
  sure: 'یقینی',
  certain: 'یقینی',
  main: 'اہم',
  single: 'واحد',
  double: 'دوگنا',
  extra: 'اضافی',
  last: 'آخری',
  next: 'اگلا',
  first: 'پہلا',
  second: 'دوسرا',
  third: 'تیسرا',
  little: 'تھوڑا',
  much: 'بہت',
  enough: 'کافی',
  great: 'عظیم',
  wonderful: 'شاندار',
  amazing: 'حیرت انگیز',
  fantastic: 'لاجواب',
  excellent: 'بہترین',
  perfect: 'کامل',
  terrible: 'خوفناک',
  pleasant: 'خوشگوار',
  lovely: 'پیارا',
  nice: 'اچھا',
  fine: 'ٹھیک',
  modern: 'جدید',
  ancient: 'قدیم',
  original: 'اصلی',
  popular: 'مقبول',
  famous: 'مشہور',
  unknown: 'نامعلوم',
  various: 'مختلف',
  several: 'کئی',
  specific: 'مخصوص',
  general: 'عام',
  entire: 'پورا',
  total: 'کل',
  complete: 'مکمل',
  natural: 'قدرتی',
  artificial: 'مصنوعی',
  useful: 'مفید',
  useless: 'بیکار',
  careful: 'محتاط',
  dangerous: 'خطرناک',
  safe: 'محفوظ',
  harmful: 'نقصان دہ',
  helpful: 'مددگار',
  colorful: 'رنگین',
  boring: 'بورنگ',
  interesting: 'دلچسپ',
  exciting: 'پرجوش',
  funny: 'مضحکہ',
  sad: 'اداس',
  hungry: 'بھوکا',
  thirsty: 'پیاسا',
  sick: 'بیمار',
  healthy: 'صحت مند',
  alive: 'زندہ',
  dead: 'مردہ',
  alone: 'اکیلا',
  together: 'ایک ساتھ',
  silent: 'خاموش',
  loud: 'اونچا',
  quiet: 'خاموش',
  noisy: 'شور',
  sweet: 'میٹھا',
  sour: 'کھٹا',
  bitter: 'کڑوا',
  salty: 'نمکین',
  spicy: 'مسالہ دار',
  delicious: 'مزیدار',
  fresh: 'تازہ',
  wet: 'گیلا',
  dry: 'خشک',
  smooth: 'ہموار',
  thick: 'موٹا',
  thin: 'پتلا',
  flat: 'چپٹا',
  square: 'مربع',
  straight: 'سیدھا',
  even: 'برابر',
  odd: 'عجیب',
  fair: 'منصفانہ',
  honest: 'ایماندار',
  loyal: 'وفادار',
  polite: 'شائستہ',
  rude: 'بد تمیز',
  generous: 'سخی',
  selfish: 'خود غرض',
  greedy: 'لالچی',
  lazy: 'سست',
  energetic: 'توانا',
  dull: 'پھیکا',
  sharp: 'تیز',
  blunt: 'کند',
  expensive: 'مہنگا',
  valuable: 'قیمتی',
  precious: 'قیمتی',
  intelligent: 'ذہین',
  brilliant: 'ذہین',

  // === Verbs ===
  run: 'دوڑنا',
  eat: 'کھانا',
  sleep: 'سونا',
  read: 'پڑھنا',
  write: 'لکھنا',
  speak: 'بولنا',
  walk: 'چلنا',
  work: 'کام کرنا',
  play: 'کھیلنا',
  swim: 'تیرنا',
  jump: 'کودنا',
  sing: 'گانا',
  dance: 'ناچنا',
  cook: 'پکانا',
  drink: 'پینا',
  give: 'دینا',
  take: 'لینا',
  come: 'آنا',
  go: 'جانا',
  see: 'دیکھنا',
  hear: 'سننا',
  teach: 'سکھانا',
  learn: 'سیکھنا',
  help: 'مدد کرنا',
  love: 'محبت کرنا',
  make: 'بنانا',
  break: 'توڑنا',
  catch: 'پکڑنا',
  bring: 'لانا',
  find: 'ڈھونڈھنا',
  buy: 'خریدنا',
  sell: 'بیچنا',
  talk: 'بات کرنا',
  sit: 'بیٹھنا',
  stand: 'کھڑا ہونا',
  think: 'سوچنا',
  know: 'جاننا',
  want: 'چاہنا',
  need: 'ضرورت ہونا',
  like: 'پسند کرنا',
  ask: 'پوچھنا',
  tell: 'بتانا',
  show: 'دکھانا',
  try: 'کوشش کرنا',
  leave: 'چھوڑنا',
  keep: 'رکھنا',
  let: 'دینا',
  begin: 'شروع کرنا',
  start: 'شروع کرنا',
  stop: 'رکنا',
  finish: 'ختم کرنا',
  open: 'کھولنا',
  close: 'بند کرنا',
  move: 'حرکت کرنا',
  change: 'بدلنا',
  follow: 'پیروی کرنا',
  remember: 'یاد رکھنا',
  forget: 'بھولنا',
  understand: 'سمجھنا',
  believe: 'یقین کرنا',
  agree: 'متعلق ہونا',
  refuse: 'انکار کرنا',
  allow: 'اجازت دینا',
  accept: 'قبول کرنا',
  receive: 'وصول کرنا',
  send: 'بھیجنا',
  call: 'بلانا',
  answer: 'جواب دینا',
  explain: 'وضاحت کرنا',
  describe: 'بیان کرنا',
  draw: 'بنانا',
  paint: 'رنگنا',
  build: 'تعمیر کرنا',
  grow: 'اگانا',
  cut: 'کاٹنا',
  push: 'دھکیلنا',
  pull: 'کھینچنا',
  lift: 'اٹھانا',
  drop: 'گرانا',
  throw: 'پھینکنا',
  hit: 'مارنا',
  kick: 'لات مارنا',
  hold: 'پکڑنا',
  carry: 'اٹھانا',
  put: 'رکھنا',
  rise: 'اٹھنا',
  raise: 'اٹھانا',
  fall: 'گرنا',
  turn: 'مڑنا',
  fly: 'اڑنا',
  drive: 'چلانا',
  ride: 'سوار ہونا',
  visit: 'ملنا',
  meet: 'ملنا',
  arrive: 'پہنچنا',
  reach: 'پہنچنا',
  enter: 'داخل ہونا',
  return: 'واپس آنا',
  wait: 'انتظار کرنا',
  stay: 'رہنا',
  live: 'رہنا',
  die: 'مرنا',
  become: 'بننا',
  seem: 'لگنا',
  appear: 'ظاہر ہونا',
  exist: 'موجود ہونا',
  happen: 'ہونا',
  remain: 'رہنا',
  continue: 'جاری رہنا',
  succeed: 'کامیاب ہونا',
  fail: 'ناکام ہونا',
  win: 'جیتنا',
  lose: 'ہارنا',
  save: 'بچانا',
  spend: 'خرچ کرنا',
  waste: 'ضائع کرنا',
  share: 'بانٹنا',
  divide: 'تقسیم کرنا',
  join: 'شامل ہونا',
  separate: 'الگ کرنا',
  combine: 'ملانا',
  mix: 'ملانا',
  add: 'شامل کرنا',
  subtract: 'منہا کرنا',
  multiply: 'ضرب کرنا',
  count: 'گننا',
  measure: 'ناپنا',
  weigh: 'تولنا',
  choose: 'چننا',
  select: 'منتخب کرنا',
  pick: 'چننا',
  collect: 'جمع کرنا',
  gather: 'اکٹھا کرنا',
  arrange: 'ترتیب دینا',
  organize: 'منظم کرنا',
  prepare: 'تیار کرنا',
  fix: 'ٹھیک کرنا',
  repair: 'مرمت کرنا',
  clean: 'صاف کرنا',
  wash: 'دھونا',
  hide: 'چھپانا',
  seek: 'تلاش کرنا',
  search: 'تلاش کرنا',
  discover: 'دریافت کرنا',
  invent: 'ایجاد کرنا',
  create: 'تخلیق کرنا',
  produce: 'پیدا کرنا',
  develop: 'ترقی دینا',
  improve: 'بہتر کرنا',
  increase: 'بڑھانا',
  decrease: 'کم کرنا',
  reduce: 'کم کرنا',
  expand: 'پھیلانا',
  fill: 'بھرنا',
  cover: 'ڈھانپنا',
  wrap: 'لپیٹنا',
  tie: 'باندھنا',
  untie: 'کھولنا',
  borrow: 'ادھار لینا',
  lend: 'ادھار دینا',
  pay: 'ادا کرنا',
  earn: 'کمانا',
  steal: 'چوری کرنا',
  fight: 'لڑنا',
  defend: 'دفاع کرنا',
  protect: 'حفاظت کرنا',
  rescue: 'بچانا',
  warn: 'خبردار کرنا',
  threaten: 'دھمکی دینا',
  promise: 'وعدہ کرنا',
  decide: 'فیصلہ کرنا',
  hope: 'امید کرنا',
  wish: 'خواہش کرنا',
  imagine: 'تصور کرنا',
  guess: 'اندازہ لگانا',
  suppose: 'فرض کرنا',
  doubt: 'شک کرنا',
  trust: 'بھروسہ کرنا',
  respect: 'احترام کرنا',
  admire: 'تعریف کرنا',
  praise: 'تعریف کرنا',
  blame: 'الزام لگانا',
  forgive: 'معاف کرنا',
  thank: 'شکریہ ادا کرنا',
  apologize: 'معافی مانگنا',
  invite: 'دعوت دینا',
  forbid: 'منع کرنا',
  encourage: 'حوصلہ افزائی کرنا',
  surprise: 'حیران کرنا',
  frighten: 'ڈرانا',
  scare: 'ڈرانا',
  amuse: 'محظوظ کرنا',
  entertain: 'تفریح کرنا',
  celebrate: 'منانا',
  enjoy: 'لطف اٹھانا',
  suffer: 'تکلیف اٹھانا',
  cry: 'رونا',
  laugh: 'ہنسنا',
  smile: 'مسکرانا',
  whisper: 'سرگوشی کرنا',
  shout: 'چلانا',
  scream: 'چیخنا',
  sigh: 'آہ بھرنا',
  yawn: 'جمائی لینا',
  nod: 'سر ہلانا',
  wave: 'ہاتھ ہلانا',
  clap: 'تالی بجانا',
  knock: 'دستک دینا',
  bite: 'کاٹنا',
  chew: 'چبانا',
  smell: 'سونگھنا',
  taste: 'چکھنا',
  touch: 'چھونا',
  feel: 'محسوس کرنا',
  watch: 'دیکھنا',
  look: 'دیکھنا',
  listen: 'سننا',
  bark: 'بھونکنا',

  // === Adverbs ===
  quickly: 'جلدی سے',
  slowly: 'آہستہ',
  happily: 'خوشی سے',
  loudly: 'اونچی آواز سے',
  carefully: 'احتیاط سے',
  quietly: 'خاموشی سے',
  beautifully: 'خوبصورتی سے',
  badly: 'بری طرح',
  always: 'ہمیشہ',
  never: 'کبھی نہیں',
  often: 'اکثر',
  sometimes: 'کبھی کبھی',
  usually: 'عام طور پر',
  rarely: 'شاذ و نادر',
  definitely: 'یقیناً',
  probably: 'شاید',
  certainly: 'بلاشبہ',
  perfectly: 'بالکل درست',
  recently: 'حال ہی میں',
  immediately: 'فوری طور پر',
  now: 'اب',
  then: 'تب',
  here: 'یہاں',
  there: 'وہاں',
  everywhere: 'ہر جگہ',
  somewhere: 'کہیں',
  anywhere: 'کہیں بھی',
  nowhere: 'کہیں نہیں',
  again: 'دوبارہ',
  also: 'بھی',
  too: 'بھی',
  very: 'بہت',
  quite: 'کافی',
  almost: 'تقریباً',
  nearly: 'قریب قریب',
  already: 'پہلے ہی',
  still: 'اب بھی',
  yet: 'ابھی تک',
  just: 'صرف',
  ever: 'کبھی',
  once: 'ایک بار',
  twice: 'دو بار',
  forward: 'آگے',
  backward: 'پیچھے',
  upward: 'اوپر کی طرف',
  downward: 'نیچے کی طرف',
  ahead: 'آگے',

  // === Grammar Terms ===
  noun: 'اسم',
  verb: 'فعل',
  adjective: 'صفت',
  adverb: 'متعلق',
  pronoun: 'ضمیر',
  preposition: 'حرف جار',
  conjunction: 'حرف عطف',
  interjection: 'حرف ندا',
  article: 'حرف تعریف',
  common: 'عام',
  proper: 'خاص',
  abstract: 'تجریدی',
  collective: 'اجتماعی',
  concrete: 'مادی',
  countable: 'گننے والا',
  uncountable: 'نہ گننے والا',
  singular: 'واحد',
  plural: 'جمع',
  definite: 'معین',
  indefinite: 'غیر معین',
  quantitative: 'مقداری',
  qualitative: 'توصیفی',
  compound: 'مرکب',
  subject: 'فاعل',
  object: 'مفعول',
  tense: 'زمانہ',
  voice: 'صدا',
  active: 'فعال',
  passive: 'مجہول',
  phrase: 'فقرہ',
  clause: 'جزو جملہ',
  sentence: 'جملہ',
  paragraph: 'پیراگراف',
  synonym: 'مترادف',
  antonym: 'متضاد',
  syllable: 'حرف',
  phonetics: 'صوتیات',
  prefix: 'سابقہ',
  suffix: 'لاحقہ',
  modal: 'موڈل',
  collocation: 'تلازم',
  figure: 'شکل',
  punctuation: 'علامات اوقاف',
  narration: 'روایت',
  morphology: 'صرف',
  poetry: 'شاعری',
  stanza: 'بند',
  rhyme: 'قافیہ',
  metaphor: 'استعارہ',
  simile: 'تشبیہ',
  personification: 'تشخیص',
  alliteration: 'ہم آواز',
  direct: 'براہ راست',
  indirect: 'بالواسطہ',
  reported: 'منقول',
  denotation: 'لغوی معنی',
  connotation: 'مفہوم',
  semicolon: 'نقطہ وار کاما',
  stylistics: 'اسلوبیات',
  obligation: 'فرض',
  necessity: 'ضرورت',
  simple: 'سادہ',

  // === Determiners ===
  a: 'ایک',
  an: 'ایک',
  the: 'یہ',
  this: 'یہ',
  that: 'وہ',
  these: 'یہ',
  those: 'وہ',
  each: 'ہر ایک',
  every: 'ہر',
  all: 'سب',
  both: 'دونوں',
  few: 'چند',
  any: 'کوئی',
  no: 'نہیں',
  none: 'کوئی نہیں',
  more: 'زیادہ',
  most: 'زیادہ تر',
  less: 'کم',
  least: 'کم سے کم',
  sufficient: 'کافی',
  plenty: 'کافی',

  // === Prepositions ===
  above: 'اوپر',
  across: 'آر پار',
  after: 'بعد',
  against: 'خلاف',
  along: 'ساتھ',
  among: 'درمیان',
  around: 'گرد',
  at: 'پر',
  before: 'پہلے',
  behind: 'پیچھے',
  below: 'نیچے',
  beneath: 'نیچے',
  beside: 'پاس',
  between: 'درمیان',
  beyond: 'آگے',
  by: 'سے',
  down: 'نیچے',
  during: 'دوران',
  except: 'سوائے',
  for: 'لئے',
  from: 'سے',
  in: 'میں',
  into: 'اندر',
  near: 'پاس',
  of: 'کا',
  off: 'دور',
  on: 'پر',
  out: 'باہر',
  over: 'اوپر',
  through: 'کے ذریعے',
  throughout: 'بھر',
  to: 'کو',
  toward: 'کی طرف',
  towards: 'کی طرف',
  under: 'نیچے',
  underneath: 'بالکل نیچے',
  until: 'تک',
  up: 'اوپر',
  upon: 'پر',
  with: 'ساتھ',
  within: 'اندر',
  without: 'بغیر',

  // === Conjunctions ===
  and: 'اور',
  but: 'لیکن',
  or: 'یا',
  because: 'کیونکہ',
  although: 'اگرچہ',
  so: 'تو',
  unless: 'جب تک نہ',
  while: 'جبکہ',
  since: 'جب سے',
  if: 'اگر',
  when: 'جب',
  where: 'جہاں',
  neither: 'نہ ... اور نہ',
  nor: 'نہ ... اور نہ',
  not: 'نہیں',
  only: 'صرف',
  however: 'لیکن',
  therefore: 'اس لئے',
  consequently: 'نتیجتاً',
  moreover: 'مزید',
  nevertheless: 'باوجود',
  besides: 'اس کے علاوہ',

  // === Modals ===
  can: 'سکتا ہے',
  could: 'سکتا تھا',
  may: 'ہو سکتا ہے',
  might: 'ہو سکتا تھا',
  must: 'لازمی',
  shall: 'گا',
  should: 'چاہیے',
  will: 'گا',
  would: 'گا تھا',
  ought: 'چاہیے',

  // === Common words ===
  man: 'آدمی',
  woman: 'عورت',
  boy: 'لڑکا',
  girl: 'لڑکی',
  children: 'بچے',
  student: 'طالب علم',
  teacher: 'استاد',
  doctor: 'ڈاکٹر',
  patient: 'مریض',
  garden: 'باغ',
  park: 'پارک',
  street: 'گلی',
  road: 'سڑک',
  shop: 'دکان',
  cat: 'بلی',
  mouse: 'چوہا',
  horse: 'گھوڑا',
  tiger: 'شیر',
  lion: 'شیر',
  fish: 'مچھلی',
  monkey: 'بندر',
  rabbit: 'خرگوش',
  duck: 'بطخ',
  hen: 'مرغی',
  cow: 'گائے',
  goat: 'بکری',
  sheep: 'بھیڑ',
  zoo: 'چڑیا گھر',
  east: 'مشرق',
  west: 'مغرب',
  north: 'شمال',
  south: 'جنوب',

  // === Numbers ===
  one: 'ایک',
  two: 'دو',
  three: 'تین',
  four: 'چار',
  five: 'پانچ',
  six: 'چھ',
  seven: 'سات',
  eight: 'آٹھ',
  nine: 'نو',
  ten: 'دس',

  // === Question Words ===
  what: 'کیا',
  who: 'کون',
  whom: 'کس کو',
  whose: 'کس کا',
  which: 'کون سا',
  why: 'کیوں',
  how: 'کیسے',

  // === Pronouns ===
  i: 'میں',
  me: 'مجھے',
  my: 'میرا',
  mine: 'میرا',
  you: 'تم',
  your: 'تمہارا',
  yours: 'تمہارا',
  he: 'وہ',
  him: 'اسے',
  his: 'اس کا',
  she: 'وہ',
  her: 'اسے',
  hers: 'اس کا',
  we: 'ہم',
  us: 'ہمیں',
  our: 'ہمارا',
  ours: 'ہمارا',
  they: 'وہ',
  them: 'انہیں',
  their: 'ان کا',
  theirs: 'ان کا',
  itself: 'خود',
  myself: 'خود',
  yourself: 'خود',
  himself: 'خود',
  herself: 'خود',
  ourselves: 'خود',
  themselves: 'خود',
  other: 'دوسرا',
  another: 'دوسرا',
  anybody: 'کوئی',
  everybody: 'سب',
  nobody: 'کوئی نہیں',
  everything: 'سب کچھ',
  nothing: 'کچھ نہیں',
  something: 'کچھ',
  everyone: 'ہر کوئی',
  noone: 'کوئی نہیں',
  someone: 'کوئی',
  anyone: 'کوئی',

  // === Additional academic words ===
  personal: 'ذاتی',
  possessive: 'ملکانی',
  reflexive: 'انعکاسی',
  relative: 'موصولی',
  demonstrative: 'اشاراتی',
  interrogative: 'استفہامی',
  intensive: 'تاکیدی',
  emphatic: 'تاکیدی',
  reciprocal: 'متقابل',
  homophone: 'ہم آواز',
  homonym: 'ہم نام',
  root: 'جڑ',
  base: 'بنیاد',
  gender: 'جنس',
  masculine: 'مذکر',
  feminine: 'مؤنث',
  neutral: 'غیر جانبدار',
  predicate: 'خبر',
  complement: 'تکملہ',
  comparison: 'تقابل',
  positive: 'اثباتی',
  comparative: 'تفضیلی',
  superlative: 'اعلیٰ',
  auxiliary: 'معاون',
  linking: 'ربط',
  transitive: 'متعدی',
  intransitive: 'لازم',
  colon: 'نقطہ وار',
  comma: 'کوما',
  apostrophe: 'الفیف',
  capital: 'بڑا حرف',
  vowel: 'متحرک',
  consonant: 'ساکن',
  literature: 'ادب',
  prose: 'نثر',
  poem: 'نظم',
  narrative: 'بیانیہ',
  descriptive: 'توصیفی',
  introduction: 'تعارف',
  title: 'عنوان',
  heading: 'سرخی',
  conclusion: 'نتیجہ',
  summary: 'خلاصہ',
  content: 'مواد',
  index: 'اشاریہ',
  source: 'ماخذ',
  text: 'متن',
  context: 'سیاق و سباق',
  purpose: 'مقصد',
  audience: 'سامعین',
  genre: 'صنف',
  theme: 'موضوع',
  plot: 'پلاٹ',
  setting: 'ترتیب',
  character: 'کردار',
  conflict: 'تصادم',
  resolution: 'حل',
  climax: 'عروج',
  moral: 'سبق',
  cursive: 'کرسیو',
  gerund: 'اسم مصدر',
  participle: 'صفت فعلی',
  infinitive: 'مصدر',
  verbal: 'فعلی',
  subordinate: 'تابع',
  coordinate: 'ہم سطح',
  correlative: 'متعلق',
  conditional: 'شرطی',
  euphemism: 'خوش فہمی',
  oxymoron: 'متضاد الفاظ',
  hyphen: 'نشان ربط',
  adjectival: 'صفت سے متعلق',
  adverbial: 'متعلق سے متعلق',
  prepositional: 'حرف جار سے متعلق',
  fiction: 'افسانہ',
  drama: 'ڈراما',
  safari: 'سفاری',
  jungle: 'جنگل',
  poster: 'پوسٹر',
  banner: 'بینر',
  board: 'بورڈ',
  click: 'کلک',
  identify: 'پہچاننا',
  check: 'چیک کریں',
  previous: 'پچھلا',
  submit: 'جمع کروائیں',
  reset: 'دوبارہ ترتیب',
  task: 'کام',
  stage: 'مرحلہ',
  round: 'دور',
  practice: 'مشق',
  exercise: 'مشق',
  quiz: 'کوئز',
  points: 'پوائنٹس',
  progress: 'پیشرفت',
  mistake: 'غلطی',
  pause: 'توقف',
  skip: 'چھوڑیں',
  undo: 'واپس',
  redo: 'دوبارہ کریں',
  cancel: 'منسوخ',
  confirm: 'تصدیق',
  edit: 'ترمیم',
  delete: 'حذف',
  remove: 'ہٹائیں',
  download: 'ڈاؤن لوڈ',
  upload: 'اپ لوڈ',
  settings: 'ترتیبات',
  options: 'اختیارات',
  menu: 'مینو',
  home: 'گھر',
  exit: 'باہر نکلیں',
  quit: 'چھوڑیں',
  enable: 'فعال',
  disable: 'غیر فعال',
  success: 'کامیابی',
  error: 'غلطی',
  warning: 'انتباہ',
  info: 'معلومات',
  featured: 'نمایاں',
  best: 'بہترین',
  worst: 'بدترین',
  fun: 'مزہ',
  awesome: 'زبردست',
  cool: 'ٹھنڈا',
  cousin: 'کزن',
  sand: 'ریت',
  bone: 'ہڈی',
  tail: 'دم',
  wing: 'پر',
  fur: 'بال',
  feather: 'پر',
  scale: 'چھلکا',
  shell: 'خول',
  nest: 'گھونسلہ',
  egg: 'انڈہ',
  hole: 'سوراخ',
  net: 'جال',
  trap: 'جال',
  cage: 'پنجرہ',
  rope: 'رسی',
  chain: 'زنجیر',
  stick: 'چھڑی',
  sword: 'تلوار',
  shield: 'ڈھال',
  crown: 'تاج',
  throne: 'تخت',
  medal: 'میڈل',
  trophy: 'ٹرافی',
  reward: 'انعام',
  business: 'کاروبار',
  company: 'کمپنی',
  meeting: 'ملاقات',
  party: 'پارٹی',
  travel: 'سفر',
};

// ============================================================
// ROMAN URDU TRANSLITERATIONS (for TTS speech synthesis)
// When no Urdu voice is available on the system, the browser
// can still pronounce Roman Urdu text using a standard voice.
// ============================================================

export const WORD_TRANSLITERATIONS: Record<string, string> = {
  // === Nouns ===
  happiness: 'khushi',
  team: 'team',
  London: 'London',
  dog: 'kutta',
  bunch: 'guchha',
  courage: 'himmat',
  Ganges: 'Ganges',
  book: 'kitaab',
  table: 'mez',
  car: 'gaari',
  apple: 'seb',
  school: 'school',
  city: 'sheher',
  mountain: 'pahaar',
  tree: 'darakht',
  flower: 'phool',
  animal: 'jaanwar',
  bird: 'parinda',
  ocean: 'samandar',
  star: 'sitaara',
  house: 'ghar',
  chair: 'kursi',
  door: 'darwaaza',
  window: 'khidki',
  food: 'khana',
  water: 'paani',
  fire: 'aag',
  earth: 'zameen',
  air: 'hawa',
  sun: 'sooraj',
  moon: 'chaand',
  information: 'maldaryaft',
  library: 'kutub khana',
  bravery: 'bahaduri',
  elephant: 'haathi',
  dragon: 'azhdaha',
  alien: 'ajnabee',
  adventure: 'muhim joi',
  journey: 'safar',
  story: 'kahani',
  secret: 'raaz',
  mystery: 'pur asrar',
  treasure: 'khazana',
  power: 'taqat',
  energy: 'tawanai',
  strength: 'taqat',
  wisdom: 'danai',
  knowledge: 'ilm',
  idea: 'khayal',
  dream: 'khwab',
  memory: 'yadasht',
  future: 'mustaqbil',
  past: 'mazi',
  present: 'haal',
  people: 'log',
  person: 'shakhs',
  place: 'jaga',
  thing: 'cheez',
  time: 'waqt',
  name: 'naam',
  world: 'duniya',
  life: 'zindagi',
  head: 'sar',
  hand: 'haath',
  eye: 'aankh',
  heart: 'dil',
  body: 'jism',
  face: 'chehra',
  foot: 'paon',
  arm: 'bazoo',
  leg: 'tang',
  child: 'bacha',
  baby: 'bacha',
  mother: 'maa',
  father: 'baap',
  brother: 'bhai',
  sister: 'behn',
  son: 'beta',
  daughter: 'beti',
  king: 'badshah',
  queen: 'malika',
  hero: 'hero',
  robot: 'robot',
  machine: 'machine',
  computer: 'computer',
  message: 'paighaam',
  word: 'lafz',
  sound: 'aawaz',
  picture: 'tasveer',
  map: 'naqsha',
  flag: 'jhandalala',
  game: 'khel',
  sport: 'khel',
  friend: 'dost',
  family: 'khandan',
  morning: 'subah',
  evening: 'shaam',
  night: 'raat',
  today: 'aaj',
  tomorrow: 'kal',
  yesterday: 'kal',
  week: 'hafta',
  month: 'mahina',
  year: 'saal',
  season: 'mausam',
  spring: 'bahaar',
  summer: 'garmi',
  winter: 'sardi',
  question: 'sawal',
  reason: 'wajah',
  problem: 'masla',
  solution: 'hal',
  method: 'tareeqa',
  part: 'hissa',
  fact: 'haqeeqat',
  truth: 'sach',
  lie: 'jhoot',
  thought: 'soch',
  feeling: 'ehsas',
  meaning: 'maani',
  definition: 'taarif',
  translation: 'tarjuma',
  language: 'zaban',
  english: 'angrezi',
  urdu: 'urdu',
  grammar: 'grammar',
  vocabulary: 'zakheera alfaaz',
  spelling: 'hijay',
  pronunciation: 'talafuz',
  accent: 'lahja',
  dialogue: 'mukalima',
  conversation: 'guftagu',
  speech: 'taqreer',
  report: 'report',
  essay: 'mazmoon',
  composition: 'tabeer',
  letter: 'khat',
  diary: 'diary',
  hint: 'ishara',
  advice: 'mashwara',
  chance: 'moqaa',
  opportunity: 'moqaa',
  danger: 'khatra',
  safety: 'hifazat',
  peace: 'aman',
  war: 'jang',
  battle: 'larhai',
  victory: 'fatah',
  defeat: 'shikast',
  attack: 'hamla',
  defense: 'difaa',
  army: 'fauj',
  force: 'taqat',

  // === Adjectives ===
  happy: 'khush',
  beautiful: 'khobsurat',
  big: 'bara',
  small: 'chhota',
  tall: 'lamba',
  short: 'chhota',
  fast: 'tez',
  slow: 'dheema',
  hot: 'garam',
  cold: 'thanda',
  new: 'naya',
  old: 'purana',
  good: 'acha',
  bad: 'bura',
  shiny: 'chamakdar',
  huge: 'bara',
  ferocious: 'khoonkhar',
  many: 'bohat',
  some: 'kuch',
  cheap: 'sasta',
  bossy: 'hukm chalane wala',
  angry: 'ghussa',
  confused: 'pareshan',
  brave: 'bahaadur',
  clever: 'hoshiyar',
  smart: 'hoshiyar',
  wise: 'aqalmand',
  foolish: 'be waqoof',
  kind: 'meharban',
  cruel: 'zalim',
  gentle: 'naram',
  hard: 'sakht',
  strong: 'mazboot',
  weak: 'kamzor',
  rich: 'ameer',
  poor: 'ghareeb',
  young: 'jawaan',
  easy: 'aasan',
  difficult: 'mushkil',
  important: 'ahem',
  incorrect: 'ghalat',
  true: 'sach',
  false: 'jhoot',
  real: 'haqiqi',
  special: 'khaas',
  strange: 'ajeeb',
  rare: 'nayab',
  different: 'mukhtalif',
  same: 'ek jaisa',
  opposite: 'mukhalif',
  clear: 'saaf',
  dirty: 'ganda',
  dark: 'andhera',
  bright: 'roshan',
  light: 'halka',
  heavy: 'bhaari',
  full: 'bhara',
  empty: 'khaali',
  closed: 'band',
  long: 'lamba',
  wide: 'chora',
  narrow: 'tang',
  deep: 'gahara',
  high: 'ooncha',
  low: 'neecha',
  far: 'door',
  early: 'jaldi',
  late: 'dayar',
  quick: 'tez',
  ready: 'tayyar',
  busy: 'masroof',
  free: 'aazaad',
  sure: 'yaqeeni',
  main: 'ahem',
  first: 'pehla',
  second: 'doosra',
  third: 'tesra',
  little: 'thhora',
  much: 'bohat',
  enough: 'kaafi',
  great: 'azeem',
  wonderful: 'shandar',
  amazing: 'hairat angaiz',
  fantastic: 'lajawab',
  excellent: 'behtareen',
  perfect: 'kaamil',
  terrible: 'khofnaak',
  nice: 'acha',
  fine: 'theek',
  famous: 'mashhoor',
  various: 'mukhtalif',
  complete: 'mukammal',
  natural: 'qudrati',
  useful: 'mufeed',
  dangerous: 'khatarnaak',
  safe: 'mehfooz',
  helpful: 'madadgaar',
  interesting: 'dilchasp',
  exciting: 'purjosh',
  funny: 'mazahia',
  sad: 'udaas',
  hungry: 'bhookha',
  thirsty: 'pyaasa',
  sick: 'bimaar',
  healthy: 'sehat mand',
  alive: 'zinda',
  dead: 'murda',
  alone: 'akela',
  together: 'ek saath',
  silent: 'khamosh',
  loud: 'ooncha',
  quiet: 'khamosh',
  sweet: 'meetha',
  delicious: 'mazedar',
  fresh: 'taaza',
  wet: 'geela',
  dry: 'khushk',
  expensive: 'mehnga',
  honest: 'imaandaar',
  intelligent: 'zahin',

  // === Verbs ===
  run: 'daurna',
  eat: 'khana',
  sleep: 'sona',
  read: 'parhna',
  write: 'likhna',
  speak: 'bolna',
  walk: 'chalna',
  work: 'kaam karna',
  play: 'khelna',
  swim: 'taina',
  jump: 'koodna',
  sing: 'gana',
  dance: 'naachna',
  cook: 'pakana',
  drink: 'peena',
  give: 'dena',
  take: 'lena',
  come: 'aana',
  go: 'jana',
  see: 'dekhna',
  hear: 'sunna',
  teach: 'sikhana',
  learn: 'sikhna',
  help: 'madad karna',
  love: 'mohabbat karna',
  make: 'banana',
  break: 'torna',
  catch: 'pakarna',
  bring: 'lana',
  find: 'dhoondna',
  buy: 'khareedna',
  sell: 'bechna',
  talk: 'baat karna',
  sit: 'baitna',
  stand: 'khara hona',
  think: 'sochna',
  know: 'jaanna',
  want: 'chahna',
  need: 'zaroorat hona',
  like: 'pasand karna',
  ask: 'poochna',
  tell: 'batana',
  show: 'dikhana',
  leave: 'chhorna',
  keep: 'rakhna',
  let: 'dena',
  begin: 'shuru karna',
  open: 'kholna',
  close: 'band karna',
  move: 'harkat karna',
  change: 'badalna',
  follow: 'pairwi karna',
  remember: 'yaad rakhna',
  forget: 'bhoolna',
  understand: 'samajhna',
  believe: 'yaqeen karna',
  accept: 'qabool karna',
  send: 'bhejna',
  call: 'bulana',
  answer: 'jawab dena',
  explain: 'wazahat karna',
  describe: 'bayaan karna',
  draw: 'banna',
  paint: 'rangna',
  build: 'taamer karna',
  grow: 'ugana',
  cut: 'kaatna',
  push: 'dhekelna',
  pull: 'khenchna',
  lift: 'uthana',
  drop: 'girana',
  throw: 'phenkna',
  hit: 'maarna',
  hold: 'pakarna',
  carry: 'uthana',
  put: 'rakhna',
  rise: 'uthna',
  fall: 'girna',
  turn: 'murna',
  fly: 'urna',
  drive: 'chalana',
  travel: 'safar karna',
  visit: 'milna',
  meet: 'milna',
  arrive: 'puhanchna',
  wait: 'intezaar karna',
  stay: 'rehna',
  live: 'rehna',
  die: 'marna',
  become: 'banna',
  win: 'jeetna',
  lose: 'haarna',
  share: 'baantna',
  join: 'shamil hona',
  count: 'ginana',
  choose: 'chunna',
  select: 'muntakhib karna',
  pick: 'chunna',
  clean: 'saaf karna',
  wash: 'dhona',
  hide: 'chupana',
  search: 'talash karna',
  discover: 'daryaft karna',
  create: 'takhleeq karna',
  improve: 'behtar karna',
  increase: 'barhana',
  decrease: 'kam karna',
  fill: 'bharna',
  cry: 'rona',
  laugh: 'hansna',
  smile: 'muskurana',
  shout: 'chalana',
  watch: 'dekhna',
  look: 'dekhna',
  listen: 'sunna',
  bark: 'bhonkna',

  // === Adverbs ===
  quickly: 'jaldi se',
  slowly: 'aahista',
  happily: 'khushi se',
  loudly: 'oonchi aawaz se',
  carefully: 'ehtiyat se',
  quietly: 'khamoshi se',
  beautifully: 'khobsurati se',
  badly: 'buree tarah',
  always: 'hamesha',
  never: 'kabhi nahi',
  often: 'aksar',
  sometimes: 'kabhi kabhi',
  usually: 'aam tor par',
  rarely: 'shaz o nadir',
  definitely: 'yaqeenan',
  probably: 'shayad',
  certainly: 'bilashuba',
  now: 'ab',
  then: 'tab',
  here: 'yahan',
  there: 'wahan',
  everywhere: 'har jaga',
  somewhere: 'kahin',
  also: 'bhi',
  too: 'bhi',
  very: 'bohat',
  almost: 'taqreeban',
  already: 'pehle hi',
  still: 'ab bhi',
  just: 'sirf',

  // === Grammar Terms ===
  noun: 'ism',
  verb: 'feal',
  adjective: 'sifat',
  adverb: 'mutlaq',
  pronoun: 'zameer',
  preposition: 'harf e jaar',
  conjunction: 'harf e ataf',
  interjection: 'harf e nida',
  article: 'harf e taarif',
  common: 'aam',
  proper: 'khaas',
  abstract: 'tajreedi',
  collective: 'ijtimai',
  concrete: 'maddi',
  countable: 'ginne wala',
  uncountable: 'nah ginne wala',
  singular: 'wahid',
  plural: 'jama',
  definite: 'muayyan',
  indefinite: 'ghair muayyan',
  subject: 'fail',
  object: 'mafool',
  tense: 'zamana',
  voice: 'sada',
  active: 'failiya',
  passive: 'majhool',
  phrase: 'jumla',
  clause: 'juz jumla',
  sentence: 'jumla',
  paragraph: 'paragraph',
  synonym: 'mutradif',
  antonym: 'mutazad',
  syllable: 'hijay',
  phonetics: 'sautiyaat',
  prefix: 'sabiqa',
  suffix: 'lahiqa',
  modal: 'modal',
  collocation: 'talazum',
  punctuation: 'alamaat e auqaf',
  narration: 'riwayat',
  morphology: 'sarf',
  poetry: 'shayari',
  metaphor: 'isteara',
  simile: 'tashbeeh',
  personification: 'tashkhees',
  alliteration: 'ham aawaz',
  direct: 'barah-e-raast',
  indirect: 'balawasta',
  reported: 'manqool',
  denotation: 'laghwi maani',
  connotation: 'mafhoom',
  semicolon: 'nuqta-waar-comma',
  stylistics: 'usloobiyat',
  obligation: 'farz',
  necessity: 'zaroorat',
  simple: 'saada',

  // === Prepositions ===
  above: 'upar',
  across: 'aar paar',
  after: 'baad',
  against: 'khilaf',
  along: 'saath',
  among: 'darmiyan',
  around: 'gird',
  at: 'par',
  before: 'pehle',
  behind: 'peecha',
  below: 'neeche',
  beneath: 'neeche',
  beside: 'paas',
  between: 'darmiyan',
  beyond: 'aage',
  by: 'se',
  down: 'neeche',
  during: 'doran',
  for: 'liye',
  from: 'se',
  in: 'mein',
  into: 'andar',
  near: 'paas',
  of: 'ka',
  on: 'par',
  out: 'bahar',
  over: 'upar',
  through: 'se',
  to: 'ko',
  toward: 'ki taraf',
  under: 'neeche',
  until: 'tak',
  up: 'upar',
  with: 'saath',
  within: 'andar',
  without: 'baghair',

  // === Conjunctions ===
  and: 'aur',
  but: 'lekin',
  or: 'ya',
  because: 'kyunke',
  although: 'agarche',
  so: 'toh',
  unless: 'jab tak nah',
  while: 'jabke',
  since: 'jab se',
  if: 'agar',
  when: 'jab',
  not: 'nahi',
  only: 'sirf',
  however: 'lekin',
  therefore: 'is liye',

  // === Modals ===
  can: 'sakta hai',
  could: 'sakta tha',
  may: 'ho sakta hai',
  might: 'ho sakta tha',
  must: 'lazmi',
  shall: 'ga',
  should: 'chahiye',
  will: 'ga',
  would: 'ga tha',

  // === Common words ===
  man: 'aadmi',
  woman: 'aurat',
  boy: 'larka',
  girl: 'larki',
  children: 'bachay',
  student: 'talib ilm',
  teacher: 'ustaad',
  doctor: 'doctor',
  garden: 'bagh',
  park: 'park',
  cat: 'billi',
  mouse: 'chooha',
  horse: 'ghora',
  tiger: 'sher',
  lion: 'sher',
  fish: 'machli',
  monkey: 'bandar',
  rabbit: 'khargosh',
  duck: 'batakh',
  cow: 'gaye',
  goat: 'bakri',
  sheep: 'bheer',
  zoo: 'chidya ghar',
  east: 'mashriq',
  west: 'maghrib',
  north: 'shamal',
  south: 'junoob',

  // === Numbers ===
  one: 'aik',
  two: 'do',
  three: 'teen',
  four: 'chaar',
  five: 'paanch',
  six: 'chay',
  seven: 'saat',
  eight: 'aath',
  nine: 'nau',
  ten: 'das',

  // === Question Words ===
  what: 'kya',
  who: 'kaun',
  which: 'kaun sa',
  why: 'kyun',
  how: 'kaise',
  where: 'jahan',

  // === Pronouns ===
  i: 'mein',
  me: 'mujhay',
  my: 'mera',
  you: 'tum',
  your: 'tumhara',
  he: 'woh',
  him: 'usay',
  his: 'us ka',
  she: 'woh',
  her: 'usay',
  we: 'hum',
  us: 'humein',
  our: 'hamara',
  they: 'woh',
  them: 'unhen',
  their: 'unka',
  itself: 'khud',
  myself: 'khud',
  someone: 'koi',
  everything: 'sab kuch',
  nothing: 'kuch nahi',
  something: 'kuch',
  anyone: 'koi',
  everyone: 'har koi',

  // === Additional words ===
  personal: 'zaati',
  possessive: 'malikana',
  reflexive: 'nfeasi',
  relative: 'mausooli',
  demonstrative: 'isharati',
  interrogative: 'istafhami',
  intensive: 'takeedi',
  homophone: 'ham aawaz',
  root: 'jar',
  base: 'bunyad',
  gender: 'jins',
  transitive: 'mutaddi',
  intransitive: 'lazim',
  capital: 'bara harf',
  vowel: 'mutaharrik',
  consonant: 'sakin',
  text: 'matan',
  context: 'siyaq o sabaaq',
  character: 'kirdaar',
  plot: 'plot',
  theme: 'mauzo',
  title: 'unwaan',
  heading: 'surkhi',
  summary: 'khulasa',
  conclusion: 'nataija',
  purpose: 'maqsad',
  audience: 'samaeen',
  practice: 'mashq',
  exercise: 'mashq',
  test: 'test',
  quiz: 'quiz',
  score: 'score',
  check: 'check karein',
  next: 'aagla',
  previous: 'pechla',
  start: 'shuru',
  finish: 'khatam',
  stop: 'rukna',
  continue: 'jaari rakhna',
  cancel: 'mansookh',
  confirm: 'tasdeek',
  save: 'mehfooz',
  delete: 'hazf',
  add: 'shamil',
  remove: 'hatao',
  settings: 'tarteebaat',
  options: 'ikhtiyarat',
  home: 'ghar',
  exit: 'bahar nikle',
  success: 'kaamyabi',
  error: 'ghalti',
  warning: 'intabah',
  info: 'maldaryaft',
  correct: 'durust',
  wrong: 'ghalat',
  try: 'koshish',
  again: 'dobara',
};

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Get the Urdu script meaning for an English word.
 */
export function getMeaning(word: string): string {
  const key = word.toLowerCase().trim();
  return WORD_MEANINGS[key] || '';
}

/**
 * Get the Roman Urdu transliteration for TTS.
 * If no transliteration exists, returns the English word itself
 * as a fallback so TTS still works.
 */
export function getTransliteration(word: string): string {
  const key = word.toLowerCase().trim();
  return WORD_TRANSLITERATIONS[key] || key;
}

/**
 * Check if a word has an Urdu meaning available.
 */
export function hasMeaning(word: string): boolean {
  return !!getMeaning(word);
}

/**
 * Extract all unique words from text that have meanings available.
 */
export function extractMeaningfulWords(text: string): string[] {
  const words = text.match(/\b[a-zA-Z]+(?:-[a-zA-Z]+)*\b/g) || [];
  const unique = new Set(words.map(w => w.toLowerCase().trim()));
  return Array.from(unique).filter(w => hasMeaning(w));
}
