import { lazy } from 'react';

/**
 * Auto-discover all lab components via Vite's import.meta.glob.
 * This eliminates the need for manual lazy() import() calls for each lab.
 */
const labFiles = import.meta.glob('../components/Lab*.tsx');

/**
 * Module ID → component name mapping.
 * Component names follow the pattern: Lab<Subject><Class><Name>
 */
const moduleIdToComponent: Record<string, string> = {
  // Class 8 Computer
  'c8c_1_1': 'LabDataComm',
  'c8c_1_2': 'LabNetworkDevices',
  'c8c_2_1': 'LabCricketSpreadsheet',
  'c8c_2_2': 'LabDataWorksheets',
  'c8c_3_1': 'LabPseudocodeInterpreter',
  'c8c_3_2': 'LabDiceGameAlgorithm',
  'c8c_4_1': 'LabScratchMaze',
  'c8c_5_1': 'LabCyberScout',
  'c8c_5_2': 'LabAntivirus',
  'c8c_6_1': 'LabBusinessPlan',
  'c8c_6_2': 'LabDigitalMarketing',

  // Class 7 Computer
  'c7c_1_1': 'LabC7Hardware',
  'c7c_1_2': 'LabC7EmergingTech',
  'c7c_1_3': 'LabC7Generations',
  'c7c_1_4': 'LabC7NetworkDiagram',
  'c7c_2_1': 'LabC7UrduTyping',
  'c7c_2_2': 'LabC7LetterFormat',
  'c7c_2_3': 'LabC7CVCreation',
  'c7c_2_4': 'LabC7IllustratedStory',
  'c7c_2_5': 'LabC7PowerPointGeometry',
  'c7c_2_6': 'LabC7WondersResearch',
  'c7c_3_1': 'LabC7ConditionalLogic',
  'c7c_3_2': 'LabC7GradingFlowchart',
  'c7c_3_3': 'LabC7ReverseFlowchart',
  'c7c_4_1': 'LabC7SpriteManipulation',
  'c7c_4_2': 'LabC7LoopAdjustments',
  'c7c_4_3': 'LabC7BouncingBall',
  'c7c_4_4': 'LabC7AnimatedDialogue',
  'c7c_4_5': 'LabC7InteractivePiano',
  'c7c_5_1': 'LabC7Cybercrime',
  'c7c_5_2': 'LabC7DevianceDiscussion',
  'c7c_5_3': 'LabC7EthicsChart',
  'c7c_6_1': 'LabC7DesignPrototype',
  'c7c_6_2': 'LabC7MothersDay',

  // Class 6 Computer
  'c6c_1_1': 'LabC6HealthCampaign',
  'c6c_1_2': 'LabC6HardwareCharts',
  'c6c_1_3': 'LabC6LabRules',
  'c6c_1_4': 'LabC6GroupPresentations',
  'c6c_2_1': 'LabC6SystemSoftware',
  'c6c_2_2': 'LabC6FileManagement1',
  'c6c_2_3': 'LabC6FileManagement2',
  'c6c_2_4': 'LabC6DietExercise',
  'c6c_2_5': 'LabC6Paint3DFace',
  'c6c_2_6': 'LabC6SolarSystem',
  'c6c_3_1': 'LabC6ProblemDecomposition',
  'c6c_3_2': 'LabC6RoadSafetyProcess',
  'c6c_4_1': 'LabC6CoordinateExp',
  'c6c_4_2': 'LabC6CostumeChange',
  'c6c_4_3': 'LabC6MovementTracking',
  'c6c_4_4': 'LabC6LoopAdjustments',
  'c6c_5_1': 'LabC6EthicsChart',
  'c6c_5_2': 'LabC6CyberScout',
  'c6c_5_3': 'LabC6PosterCompetition',
  'c6c_6_1': 'LabC6HobbyMonetization',

  // Class 8 Science
  'c8s_1_1': 'LabS8GreenhouseEffect',
  'c8s_1_2': 'LabS6EverydayTech',
  'c8s_2_1': 'LabS8StimulusResponse',
  'c8s_2_2': 'LabS8KneeJerk',
  'c8s_2_3': 'LabS8ReflexTime',
  'c8s_3_1': 'LabS8DNAExtraction',
  'c8s_3_2': 'LabS8HumanVariations',
  'c8s_3_3': 'LabS8CrossingOver',
  'c8s_4_1': 'LabS8MakingYogurt',
  'c8s_5_1': 'LabS8PeriodicTable',
  'c8s_5_2': 'LabS8ElectronicConfig',
  'c8s_5_3': 'LabS8Malleability',
  'c8s_5_4': 'LabS8Flexibility',
  'c8s_5_5': 'LabS8Density',
  'c8s_5_6': 'LabS8ThermalConductivity',
  'c8s_5_7': 'LabS8Sonorous',
  'c8s_6_1': 'LabS8ChemicalReactionSigns',
  'c8s_6_2': 'LabS8ConservationMass',
  'c8s_6_3': 'LabS8Endothermic',
  'c8s_6_4': 'LabS8Exothermic',
  'c8s_7_1': 'LabS8AcidLitmus',
  'c8s_7_2': 'LabS8AlkaliLitmus',
  'c8s_7_3': 'LabS8Neutralization',
  'c8s_7_4': 'LabS8DeterminingPH',
  'c8s_8_1': 'LabS8NailPressure',
  'c8s_8_2': 'LabS8HydraulicElevator',
  'c8s_8_3': 'LabS8WaterRocket',
  'c8s_9_1': 'LabS8LaserMaze',
  'c8s_9_3': 'LabS8Periscope',
  'c8s_9_4': 'LabS8RefractionPencil',
  'c8s_9_5': 'LabS8ConcaveMirror',
  'c8s_9_6': 'LabS8ConvexMirror',
  'c8s_10_1': 'LabS8Electromagnet',
  'c8s_11_1': 'LabS8Toothpaste',
  'c8s_11_2': 'LabS8SoapMaking',
  'c8s_11_3': 'LabS8MilkPlastic',
  'c8s_11_4': 'LabS8Detergent',
  'c8s_11_5': 'LabS8SolarCooker',
  'c8s_11_7': 'LabS8WindTurbine',
  'c8s_11_8': 'LabS8ChemicalCar',
  'c8s_11_9': 'LabS8Windsock',
  'c8s_12_1': 'LabS8SkyMap',

  // Class 7 Science
  'c7s_1_1': 'LabS7XylemTransport',
  'c7s_1_2': 'LabS7TranspirationObservation',
  'c7s_1_3': 'LabS7TranspirationLeaves',
  'c7s_1_4': 'LabS7MineralsPlantGrowth',
  'c7s_1_5': 'LabS7Unit1Projects',
  'c7s_2_1': 'LabS7MeasuringLungCapacity',
  'c7s_2_2': 'LabS7PulseRateExercise',
  'c7s_2_3': 'LabS7Unit2Projects',
  'c7s_3_1': 'LabS7ImmuneSystemRolePlay',
  'c7s_3_2': 'LabS7Unit3Projects',
  'c7s_4_1': 'LabS7ChemicalChange',
  'c7s_4_2': 'LabS7ThermalConduction',
  'c7s_4_3': 'LabS7Unit4Projects',
  'c7s_5_1': 'LabS7CalculatingSubatomicParticles',
  'c7s_5_2': 'LabS7AtomModel',
  'c7s_6_1': 'LabS7LithiumBonding',
  'c7s_7_1': 'LabS7DiluteConcentratedSolutions',
  'c7s_7_2': 'LabS7CleaningCoins',
  'c7s_7_3': 'LabS7MakingRockCandy',
  'c7s_7_4': 'LabS7OilPollutants',
  'c7s_8_1': 'LabS7BalloonRocket',
  'c7s_8_2': 'LabS7Unit8Projects',
  'c7s_9_1': 'LabS7VibratingLengthPitch',
  'c7s_9_2': 'LabS7Unit9Projects',
  'c7s_10_1': 'LabS7Unit10Projects',
  'c7s_11_1': 'LabS7DripIrrigation',
  'c7s_11_2': 'LabS7MakeStethoscope',
  'c7s_11_3': 'LabS7HandSanitizer',
  'c7s_11_4': 'LabS7Unit11Projects',
  'c7s_12_1': 'LabS7EarthSeasons',

  // Class 10 Physics
  'p10_10_1': 'LabP10CarbonFootprint',
  'p10_10_2': 'LabP10SpecificHeatMixture',
  'p10_10_3': 'LabP10SpecificHeatElectrical',
  'p10_10_4': 'LabP10ThermalConduction',
  'p10_10_5': 'LabP10ConvectionCurrents',
  'p10_10_6': 'LabP10InsulatingMaterials',
  'p10_10_7': 'LabP10AbsorbersReflectors',
  'p10_10_8': 'LabP10LeslieCube',
  'p10_11_1': 'LabP10ThermalExpansionSolid',
  'p10_11_2': 'LabP10ExpansionLiquids',
  'p10_11_3': 'LabP10GasPressureBalloon',
  'p10_11_4': 'LabP10LatentHeat',
  'p10_12_1': 'LabP10WaveMotion',
  'p10_12_2': 'LabP10RippleTank',
  'p10_12_3': 'LabP10RefractionIllusion',
  'p10_13_1': 'LabP10SoundProduction',
  'p10_13_2': 'LabP10SoundMedium',
  'p10_13_3': 'LabP10StringTelephone',
  'p10_13_4': 'LabP10SpeakerProject',
  'p10_14_1': 'LabP10PlaneMirror',
  'p10_14_2': 'LabP10RefractionBlocks',
  'p10_14_3': 'LabP10TotalInternalReflection',
  'p10_15_1': 'LabP10ElectrostaticCharges',
  'p10_15_2': 'LabP10Electroscope',
  'p10_16_1': 'LabP10OhmLaw',
  'p10_16_2': 'LabP10SeriesCircuit',
  'p10_16_3': 'LabP10ParallelCircuit',
  'p10_17_1': 'LabP10MagneticField',
  'p10_17_2': 'LabP10ElectromagnetDC',
  'p10_17_3': 'LabP10FaradayLaw',
  'p10_18_1': 'LabP10ThermionicEmission',
  'p10_18_2': 'LabP10LogicGates',
  'p10_19_1': 'LabP10RadioTransmission',
  'p10_19_2': 'LabP10OpticalFibers',
  'p10_20_1': 'LabP10Radioactivity',
  'p10_20_2': 'LabP10HalfLife',

  // Class 10 Physics Derivations
  'p10_deriv_specific_heat_mixtures': 'LabP10DerivationSpecificHeatMixtures',
  'p10_deriv_specific_heat_electrical': 'LabP10DerivationSpecificHeatElectrical',
  'p10_deriv_linear_expansion': 'LabP10DerivationLinearExpansion',
  'p10_deriv_volumetric_expansion': 'LabP10DerivationVolumetricExpansion',
  'p10_deriv_expansion_liquids': 'LabP10DerivationExpansionLiquids',
  'p10_deriv_wave_equation': 'LabP10DerivationWaveEquation',
  'p10_deriv_echo': 'LabP10DerivationEcho',
  'p10_deriv_critical_angle': 'LabP10DerivationCriticalAngle',
  'p10_deriv_magnification': 'LabP10DerivationMagnification',
  'p10_deriv_resistivity': 'LabP10DerivationResistivity',
  'p10_deriv_temp_coefficient': 'LabP10DerivationTempCoefficient',
  'p10_deriv_potential_divider': 'LabP10DerivationPotentialDivider',
  'p10_deriv_series_resistance': 'LabP10DerivationSeriesResistance',
  'p10_deriv_parallel_resistance': 'LabP10DerivationParallelResistance',
  'p10_deriv_electrical_energy': 'LabP10DerivationElectricalEnergy',
  'p10_deriv_electric_power': 'LabP10DerivationElectricPower',
  'p10_deriv_transistor_gain': 'LabP10DerivationTransistorGain',
  'p10_deriv_transformer': 'LabP10DerivationTransformer',
  'p10_deriv_photon_energy': 'LabP10DerivationPhotonEnergy',
  'p10_deriv_radioactive_decay': 'LabP10DerivationRadioactiveDecay',

  // Class 10 Chemistry
  'c10_3_1': 'LabC10DiluteSolution',
  'c10_3_2': 'LabC10StandardizationTitration',
  'c10_6_1': 'LabC10SaltTitration',
  'c10_6_2': 'LabC10SaltExcessMetal',
  'c10_6_3': 'LabC10SaltExcessBase',
  'c10_6_4': 'LabC10SaltExcessCarbonate',
  'c10_7_1': 'LabC10MetalReactivity',
  'c10_9_1': 'LabC10SaturatedUnsaturated',
  'c10_11_1': 'LabC10AceticAcidMetal',
  'c10_11_2': 'LabC10AceticAcidCarbonate',
  'c10_4_1': 'LabC10DownsCell',
  'c10_4_2': 'LabC10MoltenLeadChloride',
  'c10_4_3': 'LabC10AqueousElectrolysis',
  'c10_4_4': 'LabC10CopperRefining',
  'c10_4_5': 'LabC10Electroplating',
  'c10_4_6': 'LabC10DanielCell',
  'c10_4_7': 'LabC10FuelCell',
  'c10_5_1': 'LabC10SurfaceAreaRate',
  'c10_5_2': 'LabC10ConcentrationRate',
  'c10_8_1': 'LabC10Esterification',
  'c10_10_1': 'LabC10EthanolFermentation',
  'c10_10_2': 'LabC10EthanolHydration',
  'c10_12_1': 'LabC10AlcoholCombustion',
  'c10_12_2': 'LabC10CondensationPolymerisation',
  'c10_12_3': 'LabC10PETAcidHydrolysis',
  'c10_13_1': 'LabC10BiochemicalTest',

  // Class 10 Computer Science
  'cs10_1_1': 'LabCS10NumberSystems',
  'cs10_1_2': 'LabCS10HelloWorld',
  'cs10_2_1': 'LabCS10ComputationalThinking',
  'cs10_3_1': 'LabCS10HTMLCSS',
  'cs10_3_2': 'LabCS10JSAlgorithms',
  'cs10_3_3': 'LabCS10DynamicList',
  'cs10_4_1': 'LabCS10DataVisualization',
  'cs10_4_2': 'LabCS10ChurnPrediction',
  'cs10_5_1': 'LabCS10FutureTech',
  'cs10_6_1': 'LabCS10CyberSafety',
  'cs10_7_1': 'LabCS10DigitalMarketing',
  'cs10_8_1': 'LabCS10MarketResearch',
  'cs10_8_2': 'LabCS10Financials',
  'cs10_8_3': 'LabCS10BusinessPitch',

  // Class 10 Mathematics
  'm10_7_1': 'LabM10Vectors',
  'm10_9_1': 'LabM10ChordBisectors',
  'm10_9_2': 'LabM10EqualChords',
  'm10_10_1': 'LabM10TangentProperties',
  'm10_10_2': 'LabM10CircleAngles',
  'm10_11_1': 'LabM10CircleBasics',
  'm10_11_2': 'LabM10TangentConstruction',
  'm10_11_3': 'LabM10CommonTangents',
  'm10_12_1': 'LabM10StatisticsWheels',
  'm10_app_1': 'LabM10ComplexApplications',
  'm10_app_2': 'LabM10QuadraticApplications',
  'm10_app_3': 'LabM10MatrixApplications',
  'm10_app_4': 'LabM10InequalityApplications',
  'm10_app_5': 'LabM10FractionApplications',
  'm10_app_6': 'LabM10FunctionApplications',
  'm10_app_7': 'LabM10VectorApplications',
  'm10_app_8': 'LabM10TrigApplications',
  'm10_app_9': 'LabM10CircleApplications',
  'm10_app_12': 'LabM10StatsApplications',

  // Class 10 Biology
  'b10_1': 'LabB10DigestiveSystem',
  'b10_2': 'LabB10BloodSmear',
  'b10_3': 'LabB10RespiratorySystem',
  'b10_4': 'LabB10KidneyDissection',
  'b10_5': 'LabB10NervousSystem',
  'b10_7': 'LabB10Genetics',
  'b10_11': 'LabB10Biostatistics',

  // Class 9 Biology
  'b9_1': 'LabB9Biodiversity',
  'b9_3': 'LabB9Microscopy',
  'b9_6': 'LabB9Biochemistry',
  'b9_7': 'LabB9Enzymes',
  'b9_8': 'LabB9PlantPhysiology',
  'b9_9': 'LabB9PlantReproduction',

  // Class 9 Chemistry
  'c9_1': 'LabC9StatesOfMatter',
  'c9_2': 'LabC9AtomicStructure',
  'c9_3': 'LabC9Electrochemistry',
  'c9_4': 'LabC9EnvironmentalChem',
  'c9_5': 'LabC9OrganicChem',
  'c9_6': 'LabC9SeparationTech',
  'c9_7': 'LabC9QualitativeAnalysis',

  // Class 9 Physics Derivations
  'p9_deriv_force_momentum': 'LabP9DerivationForceMomentum',
  'p9_deriv_recoil': 'LabP9DerivationRecoil',
  'p9_deriv_orbital': 'LabP9DerivationOrbital',
  'p9_deriv_liquid_pressure': 'LabP9DerivationLiquidPressure',
  'p9_deriv_hydraulic': 'LabP9DerivationHydraulic',
  'p9_deriv_ke': 'LabP9DerivationKE',
  'p9_deriv_gpe': 'LabP9DerivationGPE',

  // Class 9 Physics
  'p9_1': 'LabP9MeasurementTools',
  'p9_2': 'LabP9VolumeDensity',
  'p9_3': 'LabP9Kinematics',
  'p9_4': 'LabP9Inertia',
  'p9_5': 'LabP9Friction',
  'p9_6': 'LabP9Pressure',
  'p9_7': 'LabP9Springs',
  'p9_8': 'LabP9MagnetismFields',
  'p9_9': 'LabP9MagnetismInduction',
  'p9_10': 'LabP9EverydayPhysics',

  // Class 9 Computer Science
  'cs9_1': 'LabCS9ComputerSystems',
  'cs9_2': 'LabCS9Algorithms',
  'cs9_3': 'LabCS9WebBasics',
  'cs9_4': 'LabCS9JavaScript',
  'cs9_5': 'LabCS9WebProjects',
  'cs9_6': 'LabCS9DataAnalysis',
  'cs9_7': 'LabCS9AIApplications',
  'cs9_8': 'LabCS9CyberSafety',
  'cs9_9': 'LabCS9Entrepreneurship',

  // Class 9 Mathematics
  'm9_1': 'LabM9RealNumbers',
  'm9_2': 'LabM9Logarithms',
  'm9_3': 'LabM9SetsRelations',
  'm9_4': 'LabM9AlgebraicManipulation',
  'm9_5': 'LabM9Trigonometry',
  'm9_6': 'LabM9CoordinateGeometry',
  'm9_7': 'LabM9LinearGraphs',
  'm9_8': 'LabM9GeometryPolygons',
  'm9_9': 'LabM9BasicStatistics',

  // Class 9 Math Theorems
  'm9_theorem_product_log': 'LabM9TheoremViewer',
  'm9_theorem_quotient_log': 'LabM9TheoremViewer',
  'm9_theorem_power_log': 'LabM9TheoremViewer',
  'm9_theorem_change_base': 'LabM9TheoremViewer',
  'm9_theorem_union_assoc': 'LabM9TheoremViewer',
  'm9_theorem_intersection_assoc': 'LabM9TheoremViewer',
  'm9_theorem_distributive_union': 'LabM9TheoremViewer',
  'm9_theorem_distributive_intersection': 'LabM9TheoremViewer',
  'm9_theorem_quotient_identity': 'LabM9TheoremViewer',
  'm9_theorem_pythagorean_identity': 'LabM9TheoremViewer',
  'm9_theorem_distance_formula': 'LabM9TheoremViewer',
  'm9_theorem_slope_intercept': 'LabM9TheoremViewer',
  'm9_theorem_point_slope': 'LabM9TheoremViewer',
  'm9_theorem_two_point': 'LabM9TheoremViewer',
  'm9_theorem_two_intercept': 'LabM9TheoremViewer',
  'm9_theorem_normal_form': 'LabM9TheoremViewer',
  'm9_theorem_angle_between_lines': 'LabM9TheoremViewer',

  // Class 10 Math Theorems
  'm10_theorem_quadratic_formula': 'LabM10TheoremViewer',
  'm10_theorem_vector_diff': 'LabM10TheoremViewer',
  'm10_theorem_law_cosines': 'LabM10TheoremViewer',
  'm10_theorem_law_sines': 'LabM10TheoremViewer',
  'm10_theorem_law_tangents': 'LabM10TheoremViewer',
  'm10_theorem_half_angle_cos': 'LabM10TheoremViewer',
  'm10_theorem_half_angle_sin': 'LabM10TheoremViewer',
  'm10_theorem_area_sas': 'LabM10TheoremViewer',
  'm10_theorem_area_aas': 'LabM10TheoremViewer',
  'm10_theorem_heros': 'LabM10TheoremViewer',
  'm10_theorem_circum_radius': 'LabM10TheoremViewer',
  'm10_theorem_in_radius': 'LabM10TheoremViewer',
  'm10_theorem_ex_radius': 'LabM10TheoremViewer',
  'm10_theorem_three_point_circle': 'LabM10TheoremViewer',
  'm10_theorem_centre_bisects': 'LabM10TheoremViewer',
  'm10_theorem_perp_bisects': 'LabM10TheoremViewer',
  'm10_theorem_equal_chords_equal_dist': 'LabM10TheoremViewer',
  'm10_theorem_equidistant_chords': 'LabM10TheoremViewer',
  'm10_theorem_congruent_arcs': 'LabM10TheoremViewer',
  'm10_theorem_equal_chords_arcs': 'LabM10TheoremViewer',
  'm10_theorem_equal_chords_angles': 'LabM10TheoremViewer',
  'm10_theorem_equal_angles_chords': 'LabM10TheoremViewer',
  'm10_theorem_perp_radius_tangent': 'LabM10TheoremViewer',
  'm10_theorem_tangent_perp_radius': 'LabM10TheoremViewer',
  'm10_theorem_equal_tangents': 'LabM10TheoremViewer',
  'm10_theorem_external_touching': 'LabM10TheoremViewer',
  'm10_theorem_internal_touching': 'LabM10TheoremViewer',
  'm10_theorem_alternate_segment': 'LabM10TheoremViewer',
  'm10_theorem_central_angle': 'LabM10TheoremViewer',
  'm10_theorem_same_segment': 'LabM10TheoremViewer',
  'm10_theorem_semicircle': 'LabM10TheoremViewer',
  'm10_theorem_major_segment': 'LabM10TheoremViewer',
  'm10_theorem_minor_segment': 'LabM10TheoremViewer',
  'm10_theorem_cyclic_quad': 'LabM10TheoremViewer',

  // Class 11 Chemistry
  'c11_1': 'LabC11AtomicStructure',
  'c11_2': 'LabC11MolecularBonding',
  'c11_3': 'LabC11Stoichiometry',
  'c11_4': 'LabC11PhasesOfMatter',
  'c11_5': 'LabC11EnergeticsKinetics',
  'c11_6': 'LabC11IndustrialEquilibrium',
  'c11_7': 'LabC11AcidsBases',
  'c11_8': 'LabC11EnvironmentalChem',
  'c11_9': 'LabC11OrganicAnalysis',
  'c11_10': 'LabC11OrganicSynthesis',

  // Class 11 Physics
  'p11_1': 'LabP11PhysicalQuantities',
  'p11_2': 'LabP11Vectors',
  'p11_3': 'LabP11TranslatoryMotion',
  'p11_4': 'LabP11RotationalMotion',
  'p11_5': 'LabP11WorkEnergy',
  'p11_6': 'LabP11FluidMechanics',
  'p11_7': 'LabP11Solids',
  'p11_8': 'LabP11Thermodynamics',
  'p11_9': 'LabP11Waves',
  'p11_10': 'LabP11Electrostatics',
  'p11_11': 'LabP11Electricity',
  'p11_12': 'LabP11Electromagnetism',
  'p11_13': 'LabP11ModernPhysics',

  // Class 11 Computer Science
  'cs11_1': 'LabCS11SystemsNetworks',
  'cs11_2': 'LabCS11Algorithms',
  'cs11_3': 'LabCS11Python',
  'cs11_4': 'LabCS11DataScience',
  'cs11_5': 'LabCS11Applications',
  'cs11_6': 'LabCS11Impacts',
  'cs11_7': 'LabCS11Research',
  'cs11_8': 'LabCS11ProductDev',

  // Class 11 Biology
  'b11_1': 'LabB11Cytology',
  'b11_2': 'LabB11Biomolecules',
  'b11_3': 'LabB11Enzymes',
  'b11_4': 'LabB11Bioenergetics',
  'b11_5': 'LabB11Microbiology',
  'b11_6': 'LabB11Fungi',
  'b11_7': 'LabB11PlantPhysiology',
  'b11_8': 'LabB11Inheritance',
  'b11_9': 'LabB11Genetics',

  // Class 12 Biology
  'b12_1': 'LabB12Digestive',
  'b12_2': 'LabB12Cardiorespiratory',
  'b12_3': 'LabB12Urinary',
  'b12_4': 'LabB12NeuroEndocrine',
  'b12_5': 'LabB12Skeletal',
  'b12_6': 'LabB12Immunity',
  'b12_7': 'LabB12Biotechnology',
  'b12_8': 'LabB12StructuralStats',
  'b12_9': 'LabB12PharmacologyEcology',

  // Class 11 Mathematics
  'm11_1': 'LabM11ComplexNumbers',
  'm11_2': 'LabM11Matrices',
  'm11_3': 'LabM11Vectors',
  'm11_4': 'LabM11SequencesSeries',
  'm11_5': 'LabM11Polynomials',
  'm11_6': 'LabM11Permutations',
  'm11_7': 'LabM11BinomialInduction',
  'm11_8': 'LabM11Trigonometry',

  // Class 12 Mathematics
  'm12_1': 'LabM12Derivatives',
  'm12_2': 'LabM12Integration',
  'm12_3': 'LabM12DifferentialEq',
  'm12_4': 'LabM12Conics',
  'm12_5': 'LabM12AnalyticalGeometry',
  'm12_6': 'LabM12Kinematics',
  'm12_7': 'LabM12Functions',
  'm12_8': 'LabM12InverseTrig',

  // Class 12 Physics
  'p12_1': 'LabP12Gravitation',
  'p12_2': 'LabP12ThermoMechanics',
  'p12_3': 'LabP12SHM',
  'p12_4': 'LabP12Diffraction',
  'p12_5': 'LabP12ElectricPotential',
  'p12_6': 'LabP12AlternatingCurrent',
  'p12_7': 'LabP12QuantumNuclear',
  'p12_8': 'LabP12CosmologyClimate',
  'p12_9': 'LabP12MedicalImaging',
  'p12_capstone_solar': 'LabP12SolarCell',

  // Class 12 Chemistry
  'c12_1': 'LabC12Electrochemistry',
  'c12_2': 'LabC12EquilibriumAcidBase',
  'c12_3': 'LabC12TransitionMetals',
  'c12_4': 'LabC12OrganicSynthesis',
  'c12_5': 'LabC12Biochemistry',
  'c12_6': 'LabC12SpectroscopyChromatography',
  'c12_7': 'LabC12Medicine',
  'c12_8': 'LabC12Agriculture',
  'c12_9': 'LabC12IndustryMaterials',

  // Class 12 Computer Science
  'cs12_1': 'LabCS12HCI',
  'cs12_2': 'LabCS12DataStructures',
  'cs12_3': 'LabCS12Programming',
  'cs12_4': 'LabCS12MachineLearning',
  'cs12_5': 'LabCS12DeepLearning',
  'cs12_6': 'LabCS12IoTCloud',
  'cs12_7': 'LabCS12Cybersecurity',
  'cs12_8': 'LabCS12DigitalLiteracy',
  'cs12_9': 'LabCS12Entrepreneurship',

  // Class 11 Math Theorems
  'm11_theorem_complex_magnitude': 'LabM11TheoremViewer',
  'm11_theorem_complex_inverse_polar': 'LabM11TheoremViewer',
  'm11_theorem_complex_division_polar': 'LabM11TheoremViewer',
  'm11_theorem_determinant_transpose': 'LabM11TheoremViewer',
  'm11_theorem_determinant_interchange': 'LabM11TheoremViewer',
  'm11_theorem_determinant_identical': 'LabM11TheoremViewer',
  'm11_theorem_parallelogram_diagonals': 'LabM11TheoremViewer',
  'm11_theorem_triangle_midpoint': 'LabM11TheoremViewer',
  'm11_theorem_trapezium_midpoint': 'LabM11TheoremViewer',
  'm11_theorem_geometric_sum': 'LabM11TheoremViewer',
  'm11_theorem_arithmetico_geometric_sum': 'LabM11TheoremViewer',
  'm11_theorem_remainder': 'LabM11TheoremViewer',
  'm11_theorem_factor': 'LabM11TheoremViewer',
  'm11_theorem_combination': 'LabM11TheoremViewer',
  'm11_theorem_binomial': 'LabM11TheoremViewer',
  'm11_theorem_fundamental_trig': 'LabM11TheoremViewer',
  'm11_theorem_trig_identities': 'LabM11TheoremViewer',

  // Class 12 Math Theorems
  'm12_theorem_power_rule': 'LabM12TheoremViewer',
  'm12_theorem_sin_derivative': 'LabM12TheoremViewer',
  'm12_theorem_inverse_trig_derivatives': 'LabM12TheoremViewer',
  'm12_theorem_basic_integrals': 'LabM12TheoremViewer',
  'm12_theorem_substitution_integrals': 'LabM12TheoremViewer',
  'm12_theorem_fundamental_theorem_calc': 'LabM12TheoremViewer',
  'm12_theorem_concurrency_altitudes': 'LabM12TheoremViewer',
  'm12_theorem_concurrency_bisectors': 'LabM12TheoremViewer',
  'm12_theorem_concurrency_medians': 'LabM12TheoremViewer',
  'm12_theorem_homogeneous_second_degree': 'LabM12TheoremViewer',
  'm12_theorem_circle_general': 'LabM12TheoremViewer',
  'm12_theorem_circle_tangent': 'LabM12TheoremViewer',
  'm12_theorem_parabola_standard': 'LabM12TheoremViewer',
  'm12_theorem_parabola_tangent': 'LabM12TheoremViewer',
  'm12_theorem_ellipse_standard': 'LabM12TheoremViewer',
  'm12_theorem_hyperbola_standard': 'LabM12TheoremViewer',

  // Class 6 Mathematics
  'm6_1': 'LabM6Factors',
  'm6_2': 'LabM6Integers',
  'm6_3': 'LabM6Proportions',
  'm6_4': 'LabM6Sets',
  'm6_5': 'LabM6Algebra',
  'm6_6': 'LabM6Geometry',
  'm6_7': 'LabM6Mensuration',
  'm6_8': 'LabM6Data',

  // Class 7 Math
  'm7_1': 'LabM7RationalSquares',
  'm7_2': 'LabM7ProportionsKinematics',
  'm7_3': 'LabM7FinancialArithmetic',
  'm7_4': 'LabM7SetsAlgebra',
  'm7_5': 'LabM7Transformations',
  'm7_6': 'LabM7Equations',
  'm7_7': 'LabM7GeometryDrafting',
  'm7_8': 'LabM7MensurationData',

  // Class 8 Math
  'm8_1': 'LabM8RealEstimation',
  'm8_2': 'LabM8RootsFinance',
  'm8_3': 'LabM8SetsAlgebra',
  'm8_4': 'LabM8EquationsInequalities',
  'm8_5': 'LabM8Transformations',
  'm8_6': 'LabM8GeometryTriangles',
  'm8_7': 'LabM8Mensuration',
  'm8_8': 'LabM8DataProbability',

  // Class 6 English
  'e6_1': 'LabE6NounsPronouns',
  'e6_2': 'LabE6SentencesAffixes',
  'e6_3': 'LabE6VerbsAdverbs',
  'e6_4': 'LabE6PrepositionsStructure',
  'e6_5': 'LabE6ClausesConjunctions',
  'e6_6': 'LabE6TensesPunctuation',
  'e6_7': 'LabE6FiguresOfSpeech',
  'e6_8': 'LabE6WritingMechanics',

  // Class 7 English
  'e7_1': 'LabE7ArticlesAdjectives',
  'e7_2': 'LabE7FiguresOfSpeech',
  'e7_3': 'LabE7PrepositionsModals',
  'e7_4': 'LabE7VerbsCollocations',
  'e7_5': 'LabE7Tenses',
  'e7_6': 'LabE7Conjunctions',
  'e7_7': 'LabE7PronounsClauses',
  'e7_8': 'LabE7VocabPunctuation',

  // Class 8 English
  'e8_1': 'LabE8NounsPhonetics',
  'e8_2': 'LabE8PronounsMorphology',
  'e8_3': 'LabE8AdjectivesPoetry',
  'e8_4': 'LabE8VerbsModals',
  'e8_5': 'LabE8AdverbsPrepositions',
  'e8_6': 'LabE8ConjunctionsClauses',
  'e8_7': 'LabE8TensesVoice',
  'e8_8': 'LabE8NarrationConditionals',

  // Class 9 English
  'c9e_1': 'LabE9PartsOfSpeech',
  'c9e_2': 'LabE9Verbals',
  'c9e_3': 'LabE9TensesAgreement',
  'c9e_4': 'LabE9Phrases',
  'c9e_5': 'LabE9PrepositionsConjunctions',
  'c9e_6': 'LabE9SentenceStructure',
  'c9e_7': 'LabE9Narration',
  'c9e_8': 'LabE9PunctuationVocabulary',

  // Class 10 English
  'c10e_1': 'LabE10NounsPronouns',
  'c10e_2': 'LabE10VerbsAdjectives',
  'c10e_3': 'LabE10AdverbsPrepositions',
  'c10e_4': 'LabE10ConjunctionsTenses',
  'c10e_5': 'LabE10ModalsConditionals',
  'c10e_6': 'LabE10PhrasesClauses',
  'c10e_7': 'LabE10SentenceNarration',
  'c10e_8': 'LabE10VocabularyStylistics',

  // Class 11 English
  'c11e_1': 'LabE11NounsPronouns',
  'c11e_2': 'LabE11AdjectivesAdverbs',
  'c11e_3': 'LabE11PrepositionsConjunctions',
  'c11e_4': 'LabE11VerbsModals',
  'c11e_5': 'LabE11TensesVerbals',
  'c11e_6': 'LabE11PhrasesClauses',
  'c11e_7': 'LabE11SentenceStructure',
  'c11e_8': 'LabE11VocabularyStylistics',

  // Class 12 English
  'e12-1': 'LabE12NounsPronouns',
  'e12-2': 'LabE12AdjectivesAdverbs',
  'e12-3': 'LabE12PrepositionsConjunctions',
  'e12-4': 'LabE12VerbsModals',
  'e12-5': 'LabE12TensesVerbals',
  'e12-6': 'LabE12PhrasesClauses',
  'e12-7': 'LabE12SentenceStructure',
  'e12-8': 'LabE12VocabularyStylistics',

  // Class 11 Physics Derivations
  'p11_deriv_dimensional_wavelength': 'LabP11DerivationDimensionalWavelength',
  'p11_deriv_dimensional_pendulum': 'LabP11DerivationDimensionalPendulum',
  'p11_deriv_rectangular_components': 'LabP11DerivationRectangularComponents',
  'p11_deriv_first_equation': 'LabP11DerivationFirstEquation',
  'p11_deriv_second_equation': 'LabP11DerivationSecondEquation',
  'p11_deriv_third_equation': 'LabP11DerivationThirdEquation',
  'p11_deriv_projectile_height': 'LabP11DerivationProjectileHeight',
  'p11_deriv_projectile_range': 'LabP11DerivationProjectileRange',
  'p11_deriv_elastic_collision': 'LabP11DerivationElasticCollision',
  'p11_deriv_linear_angular': 'LabP11DerivationLinearAngular',
  'p11_deriv_centripetal_acceleration': 'LabP11DerivationCentripetalAcceleration',
  'p11_deriv_kinetic_energy': 'LabP11DerivationKineticEnergyDerivation',
  'p11_deriv_archimedes': 'LabP11DerivationArchimedesUpthrust',
  'p11_deriv_continuity': 'LabP11DerivationContinuityEquation',
  'p11_deriv_bernoulli': 'LabP11DerivationBernoulliEquation',
  'p11_deriv_carnot_efficiency': 'LabP11DerivationCarnotEfficiency',
  'p11_deriv_doppler_listener_towards': 'LabP11DerivationDopplerListenerTowards',
  'p11_deriv_stationary_waves_string': 'LabP11DerivationStationaryWavesString',
  'p11_deriv_electric_field_point': 'LabP11DerivationElectricFieldPoint',
  'p11_deriv_drift_velocity': 'LabP11DerivationDriftVelocity',
  'p11_deriv_magnetic_force': 'LabP11DerivationMagneticForce',
  'p11_deriv_faraday_law': 'LabP11DerivationFaradayLawDerivation',
  'p11_deriv_projectile_time_flight': 'LabP11DerivationProjectileTimeFlight',
  'p11_deriv_angular_momentum': 'LabP11DerivationAngularMomentum',
  'p11_deriv_torque_inertia': 'LabP11DerivationTorqueInertia',
  'p11_deriv_artificial_gravity': 'LabP11DerivationArtificialGravity',
  'p11_deriv_terminal_velocity': 'LabP11DerivationTerminalVelocity',
  'p11_deriv_resistance_series': 'LabP11DerivationResistanceSeries',
  'p11_deriv_resistance_parallel': 'LabP11DerivationResistanceParallel',
  'p11_deriv_venturi_meter': 'LabP11DerivationVenturiMeter',
  'p11_deriv_elastic_potential_energy': 'LabP11DerivationElasticPotentialEnergy',
  'p11_deriv_work_done_gas': 'LabP11DerivationWorkDoneGas',
  'p11_deriv_cop_refrigerator': 'LabP11DerivationCopRefrigerator',
  'p11_deriv_doppler_listener_away': 'LabP11DerivationDopplerListenerAway',
  'p11_deriv_doppler_source_towards': 'LabP11DerivationDopplerSourceTowards',
  'p11_deriv_stationary_waves_air_column': 'LabP11DerivationStationaryWavesAirColumn',
  'p11_deriv_potential_gradient': 'LabP11DerivationPotentialGradient',
  'p11_deriv_maximum_power_output': 'LabP11DerivationMaximumPowerOutput',
  'p11_deriv_wheatstone_bridge': 'LabP11DerivationWheatstoneBridge',
  'p11_deriv_force_between_conductors': 'LabP11DerivationForceBetweenConductors',
  'p11_deriv_charged_particle_b_field': 'LabP11DerivationChargedParticleBField',
  'p11_deriv_velocity_selector': 'LabP11DerivationVelocitySelector',
  'p11_deriv_doppler_source_away': 'LabP11DerivationDopplerSourceAway',
  'p11_deriv_potentiometer': 'LabP11DerivationPotentiometer',
  'p11_deriv_dirac_momentum': 'LabP11DerivationDiracMomentum',

  // Class 12 Physics Derivations
  'p12_deriv_gravitation_law': 'LabP12DerivationGravitationLaw',
  'p12_deriv_g_on_surface': 'LabP12DerivationGOnSurface',
  'p12_deriv_g_variation': 'LabP12DerivationGWithAltitude',
  'p12_deriv_orbital_velocity': 'LabP12DerivationOrbitalVelocity',
  'p12_deriv_geostationary': 'LabP12DerivationGeostationaryOrbit',
  'p12_deriv_absolute_gpe': 'LabP12DerivationAbsoluteGPE',
  'p12_deriv_gravitational_potential': 'LabP12DerivationGravPotential',
  'p12_deriv_ideal_gas_pressure': 'LabP12DerivationIdealGasPressure',
  'p12_deriv_pressure_ke': 'LabP12DerivationPressureKE',
  'p12_deriv_temperature_ke': 'LabP12DerivationTemperatureKE',
  'p12_deriv_rms_speed': 'LabP12DerivationRMSSpeed',
  'p12_deriv_shm_mass_spring': 'LabP12DerivationSHMMassSpring',
  'p12_deriv_shm_displacement': 'LabP12DerivationSHMDisplacement',
  'p12_deriv_simple_pendulum': 'LabP12DerivationSimplePendulum',
  'p12_deriv_shm_energy': 'LabP12DerivationSHMEnergy',
  'p12_deriv_youngs_double_slit': 'LabP12DerivationYoungsDoubleSlit',
  'p12_deriv_diffraction_grating': 'LabP12DerivationDiffractionGrating',
  'p12_deriv_electric_potential_point': 'LabP12DerivationElectricPotentialPoint',
  'p12_deriv_capacitance': 'LabP12DerivationCapacitancePP',
  'p12_deriv_equivalent_capacitance': 'LabP12DerivationEquivalentCapacitance',
  'p12_deriv_capacitor_energy': 'LabP12DerivationCapacitorEnergy',
  'p12_deriv_rc_circuit': 'LabP12DerivationRCCircuit',
  'p12_deriv_ac_power': 'LabP12DerivationACPower',
  'p12_deriv_inductive_reactance': 'LabP12DerivationInductiveReactance',
  'p12_deriv_capacitive_reactance': 'LabP12DerivationCapacitiveReactance',
  'p12_deriv_impedance': 'LabP12DerivationImpedanceRLRC',
  'p12_deriv_photoelectric': 'LabP12DerivationPhotoelectricEffect',
  'p12_deriv_de_broglie': 'LabP12DerivationDeBroglieWavelength',
  'p12_deriv_mass_defect': 'LabP12DerivationMassDefect',
  'p12_deriv_decay_law': 'LabP12DerivationDecayLaw',
  'p12_deriv_half_life': 'LabP12DerivationHalfLifeRelation',
  'p12_deriv_wien_law': 'LabP12DerivationWiensDisplacement',
  'p12_deriv_hubble_law': 'LabP12DerivationHubbleLaw',
  'p12_deriv_coriolis': 'LabP12DerivationCoriolisForce',
  'p12_deriv_newton_cannon': 'LabP12DerivationNewtonCannonball',

  // Class 6 Science (mapped via c6s_ prefix in labModules)
  'c6s_1_1': 'LabS6Microscope',
  'c6s_1_3': 'LabS6Unit1Projects',
  'c6s_2_1': 'LabS6VegetativePropagation',
  'c6s_3_1': 'LabS6FatDetection',
  'c6s_3_2': 'LabS6BalancedDiet',
  'c6s_4_1': 'LabS6DigestionMechanics',
  'c6s_4_2': 'LabS6AlimentaryCanal',
  'c6s_4_4': 'LabS6LungModel',
  'c6s_5_1': 'LabS6ParticleSimulation',
  'c6s_6_1': 'LabS6MolecularBuilder',
  'c6s_6_2': 'LabS6ElementsCompounds',
  'c6s_7_1': 'LabS6Separation',
  'c6s_7_2': 'LabS6SolutionInvestigation',
  'c6s_8_1': 'LabS6EnergyTransformation',
  'c6s_8_2': 'LabS6EnergyProjects',
  'c6s_9_1': 'LabS6CircuitBuilder',
  'c6s_9_2': 'LabS6ConductorsInsulators',
  'c6s_10_1': 'LabS6Magnetism',
  'c6s_11_1': 'LabS6PlantGrowth',
  'c6s_12_1': 'LabS6SolarSystemBuilder',
  'c6s_12_2': 'LabS6EverydayTech',
};

/**
 * Cache lazy components so React always sees the same reference.
 * Prevents remounting — lazy() must be called once per component, not on every render.
 */
const lazyCache: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {};

/**
 * Look up a lazy-loaded lab component by module ID.
 * Uses import.meta.glob for automatic discovery — no manual import() calls needed.
 */
export function getLabComponent(moduleId: string): React.LazyExoticComponent<React.ComponentType<any>> | null {
  const componentName = moduleIdToComponent[moduleId];
  if (!componentName) return null;

  // Return cached lazy component if already created
  if (lazyCache[componentName]) return lazyCache[componentName];

  const filePath = `../components/${componentName}.tsx`;
  const loader = (labFiles as Record<string, () => Promise<any>>)[filePath];
  if (!loader) return null;

  const lazyComp = lazy(() => loader().then(m => ({ default: m.default })));
  lazyCache[componentName] = lazyComp;
  return lazyComp;
}
